Update and address questionable syntax

diff --git a/catmedia b/catmedia
--- a/catmedia
+++ b/catmedia
@@ -3,15 +3,15 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/catmedia
 # Started On        - Sun 15 Oct 13:16:02 BST 2017
-# Last Change       - Sun 12 May 15:19:43 BST 2019
+# Last Change       - Wed 27 Nov 15:53:58 GMT 2019
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
 
-_VERSION_="2019-05-12"
-_PROJECT_="${0##*/}"
+_VERSION_="2019-11-27"
+_PROJECT_=${0##*/}
 
-FAIL(){
+Err(){
 	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
 	[ $1 -eq 1 ] && exit 1
 }
@@ -55,11 +55,11 @@ while [ "$1" ]; do
 			printf "%s\n" "$_VERSION_"
 			exit 0 ;;
 		--quiet|-q)
-			BEQUIET="true" ;;
+			BEQUIET='true' ;;
 		--debug|-D)
-			DEBUGME="true" ;;
+			DEBUGME='true' ;;
 		-*)
-			FAIL 1 "$LINENO" "Incorrect OPT specified. See: --help|-h|-?" ;;
+			Err 1 $LINENO "Incorrect OPT specified. See: --help|-h|-?" ;;
 		*)
 			break ;;
 	esac
@@ -69,7 +69,7 @@ done
 declare -i DEPCOUNT=0
 for DEP in ffmpeg rm; {
 	if ! type -fP "$DEP" > /dev/null 2>&1; then
-		FAIL 0 "$LINENO" "Dependency '$DEP' not met."
+		Err 0 $LINENO "Dependency '$DEP' not met."
 		DEPCOUNT+=1
 	else
 		if [ "$DEP" == "ffmpeg" ]; then
@@ -78,10 +78,10 @@ for DEP in ffmpeg rm; {
 			MAJOR=${BUFFER%.*}
 			MINOR=${BUFFER/*.}
 
-			if ! [[ "$BUFFER" =~ ^[0-9]+\.[0-9]+$ ]]; then
-				FAIL 1 "$LINENO" "Unable to determine required version of ffmpeg."
+			if ! [[ $BUFFER =~ ^[0-9]+\.[0-9]+$ ]]; then
+				Err 1 $LINENO "Unable to determine required version of ffmpeg."
 			elif ! [ "$MAJOR" -ge 1 -a "$MINOR" -ge 1 ]; then
-				FAIL 1 "$LINENO" "Version 1.1 or greater of ffmpeg required."
+				Err 1 $LINENO "Version 1.1 or greater of ffmpeg required."
 			fi
 		fi
 	fi
@@ -89,8 +89,8 @@ for DEP in ffmpeg rm; {
 
 [ $DEPCOUNT -eq 0 ] || exit 1
 
-[ "$BEQUIET" == "true" ] && exec > /dev/null
-[ "$DEBUGME" == "true" ] && set -x
+[ "$BEQUIET" == 'true' ] && exec > /dev/null
+[ "$DEBUGME" == 'true' ] && set -x
 
 # Process the input files.
 declare -i INCOUNT=0
@@ -102,14 +102,14 @@ while [ "$1" ]; do
 	INCOUNT+=1
 done
 
-OUTPUT="${1// /%20}"
+OUTPUT=${1// /%20}
 
 if [ $INCOUNT -eq 0 ]; then
-	FAIL 1 "$LINENO" "At least two inputs and an output is required."
+	Err 1 $LINENO "At least two inputs and an output is required."
 elif ! [ "$OUTPUT" ]; then
-	FAIL 1 "$LINENO" "At least two inputs and an output is required."
+	Err 1 $LINENO "At least two inputs and an output is required."
 elif ! [ -d /tmp ]; then
-	FAIL 1 "$LINENO" "Unable to access the /tmp directory."
+	Err 1 $LINENO "Unable to access the /tmp directory."
 fi
 
 # Creating the temporary file list for ffmpeg.
@@ -119,7 +119,7 @@ for PART in $INPUT; {
 
 # Concatenation begins here.
 while read -a REPLY; do
-	if [[ "$REPLY" == frame=* ]]; then
+	if [[ $REPLY == frame=* ]]; then
 		printf "\rPROGRESS: SIZE=\"${REPLY[5]/*=}\" TIME=\"${REPLY[6]/*=}\""
 	else
 		continue
