Updated ccfiles

diff --git a/ccfiles b/ccfiles
--- a/ccfiles
+++ b/ccfiles
@@ -3,7 +3,7 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/ccfiles (Cross-Check Files)
 # Started On        - Wed 13 Dec 13:45:22 GMT 2017
-# Last Change       - Thu  9 May 00:51:51 BST 2019
+# Last Change       - Sun 12 May 15:20:31 BST 2019
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
@@ -15,10 +15,13 @@
 #       seems to have gone a different direction.
 #----------------------------------------------------------------------------------
 
-_VERSION_="2019-05-09"
+_VERSION_="2019-05-12"
+_PROJECT_="${0##*/}"
 
-XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
-ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }
+FAIL(){
+	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
+	[ $1 -eq 1 ] && exit 1
+}
 
 DIR="/var/lib/dpkg/info"
 
@@ -26,12 +29,12 @@ USAGE(){
 	while read -r; do
 		printf "%s\n" "$REPLY"
 	done <<-EOF
-		            CCFILES ($_VERSION_)
+		            ${_PROJECT_^^} ($_VERSION_)
 		            Written by terminalforlife (terminalforlife@yahoo.com)
 
 		            Cross-check files installed by dpkg.
 
-		SYNTAX:     ccfiles [OPTS]
+		SYNTAX:     $_PROJECT_ [OPTS]
 
 		OPTS:       --help|-h|-?            - Displays this help information.
 		            --quiet|-q              - Runs in quiet mode. Errors still output.
@@ -43,28 +46,29 @@ USAGE(){
 	EOF
 }
 
-while [ -n "$1" ]; do
+while [ "$1" ]; do
 	case "$1" in
 		--help|-h|-\?)
 			USAGE; exit 0 ;;
-		--debug|-D)
-			DEBUGME="true" ;;
 		--quiet|-q)
 			BEQUIET="true" ;;
+		--debug|-D)
+			DEBUGME="true" ;;
 		--nopause|-N)
 			NOPAUSE="true" ;;
 		--nobell|-B)
 			NOBELL="true" ;;
 		*)
-			XERR "$LINENO" "Incorrect argument(s) specified." ;;
+			FAIL 1 "$LINENO" "Incorrect argument(s) specified." ;;
 	esac
-
 	shift
 done
 
-[ -x /bin/readlink ] || XERR "$LINENO" "Dependency '/bin/readlink' not met."
+if ! type -fP readlink > /dev/null 2>&1; then
+	FAIL 1 "$LINENO" "Dependency 'readlink' not met."
+fi
 
-[ "$BEQUIET" == "true" ] && exec >&-
+[ "$BEQUIET" == "true" ] && exec > /dev/null
 [ "$DEBUGME" == "true" ] && set -x
 
 #TODO - Check for Debian/Ubuntu base.
@@ -73,7 +77,7 @@ if [ -d $DIR/ ]; then
 	for FILE in $DIR/*.list; {
 		while read -r; do
 			for EXE in /proc/*/exe; {
-				RESOLVED=`/bin/readlink --quiet "$EXE"`
+				RESOLVED=`readlink --quiet "$EXE"`
 
 				if ! [ -x "$RESOLVED" ]; then
 					if ! [ "$NOBELL" == "true" ]; then
@@ -92,5 +96,7 @@ if [ -d $DIR/ ]; then
 		done < "$FILE"
 	}
 else
-	XERR "$LINENO" "Directory '$DIR' not found."
+	FAIL 1 "$LINENO" "Directory '$DIR' not found."
 fi
+
+# vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
