Updated dwwdl

diff --git a/dwwdl b/dwwdl
--- a/dwwdl
+++ b/dwwdl
@@ -3,36 +3,34 @@
 #----------------------------------------------------------------------------------
 # Project Name      - dwwdl (Distrowatch Weekly Downloader)
 # Started On        - Sat 16 Sep 22:41:54 BST 2017
-# Last Change       - Mon  6 Nov 16:05:37 GMT 2017
+# Last Change       - Sun 12 May 16:06:55 BST 2019
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
 
-XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
-ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }
+_VERSION_="2019-05-12"
+_PROJECT_="${0##*/}"
 
-declare -i DEPCOUNT=0
-for DEP in /usr/bin/wget /bin/{sync,sleep}; {
-	[ -x "$DEP" ] || {
-		ERR "$LINENO" "Dependency '$DEP' not met."
-		DEPCOUNT+=1
-	}
+FAIL(){
+	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
+	[ $1 -eq 1 ] && exit 1
 }
 
-[ $DEPCOUNT -gt 0 ] && exit 1
+DLURL="http://distrowatch.com/podcast/dww"
 
 USAGE(){
 	while read; do
 		printf "%s\n" "$REPLY"
 	done <<-EOF
-		            DWWDL - Distrowatch Weekly Downloader (6th November 2017)
+		            ${_PROJECT_^^} - Distrowatch Weekly Downloader ($_VERSION_)
 		            Written by terminalforlife (terminalforlife@yahoo.com)
-		
+
 		            Download all of the available DistroWatch Weekly podcasts.
 
-		SYNTAX:     dwwdl [OPTS]
-		
+		SYNTAX:     $_PROJECT_ [OPTS]
+
 		OPTS:       --help|-h|-?            - Displays this help information.
+		            --version|-v            - Output only the version datestamp.
 		            --server-kind           - A random number of seconds from 1-9 between
 		                                      each image. An 'interval' also occurs for
 		                                      every set of images, in minutes.
@@ -46,37 +44,39 @@ USAGE(){
 		                                      An example of n would be 20170804.
 		            --quiet-sleep           - Prevents the display of the sleep messages.
 		                                      Only applicable if --server-kind is used.
-		            --suspend|-s            - Suspend the system after dwwdl finishes.
-		            --shutdown|-S           - Shut the system down after dwwdl finishes.
+		            --suspend|-s            - Suspend the system after $_PROJECT_ finishes.
+		            --shutdown|-S           - Shut the system down after $_PROJECT_ finishes.
 
 		NOTE:       All podcasts will be downloaded to the current working directory and
 		            are from newest to oldest, unless --date=n is used.
 
 		            Entries older than 20050822 were before DWW podcasts were available.
-		
-		SITE:       https://www.distrowatch.com
+
+		SITE:       ${DLURL%/podcast/*}
 	EOF
 }
 
-PROGRESS=""
 SERVER_KIND="false"
 SLEEP_S=9
 INTERVAL=10
 EXT="ogg"
-PODS=""
 
 while [ "$1" ]; do
 	case "$1" in
 		--help|-h|-\?)
 			USAGE; exit 0 ;;
+		--version|-v)
+			printf "%s\n" "$_VERSION_"; exit 0 ;;
 		--server-kind)
 			SERVER_KIND="true" ;;
 		--interval|-i)
 			shift
 
-			[[ "$1" =~ [0-9]+ ]] && INTERVAL="$1" || {
-				XERR "$LINENO" "Incorrect interval."
-			} ;;
+			if [[ "$1" =~ [0-9]+ ]]; then
+				INTERVAL="$1"
+			else
+				FAIL 1 "$LINENO" "Incorrect interval."
+			fi ;;
 		--quiet-sleep)
 			QUIET_SLEEP="true" ;;
 		--show-progress)
@@ -84,112 +84,120 @@ while [ "$1" ]; do
 		--type|-t)
 			shift
 
-			[[ "$1" =~ ^(mp3|ogg)$ ]] && EXT="$1" || {
-				XERR "$LINENO" "Incorrect file type selected."
-			} ;;
+			if [[ "$1" =~ ^(mp3|ogg)$ ]]; then
+				EXT="$1"
+			else
+				FAIL 1 "$LINENO" "Incorrect file type selected."
+			fi ;;
 		--date|-d)
 			shift
 
-			[[ "$1" =~ ^[0-9]{8} ]] && PODS+=" $1" || {
-				XERR "$LINENO" "Incorrect podcast date provided."
-			} ;;
+			if [[ "$1" =~ ^[0-9]{8} ]]; then
+				PODS+=" $1"
+			else
+				FAIL 1 "$LINENO" "Incorrect podcast date provided."
+			fi ;;
 		--suspend|-s)
 			SUSPEND="true"
-			[ -x /bin/systemctl ] || {
-				XERR "$LINENO" "Dependency 'systemctl' not met."
-			} ;;
+			if ! type -fP systemctl > /dev/null 2>&1; then
+				FAIL 1 "$LINENO" "Dependency 'systemctl' not met."
+			fi ;;
 		--shutdown|-S)
 			SHUTDOWN="true"
-			[ -x /sbin/shutdown ] || {
-				XERR "$LINENO" "Dependency 'shutdown' not met."
-			} ;;
+			if ! type -fP shutdown > /dev/null 2>&1; then
+				FAIL 1 "$LINENO" "Dependency 'shutdown' not met."
+			fi ;;
 		*)
 			break ;;
 	esac
-
 	shift
 done
 
-[ "$*" ] && XERR "$LINENO" "Incorrect argument(s) detected."
-
-[ "$SERVER_KIND" == "true" ] || {
-	[ "$QUIET_SLEEP" == "true" -o ! "$INTERVAL" -eq 10 ] && {
-		XERR "$LINENO" "Expecting '--server-kind' argument."
-	}
+declare -i DEPCOUNT=0
+for DEP in wget sync sleep; {
+	if ! type -fP "$DEP" > /dev/null 2>&1; then
+		FAIL 0 "$LINENO" "Dependency '$DEP' not met."
+		DEPCOUNT+=1
+	fi
 }
 
-[ $UID -gt 0 ] || XERR "$LINENO" "Root access is not recommended."
+[ $DEPCOUNT -gt 0 ] && exit 1
+
+[ "$*" ] && FAIL 1 "$LINENO" "Incorrect argument(s) detected."
+
+if ! [ "$SERVER_KIND" == "true" ]; then
+	if [ "$QUIET_SLEEP" == "true" -o ! "$INTERVAL" -eq 10 ]; then
+		FAIL 1 "$LINENO" "Expecting '--server-kind' argument."
+	fi
+fi
 
 declare -i TIME_COUNT=0
 
-[ -z "$PODS" ] && {
+if ! [ "$PODS" ]; then
 	#TODO - See about adding $OLDTONEW functionality here with pure shell.
 	PODS=$(
 		LINK="http://distrowatch.com/weekly.php?issue=1"
 
 		while read -ra X; do
 			for A in ${X[@]}; {
-				[[ "$A" == *\?issue\=* ]] && {
+				if [[ "$A" == *\?issue\=* ]]; then
 					printf "%s\n" ${A//[!0-9]/}
-				}
+				fi
 			}
-		done <<< `/usr/bin/wget -q "$LINK" -O -`
+		done <<< `wget -q "$LINK" -O -`
 	)
-}
+fi
 
 DLURL="http://distrowatch.com/podcast/dww"
 
 for DATE in $PODS; {
 	[ $DATE -lt 20050822 ] && continue
 
-	[ -z "$PROGRESS" ] && printf "PODCAST: %s\n" "$DATE"
+	[ "$PROGRESS" ] || printf "PODCAST: %s\n" "$DATE"
 
-	[ "$SERVER_KIND" == "true" -a ! -f "${DL_LINK//*\/}" ] && {
+	if [ "$SERVER_KIND" == "true" -a ! -f "${DL_LINK//*\/}" ]; then
 		TIME_COUNT+=1; printf -v RAND "%0.5d" "$RANDOM"
-		[ "$QUIET_SLEEP" == "true" ] || {
+		if ! [ "$QUIET_SLEEP" == "true" ]; then
 			printf "Sleeping for %d second(s)...\n" "${RAND/????}"
-		}
+		fi
 
-		/bin/sleep ${RAND/????}s
+		sleep ${RAND/????}s
 
-		[ $INTERVAL -eq 0 -a $TIME_COUNT -eq $INTERVAL ] && {
+		if [ $INTERVAL -eq 0 -a $TIME_COUNT -eq $INTERVAL ]; then
 			printf -v RAND "%0.5d" "$RANDOM"
 
-			[ "$QUIET_SLEEP" == "true" ] || {
+			if ! [ "$QUIET_SLEEP" == "true" ]; then
 				printf "Sleeping for %d minute(s)...\n"\
 					"${RAND/????}"
-			}
+			fi
 
-			/bin/sleep ${RAND/????}m
+			sleep ${RAND/????}m
 			TIME_COUNT=0
-		}
-	}
+		fi
+	fi
 
-	/usr/bin/wget -cq --no-cookies $PROGRESS ${DLURL}${DATE}.${EXT} || {
-		ERR "$LINENO" "Podcast '$DATE' failed."
-	}
+	if ! wget -cq --no-cookies $PROGRESS ${DLURL}${DATE}.${EXT}; then
+		FAIL 0 "$LINENO" "Podcast '$DATE' failed."
+	fi
 }
 
-[ "$SHUTDOWN" == "true" ] && {
-	/sbin/shutdown +3 &> /dev/null
+if [ "$SHUTDOWN" == "true" ]; then
+	shutdown +3 &> /dev/null
 	printf "%s\n" "Shutting down in 3 minutes..."
 	read -n 1 -e -p "Type 'C' to cancel, or 'N' to shutdown now: " SHUTDOWN_PROMPT
 
 	case "${SHUTDOWN_PROMPT:-EMPTY}" in
 		[Cc])
-			/sbin/shutdown --no-wall -c
+			shutdown --no-wall -c
 			exit 0 ;;
 		[Nn])
-			/sbin/shutdown --no-wall now ;;
+			shutdown --no-wall now ;;
 		EMPTY|*)
-			echo "Incorrect response. Quitting." 1>&2
-			exit 1 ;;
+			FAIL 1 "$LINENO" "Invalid response -- quitting." ;;
 	esac
-}
-
-[ "$SUSPEND" == "true" ] && {
-	/bin/sync
-	printf "%s\n" "System will suspend in 3s; type Ctrl+C to cancel and quit dwwdl."
-	/bin/sleep 3
-	/bin/systemctl suspend
-}
+elif [ "$SUSPEND" == "true" ]; then
+	sync
+	printf "%s\n" "System will suspend in 3s; type Ctrl+C to cancel and quit $_PROJECT_."
+	sleep 3
+	systemctl suspend
+fi
