Updated

diff --git a/filesitter b/filesitter
--- a/filesitter
+++ b/filesitter
@@ -3,19 +3,18 @@
 #----------------------------------------------------------------------------------
 # Project Name      - miscellaneous/filesitter
 # Started On        - Thu 28 Sep 23:58:07 BST 2017
-# Last Change       - Wed  4 Oct 21:02:46 BST 2017
+# Last Change       - Thu  5 Oct 18:43:12 BST 2017
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
 
-XERR(){ echo "[L${LINENO}]: ERROR: $1" 1>&2; exit 1; }
-ERR(){ echo "[L${LINENO}]: ERROR: $1" 1>&2; }
+XERR(){ echo "[L${1}] ERROR: $2" 1>&2; exit 1; }
+ERR(){ echo "[L${1}] ERROR: $2" 1>&2; }
 
 declare -i DEPCOUNT=0
-for DEP in /usr/bin/{tr,cut,stat} /bin/{systemctl,sleep}
-{
+for DEP in /usr/bin/{tr,cut,stat} /bin/{systemctl,sleep}; {
 	[ -x "$DEP" ] || {
-		ERR "Dependency '$DEP' not met."
+		ERR "$LINENO" "Dependency '$DEP' not met."
 		DEPCOUNT+=1
 	}
 }
@@ -24,13 +23,11 @@ for DEP in /usr/bin/{tr,cut,stat} /bin/{systemctl,sleep}
 
 shopt -s extglob
 
-USAGE()
-{
-	while read -r
-	do
+USAGE(){
+	while read -r; do
 		echo "$REPLY"
 	done <<-EOF
-		            FILESITTER (4th October 2017)
+		            FILESITTER (5th October 2017)
 		            Written by terminalforlife (terminalforlife@yahoo.com)
 		
 		            Watch for and act upon the completion of file size changes.
@@ -51,10 +48,8 @@ USAGE()
 	EOF
 }
 
-for ARG in $@
-{
-	case "$ARG"
-	in
+for ARG in $@; {
+	case "$ARG" in
 		--help|-h|-\?)
 			USAGE; exit 0 ;;
 		--debug)
@@ -74,16 +69,15 @@ for ARG in $@
 
 IFS=""; FILENAME1="$1"; FILENAME2="$2"; FILENAME3="$3"
 ([ -z "$FILENAME1" ] && [ -z "$FILENAME2" ] && [ -z "$FILENAME3" ]) && {
-	XERR "At least one filename is required."
+	XERR "$LINENO" "At least one filename is required."
 }
 
-[ $UID -eq 0 ] && XERR "Root access isn't required."
+[ $UID -eq 0 ] && XERR "$LINENO" "Root access isn't required."
 
 [ "$BEQUIET" == "true" ] && exec 1> /dev/null
 [ "$DEBUGME" == "true" ] && set -xeu
 
-while :
-do
+while :; do
 	for FILE in\
 	\
 		"${FILENAME1:-NULL}" "${FILENAME2:-NULL}" "${FILENAME3:-NULL}"
@@ -91,7 +85,7 @@ do
 		[ "$FILE" == "NULL" ] && continue
 
 		([ -f "$FILE" ] || [ -r "$FILE" ]) || {
-			XERR "Cannot find or access: $FILE"
+			XERR "$LINENO" "Cannot find or access: $FILE"
 		}
 
 		NEW+=`/usr/bin/stat --printf="%s" "$FILE"`
@@ -103,7 +97,7 @@ do
 		trap "/bin/systemctl $ACTION" HUP
 
 		# Exit if kill succeeds, otherwise just exit with error.
-		kill -HUP $$ && exit 0 || XERR "Failed to $ACTION the system."
+		kill -HUP $$ && exit 0 || XERR "$LINENO" "Failed to $ACTION the system."
 	}
 
 	OLD="$NEW"
diff --git a/medlog b/medlog
--- a/medlog
+++ b/medlog
@@ -3,33 +3,31 @@
 #----------------------------------------------------------------------------------
 # Project Name      - medlog
 # Started On        - Fri 18 Nov ??:??:?? BST 2016
-# Last Change       - Mon 18 Sep 14:42:51 BST 2017
+# Last Change       - Thu  5 Oct 18:45:20 BST 2017
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
 
-XERR(){ echo "ERROR: $1" 1>&2; exit 1; }
-ERR(){ echo "ERROR: $1" 1>&2; }
+XERR(){ echo "[L${1}] ERROR: $2" 1>&2; exit 1; }
+ERR(){ echo "[L${1}] ERROR: $2" 1>&2; }
 
-DEPCOUNT=0
-for DEP in /usr/bin/{xmessage,paplay,cut,tr,tail,notify-send} /bin/{date,mkdir}
-{
-	if ! type -P "$DEP" &> /dev/null
-	then
-		ERR "Dependency '$DEP' not met."
-		let DEPCOUNT++
-	fi
+declare -i DEPCOUNT=0
+for DEP in /usr/bin/{xmessage,paplay,cut,tr,tail,notify-send} /bin/mkdir}; {
+	[ -x "$DEP" ] || {
+		ERR "$LINENO" "Dependency '$DEP' not met."
+		DEPCOUNT+=1
+	}
 }
 
 [ $DEPCOUNT -eq 0 ] || exit 1
 
-[ $UID -eq 0 ] && XERR "Root access not required."
+[ $UID -eq 0 ] && XERR "$LINENO" "Root access not required."
 
 MAINDIR="$HOME/.medlog"
 [ -d "$MAINDIR" ] || /bin/mkdir --parents "$MAINDIR"
 LOGFILE="$MAINDIR/medlog.log"
 [ -f "$LOGFILE" ] || > "$LOGFILE"
-[ -w "$LOGFILE" ] || XERR "File '${LOGFILE//*\/}' has no write access."
+[ -w "$LOGFILE" ] || XERR "$LINENO" "File '${LOGFILE//*\/}' has no write access."
 NOTIFILE="$MAINDIR/notify.ogg"
 
 LAST_LOG=$(
@@ -38,24 +36,22 @@ LAST_LOG=$(
 		| /usr/bin/cut -d " " -f 1-3
 )
 
-TODAY_DATE=`/bin/date +%a\ %d\ %b`
+TODAY_DATE=`printf '%(%a %d %b)T'`
 MSG="Medication taken today, $USER?"
 MSG_NO="Take medication, then reload medlog."
 
-if [ "${TODAY_DATE// /}" == "${LAST_LOG// /}" ]
-then
+[ "${TODAY_DATE// /}" == "${LAST_LOG// /}" ] && {
 	/usr/bin/notify-send "Medication already taken today."
-else
+} || {
 	/usr/bin/paplay "$NOTIFILE"
 	
 	ANSWER=$(/usr/bin/xmessage -buttons yes,no -center "$MSG" -print)
 	
-	case "$ANSWER"
-	in
+	case "$ANSWER" in
 		no)
 			/usr/bin/notify-send "$MSG_NO"
 			exit 1 ;;
 		yes)
 			/bin/date "+%a %d %b %X %Z %Y" >> "$LOGFILE" ;;
 	esac
-fi
+}
diff --git a/mplay b/mplay
--- a/mplay
+++ b/mplay
@@ -3,7 +3,7 @@
 #----------------------------------------------------------------------------------
 # Project Name      - mplay
 # Started On        - Sat 16 Sep 19:42:57 BST 2017
-# Last Change       - Sat 16 Sep 20:03:32 BST 2017
+# Last Change       - Thu  5 Oct 18:47:59 BST 2017
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
@@ -11,32 +11,31 @@
 #My mocp (moc) settings. Simple script to allow me to quickly load mocp how I like.
 
 # Load error functions.
-ERR(){ echo "ERROR: $1" 1>&2; }
-XERR(){ echo "ERROR: $1" 1>&2; exit 1; }
+ERR(){ echo "[L${1}] ERROR: $2" 1>&2; }
+XERR(){ echo "[L${1}] ERROR: $2" 1>&2; exit 1; }
 
 # Check for root access.
-[ $UID -eq 0 ] && XERR "Root access is not required."
+[ $UID -eq 0 ] && XERR "$LINENO" "Root access is not required."
 
 # Check for zero arguments.
-[ $# -eq 0 ] || XERR "No arguments required."
+[ $# -eq 0 ] || XERR "$LINENO" "No arguments required."
 
 # The directory where all the mocp themes are stored.
 THEME_DIR="/usr/share/moc/themes"
 
 # If the directory doesn't exist, as above, the error and exit.
-[ -d $THEME_DIR ] || XERR "Theme directory not found."
+[ -d $THEME_DIR ] || XERR "$LINENO" "Theme directory not found."
 
 # This is the selected theme which should be in the above directory.
 CHOSEN_THEME="transparent-background"
 
 # If the chosen theme doesn't exist as above, error and exit.
-[ -f "$THEME_DIR/$CHOSEN_THEME" ] || XERR "Theme file not found."
+[ -f "$THEME_DIR/$CHOSEN_THEME" ] || XERR "$LINENO" "Theme file not found."
 
  # If mocp and alsa are found, ...
-if type -P /usr/bin/mocp /sbin/alsa &> /dev/null
-then
+([ -x /usr/bin/mocp ] && [ -x /sbin/alsa ]) && {
 	# Actually launch mocp, using the flags and above chosen theme.
-	if ! /usr/bin/mocp -T $THEME_DIR/$CHOSEN_THEME   \
+	/usr/bin/mocp -T $THEME_DIR/$CHOSEN_THEME        \
 		-O ShowFormat=yes                        \
 		-O ShowTime=no                           \
 		-O Shuffle=yes                           \
@@ -56,12 +55,12 @@ then
 		-O SoundDriver=ALSA                      \
 		-O InputBuffer=512                       \
 		-O OutputBuffer=512                      \
-		-O Prebuffering=256
-	then
+		-O Prebuffering=256                      \
+	|| {
 		# If MOC fails to launch, error and exit.
-		XERR "Unable to start the MOC player."
-	fi
-else
+		XERR "$LINENO" "Unable to start the MOC player."
+	}
+} || {
 	# If alsa and/or mocp aren't found, error and exit.
-	XERR "Dependency '/usr/bin/mocp' unmet."
-fi
+	XERR "$LINENO" "Dependency '/usr/bin/mocp' unmet."
+}
diff --git a/nosp b/nosp
--- a/nosp
+++ b/nosp
@@ -3,30 +3,29 @@
 #----------------------------------------------------------------------------------
 # Project Name      - nosp
 # Started On        - Sat 16 Sep 20:03:52 BST 2017
-# Last Change       - Sat 16 Sep 20:30:24 BST 2017
+# Last Change       - Thu  5 Oct 18:49:25 BST 2017
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
 
 # Load error functions.
-XERR(){ echo "ERROR: $1" 1>&2; exit 1; }
-ERR(){ echo "ERROR: $1" 1>&2; }
+XERR(){ echo "[L${1}] ERROR: $2" 1>&2; exit 1; }
+ERR(){ echo "[L${1}] ERROR: $2" 1>&2; }
 
 # Check for root access.
-[ $UID -eq 0 ] && XERR "Root access is not required."
+[ $UID -eq 0 ] && XERR "$LINENO" "Root access is not required."
 
 # Check for zero arguments.
-[ $# -eq 0 ] || XERR "No arguments are required."
+[ $# -eq 0 ] || XERR "$LINENO" "No arguments are required."
 
 # Check for dependencies.
-DEPCOUNT=0
+declare -i DEPCOUNT=0
 for DEP in /usr/bin/xfconf-query /bin/sleep
 {
-	if ! type -P "$DEP" &> /dev/null
-	then
-		ERR "Dependency '$DEP' unmet."
-		let DEPCOUNT++
-	fi
+	[ -x "$DEP" ] || {
+		ERR "$LINENO" "Dependency '$DEP' not met."
+		DEPCOUNT+=1
+	}
 }
 
 # If any unmet dependencies, exit.
@@ -40,8 +39,7 @@ LOCAL_XML_FILE="$HOME/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml"
 CURRENT_VALUE=`/usr/bin/xfconf-query -c xfwm4 -p /general/placement_ratio -t int`
 
 # If the local XML file is exists, is a file, and has write access...
-if [ -f "$LOCAL_XML_FILE" ] && [ -w "$LOCAL_XML_FILE" ]
-then
+([ -f "$LOCAL_XML_FILE" ] && [ -w "$LOCAL_XML_FILE" ]) && {
 	# This command group waits, sets value to 90, waits, then sets back to 100.
 	{
 		/bin/sleep 3s
@@ -49,7 +47,7 @@ then
 		/bin/sleep 0.3 # Removing wait time results in this fix not working.
 		/usr/bin/xfconf-query -c xfwm4 -p /general/placement_ratio -s 100 -t int
 	} &
-else
+} || {
 	# Error and exit if the XML file is inaccessible.
-	XERR "Unable to fix Smart Placement."
-fi
+	XERR "$LINENO" "Unable to fix Smart Placement."
+}
