Updated fix-ff-gtk

diff --git a/fix-ff-gtk b/fix-ff-gtk
--- a/fix-ff-gtk
+++ b/fix-ff-gtk
@@ -3,15 +3,18 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/fix-ff-gtk
 # Started On        - Fri 29 Mar 13:12:04 GMT 2019
-# Last Change       - Thu  9 May 00:56:56 BST 2019
+# Last Change       - Sun 12 May 16:16:02 BST 2019
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
 
-_VERSION_="2019-05-09"
+_VERSION_="2019-05-12"
+_PROJECT_="${0##*/}"
 
-XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
-ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }
+FAIL(){
+	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
+	[ $1 -eq 1 ] && exit 1
+}
 
 FF="/usr/bin/firefox"
 
@@ -19,12 +22,12 @@ USAGE(){
 	while read -r; do
 		printf "%s\n" "$REPLY"
 	done <<-EOF
-		            FIX-FF-GTK ($_VERSION_)
+		            ${_PROJECT_^^} ($_VERSION_)
 		            Written by terminalforlife (terminalforlife@yahoo.com)
 
 		            Psuedo-Fix colors used in Firefox when using a dark GTK theme.
 
-		SYNTAX:     fix-ff-gtk [OPTS]
+		SYNTAX:     $_PROJECT_ [OPTS]
 
 		OPTS:       --help|-h|-?            - Displays this help information.
 		            --version|-v            - Output only the version datestamp.
@@ -55,34 +58,39 @@ while [ "$1" ]; do
 		--help|-h|-\?)
 			USAGE; exit 0 ;;
 		--version|-v)
-			printf "%s\n" "$_VERSION_"
-			exit 0 ;;
+			printf "%s\n" "$_VERSION_"; exit 0 ;;
 		--theme|-t)
 			THEME="$2" ;;
 		*)
-			XERR "$LINENO" "Incorrect argument(s) specified." ;;
+			FAIL 1 "$LINENO" "Incorrect argument(s) specified." ;;
 	esac
 	shift
 done
 
 [ -z "$THEME" ] && THEME="Adwaita"
 
-[ $UID -eq 0 ] || XERR "$LINENO" "Root access is required."
-[ -x /bin/sed ] || XERR "$LINENO" "Dependency '/bin/sed' not met."
-if ! [ -f "$FF" ] || ! [ -r "$FF" ] || ! [ -w "$FF" ]; then
-	XERR "$LINENO" "File "$FF" not found or inaccessible."
+[ $UID -eq 0 ] || FAIL 1 "$LINENO" "Root access is required."
+
+if ! type -fP sed > /dev/null 2>&1; then
+	FAIL 1 "$LINENO" "Dependency '/bin/sed' not met."
+fi
+
+if ! [ -f "$FF" -a -r "$FF" -a -w "$FF" ]; then
+	FAIL 1 "$LINENO" "File "$FF" not found or inaccessible."
 fi
 
 declare -i LINE=0
 STRING='exec\ \$MOZ_LIBDIR\/\$MOZ_APP_NAME\ \"\$\@\"'
+
 while read; do
 	LINE+=1
+
 	if [[ "$REPLY" =~ ^\ +$STRING ]] && [ $LINE -eq 110 ]; then
-		if /bin/sed -in 110s/'^\(\s\+\)'"$STRING"/'\1GTK_THEME="'$THEME'" '"$STRING"/ "$FF"; then
+		if sed -in 110s/'^\(\s\+\)'"$STRING"/'\1GTK_THEME="'$THEME'" '"$STRING"/ "$FF"; then
 			printf "File '%s' modified.\n" "$FF"
 			exit 0
 		else
-			XERR "$LINENO" "File '$FF' failed during editing."
+			FAIL 1 "$LINENO" "File '$FF' failed during editing."
 		fi
 	elif [[ "$REPLY" =~ ^\ +GTK_THEME\=\"$THEME\"\ $STRING ]]; then
 		printf "File '%s' already modified.\n" "$FF"
@@ -90,4 +98,4 @@ while read; do
 	fi
 done < "$FF"
 
-XERR "$LINENO" "File '$FF' contents unexpected."
+FAIL 1 "$LINENO" "File '$FF' contents unexpected."
