Update and address questionable syntax

diff --git a/forex b/forex
--- a/forex
+++ b/forex
@@ -3,15 +3,15 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/forex
 # Started On        - Sun 15 Oct 16:25:38 BST 2017
-# Last Change       - Sun 12 May 16:21:39 BST 2019
+# Last Change       - Wed 27 Nov 15:54:13 GMT 2019
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
 
-_VERSION_="2019-05-12"
-_PROJECT_="${0##*/}"
+_VERSION_="2019-11-27"
+_PROJECT_=${0##*/}
 
-FAIL(){
+Err(){
 	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
 	[ $1 -eq 1 ] && exit 1
 }
@@ -48,11 +48,11 @@ while [ "$1" ]; do
 		--version|-v)
 			printf "%s\n" "$_VERSION_"; exit 0 ;;
 		--debug|-D)
-			DEBUGME="true" ;;
+			DEBUGME='true' ;;
 		--rounded|-R)
-			ROUNDED="true" ;;
+			ROUNDED='true' ;;
 		-*)
-			FAIL 1 "$LINENO" "Incorrect argument(s) specified." ;;
+			Err 1 $LINENO "Incorrect argument(s) specified." ;;
 		*)
 			break ;;
 	esac
@@ -60,12 +60,12 @@ while [ "$1" ]; do
 done
 
 if ! type -fP wget > /dev/null 2>&1; then
-	FAIL 1 "$LINENO" "Dependency 'wget' not met."
+	Err 1 $LINENO "Dependency 'wget' not met."
 fi
 
-SOURCE="$1"
-AMOUNT="$2"
-TARGET="$3"
+SOURCE=$1
+AMOUNT=$2
+TARGET=$3
 
 read -a WGET_VER_LINE <<< "$(wget --version)"
 WGET_VERSION=0${WGET_VER_LINE[2]//[!0-9]}
@@ -73,7 +73,7 @@ if [ $WGET_VERSION -ge 01192 -a $WGET_VERSION -lt 01194 ]; then
 	NOWARC="--no-warc-compression"
 fi
 
-[ "$DEBUGME" == "true" ] && set -x
+[ "$DEBUGME" == 'true' ] && set -x
 
 # Curent and historical currency abbreviations. Taken from: http://www.xe.com
 declare -a VALID=(
@@ -89,30 +89,30 @@ declare -a VALID=(
 )
 
 for TYPE in ${VALID[@]}; {
-	[ "$TYPE" == "$SOURCE" ] && SOURCE_YES="true"
-	[ "$TYPE" == "$TARGET" ] && TARGET_YES="true"
+	[ "$TYPE" == "$SOURCE" ] && SOURCE_YES='true'
+	[ "$TYPE" == "$TARGET" ] && TARGET_YES='true'
 }
 
-if ! [ "$SOURCE_YES" == "true" ]; then
-	FAIL 1 "$LINENO" "Currency SOURCE '$SOURCE' not recognised."
-elif ! [ "$TARGET_YES" == "true" ]; then
-	FAIL 1 "$LINENO" "Currency TARGET '$TARGET' not recognised."
+if ! [ "$SOURCE_YES" == 'true' ]; then
+	Err 1 $LINENO "Currency SOURCE '$SOURCE' not recognised."
+elif ! [ "$TARGET_YES" == 'true' ]; then
+	Err 1 $LINENO "Currency TARGET '$TARGET' not recognised."
 fi
 
 SITE="$DOM/fx-rates/conversion/$AMOUNT/$SOURCE/$TARGET"
 while read -a X; do
-	if [[ "${X[*]}" =~ name=\"answer\" ]]; then
-		RESULT="${X[3]//[!0-9.]}"
+	if [[ ${X[*]} =~ name=\"answer\" ]]; then
+		RESULT=${X[3]//[!0-9.]}
 	fi
 done <<< "$(wget -q -t 1 $NOWARC "$SITE" -O -)"
 
-if [[ "$RESULT" =~ ^[0-9.]+$ ]]; then
-	if [ "$ROUNDED" == "true" ]; then
+if [[ $RESULT =~ ^[0-9.]+$ ]]; then
+	if [ "$ROUNDED" == 'true' ]; then
 		printf "%s\n" "${RESULT%.*}"
 	else
 		printf "%.4f\n" "$RESULT"
 	fi
 else
-	FAIL 1 "$LINENO" "Unable to determine the correct result."
+	Err 1 $LINENO "Unable to determine the correct result."
 fi
 
