Updated isbatlow

diff --git a/isbatlow b/isbatlow
--- a/isbatlow
+++ b/isbatlow
@@ -3,15 +3,18 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/isbatlow
 # Started On        - Sun  8 Apr 20:47:08 BST 2018
-# Last Change       - Thu  9 May 00:57:28 BST 2019
+# Last Change       - Sun 12 May 22:51:50 BST 2019
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
 
-_VERSION_="2019-05-09"
+_VERSION_="2019-05-12"
+_PROJECT_="${0##*/}"
 
-XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
-ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }
+FAIL(){
+	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
+	[ $1 -eq 1 ] && exit 1
+}
 
 DOM="https://github.com"
 
@@ -19,16 +22,15 @@ USAGE(){
 	while read -r; do
 		printf "%s\n" "$REPLY"
 	done <<-EOF
-		            ISBATLOW ($_VERSION_)
+		            ${_PROJECT_^^} ($_VERSION_)
 		            Written by terminalforlife (terminalforlife@yahoo.com)
 
 		            Simple utility for laptops, to check if the battery is low.
 
-		SYNTAX:     isbatlow [OPTS] [CMD]
+		SYNTAX:     $_PROJECT_ [OPTS] [CMD]
 
 		OPTS:       --help|-h|-?            - Displays this help information.
 		            --version|-v            - Output only the version datestamp.
-		            --update|-U             - Check for updates to simplify-ubuntu.
 		            --debug|-D              - Enables the built-in bash debugging.
 		            --interval|-I N         - Set the check interval,in seconds, to N.
 		            --limit|-L N            - Set the battery percentile limit to N.
@@ -52,8 +54,6 @@ while [ "$1" ]; do
 		--version|-v)
 			printf "%s\n" "$_VERSION_"
 			exit 0 ;;
-		--update|-U)
-			UPDATE="true" ;;
 		--debug|-D)
 			DEBUGME="true" ;;
 		--interval|-I)
@@ -61,7 +61,7 @@ while [ "$1" ]; do
 			if [[ "$1" =~ ^[0-9]+$ ]] && [ $1 -gt 0 ]; then
 				LIMIT=$1
 			else
-				XERR "$LINENO" "Invalid interval specified."
+				FAIL 1 "$LINENO" "Invalid interval specified."
 			fi ;;
 		--limit|-L)
 			shift
@@ -69,17 +69,17 @@ while [ "$1" ]; do
 			&& [ $1 -gt 0 -a $1 -lt 100 ]; then
 				LIMIT=$1
 			else
-				XERR "$LINENO" "Invalid limit specified."
+				FAIL 1 "$LINENO" "Invalid limit specified."
 			fi ;;
 		--battery|-B)
 			shift
 			if ! [ "$1" ]; then
-				XERR "$LINENO" "Missing battery specification."
+				FAIL 1 "$LINENO" "Missing battery specification."
 			else
 				BATTERY="$1"
 			fi ;;
 		-*)
-			XERR "$LINENO" "Incorrect argument(s) specified." ;;
+			FAIL 1 "$LINENO" "Incorrect argument(s) specified." ;;
 		*)
 			break ;;
 	esac
@@ -89,52 +89,27 @@ done
 CMD="$@"
 
 declare -i DEPCOUNT=0
-for DEP in /usr/bin/{notify-send,on_ac_power,wget} /bin/sleep; {
-	if ! [ -x "$DEP" ]; then
-		ERR "$LINENO" "Dependency '$DEP' not met."
+for DEP in notify-send on_ac_power wget sleep; {
+	if ! type -fP "$DEP" > /dev/null 2>&1; then
+		FAIL 0 "$LINENO" "Dependency '$DEP' not met."
 		DEPCOUNT+=1
 	fi
 }
 
 [ $DEPCOUNT -eq 0 ] || exit 1
 
-read -a WGET_VER_LINE <<< "$(/usr/bin/wget --version)"
-WGET_VERSION=0${WGET_VER_LINE[2]//[!0-9]}
-if [ $WGET_VERSION -ge 01192 -a $WGET_VERSION -lt 01194 ]; then
-	NOWARC="--no-warc-compression"
-fi
-
-if [ "$UPDATE" == "true" ]; then
-	VERSION_URL="$DOM/terminalforlife/Extra/raw/master/isbatlow-version"
-	LATEST=`/usr/bin/wget $NOWARC -q "$VERSION_URL" -O -`
-	if [[ "${LATEST//-}" =~ ^[0-9]{8}$ ]]; then
-		if [ ${LATEST//-} -gt ${_VERSION_//-} ]; then
-			while read -r; do
-				printf "%s\n" "$REPLY"
-			done <<-EOF
-				New version available:    $LATEST
-				Current version:          $_VERSION_
-			EOF
-		fi
-	else
-		XERR "$LINENO" "Failed to check for available updates."
-	fi
-
-	exit 0
-fi
-
 [ "$DEBUGME" == "true" ] && set -x
 
-if ! /usr/bin/on_ac_power; then
+if ! on_ac_power; then
 	while IFS=":" read -a X; do
 		if [ "${X[0]// }" == "percentage" ]; then
 			if ! [[ "${X[1]// }" =~ ^[0-9]+%$ ]]; then
-				/usr/bin/notify-send --urgency=critical\
+				notify-send --urgency=critical\
 					"Unable to get valid battery value."
-				ERR "$LINENO" "Unable to get valid percentile."
+				FAIL 0 "$LINENO" "Unable to get valid percentile."
 			else
 				if [ ${X[1]%\%} -le $LIMIT ]; then
-					/usr/bin/notify-send --urgency=critical\
+					notify-send --urgency=critical\
 						"Battery is critically low!"
 
 					($CMD)
@@ -143,6 +118,8 @@ if ! /usr/bin/on_ac_power; then
 
 			break
 		fi
-	done <<< "$(/usr/bin/upower -i /org/freedesktop/UPower/devices/$BATTERY)"
-	/bin/sleep ${INTERVAL}s
+	done <<< "$(upower -i /org/freedesktop/UPower/devices/$BATTERY)"
+	sleep ${INTERVAL}s
 fi
+
+# vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
