Add `BaseName()`, `DirName()`, and `ChkDep()`

diff --git a/libtflbp-sh b/libtflbp-sh
--- a/libtflbp-sh
+++ b/libtflbp-sh
@@ -3,7 +3,7 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/libtflbp-sh (Terminal for Life Bourne POSIX)
 # Started On        - Mon  2 Dec 15:32:30 GMT 2019
-# Last Change       - Thu  5 Dec 00:38:05 GMT 2019
+# Last Change       - Thu  5 Dec 20:20:07 GMT 2019
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
@@ -124,9 +124,35 @@ YNInput(){ #: An easy-to-script prompt for the user, asking yes or no.
 		[Nn]|[Nn][Oo])
 			return 1 ;;
 		''|*)
-			printf 'ERROR: Invalid response -- quitting.' 1>&2
-			exit 1 ;;
+			Err 1 'Invalid response -- quitting.' ;;
 	esac
 
 	unset Answer
+}
+
+ChkDep(){ #: Presentable check of PATH directories for dependency $@.
+	DepCount=0
+	for CurDep in "$@"; do
+		if command -v "$CurDep" 1> /dev/null 2>&1; then
+			DepCount=$((DepCount + 1))
+		else
+			Err 0 "Dependency '$CurDep' not met."
+		fi
+	done
+
+	[ $DepCount -eq $# ] || exit 1
+}
+
+BaseName(){ #: Output the base name (like `basename`) of $@.
+	for CurFile in "$@"; do
+		[ -f "$CurFile" ] || return 1
+		printf "%s\n" "${CurFile##*/}"
+	done
+}
+
+DirName(){ #: Output the directory name (like `dirname`) of $@.
+	for CurDir in "$@"; do
+		[ -d "$CurDir" ] || return 1
+		printf "%s\n" "${CurDir%/*}"
+	done
 }
