Updated lspkg-set

diff --git a/lspkg-set b/lspkg-set
--- a/lspkg-set
+++ b/lspkg-set
@@ -3,26 +3,29 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/lspkg-set (List Packages Set)
 # Started On        - Wed 24 Jan 17:31:41 GMT 2018
-# Last Change       - Sat  7 Apr 16:03:15 BST 2018
+# Last Change       - Sun 12 May 23:02:09 BST 2019
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
 
-_VERSION_="2018-04-07"
+_VERSION_="2019-05-12"
+_PROJECT_="${0##*/}"
 
-XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
-ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }
+FAIL(){
+	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
+	[ $1 -eq 1 ] && exit 1
+}
 
 USAGE(){
 	while read -r; do
 		printf "%s\n" "$REPLY"
 	done <<-EOF
-		            LSPKG-SET ($_VERSION_)
+		            ${_PROJECT_^^} ($_VERSION_)
 		            Written by terminalforlife (terminalforlife@yahoo.com)
 
 		            Add-on for lspkg to output sets of installed packages.
 
-		SYNTAX:     lspkg-set [OPT]
+		SYNTAX:     $_PROJECT_ [OPT]
 
 		OPTS:       --help|-h|-?            - Displays this help information.
 		            --version|-v            - Output only the version datestamp.
@@ -54,11 +57,11 @@ case "$*" in
 	--important|-I)
 		TYPE="Priority:important" ;;
 	*)
-		XERR "$LINENO" "Incorrect argument(s) specified." ;;
+		FAIL 1 "$LINENO" "Incorrect argument(s) specified." ;;
 esac
 
-if ! [ -x "/usr/bin/dpkg-query" ]; then
-	XERR "$LINENO" "Dependency '/usr/bin/dpkg-query' not met."
+if ! type -fP dpkg-query > /dev/null 2>&1; then
+	FAIL 1 "$LINENO" "Dependency 'dpkg-query' not met."
 fi
 
 #TODO - Not seeing the Binary:Summary of the packages.
@@ -81,6 +84,6 @@ while read -a X; do
 			printf "%s\n" "$NEW"
 		fi
 	fi
-done <<< "$(/usr/bin/dpkg-query -Wf="${FMT1}${FMT2}\n" \*)"
+done <<< "$(dpkg-query -Wf="${FMT1}${FMT2}\n" \*)"
 
 # vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
