Updated medlog

diff --git a/medlog b/medlog
--- a/medlog
+++ b/medlog
@@ -3,7 +3,7 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/medlog
 # Started On        - Fri 18 Nov ??:??:?? BST 2016
-# Last Change       - Thu  9 May 00:57:55 BST 2019
+# Last Change       - Sun 12 May 23:07:26 BST 2019
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
@@ -13,25 +13,27 @@
 #          so I may include that at some point.
 #----------------------------------------------------------------------------------
 
-_VERSION_="2019-05-09"
+_VERSION_="2019-05-12"
+_PROJECT_="${0##*/}"
 
-XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
-ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }
+FAIL(){
+	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
+	[ $1 -eq 1 ] && exit 1
+}
 
 USAGE(){
 	while read -r; do
 		printf "%s\n" "$REPLY"
 	done <<-EOF
-		            MEDLOG ($_VERSION_)
+		            ${_PROJECT_^^} ($_VERSION_)
 		            Written by terminalforlife (terminalforlife@yahoo.com)
 
 		            Need help logging when you've taken your daily medication?
 
-		SYNTAX:     medlog [OPTS]
+		SYNTAX:     $_PROJECT_ [OPTS]
 
 		OPTS:       --help|-h|-?            - Displays this help information.
 		            --version|-v            - Output only the version datestamp.
-		            --debug|-D              - Enables the built-in bash debugging.
 	EOF
 }
 
@@ -40,35 +42,28 @@ while [ "$1" ]; do
 		--help|-h|-\?)
 			USAGE; exit 0 ;;
 		--version|-v)
-			printf "%s\n" "$_VERSION_"
-			exit 0 ;;
-		--debug|-D)
-			DEBUGME="true" ;;
-		--quiet|-q)
-			BEQUIET="true" ;;
+			printf "%s\n" "$_VERSION_"; exit 0 ;;
 		*)
-			XERR "$LINENO" "Incorrect argument(s) specified." ;;
+			FAIL 1 "$LINENO" "Incorrect argument(s) specified." ;;
 	esac
 	shift
 done
 
 declare -i DEPCOUNT=0
-for DEP in /usr/bin/{xmessage,notify-send} /bin/mkdir; {
-	if ! [ -x "$DEP" ]; then
-		ERR "$LINENO" "Dependency '$DEP' not met."
+for DEP in xmessage notify-send mkdir; {
+	if ! type -fP "$DEP" > /dev/null 2>&1; then
+		FAIL 0 "$LINENO" "Dependency '$DEP' not met."
 		DEPCOUNT+=1
 	fi
 }
 
 [ $DEPCOUNT -eq 0 ] || exit 1
 
-[ "$DEBUGME" == "true" ] && set -x
-
-MAINDIR="$HOME/.medlog"
-LOGFILE="$MAINDIR/medlog.log"
-[ -d "$MAINDIR" ] || /bin/mkdir -p "$MAINDIR"
+MAINDIR="$HOME/.$_PROJECT_"
+LOGFILE="$MAINDIR/$_PROJECT_.log"
+[ -d "$MAINDIR" ] || mkdir -p "$MAINDIR"
 [ -f "$LOGFILE" ] || > "$LOGFILE"
-[ -w "$LOGFILE" ] || XERR "$LINENO" "File '${LOGFILE//*\/}' has no write access."
+[ -w "$LOGFILE" ] || FAIL 1 "$LINENO" "File '${LOGFILE//*\/}' has no write access."
 
 while read -a X; do
 	printf -v LAST_LOG "%s\n" "${X[0]}"
@@ -76,13 +71,13 @@ done < "$LOGFILE"
 
 printf -v TODAY_DATE "%(%F (%X))T" -1
 MSG="Medication taken today, $USER?"
-MSG_NO="Take medication, then reload medlog."
+MSG_NO="Take medication, then reload $_PROJECT_."
 if [ "${TODAY_DATE%/*}" == "${LAST_LOG%/*}" ]; then
-	/usr/bin/notify-send "Medication already taken today."
+	notify-send "Medication already taken today."
 else
-	if ! /usr/bin/xmessage -buttons yes,no -center "$MSG"; then
+	if ! xmessage -buttons yes,no -center "$MSG"; then
 		#TODO - Loop a reminder notification every X minutes.
-		/usr/bin/notify-send "$MSG_NO"
+		notify-send "$MSG_NO"
 		exit 1
 	else
 		printf "%(%F (%X))T\n" -1 >> "$LOGFILE"
