Updated mif; minor code changes

diff --git a/mif b/mif
--- a/mif
+++ b/mif
@@ -3,7 +3,7 @@
 #----------------------------------------------------------------------------------
 # Project Name      - miscellaneous/mif (Movie Index Filter)
 # Started On        - Fri 13 Oct 13:21:13 BST 2017
-# Last Change       - Wed  1 Nov 17:28:11 GMT 2017
+# Last Change       - Tue  9 Jan 18:51:34 GMT 2018
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
@@ -15,9 +15,9 @@ shopt -s extglob globstar
 
 USAGE(){
 	while read -r; do
-		echo "$REPLY"
+		printf "%s\n" "$REPLY"
 	done <<-EOF
-		            MIF - Movie Index Filter (1st November 2017)
+		            MIF - Movie Index Filter (9th January 2018)
 		            Written by terminalforlife (terminalforlife@yahoo.com)
 		
 		            Shell program to filter films by year and whether seen or not.
@@ -69,12 +69,12 @@ MAKE_LIST(){
 	for FILE in **; {
 		[ -f "$FILE" ] && {
 			#TODO - Find pure shell approach. Use variable buffers?
-			echo "${FILE% (*}" | /bin/sed "s/\//${1}: /"
+			printf "%s\n" "${FILE% (*}" | /bin/sed "s/\//${1}: /"
 		}
 	}
 }
 
-while [ -n "$1" ]; do
+while [ "$1" ]; do
 	case "$1" in
 		--help|-h|-\?)
 			USAGE; exit 0 ;;
@@ -109,7 +109,7 @@ while [ -n "$1" ]; do
 done
 
 [ "$ORGANIZE" == "true" ] || {
-	if [[ "$1" == +([0-9]) ]]; then
+	if [[ "$1" =~ ^[0-9]+$ ]]; then
 		YEAR="$1"
 		shift
 	else
@@ -129,22 +129,26 @@ done
 [ "$ORGANIZE" == "true" ] && {
 	[ -e /dev/null ] || XERR "$LINENO" "Unable to find: /dev/null"
 
-	[ -x /bin/mkdir -a -x /bin/mv ] || {
+	if ! [ -x /bin/mkdir -a -x /bin/mv ]; then
 		XERR "$LINENO" "Dependency '/bin/mkdir' or '/bin/mv' not met."
-	}
+	fi
 
 	for X in *; {
 		Y="${X//*\(}"
 
-		[[ "${Y%\)*}" == +([0-9]) ]] || continue
+		[[ "${Y%\)*}" =~ ^[0-9]+$ ]] || continue
 
-		/bin/mkdir "${Y%\)*}" && {
-			echo "MAKE: ${Y%\)*}"
-		} || echo "FAIL: ${Y%\)*}"
+		if /bin/mkdir "${Y%\)*}"; then
+			printf "%s\n" "MAKE: ${Y%\)*}"
+		else
+			printf "%s\n" "FAIL: ${Y%\)*}"
+		fi
 
-		/bin/mv "$X" ${Y%\)*}/ && {
-			echo "MOVE: ${Y%\)*}/${X//*\/}"
-		} || echo "FAIL: ${Y%\)*}/${X//*\/}"
+		if /bin/mv "$X" ${Y%\)*}/; then
+			printf "%s\n" "MOVE: ${Y%\)*}/${X//*\/}"
+		else
+			printf "%s\n" "FAIL: ${Y%\)*}/${X//*\/}"
+		fi
 	} # 2> /dev/null
 
 	exit 0
@@ -156,26 +160,24 @@ declare -i LINE=0
 while read -r; do
 	{ [[ "$REPLY" == +(#)* ]] || [ -z "$REPLY" ]; } && continue
 
-	[ "$NOSTATUS" == "false" ] && {
+	if [ "$NOSTATUS" == "false" ]; then
 		if [ "$SEEN" == "false"  ]; then
 			[[ "$REPLY" == $YEAR\[\+\]:\ * ]] && {
-				echo "${REPLY/+([0-9])\[?\]: }"; LINE+=1
+				printf "%s\n" "${REPLY/+([0-9])\[?\]: }"; LINE+=1
 			}
 		elif [ "$SEEN" == "true"  ]; then
 			[[ "$REPLY" == $YEAR\[\-\]:\ * ]] && {
-				echo "${REPLY/+([0-9])\[?\]: }"; LINE+=1
+				printf "%s\n" "${REPLY/+([0-9])\[?\]: }"; LINE+=1
 			}
 		elif [ "$SEEN" == "all"  ]; then
-			echo "${REPLY/+([0-9])\[?\]: }"; LINE+=1
+			printf "%s\n" "${REPLY/+([0-9])\[?\]: }"; LINE+=1
 		fi
-	} || {
-		[[ "$REPLY" == $YEAR:\ * ]] && {
-			echo "${REPLY/+([0-9])\[?\]: }"; LINE+=1
-		}
-	}
+	else
+		if [[ "$REPLY" == $YEAR:\ * ]]; then
+			printf "%s\n" "${REPLY/+([0-9])\[?\]: }"; LINE+=1
+		fi
+	fi
 done < "$INDEX"
 
 [ $LINE -eq 0 ] && XERR "$LINENO" "Unable to find year $YEAR."
 [ "$TTL" == "true" ] && printf "\nTotal: %d\n" "$LINE"
-
-[ "$DEBUGME" == "true" ] && set +xeu || exit 0
