Update and address questionable syntax

diff --git a/mif b/mif
--- a/mif
+++ b/mif
@@ -3,15 +3,15 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/mif (Movie Index Filter)
 # Started On        - Fri 13 Oct 13:21:13 BST 2017
-# Last Change       - Sun 12 May 23:13:01 BST 2019
+# Last Change       - Wed 27 Nov 15:56:20 GMT 2019
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
 
-_VERSION_="2019-05-12"
-_PROJECT_="${0##*/}"
+_VERSION_="2019-11-27"
+_PROJECT_=${0##*/}
 
-FAIL(){
+Err(){
 	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
 	[ $1 -eq 1 ] && exit 1
 }
@@ -67,12 +67,12 @@ USAGE(){
 if [ "${BASH_VERSINFO[0]}" -ge 4 ]; then
 	shopt -s extglob globstar
 else
-	FAIL 1 "$LINENO" "Bash version 4.0 or greater is required."
+	Err 1 $LINENO "Bash version 4.0 or greater is required."
 fi
 
 INDEX="$HOME/.$_PROJECT_"
-SEEN="false"
-TTL="false"
+SEEN='false'
+TTL='false'
 
 while [ "$1" ]; do
 	case $1 in
@@ -81,7 +81,7 @@ while [ "$1" ]; do
 		--version|-v)
 			printf "%s\n" "$_VERSION_"; exit 0 ;;
 		--debug|-D)
-			DEBUGME="true" ;;
+			DEBUGME='true' ;;
 		--mklist|-M)
 			shift; MAKE_LIST_OPT=":[+]" ;;
 		--mklist:N|-M:N)
@@ -93,13 +93,13 @@ while [ "$1" ]; do
 		--mark)
 			shift; MARK="$1" ;;
 		--organize|-O)
-			ORGANIZE="true" ;;
+			ORGANIZE='true' ;;
 		--total|-t)
-			TTL="true" ;;
+			TTL='true' ;;
 		--seen|-s)
-			SEEN="true" ;;
+			SEEN='true' ;;
 		--unseen|-u)
-			SEEN="false" ;;
+			SEEN='false' ;;
 		*)
 			break ;;
 	esac
@@ -109,14 +109,14 @@ done
 declare -i DEPCOUNT=0
 for DEP in mkdir mv; {
 	if ! type -fP "$DEP" > /dev/null 2>&1; then
-		FAIL 0 "$LINENO" "Dependency '$DEP' not met."
+		Err 0 $LINENO "Dependency '$DEP' not met."
 		DEPCOUNT+=1
 	fi
 }
 
 [ $DEPCOUNT -eq 0 ] || exit 1
 
-if [[ "$MAKE_LIST_OPT" =~ (:|:\[+\]) ]]; then
+if [[ $MAKE_LIST_OPT =~ (:|:\[+\]) ]]; then
 	for FILE in **; {
 		[ -f "$FILE" ] || continue
 		IFS="/" read -a X <<< "${FILE% (*}"
@@ -126,54 +126,54 @@ if [[ "$MAKE_LIST_OPT" =~ (:|:\[+\]) ]]; then
 	exit 0
 fi
 
-if ! [ "$ORGANIZE" == "true" ]; then
-	if [[ "$1" =~ ^[0-9]+$ ]]; then
+if ! [ "$ORGANIZE" == 'true' ]; then
+	if [[ $1 =~ ^[0-9]+$ ]]; then
 		YEAR="$1"; shift
 	else
 		if ! [ "$SEEN" == "all" ]; then
-			FAIL 1 "$LINENO" "Invalid year specified."
+			Err 1 $LINENO "Invalid year specified."
 		fi
 	fi
 fi
 
-[ "$*" ] && FAIL 1 "$LINENO" "Incorrect argument(s) specified."
+[ "$*" ] && Err 1 $LINENO "Incorrect argument(s) specified."
 
-[ "$DEBUGME" == "true" ] && set -x
+[ "$DEBUGME" == 'true' ] && set -x
 
-if [ "$ORGANIZE" == "true" ]; then
+if [ "$ORGANIZE" == 'true' ]; then
 	for X in *; {
-		Y="${X//*\(}"
+		Y=${X//*\(}
 
-		[[ "${Y%\)*}" =~ ^[0-9]+$ ]] || continue
+	 [[ ${Y%\)*} =~ ^[0-9]+$ ]] || continue
 
 		if mkdir "${Y%\)*}"; then
 			printf "%s\n" "MAKE: ${Y%\)*}"
 		else
-			printf "%s\n" "FAIL: ${Y%\)*}"
+			printf "%s\n" "Err: ${Y%\)*}"
 		fi
 
 		if mv "$X" ${Y%\)*}/; then
 			printf "%s\n" "MOVE: ${Y%\)*}/${X//*\/}"
 		else
-			printf "%s\n" "FAIL: ${Y%\)*}/${X//*\/}"
+			printf "%s\n" "Err: ${Y%\)*}/${X//*\/}"
 		fi
 	}
 
 	exit 0
 fi
 
-[ -f "$INDEX" ] || FAIL 1 "$LINENO" "Index file '$INDEX' not found."
+[ -f "$INDEX" ] || Err 1 $LINENO "Index file '$INDEX' not found."
 
 declare -i LINE=0
 while read -r; do
-	{ [[ "$REPLY" == +(#)* ]] || [ -z "$REPLY" ]; } && continue
-	if [ "$SEEN" == "false"  ]; then
-		if [[ "$REPLY" == $YEAR\[\+\]:\ * ]]; then
+	{ [[ $REPLY == +(#)* ]] || [ -z "$REPLY" ]; } && continue
+	if [ "$SEEN" == 'false'  ]; then
+		if [[ $REPLY == $YEAR\[\+\]:\ * ]]; then
 			printf "%s\n" "${REPLY/+([0-9])\[?\]: }"
 			LINE+=1
 		fi
-	elif [ "$SEEN" == "true"  ]; then
-		if [[ "$REPLY" == $YEAR\[\-\]:\ * ]]; then
+	elif [ "$SEEN" == 'true'  ]; then
+		if [[ $REPLY == $YEAR\[\-\]:\ * ]]; then
 			printf "%s\n" "${REPLY/+([0-9])\[?\]: }"
 			LINE+=1
 		fi
@@ -183,6 +183,6 @@ while read -r; do
 	fi
 done < "$INDEX"
 
-[ $LINE -eq 0 ] && FAIL 1 "$LINENO" "Unable to find year $YEAR."
-[ "$TTL" == "true" ] && printf "\nTotal: %d\n" "$LINE"
+[ $LINE -eq 0 ] && Err 1 $LINENO "Unable to find year $YEAR."
+[ "$TTL" == 'true' ] && printf "\nTotal: %d\n" "$LINE"
 
