Updated mkpass

diff --git a/mkpass b/mkpass
--- a/mkpass
+++ b/mkpass
@@ -3,26 +3,29 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/mkpass
 # Started On        - Fri 20 Oct 12:14:09 BST 2017
-# Last Change       - Thu  9 May 00:58:09 BST 2019
+# Last Change       - Sun 12 May 23:14:45 BST 2019
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
 
-_VERSION_="2019-05-09"
+_VERSION_="2019-05-12"
+_PROJECT_="${0##*/}"
 
-XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
-ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }
+FAIL(){
+	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
+	[ $1 -eq 1 ] && exit 1
+}
 
 USAGE(){
 	while read -r; do
 		printf "%s\n" "$REPLY"
 	done <<-EOF
-		            MKPASS ($_VERSION_)
+		            ${_PROJECT_^^} ($_VERSION_)
 		            Written by terminalforlife (terminalforlife@yahoo.com)
 
 		            Pure Bourne Again Shell approach to complex password generation.
 
-		SYNTAX:     mkpass [OPTS] INT
+		SYNTAX:     $_PROJECT_ [OPTS] INT
 
 		OPTS:       --help|-h|-?            - Displays this help information.
 		            --version|-v            - Output only the version datestamp.
@@ -53,12 +56,11 @@ while [ "$1" ]; do
 		--help|-h|-\?)
 			USAGE; exit 0 ;;
 		--version|-v)
-			printf "%s\n" "$_VERSION_"
-			exit 0 ;;
+			printf "%s\n" "$_VERSION_"; exit 0 ;;
 		--type|-t)
 			shift; TYPE="$1" ;;
 		-*)
-			XERR "$LINENO" "Incorrect argument(s) specified." ;;
+			FAIL 1 "$LINENO" "Incorrect argument(s) specified." ;;
 		*)
 			break ;;
 	esac
@@ -68,11 +70,11 @@ done
 if [[ "$1" =~ [0-9]+ ]]; then
 	INT=$1
 elif [ -z "$INT" ]; then
-	XERR "$LINENO" "Invalid or missing INT."
+	FAIL 1 "$LINENO" "Invalid or missing INT."
 elif ! [ -e /dev/urandom ]; then
-	XERR "$LINENO" "Unable to access /dev/urandom device."
+	FAIL 1 "$LINENO" "Unable to access /dev/urandom device."
 elif ! [[ "$*" =~ [0-9]+ ]] && [ "$INT" -ge 1 ]; then
-	XERR "$LINENO" "Requires an integer greater than or equal to 1."
+	FAIL 1 "$LINENO" "Requires an integer greater than or equal to 1."
 fi
 
 case "${TYPE:-EMPTY}" in
@@ -87,7 +89,7 @@ case "${TYPE:-EMPTY}" in
 	alphapunct|EMPTY)
 		CHARS='[\`/\+\\\|0-9A-Za-z\_\,\.\?\!\"\\\/\$\%\^\&\*\(\)\{\}\]\[-\>\<\:\@\~]' ;;
 	*)
-		XERR "$LINENO" "Invalid TYPE selected." ;;
+		FAIL 1 "$LINENO" "Invalid TYPE selected." ;;
 esac
 
 declare -i A=0
@@ -101,4 +103,4 @@ done < /dev/urandom
 
 printf "\n"
 
-# vim: ft=sh noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
+# vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
