Update and address questionable syntax

diff --git a/notify-upgrade b/notify-upgrade
--- a/notify-upgrade
+++ b/notify-upgrade
@@ -3,15 +3,15 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/notify-upgrade
 # Started On        - Sun 17 Sep 16:07:59 BST 2017
-# Last Change       - Sun 12 May 23:23:38 BST 2019
+# Last Change       - Wed 27 Nov 15:56:25 GMT 2019
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
 
-_VERSION_="2019-05-12"
-_PROJECT_="${0##*/}"
+_VERSION_="2019-11-27"
+_PROJECT_=${0##*/}
 
-FAIL(){
+Err(){
 	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
 	[ $1 -eq 1 ] && exit 1
 }
@@ -46,17 +46,17 @@ while [ "$1" ]; do
 			printf "%s\n" "$_VERSION_"
 			exit 0 ;;
 		--quiet|-q)
-			BEQUIET="true" ;;
+			BEQUIET='true' ;;
 		--debug|-D)
-			DEBUGME="true" ;;
+			DEBUGME='true' ;;
 		--interval|-i)
-			shift; INT="$1"
+			shift; INT=$1
 
-			if ! [[ "$INT" =~ ^[0-9]+$ ]]; then
-				FAIL 1 "$LINENO" "Invalid, non-integer minute interval set."
+			if ! [[ $INT =~ ^[0-9]+$ ]]; then
+				Err 1 $LINENO "Invalid, non-integer minute interval set."
 			fi ;;
 		*)
-			FAIL 1 "$LINENO" "Incorrect argument(s) specified." ;;
+			Err 1 $LINENO "Incorrect argument(s) specified." ;;
 	esac
 	shift
 done
@@ -64,7 +64,7 @@ done
 declare -i DEPCOUNT=0
 for DEP in sleep apt-get notify-send; {
 	if ! type -fP "$DEP" > /dev/null 2>&1; then
-		FAIL 0 "$LINENO" "Dependency '$DEP' not met."
+		Err 0 $LINENO "Dependency '$DEP' not met."
 		DEPCOUNT+=1
 	fi
 }
@@ -75,12 +75,12 @@ OPT='APT::Get::Show-User-Simulation-Note=0'
 
 while :; do
         while read -a X; do
-                if [[ "${X[*]}" == *not\ to\ upgrade. ]]; then
+                if [[ ${X[*]} == *not\ to\ upgrade. ]]; then
                         SUM="$((${X[0]}+${X[3]}))"
 			MSG="APT: $SUM package(s) due for update."
 
-                        if ! [[ "$SUM" =~ ^[0-9]+$ ]]; then
-                                FAIL 1 "$LINENO" "Invalid SUM detected."
+                        if ! [[ $SUM =~ ^[0-9]+$ ]]; then
+                                Err 1 $LINENO "Invalid SUM detected."
                         elif [ $SUM -gt 0 ]; then
 				notify-send --urgency=critical "$MSG"
                         fi
