Add obligatory tests

diff --git a/nts b/nts
--- a/nts
+++ b/nts
@@ -3,14 +3,14 @@
 #----------------------------------------------------------------------------------
 # Project Name      - nts (Note to Self)
 # Started On        - Sun 10 Nov 23:54:20 GMT 2019
-# Last Change       - Sun 10 Nov 23:56:02 GMT 2019
+# Last Change       - Mon 11 Nov 00:28:49 GMT 2019
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
 # Work in progress...
 #----------------------------------------------------------------------------------
 
-_VERSION_="2019-11-10"
+_VERSION_="2019-11-11"
 _PROJECT_="${0##*/}"
 
 FAIL(){
@@ -59,7 +59,7 @@ while [ "$1" ]; do
 done
 
 declare -i DEPCOUNT=0
-for DEP in :; {
+for DEP in mkdir; {
 	if ! type -fP "$DEP" > /dev/null 2>&1; then
 		FAIL 0 "$LINENO" "Dependency '$DEP' not met."
 		DEPCOUNT+=1
@@ -97,3 +97,22 @@ if [ "$UPDATE" == "true" ]; then
 fi
 
 [ "$DEBUGME" == "true" ] && set -x
+
+MAIN_DIR="$HOME/.config/nts"
+DB="$MAIN_DIR/db"
+
+if ! [ -d "$MAIN_DIR" ]; then
+	mkdir -p "$MAIN_DIR" || FAIL 1 "$LINENO" "Unable to make 'nts' directory."
+fi
+
+if ! [ -f "$DB" ]; then
+	> "$DB" || FAIL 1 "$LINENO" "Unable to generate a database."
+else
+	if ! [ -r "$DEB" ]; then
+		FAIL 1 "$LINENO" "Unable to read the database."
+	fi
+fi
+
+PARSEDB(){
+	:
+}
