Update and address questionable syntax

diff --git a/nwchk b/nwchk
--- a/nwchk
+++ b/nwchk
@@ -3,17 +3,17 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/nwchk (Network Check)
 # Started On        - Thu 18 Apr 11:19:19 BST 2019
-# Last Change       - Sun 12 May 23:28:16 BST 2019
+# Last Change       - Wed 27 Nov 15:56:29 GMT 2019
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
 # Written by inspiration of YouTube and Arch user, 'S3NTYN3L'.
 #----------------------------------------------------------------------------------
 
-_VERSION_="2019-05-12"
-_PROJECT_="${0##*/}"
+_VERSION_="2019-11-27"
+_PROJECT_=${0##*/}
 
-FAIL(){
+Err(){
 	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
 	[ $1 -eq 1 ] && exit 1
 }
@@ -74,41 +74,41 @@ while [ "$1" ]; do
 			printf "%s\n" "$_VERSION_"
 			exit 0 ;;
 		--quiet|-q)
-			BEQUIET="true" ;;
+			BEQUIET='true' ;;
 		--debug|-D)
-			DEBUGME="true" ;;
+			DEBUGME='true' ;;
 		--once-only|-o)
-			ONCE="true" ;;
+			ONCE='true' ;;
 		--interval|-i)
 			shift
 
-			if ! [[ "$1" =~ ^[0-9]+$ ]] || [ $1 -lt 3 ]; then
-				FAIL 1 "$LINENO" "Invalid seconds of interval provided."
+			if ! [[ $1 =~ ^[0-9]+$ ]] || [ $1 -lt 3 ]; then
+				Err 1 $LINENO "Invalid seconds of interval provided."
 			fi
 
 			declare -i INT=$1 ;;
 		--log|-l)
-			LOG="true" ;;
+			LOG='true' ;;
 		--logfile|-L)
 			shift; LOGFILE="$1" ;;
 		--internet|-I)
-			INTERNET="true" ;;
+			INTERNET='true' ;;
 		--bell|-b)
-			BELL="true" ;;
+			BELL='true' ;;
 		--ping-addr|-p)
 			shift
 
-			if ! [[ "$1" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-				FAIL 1 "$LINENO" "Invalid ping IP address provided."
+			if ! [[ $1 =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+				Err 1 $LINENO "Invalid ping IP address provided."
 			fi
 
 			IP="$1" ;;
 		--spider-addr|-S)
 			shift; SPIDER="$1" ;;
 		--no-notify|-N)
-			NO_NOTIFY="true" ;;
+			NO_NOTIFY='true' ;;
 		--*)
-			FAIL 1 "$LINENO" "Incorrect argument(s) specified." ;;
+			Err 1 $LINENO "Incorrect argument(s) specified." ;;
 		*)
 			break ;;
 	esac
@@ -117,28 +117,28 @@ done
 
 #TODO - Check for -S and/or -p but no -I.
 
-if [ "$INT" -a "$ONCE" == "true" ]; then
-	FAIL 1 "$LINENO" "Interval specified, but $_PROJECT_ was told to run once."
+if [ "$INT" -a "$ONCE" == 'true' ]; then
+	Err 1 $LINENO "Interval specified, but $_PROJECT_ was told to run once."
 fi
 
-if ! [ "$LOG" == "true" ] && [ "$LOGFILE" ]; then
-	FAIL 1 "$LINENO" "Logfile specified, but $_PROJECT_ wasn't told to log."
+if ! [ "$LOG" == 'true' ] && [ "$LOGFILE" ]; then
+	Err 1 $LINENO "Logfile specified, but $_PROJECT_ wasn't told to log."
 fi
 
 if ! [ "$*" ]; then
-	FAIL 1 "$LINENO" "Missing user-specified network interface."
+	Err 1 $LINENO "Missing user-specified network interface."
 else
 	if [ "${#@}" -gt 1 ]; then
-		FAIL 1 "$LINENO" "Only one interface may be specified at one time."
+		Err 1 $LINENO "Only one interface may be specified at one time."
 	else
-		IFACE="$1"
+		IFACE=$1
 	fi
 fi
 
 declare -i DEPCOUNT=0
 for DEP in dirname sleep ping notify-send; {
 	if ! type -Pf "$DEP" > /dev/null 2>&1; then
-		FAIL 0 "$LINENO" "Dependency '$DEP' not met."
+		Err 0 $LINENO "Dependency '$DEP' not met."
 		DEPCOUNT+=1
 	fi
 }
@@ -146,33 +146,33 @@ for DEP in dirname sleep ping notify-send; {
 [ $DEPCOUNT -eq 0 ] || exit 1
 
 if type -Pf ip > /dev/null 2>&1; then
-	USEIP="true"
+	USEIP='true'
 elif type -Pf ifconfig > /dev/null 2>&1; then
-	USEIF="true"
+	USEIF='true'
 else
-	FAIL 1 "$LINENO" "Unable to find applicable executable."
+	Err 1 $LINENO "Unable to find applicable executable."
 fi
 
-if [ "$INTERNET" == "true" ] && ! type -Pf ping > /dev/null 2>&1; then
-	FAIL 1 "$LINENO" "Dependency 'ping' not met."
+if [ "$INTERNET" == 'true' ] && ! type -Pf ping > /dev/null 2>&1; then
+	Err 1 $LINENO "Dependency 'ping' not met."
 fi
 
 # Prefer ip, if both are found, as ifconfig is deprecated.
-[ "$USEIP" == "true" -a "$USEIF" == "true" ] && unset USEIF
+[ "$USEIP" == 'true' -a "$USEIF" == 'true' ] && unset USEIF
 
-[ "$BEQUIET" == "true" ] && exec > /dev/null
-[ "$DEBUGME" == "true" ] && set -x
+[ "$BEQUIET" == 'true' ] && exec > /dev/null
+[ "$DEBUGME" == 'true' ] && set -x
 
 NOTIFY(){
-	if ! [ "$NO_NOTIFY" == "true" ]; then
+	if ! [ "$NO_NOTIFY" == 'true' ]; then
 		#TODO - Add exclamation or other type of alert icon.
 		if ! notify-send --urgency=$1 "$2"; then
 			LOGIT="Unable to send a notification."
-			FAIL 1 "$LINENO" "Unable to send a notification -- quitting."
+			Err 1 $LINENO "Unable to send a notification -- quitting."
 		fi
 	fi
 
-	if [ "$BELL" == "true" ]; then
+	if [ "$BELL" == 'true' ]; then
 		for I in {1..3}; { printf "\a"; sleep 1s; }
 	fi
 }
@@ -181,14 +181,14 @@ LOGIT(){
 	# If logfile is or becomes invalid during loop, go with the default.
 	[ "$LOGFILE" ] || LOGFILE="$HOME/.$_PROJECT_.log"
 
-	if [ "$LOG" == "true" ]; then
+	if [ "$LOG" == 'true' ]; then
 		printf "%(%F_%X)T: %s\n" -1 "$1" >> "$LOGFILE"
 	fi
 }
 
 EXIT(){
 	LOGIT "NWCHK has exited."
-	if ! [ "$ONCE" == "true" ]; then
+	if ! [ "$ONCE" == 'true' ]; then
 		NOTIFY normal "No longer checking network connectivity."
 	fi
 }
@@ -198,25 +198,25 @@ trap 'EXIT' EXIT
 LOGIT "Begun checking network connectivity."
 
 while :; do
-	if [ "$USEIP" == "true" ]; then
+	if [ "$USEIP" == 'true' ]; then
 		for WORD in `ip link show "$IFACE"`; {
-			if [ "$GET_STATE" == "true" -a "$WORD" == "DOWN" ]; then
+			if [ "$GET_STATE" == 'true' -a "$WORD" == "DOWN" ]; then
 				LOGIT "Network '$IFACE' detected as 'DOWN' by ip."
 				NOTIFY critical "Network connectivity error(s) detected."
 
 				break
 			elif [ "$WORD" == "state" ]; then
-				GET_STATE="true"
+				GET_STATE='true'
 			fi
 		}
-	elif [ "$USEIF" == "true" ]; then
+	elif [ "$USEIF" == 'true' ]; then
 		while read -a X; do
 			if [ "${X[0]}" == "UP" ]; then
 				for WORD in ${X[@]}; {
-					[ "$WORD" == "RUNNING" ] && RUNNING="true"
+					[ "$WORD" == "RUNNING" ] && RUNNING='true'
 				}
 
-				if ! [ "$RUNNING" == "true" ]; then
+				if ! [ "$RUNNING" == 'true' ]; then
 					LOGIT "Network '$IFACE' not detected as 'RUNNING' by ifconfig."
 					NOTIFY critical "Network connectivity error(s) detected."
 				fi
@@ -224,7 +224,7 @@ while :; do
 		done <<< "$(ifconfig "$IFACE")"
 	fi
 
-	if [ "$INTERNET" == "true" ]; then
+	if [ "$INTERNET" == 'true' ]; then
 		if type -Pf wget > /dev/null 2>&1; then
 			if ! wget -q -T 3 --spider "$SADDR"; then
 				LOGIT "Unable to confirm server availability."
@@ -237,7 +237,7 @@ while :; do
 		fi
 	fi
 
-	if ! [ "$ONCE" == "true" ]; then
+	if ! [ "$ONCE" == 'true' ]; then
 		sleep ${INT:-10}s
 	else
 		break
