Updated nxbt

diff --git a/nxbt b/nxbt
--- a/nxbt
+++ b/nxbt
@@ -1,19 +1,22 @@
 #!/bin/bash
 
 #----------------------------------------------------------------------------------
-# Project Name      - Extra/nxbt
+# Project Name      - Extra/nxbt (New XBT)
 # Started On        - Fri  6 Oct 17:52:55 BST 2017
-# Last Change       - Thu  9 May 00:58:25 BST 2019
+# Last Change       - Sun 12 May 23:33:04 BST 2019
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
 
-_VERSION_="2019-05-09"
+_VERSION_="2019-05-12"
+_PROJECT_="${0##*/}"
 
 declare -i SECONDS=0
 
-XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
-ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }
+FAIL(){
+	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
+	[ $1 -eq 1 ] && exit 1
+}
 
 DOM="https://github.com"
 
@@ -21,28 +24,27 @@ USAGE(){
 	while read -r; do
 		printf "%s\n" "$REPLY"
 	done <<-EOF
-		            NXBT - NEW XBT ($_VERSION_)
+		            ${_PROJECT_^^} - NEW XBT ($_VERSION_)
 		            Written by terminalforlife (terminalforlife@yahoo.com)
 
 		            A fork and improvement of the XBT program written by Joe Collins.
 
-		SYNTAX:     nxbt [OPTS] TARGET
+		SYNTAX:     $_PROJECT_ [OPTS] TARGET
 
 		OPTS:       --help|-h|-?            - Displays this help information.
 		            --version|-v            - Output only the version datestamp.
 		            --quiet|-q              - Runs in quiet mode. Errors still output.
-		            --update|-U             - Check for updates to nxbt.
 		            --debug|-D              - Enables the built-in bash debugging.
 		            --log|-l PATH           - Choose a different location for the logfile.
 
 		NOTE:       Where TARGET is the location to store the backed up files. The files
 		            will be stored within a timestamped directory. An example TARGET:
 
-		              nxbt /media/\$USER/Backup_Drive/
+		              $_PROJECT_ /media/\$USER/Backup_Drive/
 
-		FILE:       By default, errors are redirected to: /tmp/nxbt_*.log
+		FILE:       By default, errors are redirected to: /tmp/${_PROJECT_}_*.log
 
-		SITE:       $DOM/terminalforlife/nxbt
+		SITE:       $DOM/terminalforlife/$_PROJECT_
 	EOF
 }
 
@@ -58,8 +60,6 @@ while [ "$1" ]; do
 			exit 0 ;;
 		--quiet|-q)
 			BEQUIET="true" ;;
-		--update|-U)
-			UPDATE="true" ;;
 		--debug|-D)
 			DEBUGME="true" ;;
 		--logfile|-l)
@@ -74,14 +74,14 @@ while [ "$1" ]; do
 #			if [ -d "${1%\/*}" ]; then
 #				SOURCE+=" $1"
 #			else
-#				XERR "$LINENO" "Source directory not found."
+#				FAIL 1 "$LINENO" "Source directory not found."
 #			fi ;;
 #		--and-source|-S)
 #			shift
 #			if [ -d "${1%\/*}" ]; then
 #				ANDSOURCE="true" SOURCE+=( "$1")
 #			else
-#				XERR "$LINENO" "Source directory not found."
+#				FAIL 1 "$LINENO" "Source directory not found."
 #			fi ;;
 		*)
 			break ;;
@@ -90,56 +90,31 @@ while [ "$1" ]; do
 done
 
 declare -i DEPCOUNT=0
-for DEP in /usr/bin/{wget,rsync} /bin/{mkdir,sync}; {
-	if ! [ -x "$DEP" ]; then
-		ERR "$LINENO" "Dependency '$DEP' not met."
+for DEP in wget rsync mkdir sync; {
+	if ! type -fP "$DEP" > /dev/null 2>&1; then
+		FAIL 0 "$LINENO" "Dependency '$DEP' not met."
 		DEPCOUNT+=1
 	fi
 }
 
 [ $DEPCOUNT -eq 0 ] || exit 1
 
-read -a WGET_VER_LINE <<< "$(/usr/bin/wget --version)"
-WGET_VERSION=0${WGET_VER_LINE[2]//[!0-9]}
-if [ $WGET_VERSION -ge 01192 -a $WGET_VERSION -lt 01194 ]; then
-	NOWARC="--no-warc-compression"
-fi
-
-if [ "$UPDATE" == "true" ]; then
-	VERSION_URL="$DOM/terminalforlife/nxbt/raw/master/version"
-	LATEST=`/usr/bin/wget $NOWARC -q "$VERSION_URL" -O -`
-	if [[ "${LATEST//-}" =~ ^[0-9]{8}$ ]]; then
-		if [ ${LATEST//-} -gt ${_VERSION_//-} ]; then
-			while read -r; do
-				printf "%s\n" "$REPLY"
-			done <<-EOF
-				New version available:    $LATEST
-				Current version:          $_VERSION_
-			EOF
-		fi
-	else
-		XERR "$LINENO" "Failed to check for available updates."
-	fi
-
-	exit 0
-fi
-
-#XERR "$LINENO" "Incorrect option(s) specified." ;;
-[ "$BEQUIET" == "true" ] && exec >&-
+#FAIL 1 "$LINENO" "Incorrect option(s) specified." ;;
+[ "$BEQUIET" == "true" ] && exec > /dev/null
 [ "$DEBUGME" == "true" ] && set -x
 
-[ -d "$*" ] || XERR "$LINENO" "Unable to find or access the TARGET directory."
+[ -d "$*" ] || FAIL 1 "$LINENO" "Unable to find or access the TARGET directory."
 
 TARGET="$*"
-[ -f "$TARGET" ] && XERR "Target is not a directory."
+[ -f "$TARGET" ] && FAIL 1 "Target is not a directory."
 [[ "$TARGET" == */ ]] || TARGET+="/"
 
 printf -v CURDATE "%(%F_%X)T" "-1"
 #TODO - Make the logfile skip the whole /tmp part; redundant.
-LOGFILE="/tmp/nxbt_${USER}_${CURDATE}.log"
-BACKNAME="NXBT_${UID}_${CURDATE}"
+LOGFILE="/tmp/${_PROJECT_}_${USER}_${CURDATE}.log"
+BACKNAME="${_PROJECT_^^}_${UID}_${CURDATE}"
 if ! [ -d "$BACKNAME" ]; then
-	/bin/mkdir "${TARGET}${BACKNAME}" || exit $?
+	mkdir "${TARGET}${BACKNAME}" || exit $?
 fi
 
 printf "[+%0.7d] LOGGING: %s\n" "$SECONDS" "$LOGFILE"
@@ -150,17 +125,15 @@ printf "[%s]: TARGET='%s' FROM='%s' USER='%s' UID='%s'\n"\
 DEFAULT_PATHS(){
 	printf "[+%0.7d] PROCESSING: %s\n" "$SECONDS" "$HOME"
 	TARGETPATH="${TARGET}${BACKNAME}/$USER/"
-	[ -d "$TARGETPATH" ] || /bin/mkdir "$TARGETPATH"
+	[ -d "$TARGETPATH" ] || mkdir "$TARGETPATH"
 
-	/usr/bin/rsync -a --delete --info=progress2\
-		"$HOME" "$TARGETPATH" 2> "$LOGFILE"
+	rsync -a --delete --info=progress2 "$HOME" "$TARGETPATH" 2> "$LOGFILE"
 
 	printf "[+%0.7d] PROCESSING: %s\n" "$SECONDS" "/etc"
 	TARGETPATH="${TARGET}${BACKNAME}/etc/"
-	[ -d "$TARGETPATH" ] || /bin/mkdir "$TARGETPATH"
+	[ -d "$TARGETPATH" ] || mkdir "$TARGETPATH"
 
-	/usr/bin/rsync -a --delete --info=progress2\
-		"/etc" "$TARGETPATH" 2> "$LOGFILE"
+	rsync -a --delete --info=progress2 "/etc" "$TARGETPATH" 2> "$LOGFILE"
 }
 
 USER_PATH(){
@@ -170,9 +143,9 @@ USER_PATH(){
 	for I in $SOURCE; {
 		printf "[+%0.7d] PROCESSING: %s\n" "$SECONDS" "$SOURCE"
 		TARGETPATH="${TARGET}/${BACKNAME}/${SOURCE//*\/}"
-		[ -d "$TARGETPATH" ] || /bin/mkdir "$TARGETPATH"
+		[ -d "$TARGETPATH" ] || mkdir "$TARGETPATH"
 
-		/usr/bin/rsync -a --delete --info=progress2\
+		rsync -a --delete --info=progress2\
 			"$SOURCE" "$TARGETPATH"/ 2> "$LOGFILE"
 	}
 }
@@ -189,7 +162,7 @@ else
 fi
 
 printf "[+%0.7d] SYNCHRONIZING...\n" "$SECONDS"
-/bin/sync
+sync
 
 if [ -f "$LOGFILE" ]; then
 	readarray REPLY < "$LOGFILE"
@@ -203,7 +176,7 @@ if [ -f "$LOGFILE" ]; then
 		printf "[+%0.7d] CLEANING: %s\n" "$SECONDS" "$LOGFILE"
 	fi
 else
-	XERR "$LINENO" "Logfile not found."
+	FAIL 1 "$LINENO" "Logfile not found."
 fi
 
 if [ -f "$LOGFILE" ]; then
@@ -223,4 +196,4 @@ done <<-EOF
 	LINE: ${ERRCOUNT:-???}
 EOF
 
-# vim: ft=sh noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
+# vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
