Updated pagewatch

diff --git a/pagewatch b/pagewatch
--- a/pagewatch
+++ b/pagewatch
@@ -3,32 +3,25 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/pagewatch
 # Started On        - Wed 18 Oct 19:27:40 BST 2017
-# Last Change       - Thu  9 May 00:58:28 BST 2019
+# Last Change       - Sun 12 May 23:36:43 BST 2019
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
-
 # This came to be because I got excited and impatient waiting for Ubuntu 17.10 to
 # be released and therefor available on the Ubuntu website.
 #
 # I devised a simple way to quickly and automatically check for changes on a given
 # webpage, which for me was the download page, where I had hoped to see the new
 # 17.10 download link.
-
 #----------------------------------------------------------------------------------
 
-XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
-ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }
+_VERSION_="2019-05-12"
+_PROJECT_="${0##*/}"
 
-declare -i DEPCOUNT=0
-for DEP in /bin/sleep /usr/bin/{md5sum,wget}; {
-	[ -x "$DEP" ] || {
-		ERR "$LINENO" "Dependency '$DEP' not met."
-		DEPCOUNT+=1
-	}
+FAIL(){
+	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
+	[ $1 -eq 1 ] && exit 1
 }
-
-[ $DEPCOUNT -eq 0 ] || exit 1
 
 shopt -s extglob
 
@@ -36,16 +29,17 @@ USAGE(){
 	while read -r; do
 		echo "$REPLY"
 	done <<-EOF
-		            PAGEWATCH (19th December 2017)
+		            ${_PROJECT_^^} ($_VERSION_)
 		            Written by terminalforlife (terminalforlife@yahoo.com)
 
 		            Watch a webpage for signs of change by checkings its md5sum.
 
-		SYNTAX:     pagewatch [OPTS] URL COMMANDS
+		SYNTAX:     $_PROJECT_ [OPTS] URL COMMANDS
 
 		OPTS:       --help|-h|-?            - Displays this help information.
-		            --debug|-D              - Enables the built-in bash debugging.
+		            --version|-v            - Output only the version datestamp.
 		            --quiet|-q              - Runs in quiet mode. Errors still output.
+		            --debug|-D              - Enables the built-in bash debugging.
 		            --interval|-i N         - Check for changes every N seconds. The
 		                                      default is to check every 60 seconds.
 
@@ -53,29 +47,30 @@ USAGE(){
 		            any changes to the specified webpage. See below for examples.
 
 		EXAMPLE:
-		            pagewatch --interval 10m "https://www.ubuntu.com" notify-send "Ready!"
+		            $_PROJECT_ --interval 10m "https://www.ubuntu.com" notify-send "Ready!"
 
-		CAVEAT:     Some webpages update so frequently that pagewatch would for them be
+		CAVEAT:     Some webpages update so frequently that $_PROJECT_ would for them be
 		            no use. Such pages tend to have content like counters or timers.
 	EOF
 }
 
-while [ -n "$1" ]; do
+while [ "$1" ]; do
 	case "$1" in
 		--help|-h|-\?)
 			USAGE; exit 0 ;;
-		--debug|-D)
-			DEBUGME="true" ;;
+		--version|-v)
+			printf "%s\n" "$_VERSION_"; exit 0 ;;
 		--quiet|-q)
 			BEQUIET="true" ;;
+		--debug|-D)
+			DEBUGME="true" ;;
 		--interval|-i)
 			shift; INTERVAL="$1" ;;
 		-*|--*)
-			XERR "$LINENO" "Incorrect argument(s) specified." ;;
+			FAIL 1 "$LINENO" "Incorrect argument(s) specified." ;;
 		*)
 			break ;;
 	esac
-
 	shift
 done
 
@@ -85,22 +80,29 @@ shift
 
 COMMANDS="$@"
 
-[ -z "$URL" ] && XERR "$LINENO" "A webpage address (URL) is required."
+declare -i DEPCOUNT=0
+for DEP in sleep md5sum wget; {
+	if ! type -fP "$DEP" > /dev/null 2>&1; then
+		FAIL 0 "$LINENO" "Dependency '$DEP' not met."
+		DEPCOUNT+=1
+	fi
+}
 
-[ $UID -eq 0 ] && XERR "$LINENO" "Root access isn't required."
+[ $DEPCOUNT -eq 0 ] || exit 1
 
-[ "$BEQUIET" == "true" ] && exec >&-
-[ "$DEBUGME" == "true" ] && set -xeu
+[ "$URL" ] || FAIL 1 "$LINENO" "A webpage address (URL) is required."
 
-printf -v BUFFER "/tmp/pagewatch_%(%F_%X)T.md5" "-1"
-[ -d /tmp ] || XERR "$LINENO" "Directory /tmp is missing or inaccessible."
+[ "$BEQUIET" == "true" ] && exec > /dev/null
+[ "$DEBUGME" == "true" ] && set -x
 
-/usr/bin/wget -q "$URL" -O - | /usr/bin/md5sum > "$BUFFER" 2>&-
+printf -v BUFFER "/tmp/${_PROJECT_}_%(%F_%X)T.md5" "-1"
+[ -d /tmp ] || FAIL 1 "$LINENO" "Directory /tmp is missing or inaccessible."
+
+wget -q "$URL" -O - | md5sum > "$BUFFER" 2>&-
 
 declare -i COUNT=0
 while :; do
-	/usr/bin/wget -q "$URL" -O -\
-		| /usr/bin/md5sum -c "$BUFFER" >&- 2>&- || ($COMMANDS)
+	wget -q "$URL" -O - | md5sum -c "$BUFFER" >&- 2>&- || ($COMMANDS)
 
 	COUNT+=1
 
@@ -109,7 +111,7 @@ while :; do
 
 	printf "CHECK[#%0.4d]: %(%F (%X))T\n" "$COUNT"
 
-	/bin/sleep "${INTERVAL:-1m}"
+	sleep "${INTERVAL:-1m}"
 done
 
 # vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
