Add '--wait|-w' and '--skip-start|-s'
I've also made the argument processing more robust, so now an error is
displayed as would be expected from conflicting arguments (flags).

diff --git a/shlides b/shlides
--- a/shlides
+++ b/shlides
@@ -3,7 +3,7 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/shlides
 # Started On        - Sun 17 Nov 16:27:40 GMT 2019
-# Last Change       - Mon 18 Nov 03:52:55 GMT 2019
+# Last Change       - Mon 18 Nov 13:31:48 GMT 2019
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
@@ -49,10 +49,14 @@ USAGE(){
 		            --tildes|-T             - Use the EOF tildes like in vim.
 		            --no-header|-N          - Omit the header from each slide.
 		            --borders|-b            - Pretty borders around the header.
+		            --wait|-w INT           - Wait INT second(s) between slides.
+		            --skip-start|-s         - Skip the message at project start.
 
 		SITE:       $DOM/terminalforlife/Extra
 	EOF
 }
+
+WaitTime=30
 
 while [ "$1" ]; do
 	case $1 in
@@ -84,6 +88,22 @@ while [ "$1" ]; do
 			BORDERS='true'
 
 			DEBUG "$LINENO" "BORDERS" "$BORDERS" ;;
+		--wait|-w)
+			shift
+
+			if [[ $1 =~ ^[0-9]+$ ]]; then
+				WaitTime=$1
+				WAIT='true'
+
+				DEBUG "$LINENO" "WaitTime" "$WaitTime"
+				DEBUG "$LINENO" "WAIT" "$WAIT"
+			else
+				FAIL 1 "$LINENO" "Specified wait time is invalid."
+			fi ;;
+		--skip-start|-s)
+			SKIPSTART='true'
+
+			DEBUG "$LINENO" "SKIPSTART" "$SKIPSTART" ;;
 		-*)
 			DEBUG "$LINENO" "1" "$1"
 
@@ -100,6 +120,12 @@ while [ "$1" ]; do
 
 	shift
 done
+
+if [ "$WAIT" == 'true' -a "$INTERACTIVE" == 'true' ]; then
+	FAIL 1 "$LINENO" "Either '--wait|-w' or '--interactive|-i', not both."
+elif [ "$NOHEADER" == 'true' -a "$BORDERS" == 'true' ]; then
+	FAIL 1 "$LINENO" "Option '--borders|-b' used but headers disabled."
+fi
 
 DEBUG "$LINENO" "Checking for 'tput' PATH executable."
 
@@ -245,20 +271,24 @@ PushLines(){
 
 clear
 
-while read; do
-	printf "%s\n" "$REPLY"
-done <<-EOF
+if ! [ "$SKIPSTART" == 'true' ]; then
+	while read; do
+		printf "%s\n" "$REPLY"
+	done <<-EOF
 
-	  Project started!
+		  Project started!
 
-	    FILE: $ProjectFile
-	    USER: $USER ($UID)
-	    HOST: ${HOSTNAME:-$HOST}
-	    DATE: `printf '%(%F %X)T' -1`
+		    FILE: $ProjectFile
+		    USER: $USER ($UID)
+		    HOST: ${HOSTNAME:-$HOST}
+		    DATE: `printf '%(%F %X)T' -1`
 
-EOF
+	EOF
+fi
 
-printf '  Press any key to begin... '
+if [ "$INTERACTIVE" == 'true' ]; then
+	printf '  Press any key to begin... '
+fi
 
 # Output and parse lines of body.
 FirstLineFromBuffArr='false'
@@ -284,7 +314,7 @@ for CurLine in "${BuffArr[@]%$'\n'}"; {
 		if [ "$INTERACTIVE" == 'true' ]; then
 	  		PAKTC
 		else
-			sleep 0.3
+			sleep ${WaitTime}s
 		fi
 
 		clear
@@ -383,7 +413,7 @@ PushLines $[(Lines - BodyLines) - 4]
 if [ "$INTERACTIVE" == 'true' ]; then
 	PAKTC
 else
-	sleep 0.3
+	sleep ${WaitTime}s
 fi
 
 clear
