Clean up and correct syntax

diff --git a/snotes b/snotes
--- a/snotes
+++ b/snotes
@@ -3,28 +3,28 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/snotes (Search Notes)
 # Started On        - Fri  9 Feb 00:07:19 GMT 2018
-# Last Change       - Mon 28 Oct 12:51:20 GMT 2019
+# Last Change       - Wed 27 Nov 13:55:03 GMT 2019
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
-# To use your own comment character, change the COM variable. This feature will
+# To use your own comment character, change the Comment variable. This feature will
 # eventually be included into snotes properly.
 #----------------------------------------------------------------------------------
 
 #TODO - Fix clash between snotes' arguments and when searching with notes for those
 #       arguments. Also, --edit/-e CMD is not working.
 
-_VERSION_="2019-10-28"
+_VERSION_="2019-11-27"
 _PROJECT_="${0##*/}"
 
-FAIL(){
+Err(){
 	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
 	[ $1 -eq 1 ] && exit 1
 }
 
-COM="#"
+Comment="#"
 
-USAGE(){
+Usage(){
 	while read -r; do
 		printf "%s\n" "$REPLY"
 	done <<-EOF
@@ -48,7 +48,7 @@ USAGE(){
 		            $_PROJECT_ when you wish to stop searching for the MATCH, have a line in
 		            the notes file which contains only:
 
-		              ${COM}END
+		              ${Comment}END
 
 		            When using --edit|-e for editing a file, the editor used will be the
 		            one pointed to within the
@@ -57,81 +57,81 @@ USAGE(){
 	EOF
 }
 
+ProjConf="$HOME/.config/$_PROJECT_.conf"
+
 while [ "$1" ]; do
 	case $1 in
 		--help|-h|-\?)
-			USAGE; exit 0 ;;
+			Usage; exit 0 ;;
 		--version|-v)
 			printf "%s\n" "$_VERSION_"
 			exit 0 ;;
 		--debug|-D)
-			DEBUGME="true" ;;
+			DEBUGME='true' ;;
 		--comment|-C)
-			shift; COM="${1:0:1}" ;;
+			shift; Comment=${1:0:1} ;;
 		--file|-f)
-			shift; FILE="$1" ;;
+			shift; NotesFile=$1 ;;
 		--edit|-e)
-			shift; EDIT="$1" ;;
+			shift; EDIT=$1 ;;
 		-*)
-			FAIL 1 "$LINENO" "Incorrect argument(s) specified." ;;
+			FAIL 1 $LINENO "Incorrect argument(s) specified." ;;
 		*)
 			break ;;
 	esac
-
 	shift
 done
 
 if [ "$2" ]; then
-	FAIL 1 "$LINENO" "Argument error -- is your match correct?"
+	FAIL 1 $LINENO "Argument error -- is your match correct?"
 fi
 
-[ "$DEBUGME" == "true" ] && set -x
+[ "$DEBUGME" == 'true' ] && set -x
 
-SNOTESCHK(){
-	if ! [ -f "$FILE" -a -r "$FILE" ]; then
-		FAIL 1 "$LINENO" "Notes file inaccessible or not found."
+SnotesChk(){
+	if ! [ -f "$NotesFile" ] || ! [ -r "$NotesFile" ]; then
+		FAIL 1 $LINENO "Notes file inaccessible or not found."
 	fi
 }
 
-if [ -f $HOME/.config/$_PROJECT_.conf ]; then
-	if [ "$FILE" ]; then
-		SNOTESCHK
-		read -n 1 -e -p "Notes file already exists -- replace? "
+if [ -f "$HOME/.config/$_PROJECT_.conf" ]; then
+	if [ -n "$NotesFile" ]; then
+		SnotesChk
+		read -n 1 -e -p "Notes file already set -- replace? "
 		if ! [[ "$REPLY" == [Yy] ]]; then
 			printf "No action taken -- quitting.\n"
 			exit 0
 		else
-			if ! [ -d $HOME/.config ]; then
+			if ! [ -d "$HOME/.config" ]; then
 				if type -fP mkdir > /dev/null 2>&1; then
 					mkdir $HOME/.config
 				else
-					FAIL 1 "$LINENO" "Dependency 'mkdir' not met."
+					FAIL 1 $LINENO "Dependency 'mkdir' not met."
 				fi
 			fi
 
-			printf "%q\n" "$FILE" > $HOME/.config/$_PROJECT_.conf
+			printf "%q\n" "$NotesFile" > "$HOME/.config/$_PROJECT_.conf"
 		fi
 	else
-		FILE="$(< $HOME/.config/$_PROJECT_.conf)"
+		NotesFile=$(< $HOME/.config/$_PROJECT_.conf)
 	fi
 else
-	printf "$FILE\n" > $HOME/.config/$_PROJECT_.conf
+	printf "$NotesFile\n" > "$HOME/.config/$_PROJECT_.conf"
 fi
 
-SNOTESCHK
-MATCH="$1"
-declare -i LINE_COUNT=0
-while read -r LINE; do
-	LINE_COUNT+=1
-	[ "$LINE" == "${COM}END" ] && break
-	if [[ "$LINE" =~ ^(|${COM}.*)$ ]]; then
+SnotesChk
+Match=$1
+declare -i LineCount=0
+while read -r CurLine; do
+	CurLineCount+=1
+	[ "$CurLine" == "${Comment}END" ] && break
+	if [[ $CurLine =~ ^(|${Comment}.*)$ ]]; then
 		continue
-	elif [[ "$LINE" =~ $MATCH ]]; then
-		if [ "$LINE_NUMBERS" == "true" ]; then
-			printf "%4d  %s\n" "$LINE_COUNT" "$LINE"
+	elif [[ $CurLine =~ "$Match" ]]; then
+		if [ "$CurLineNums" == "true" ]; then
+			printf "%4d  %s\n" "$CurLineCount" "$CurLine"
 		else
-			printf "%s\n" "$LINE"
+			printf "%s\n" "$CurLine"
 		fi
 	fi
-done < "$FILE"
-
+done < "$NotesFile"
