Update standard of code and add update check
Still incomplete, but this is a nudge in the right direction.

diff --git a/swap-file b/swap-file
--- a/swap-file
+++ b/swap-file
@@ -1,34 +1,39 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/swap-file
 # Started On        - Sat 27 Jan 11:49:19 GMT 2018
-# Last Change       - Thu  9 May 00:58:58 BST 2019
+# Last Change       - Mon 11 Nov 22:26:37 GMT 2019
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
 # This is an early work in progress; don't yet run on your production machines!
 #----------------------------------------------------------------------------------
 
-_VERSION_="2019-05-09"
+_VERSION_="2019-11-11"
+_PROJECT_="${0##*/}"
 
-XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
-ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }
+FAIL(){
+	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
+	[ $1 -eq 1 ] && exit 1
+}
+
+DOM="https://github.com"
 
 USAGE(){
 	while read -r; do
 		printf "%s\n" "$REPLY"
 	done <<-EOF
-		            SWAP-FILE ($_VERSION_)
+		            ${_PROJECT_^^} ($_VERSION_)
 		            Written by terminalforlife (terminalforlife@yahoo.com)
 
-		            A simple, small tool to easily create and set up a swap file.
+		            Dummy description for this template.
 
-		SYNTAX:     swap-file [OPTS] [NAME] [SIZE]
+		SYNTAX:     $_PROJECT_ [OPTS] [NAME] [SIZE]
 
 		OPTS:       --help|-h|-?            - Displays this help information.
 		            --version|-v            - Output only the version datestamp.
-		            --quiet|-q              - Runs in quiet mode. Errors still output.
+		            --update|-U             - Check for updates to $_PROJECT_.
 		            --debug|-D              - Enables the built-in bash debugging.
 
 		NOTE:       Where NAME is the swap file name to be created in /; the file name must
@@ -37,6 +42,8 @@ USAGE(){
 		            Where SIZE is the size of the swap file to create, in MB.
 
 		FILE:       The '/etc/fstab' file is by default edited.
+
+		SITE:       $DOM/terminalforlife/Extra
 	EOF
 }
 
@@ -47,8 +54,6 @@ while [ "$1" ]; do
 		--version|-v)
 			printf "%s\n" "$_VERSION_"
 			exit 0 ;;
-		--quiet|-q)
-			BEQUIET="true" ;;
 		--debug|-D)
 			DEBUGME="true" ;;
 		*)
@@ -62,8 +67,8 @@ NAME="/${1//[![:alnum:]]}"
 SIZE="${2//[!0-9]}"
 
 declare -i DEPCOUNT=0
-for DEP in /bin/{sync,grep,cp,chown,chmod,sed,dd} /sbin/{swap{on,off},mkswap}; {
-	if ! [ -x "$DEP" ]; then
+for DEP in sync grep cp ch{own,mod} sed dd swap{on,off} mkswap; {
+	if ! type -fP "$DEP" > /dev/null 2>&1; then
 		ERR "$LINENO" "Dependency '$DEP' not met."
 		DEPCOUNT+=1
 	fi
@@ -76,7 +81,6 @@ for DEP in /bin/{sync,grep,cp,chown,chmod,sed,dd} /sbin/{swap{on,off},mkswap}; {
 
 [ $UID -eq 0 ] || XERR "$LINENO" "Setting up a swap file requires root access."
 
-[ "$BEQUIET" == "true" ] && exec 1>&-
 [ "$DEBUGME" == "true" ] && set -x
 
 if [ -f "$NAME" ]; then
@@ -93,22 +97,22 @@ if [ -f "$NAME" ]; then
 fi
 
 printf "Creating %dMB swap file: %s\n" "$SIZE" "$NAME"
-/bin/dd if=/dev/zero of="$NAME" bs=1024K count="$SIZE"
-/bin/sync "$NAME"
+dd if=/dev/zero of="$NAME" bs=1024K count="$SIZE"
+sync "$NAME"
 
-/bin/chown -v 0:0 "$NAME"
-/bin/chmod -v 600 "$NAME"
-LIBBLKID_DEBUG=all /sbin/mkswap -v "$NAME"
+chown -v 0:0 "$NAME"
+chmod -v 600 "$NAME"
+LIBBLKID_DEBUG='all' mkswap -v "$NAME"
 #TODO - Why does mkswap fail here, saying it can't read the swap header? Yet when
 #       I run the command separately on the terminal, all is fine.
 
-/bin/cp -iv "$FST"{,.bak}
+cp -iv "$FST"{,.bak}
 
 printf "Updating the file system table: %s\n" "$FST"
-/bin/sed -i '/^UUID=.*\s.*\sswap/s/^/#/' "$FST"
+sed -i '/^UUID=.*\s.*\sswap/s/^/#/' "$FST"
 
 if [ -f "$FST" ]; then
-	if ! /bin/grep -q "/$NAME none swap sw 0 0" "$FST"; then
+	if ! grep -q "/$NAME none swap sw 0 0" "$FST"; then
 		printf "/%s none swap sw 0 0\n" "$NAME" >> "$FST" >&-
 	else
 		XERR "$LINENO" "Current entry already present in: $FST"
@@ -117,7 +121,7 @@ else
 	XERR "$LINENO" "Unable to find or access: $FST"
 fi
 
-LIBBLKID_DEBUG=all /sbin/swapoff -va
-LIBBLKID_DEBUG=all /sbin/swapon -v "$NAME"
+LIBBLKID_DEBUG='all' swapoff -va
+LIBBLKID_DEBUG='all' swapon -v "$NAME"
 
 # vim: ft=sh noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
