Updated tlptog to newer standards

diff --git a/tlptog b/tlptog
--- a/tlptog
+++ b/tlptog
@@ -3,17 +3,20 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/tlptog
 # Started On        - Fri 18 May 14:19:48 BST 2018
-# Last Change       - Thu  9 May 17:05:23 BST 2019
+# Last Change       - Tue  5 Nov 14:10:58 GMT 2019
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
 # Quick shell program to toggle TLP to improve power management on portable setups.
 #----------------------------------------------------------------------------------
 
-_VERSION_="2019-05-09"
+_VERSION_="2019-11-05"
+_PROJECT_="${0##*/}"
 
-XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
-ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }
+FAIL(){
+	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
+	[ $1 -eq 1 ] && exit 1
+}
 
 DOM="https://github.com"
 WORK_FILE="/etc/default/tlp"
@@ -22,15 +25,15 @@ USAGE(){
 	while read -r; do
 		printf "%s\n" "$REPLY"
 	done <<-EOF
-		            TLPTOG ($_VERSION_)
+		            ${_PROJECT_^^} ($_VERSION_)
 		            Written by terminalforlife (terminalforlife@yahoo.com)
 
 		            Simple command to quickly toggle the 'TLP_ENABLE' parameter.
 
-		SYNTAX:     tlptog [OPTS]
+		SYNTAX:     $_PROJECT_ [OPTS]
 
 		OPTS:       --help|-h|-?            - Displays this help information.
-		            --update|-U             - Check for updates to simplify-ubuntu.
+		            --update|-U             - Check for updates to $_PROJECT_.
 		            --version|-v            - Output only the version datestamp.
 
 		FILE:       $WORK_FILE
@@ -47,34 +50,34 @@ while [ "$1" ]; do
 			printf "%s\n" "$_VERSION_"
 			exit 0 ;;
 		*)
-			XERR "$LINENO" "Incorrect argument(s) specified." ;;
+			FAIL 1 "$LINENO" "Incorrect argument(s) specified." ;;
 	esac
 	shift
 done
 
-[ -x /bin/sed ] || XERR "$LINENO" "Dependency '/bin/sed' not met."
+type -fP sed > /dev/null 2>&1 || FAIL 1 "$LINENO" "Dependency '/bin/sed' not met."
 
-[ $UID -eq 0 ] || XERR "$LINENO" "Root access is required for system-wide configuration."
+[ $UID -eq 0 ] || FAIL 1 "$LINENO" "Root access is required for system-wide configuration."
 
 if [ -f "$WORK_FILE" ]; then
 	while IFS="=" read -a X; do
 		[[ "${X[0]}" =~ ^# ]] && continue
 		if [ "${X[0]}" == "TLP_ENABLE" ]; then
 			if [ ${X[1]} -eq 1 ]; then
-				if ! /bin/sed -i 's/\(TLP_ENABLE=\)1/\10/' "$WORK_FILE"; then
-					XERR "$LINENO" "Parameter 'TLP_ENABLE' unsuccessfully set to '1'."
+				if ! sed -i 's/\(TLP_ENABLE=\)1/\10/' "$WORK_FILE"; then
+					FAIL 1 "$LINENO" "Parameter 'TLP_ENABLE' unsuccessfully set to '1'."
 				fi
 			elif [ ${X[1]} -eq 0 ]; then
-				if ! /bin/sed -i 's/\(TLP_ENABLE=\)0/\11/' "$WORK_FILE"; then
-					XERR "$LINENO" "Parameter 'TLP_ENABLE' unsuccessfully set to '0'."
+				if ! sed -i 's/\(TLP_ENABLE=\)0/\11/' "$WORK_FILE"; then
+					FAIL 1 "$LINENO" "Parameter 'TLP_ENABLE' unsuccessfully set to '0'."
 				fi
 			else
-				XERR "$LINENO" "Invalid 'TLP_ENABLE' parameter assignment."
+				FAIL 1 "$LINENO" "Invalid 'TLP_ENABLE' parameter assignment."
 			fi
 
 			break
 		fi
 	done < "$WORK_FILE"
 else
-	XERR "$LINENO" "Unable to find the '$WORK_FILE' file."
+	FAIL 1 "$LINENO" "Unable to find the '$WORK_FILE' file."
 fi
