Updated todo; added ERR() & XERR()

diff --git a/todo b/todo
--- a/todo
+++ b/todo
@@ -3,7 +3,7 @@
 #----------------------------------------------------------------------------------
 # Project Name      - miscellaneous/todo
 # Started On        - Mon  2 Apr 02:04:43 BST 2018
-# Last Change       - Mon  2 Apr 02:43:03 BST 2018
+# Last Change       - Mon  2 Apr 02:57:31 BST 2018
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
@@ -18,11 +18,17 @@ HUB="$HOME/GitHub/terminalforlife/Personal"
 
 # Here, you can exclude specified repositories (directories) found in HUB. This is
 # an array, so be sure to correctly quote names with spaces and special characters.
-EXCLUDE=(
-	swap-alert pymisc learnlinux get-uuid medlog-in-c
-)
+EXCLUDE=(swap-alert pymisc learnlinux get-uuid medlog-in-c)
+
+#TODO - Incomplete feature is pretty much a placeholder for now; finish it.
+# If you want to only check only these (array, as above) repositories, you can, -
+# but if you don't, be sure to either comment this assignment out, or empty it.
+ONLY=(installit apt-undo-install bashconfig i3config miscellaneous vimconfig)
 
 #---------------------------------------------------FETCH AND CHECK REPOSITORY LIST
+
+XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
+ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }
 
 REPOS=()
 if [ -d "$HUB" ]; then
@@ -33,17 +39,29 @@ if [ -d "$HUB" ]; then
 			NUM+=1
 		fi
 	}
+else
+	XERR "$LINENO" "Unable to find or access git repository HUB."
 fi
 
-[ ${#REPOS[@]} -gt 0 ] && T="ies were" || T="y was"
-printf "%d repositor%s found.\n" "${#REPOS[@]}" "$T"
+if ! [ ${!REPOS[@]} -eq 0 ]; then
+	[ ${#REPOS[@]} -gt 0 ] && T="ies were" || T="y was"
+	printf "%d repositor%s found.\n" "${#REPOS[@]}" "$T"
+else
+	XERR "$LINENO" "No git repositories were found in HUB."
+fi
 
 #-----------------------------------------------------------PROCESS EACH REPOSITORY
 
 for I in ${!REPOS[@]}; {
-	for OMIT in ${EXCLUDE[@]}; {
-		[ "$OMIT" == "${REPOS[I]//*\/}" ] && continue 2
-	}
+	if [ ${!ONLY[@]} -gt 0 ]; then
+		:
+	else
+		for OMIT in ${EXCLUDE[@]}; {
+			[ "$OMIT" == "${REPOS[I]//*\/}" ] && continue 2
+		}
+	fi
+
+
 
 	printf "Checking: %s\n" "${REPOS[I]//*\/}"
 }
