Update and address questionable syntax

diff --git a/ubuntu-syschk b/ubuntu-syschk
--- a/ubuntu-syschk
+++ b/ubuntu-syschk
@@ -3,20 +3,20 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/ubuntu-syschk
 # Started On        - Mon 22 Jan 12:03:01 GMT 2018
-# Last Change       - Tue  5 Nov 14:48:06 GMT 2019
+# Last Change       - Wed 27 Nov 15:56:52 GMT 2019
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
 
-_VERSION_="2019-11-05"
-_PROJECT_="${0##*/}"
+_VERSION_="2019-11-27"
+_PROJECT_=${0##*/}
 
-FAIL(){
+Err(){
 	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
 	[ $1 -eq 1 ] && exit 1
 }
 
-INFO(){ [ "$VERBOSE" == "true" ] && printf "%s\n" "$1"; }
+INFO(){ [ "$VERBOSE" == 'true' ] && printf "%s\n" "$1"; }
 ALERT(){ AC+=1; printf "ALERT: %s\n" "$1"; }
 
 DOM="https://github.com"
@@ -87,19 +87,19 @@ while [ "$1" ]; do
 			printf "%s\n" "$_VERSION_"
 			exit 0 ;;
 		--quiet|-q)
-			BEQUIET="true" ;;
+			BEQUIET='true' ;;
 		--update|-U)
-			UPDATE="true" ;;
+			UPDATE='true' ;;
 		--debug|-D)
-			DEBUGME="true" ;;
+			DEBUGME='true' ;;
 		--no-summary|-S)
-			NO_SUMMARY="true" ;;
+			NO_SUMMARY='true' ;;
 		--ignore-distro|-I)
-			IGNORE_DISTRO="true" ;;
+			IGNORE_DISTRO='true' ;;
 		--verbose|-V)
-			VERBOSE="true" ;;
+			VERBOSE='true' ;;
 		-*)
-			FAIL 1 "$LINENO" "Incorrect argument(s) specified." ;;
+			Err 1 $LINENO "Incorrect argument(s) specified." ;;
 		*)
 			break ;;
 	esac
@@ -159,26 +159,26 @@ while [ "$1" ]; do
 		logchk=[01])
 			LOGCHK=${1/*=} ;;
 		*)
-			FAIL 1 "$LINENO" "Incorrect CHECK value(s) specified." ;;
+			Err 1 $LINENO "Incorrect CHECK value(s) specified." ;;
 	esac
 	shift
 done
 
-[ "$BEQUIET" == "true" ] && exec > /dev/null
-[ "$DEBUGME" == "true" ] && set -x
+[ "$BEQUIET" == 'true' ] && exec > /dev/null
+[ "$DEBUGME" == 'true' ] && set -x
 
-if [ "$UPDATE" == "true" ]; then
+if [ "$UPDATE" == 'true' ]; then
 	if ! type -fP wget > /dev/null 2>&1; then
-		FAIL 1 "$LINENO" "Dependency 'wget' not met."
+		Err 1 $LINENO "Dependency 'wget' not met."
 	fi
 
 	INFO "Checking for available updates to $_PROJECT_."
 	VERSION_URL="$DOM/terminalforlife/Extra/raw/master/versions"
 	while IFS='=' read -a LINE; do
 		if  [ "${LINE[0]}" == "$0" ]; then
-			LATEST="${LINE[1]}"
+			LATEST=${LINE[1]}
 
-			if [[ "${LATEST//-}" =~ ^[0-9]{8}$ ]]; then
+			if [[ ${LATEST//-} =~ ^[0-9]{8}$ ]]; then
 				if [ ${LATEST//-} -gt ${_VERSION_//-} ]; then
 					while read -r; do
 						printf "%s\n" "$REPLY"
@@ -190,7 +190,7 @@ if [ "$UPDATE" == "true" ]; then
 					INFO "No updates are available."
 				fi
 			else
-				FAIL 1 "$LINENO" "Failed to check for available updates."
+				Err 1 $LINENO "Failed to check for available updates."
 			fi
 		fi
 	done <<< "$(wget -q "$VERSION_URL" -O -)"
@@ -198,20 +198,20 @@ if [ "$UPDATE" == "true" ]; then
 	exit 0
 fi
 
-if ! [ "$IGNORE_DISTRO" == "true" ]; then
+if ! [ "$IGNORE_DISTRO" == 'true' ]; then
 	INFO "Checking distribution ID via: /etc/os-release"
 	if [ -f /etc/os-release -a -r /etc/os-release ]; then
 		while IFS="=" read -a X; do
 			if [ "${X[0]//\"}" == "ID_LIKE" ]; then
-				if ! [[ "${X[1]//\"}" =~ (debian|ubuntu) ]]; then
-					FAIL 1 "$LINENO" "Unsupported distribution base."
+				if ! [[ ${X[1]//\"} =~ (debian|ubuntu) ]]; then
+					Err 1 $LINENO "Unsupported distribution base."
 				fi
 
 				break
 			fi
 		done < /etc/os-release
 	else
-		FAIL 1 "$LINENO" "Unable to determine the distribution ID."
+		Err 1 $LINENO "Unable to determine the distribution ID."
 	fi
 fi
 
@@ -238,14 +238,14 @@ if [ $SERVICES -eq 0 ]; then
 				ALERT "The operational state could not be determined." ;;
 		esac
 	else
-		FAIL 0 "$LINENO" "Unable to find or access: systemctl"
+		Err 0 $LINENO "Unable to find or access: systemctl"
 	fi
 
 	if type -fP systemd-analyze > /dev/null 2>&1; then
 		INFO "Loading and checking unit files with SystemD."
 		systemd-analyze verify || ALERT "SystemD detected one or more unit-related errors."
 	else
-		FAIL 0 "$LINENO" "Unable to find or access: systemd-analyze"
+		Err 0 $LINENO "Unable to find or access: systemd-analyze"
 	fi
 fi
 
@@ -254,7 +254,7 @@ if [ $PASSWORD -eq 0 ]; then
 		INFO "Checking current user's password expiration."
 		expiry -c || ALERT "Error(s) detected while checking password expiration."
 	else
-		FAIL 0 "$LINENO" "Unable to find or access: expiry"
+		Err 0 $LINENO "Unable to find or access: expiry"
 	fi
 fi
 
@@ -266,14 +266,14 @@ if [ $SWAP -eq 0 ]; then
 			ALERT "Unable to detect an active swap file/partition."
 		fi
 	else
-		FAIL 0 "$LINENO" "Unable to find or access: /sbin/swapon"
+		Err 0 $LINENO "Unable to find or access: /sbin/swapon"
 	fi
 fi
 
 if [ $STORAGE -eq 0 ]; then
 	if type -fP df > /dev/null 2>&1; then
 		while read -a X; do
-			if [[ "${X[0]}" == /dev/* ]]; then
+			if [[ ${X[0]} == /dev/* ]]; then
 				INFO "Querying ${X[0]} for usage greater than 90%."
 				if [ "${X[1]%\%}" -gt 90 ]; then
 					ALERT "Low remaining storage space detected: ${X[0]}"
@@ -281,7 +281,7 @@ if [ $STORAGE -eq 0 ]; then
 			fi
 		done <<< "$(df --output=source,pcent)"
 	else
-		FAIL 0 "$LINENO" "Unable to find or access: /bin/df"
+		Err 0 $LINENO "Unable to find or access: /bin/df"
 	fi
 
 	#TODO - Experimental, unfinished pure-shell approach.
@@ -289,7 +289,7 @@ if [ $STORAGE -eq 0 ]; then
 	#	MATCH='^([sh]d[a-z]$|[sf][dr][0-9])$'
 
 	#	while read -a X; do
-	#		if [[ "${X[3]}" =~ $MATCH ]]; then
+	#		if [[ ${X[3]} =~ $MATCH ]]; then
 	#			printf -v SIZE "%d\n" "${X[2]}"
 	#			printf -v NAME "%s\n" "${X[3]}"
 
@@ -297,7 +297,7 @@ if [ $STORAGE -eq 0 ]; then
 	#		fi
 	#	done < /proc/partitions
 	#else
-	#	FAIL 0 "$LINENO" "Unable to find or access: /sys/block"
+	#	Err 0 $LINENO "Unable to find or access: /sys/block"
 	#fi
 fi
 
@@ -371,7 +371,7 @@ if [ $PERMS -eq 0 ]; then
 			fi
 		}
 	else
-		FAIL 0 "$LINENO" "Unable to find or access: stat"
+		Err 0 $LINENO "Unable to find or access: stat"
 	fi
 fi
 
@@ -380,10 +380,10 @@ if [ $PACKAGES -eq 0 ]; then
 		INFO "Asking APT if there are any package changes."
 		OPT='APT::Get::Show-User-Simulation-Note=0'
 		while read -a X; do
-			if [[ "${X[*]}" == *not\ to\ upgrade. ]]; then
+			if [[ ${X[*]} == *not\ to\ upgrade. ]]; then
 				SUM="$((${X[0]}+${X[3]}))"
-				if ! [[ "$SUM" =~ ^[0-9]+$ ]]; then
-					FAIL 0 "$LINENO" "Invalid SUM detected."
+				if ! [[ $SUM =~ ^[0-9]+$ ]]; then
+					Err 0 $LINENO "Invalid SUM detected."
 				elif [ $SUM -gt 0 ]; then
 					ALERT "APT has detected $SUM package change(s)."
 				fi
@@ -396,7 +396,7 @@ if [ $PACKAGES -eq 0 ]; then
 		INSCHK=`apt-get -o "$OPT" -qq -s install -f`
 		[ -n "$INSCHK" ] && ALERT "Missing dependencies are available to be fixed."
 	else
-		FAIL 0 "$LINENO" "Unable to find or access: apt-get"
+		Err 0 $LINENO "Unable to find or access: apt-get"
 	fi
 
 	if type -fP dpkg > /dev/null 2>&1; then
@@ -405,7 +405,7 @@ if [ $PACKAGES -eq 0 ]; then
 			ALERT "One or more APT database checks have failed."
 		fi
 	else
-		FAIL 0 "$LINENO" "Unable to find or access: dpkg"
+		Err 0 $LINENO "Unable to find or access: dpkg"
 	fi
 fi
 
@@ -414,25 +414,25 @@ if [ $TEMPS -eq 0 ]; then
 		INFO "Checking hardware sensors for high CPU temperature."
 		while read -a X; do
 			if [ "${X[0]}${X[1]}${X[2]}" == "Physicalid0:" ]; then
-				TEMP="${X[3]//[!0-9]}"
-				if [[ "$TEMP" =~ ^[0-9]+$ ]]; then
+				TEMP=${X[3]//[!0-9]}
+				if [[ $TEMP =~ ^[0-9]+$ ]]; then
 					[ $TEMP -gt 800 ] && ALERT "Current CPU temperature exceeding 80°C!"
 				else
-					FAIL 0 "$LINENO" "Unable to determine the temperature of the CPU."
+					Err 0 $LINENO "Unable to determine the temperature of the CPU."
 				fi
 
 				break
 			fi
 		done <<< "$(sensors -A)"
 	else
-		FAIL 0 "$LINENO" "Unable to find or access: sensors"
+		Err 0 $LINENO "Unable to find or access: sensors"
 	fi
 fi
 
 if [ $SAFEKERN -eq 0 ]; then
 	KERN(){
-		P="${1//\//.}"
-		P="${P/\/proc\/sys\/}"
+		P=${1//\//.}
+		P=${P/\/proc\/sys\/}
 		INFO "Checking parameter: $P"
 		declare -i V=`< /"$1"`
 		if ! [ -f /"$1" ]; then
@@ -489,7 +489,7 @@ if [ $SWAPPINESS -eq 0 ]; then
 			ALERT "Potentially unsuitable swappiness: $SWAP"
 		fi
 	else
-		FAIL 0 "$LINENO" "Unable to find or access: $FILE"
+		Err 0 $LINENO "Unable to find or access: $FILE"
 	fi
 fi
 
@@ -501,10 +501,10 @@ if [ $GRUB -eq 0 ]; then
 				ALERT "One or more errors found in: /boot/grub/grub.cfg"
 			fi
 		else
-			FAIL 0 "$LINENO" "Unable to find or access: /boot/grub/grub.cfg"
+			Err 0 $LINENO "Unable to find or access: /boot/grub/grub.cfg"
 		fi
 	else
-		FAIL 0 "$LINENO" "Unable to find or access: grub-script-check"
+		Err 0 $LINENO "Unable to find or access: grub-script-check"
 	fi
 fi
 
@@ -516,16 +516,16 @@ if [ $SHMCHK -eq 0 ]; then
 				IFS="(" read -a X <<< "${X[5]%)}"
 				for O in ${X[1]//,/ }; {
 					OKMATCH='^(rw|ro|nosuid|nodev)$'
-					if [[ "$O" =~ $OKMATCH ]]; then
+					if [[ $O =~ $OKMATCH ]]; then
 						continue
 					elif [ "$O" == "noexec" ]; then
-						N="true"
+						N='true'
 					else
 						ALERT "Unknown mount option '$O' detected: /dev/shm"
 					fi
 				}
 
-				if ! [ "$N" == "true" ]; then
+				if ! [ "$N" == 'true' ]; then
 					ALERT "Mount option 'noexec' not found: /dev/shm"
 				fi
 
@@ -533,7 +533,7 @@ if [ $SHMCHK -eq 0 ]; then
 			fi
 		done <<< "$(/bin/mount)"
 	else
-		FAIL 0 "$LINENO" "Unable to find or access: /bin/mount"
+		Err 0 $LINENO "Unable to find or access: /bin/mount"
 	fi
 fi
 
@@ -547,7 +547,7 @@ if [ $DPKGRC -eq 0 ]; then
 			fi
 		done <<< "$(dpkg -l 2> /dev/null)"
 	else
-		FAIL 0 "$LINENO" "Unable to find or access: dpkg"
+		Err 0 $LINENO "Unable to find or access: dpkg"
 	fi
 fi
 
@@ -557,9 +557,9 @@ if [ $IPSPOOF -eq 0 ]; then
 	if [ -f "$FILE" -a -r "$FILE" ]; then
 		while read -a X; do
 			if [ "${X[0]}${X[1]}" == "orderbind,hosts" ]; then
-				PASS1="true"
+				PASS1='true'
 			elif [ "${X[0]}${X[1]}" == "nospoofon" ]; then
-				PASS2="true"
+				PASS2='true'
 			fi
 		done < "$FILE"
 
@@ -567,15 +567,15 @@ if [ $IPSPOOF -eq 0 ]; then
 		#       has other priorities set here? Perhaps check for however
 		#       many comma-separated fields there are, to ascertain whether
 		#       the use-case is non-standard.
-		if ! [ "$PASS1" == "true" ]; then
+		if ! [ "$PASS1" == 'true' ]; then
 			ALERT "Safer setting 'order bind,hosts' not found: $FILE"
 		fi
 
-		if ! [ "$PASS2" == "true" ]; then
+		if ! [ "$PASS2" == 'true' ]; then
 			ALERT "Safer setting 'nospoof on' not found: $FILE"
 		fi
 	else
-		FAIL 0 "$LINENO" "Unable to find or access: $FILE"
+		Err 0 $LINENO "Unable to find or access: $FILE"
 	fi
 fi
 
@@ -583,7 +583,7 @@ if [ $SSHSRV -eq 0 ]; then
 	if type -fP dpkg-query > /dev/null 2>&1; then
 		INFO "Checking for safer SSH server settings: $FILE"
 		if ! dpkg-query -W openssh-server > /dev/null 2>&1; then
-			FAIL 0 "$LINENO" "Is the OpenSSH server installed?"
+			Err 0 $LINENO "Is the OpenSSH server installed?"
 		else
 			MATCH1="^[Pp]ermit[Rr]oot[Ll]ogin no$"
 			MATCH2="^[Pp]ort [0-9]+$"
@@ -591,18 +591,18 @@ if [ $SSHSRV -eq 0 ]; then
 			FILE="/etc/ssh/sshd_config"
 			if [ -f "$FILE" -a -r "$FILE" ]; then
 				while read LINE; do
-					if ! [[ "$LINE" =~ $MATCH1 ]]; then
+					if ! [[ $LINE =~ $MATCH1 ]]; then
 						ALERT "Root login via SSH is enabled: $FILE"
-					elif ! [[ "$LINE" =~ $MATCH2 ]]; then
+					elif ! [[ $LINE =~ $MATCH2 ]]; then
 						ALERT "The SSH server port '22' is too common: $FILE"
-					elif ! [[ "$LINE" =~ $MATCH3 ]]; then
+					elif ! [[ $LINE =~ $MATCH3 ]]; then
 						ALERT "SSH server login via password enabled: $FILE"
 					fi
 				done < "$FILE"
 			fi
 		fi
 	else
-		FAIL 0 "$LINENO" "Unable to find or access: ssh"
+		Err 0 $LINENO "Unable to find or access: ssh"
 	fi
 fi
 
@@ -629,12 +629,12 @@ if [ $LOGCHK -eq 0 ]; then
 				ALERT "File ${FILE##*/} has `printf "%'d" "$ERROR"` line(s) with 'ERROR' in it."
 			fi
 		else
-			FAIL 0 "$LINENO" "Unable to find or access: $FILE"
+			Err 0 $LINENO "Unable to find or access: $FILE"
 		fi
 	}
 fi
 
-if ! [ "$NO_SUMMARY" == "true" ]; then
+if ! [ "$NO_SUMMARY" == 'true' ]; then
 	[ $AC -gt 0 ] || printf "Nothing to report!\n\n"
 	printf "DATE       - %(%F (%X))T\n" "-1"
 	printf "USER       - %s (%d)\n" "$USER" "$UID"
