Updated ubuntu-syschk; POSIX-ified nulls; fixed update check method

diff --git a/ubuntu-syschk b/ubuntu-syschk
--- a/ubuntu-syschk
+++ b/ubuntu-syschk
@@ -3,7 +3,7 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/ubuntu-syschk
 # Started On        - Mon 22 Jan 12:03:01 GMT 2018
-# Last Change       - Sun 27 Oct 00:06:35 BST 2019
+# Last Change       - Sun 27 Oct 13:13:33 GMT 2019
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
@@ -163,37 +163,36 @@ while [ "$1" ]; do
 	shift
 done
 
-[ "$BEQUIET" == "true" ] && exec 1> /dev/null
+[ "$BEQUIET" == "true" ] && exec > /dev/null
 [ "$DEBUGME" == "true" ] && set -x
 
-if ! type -fP wget &> /dev/null; then
-	FAIL 1 "$LINENO" "Dependency 'wget' not met."
-fi
-
-read -a WGET_VER_LINE <<< "$(wget --version)"
-WGET_VERSION=0${WGET_VER_LINE[2]//[!0-9]}
-if [ $WGET_VERSION -ge 01192 -a $WGET_VERSION -lt 01194 ]; then
-	NOWARC="--no-warc-compression"
-fi
-
 if [ "$UPDATE" == "true" ]; then
-	INFO "Checking for available updates to ubuntu-syschk."
-	VERSION_URL="$DOM/terminalforlife/ubuntu-syschk/raw/master/version"
-	LATEST=`wget $NOWARC -q "$VERSION_URL" -O -`
-	if [[ "${LATEST//-}" =~ ^[0-9]{8}$ ]]; then
-		if [ ${LATEST//-} -gt ${_VERSION_//-} ]; then
-			while read -r; do
-				printf "%s\n" "$REPLY"
-			done <<-EOF
-				New version available:    $LATEST
-				Current version:          $_VERSION_
-			EOF
-		else
-			INFO "No updates are available."
-		fi
-	else
-		FAIL 1 "$LINENO" "Failed to check for available updates."
+	if ! type -fP wget > /dev/null 2>&1; then
+		FAIL 1 "$LINENO" "Dependency 'wget' not met."
 	fi
+
+	INFO "Checking for available updates to ubuntu-syschk."
+	VERSION_URL="$DOM/terminalforlife/Extra/raw/master/versions"
+	while IFS='=' read -a LINE; do
+		if  [ "${LINE[0]}" == "$0" ]; then
+			LATEST="${LINE[1]}"
+
+			if [[ "${LATEST//-}" =~ ^[0-9]{8}$ ]]; then
+				if [ ${LATEST//-} -gt ${_VERSION_//-} ]; then
+					while read -r; do
+						printf "%s\n" "$REPLY"
+					done <<-EOF
+						New version available:    $LATEST
+						Current version:          $_VERSION_
+					EOF
+				else
+					INFO "No updates are available."
+				fi
+			else
+				FAIL 1 "$LINENO" "Failed to check for available updates."
+			fi
+		fi
+	done <<< "$(wget -q "$VERSION_URL" -O -)"
 
 	exit 0
 fi
@@ -218,7 +217,7 @@ fi
 declare -i AC=0
 
 if [ $SERVICES -eq 0 ]; then
-	if type -fP systemctl &> /dev/null; then
+	if type -fP systemctl > /dev/null 2>&1; then
 		if [ $FIREWALL -eq 0 ]; then
 			INFO "Asking SystemD if the UFW service is active."
 			if ! systemctl -q is-active ufw; then
@@ -241,7 +240,7 @@ if [ $SERVICES -eq 0 ]; then
 		FAIL 0 "$LINENO" "Unable to find or access: systemctl"
 	fi
 
-	if type -fP systemd-analyze &> /dev/null; then
+	if type -fP systemd-analyze > /dev/null 2>&1; then
 		INFO "Loading and checking unit files with SystemD."
 		systemd-analyze verify || ALERT "SystemD detected one or more unit-related errors."
 	else
@@ -250,7 +249,7 @@ if [ $SERVICES -eq 0 ]; then
 fi
 
 if [ $PASSWORD -eq 0 ]; then
-	if type -fP expiry &> /dev/null; then
+	if type -fP expiry > /dev/null 2>&1; then
 		INFO "Checking current user's password expiration."
 		expiry -c || ALERT "Error(s) detected while checking password expiration."
 	else
@@ -259,7 +258,7 @@ if [ $PASSWORD -eq 0 ]; then
 fi
 
 if [ $SWAP -eq 0 ]; then
-	if type -fP /sbin/swapon &> /dev/null; then
+	if type -fP /sbin/swapon > /dev/null 2>&1; then
 		INFO "Looking for active swap files or partitions."
 		readarray ARRAY <<< "$(/sbin/swapon --noheadings)"
 		if [ ${#ARRAY[@]} -eq 0 ]; then
@@ -271,7 +270,7 @@ if [ $SWAP -eq 0 ]; then
 fi
 
 if [ $STORAGE -eq 0 ]; then
-	if type -fP df &> /dev/null; then
+	if type -fP df > /dev/null 2>&1; then
 		while read -a X; do
 			if [[ "${X[0]}" == /dev/* ]]; then
 				INFO "Querying ${X[0]} for usage greater than 90%."
@@ -302,7 +301,7 @@ if [ $STORAGE -eq 0 ]; then
 fi
 
 if [ $PERMS -eq 0 ]; then
-	if type -fP stat &> /dev/null; then
+	if type -fP stat > /dev/null 2>&1; then
 		STAT(){
 			if [ -e "$1" ]; then
 				if [ -d "$1" ]; then
@@ -376,7 +375,7 @@ if [ $PERMS -eq 0 ]; then
 fi
 
 if [ $PACKAGES -eq 0 ]; then
-	if type -fP apt-get &> /dev/null; then
+	if type -fP apt-get > /dev/null 2>&1; then
 		INFO "Asking APT if there are any package changes."
 		OPT='APT::Get::Show-User-Simulation-Note=0'
 		while read -a X; do
@@ -399,7 +398,7 @@ if [ $PACKAGES -eq 0 ]; then
 		FAIL 0 "$LINENO" "Unable to find or access: apt-get"
 	fi
 
-	if type -fP dpkg &> /dev/null; then
+	if type -fP dpkg > /dev/null 2>&1; then
 		INFO "Performing database sanity and consistency checks."
 		if ! dpkg --audit; then
 			ALERT "One or more APT database checks have failed."
@@ -410,7 +409,7 @@ if [ $PACKAGES -eq 0 ]; then
 fi
 
 if [ $TEMPS -eq 0 ]; then
-	if type -fP sensors &> /dev/null; then
+	if type -fP sensors > /dev/null 2>&1; then
 		INFO "Checking hardware sensors for high CPU temperature."
 		while read -a X; do
 			if [ "${X[0]}${X[1]}${X[2]}" == "Physicalid0:" ]; then
@@ -494,7 +493,7 @@ if [ $SWAPPINESS -eq 0 ]; then
 fi
 
 if [ $GRUB -eq 0 ]; then
-	if type -fP grub-script-check &> /dev/null; then
+	if type -fP grub-script-check > /dev/null 2>&1; then
 		if [ -r /boot/grub/grub.cfg ]; then
 			INFO "Checking /boot/grub/grub.cfg for errors."
 			if ! grub-script-check /boot/grub/grub.cfg; then
@@ -509,7 +508,7 @@ if [ $GRUB -eq 0 ]; then
 fi
 
 if [ $SHMCHK -eq 0 ]; then
-	if type -fP /bin/mount &> /dev/null; then
+	if type -fP /bin/mount > /dev/null 2>&1; then
 		# Ubuntu-recommended settings.
 		while read -a X; do
 			if [ "${X[0]}${X[2]}" == "tmpfs/dev/shm" ]; then
@@ -538,7 +537,7 @@ if [ $SHMCHK -eq 0 ]; then
 fi
 
 if [ $DPKGRC -eq 0 ]; then
-	if type -fP dpkg &> /dev/null; then
+	if type -fP dpkg > /dev/null 2>&1; then
 		#TODO - Add a blacklist for the user!
 		INFO "Querying DPKG for packages with an 'rc' status."
 		while read -ra REPLY; do
@@ -580,9 +579,9 @@ if [ $IPSPOOF -eq 0 ]; then
 fi
 
 if [ $SSHSRV -eq 0 ]; then
-	if type -fP dpkg-query &> /dev/null; then
+	if type -fP dpkg-query > /dev/null 2>&1; then
 		INFO "Checking for safer SSH server settings: $FILE"
-		if ! dpkg-query -W openssh-server &> /dev/null; then
+		if ! dpkg-query -W openssh-server > /dev/null 2>&1; then
 			FAIL 0 "$LINENO" "Is the OpenSSH server installed?"
 		else
 			MATCH1="^[Pp]ermit[Rr]oot[Ll]ogin no$"
