Update autoexec with omission of libtflbp-sh

diff --git a/source/autoexec/autoexec b/source/autoexec/autoexec
--- a/source/autoexec/autoexec
+++ b/source/autoexec/autoexec
@@ -3,7 +3,7 @@
 #------------------------------------------------------------------------------
 # Project Name      - Extra/source/autoexec/autoexec
 # Started On        - Thu 31 Oct 22:49:41 GMT 2019
-# Last Change       - Sat 22 Feb 11:03:24 GMT 2020
+# Last Change       - Wed 11 Nov 04:07:17 GMT 2020
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
@@ -14,16 +14,10 @@
 #
 #   bash (>= 4.4.18-2)
 #   coreutils (>= 8.28-1)
-#   libtflbp-sh (>= 2019-12-10)
 #   ncurses-bin (>= 6.1-1)
 #------------------------------------------------------------------------------
 
-set -e
-. /usr/lib/tflbp-sh/Err
-. /usr/lib/tflbp-sh/ChkDep
-set +e
-
-CurVer='2020-02-22'
+CurVer='2020-11-11'
 Progrm=${0##*/}
 
 Usage(){
@@ -38,6 +32,11 @@ Usage(){
 		  -o, --once               - Execute FILE only once; no looping.
 		  -r, --refresh <INT>      - Adjust to fit your performance needs.
 	EOF
+}
+
+Err(){
+	printf 'ERROR: %s\n' "$2" 1>&2
+	[ $1 -eq 1 ] && exit 1
 }
 
 while [ "$1" ]; do
@@ -88,7 +87,15 @@ fi
 
 ExecFile=$1; shift
 
-ChkDep tput sleep stat
+declare -i DepCount=0
+for Dep in tput sleep stat; {
+	if ! type -fP "$Dep" 1> /dev/null 2>&1; then
+		printf "Dependency '%s' not met.\n" "$Dep" 1>&2
+		DepCount++
+	fi
+}
+
+[ "$DepCount" == 'True' ] && exit 1
 
 if [ "$Once" != 'true' ]; then
 	TRAP(){
