Add bug TODO & some basic mimetype checking

diff --git a/source/autoexec/autoexec b/source/autoexec/autoexec
--- a/source/autoexec/autoexec
+++ b/source/autoexec/autoexec
@@ -3,7 +3,7 @@
 #------------------------------------------------------------------------------
 # Project Name      - Extra/source/autoexec/autoexec
 # Started On        - Thu 31 Oct 22:49:41 GMT 2019
-# Last Change       - Tue 15 Dec 22:15:07 GMT 2020
+# Last Change       - Thu 17 Dec 20:39:49 GMT 2020
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
@@ -13,16 +13,22 @@
 #
 # Bugs:
 #
-# N/A
+#TODO: Using AutoExec for man pages is buggy, but functional.
+#
+#      More specifically, the prompt shows through and when ^C-ing, the last
+#      line (message line with exit status) still shows. Pretty ugly. I'm not
+#      sure this is something which can be fixed, as it's probably just a
+#      limitation of Shell/terminals.
 #
 # Dependencies:
 #
 #   bash (>= 4.4.18-2)
 #   coreutils (>= 8.28-1)
+#   file (>= 1:5.32-2)
 #   ncurses-bin (>= 6.1-1)
 #------------------------------------------------------------------------------
 
-CurVer='2020-12-15'
+CurVer='2020-12-17'
 Progrm=${0##*/}
 
 Usage(){
@@ -108,7 +114,7 @@ fi
 ExecFile=$1; shift
 
 declare -i DepCount=0
-for Dep in tput sleep stat; {
+for Dep in file tput sleep stat; {
 	if ! type -P "$Dep" 1> /dev/null 2>&1; then
 		printf "Dependency '%s' not met.\n" "$Dep" 1>&2
 		DepCount++
@@ -116,6 +122,14 @@ for Dep in tput sleep stat; {
 }
 
 [ "$DepCount" == 'True' ] && exit 1
+
+# Check the mimetype of the file.
+case `file -b --mime-type "$ExecFile"` in
+	application|application/*)
+		Err 1 "Binary files are not supported." ;;
+	text/troff)
+		printf 'CAUTION: Unsupported Troff file detected.\n' 1>&2 ;;
+esac
 
 if [ "$Once" != 'true' ]; then
 	TRAP(){
