Add file-replacement prompt to installers

diff --git a/source/autoexec/autoexec-installer b/source/autoexec/autoexec-installer
--- a/source/autoexec/autoexec-installer
+++ b/source/autoexec/autoexec-installer
@@ -3,7 +3,7 @@
 #------------------------------------------------------------------------------
 # Project Name      - Extra/source/autoexec/autoexec-installer
 # Started On        - Thu 12 Mar 14:54:26 GMT 2020
-# Last Change       - Fri  9 Jul 11:24:31 BST 2021
+# Last Change       - Wed  1 Sep 10:18:23 BST 2021
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
@@ -46,17 +46,23 @@ fi
 
 [ `id -u` -ne 0 ] && Err 1 'Root access is required for system-wide changes.'
 
-printf 'Install latest version of AutoExec? [Y/N] '
-read Answer
-case $Answer in
-	[Yy]|[Yy][Ee][Ss])
-		printf 'Continuing with installation.\n' ;;
-	[Nn]|[Nn][Oo])
-		printf 'Abandoning installation.\n'
-		exit 0 ;;
-	*)
-		Err 2 'Invalid response -- quitting.' ;;
-esac
+while :; do
+	printf 'Install latest version of AutoExec? [Y/N] '
+
+	read Input
+	case $Input in
+		[Yy]|[Yy][Ee][Ss])
+			printf 'Continuing with installation.\n'
+			break ;;
+		[Nn]|[Nn][Oo])
+			printf 'Abandoning installation.\n'
+			exit 0 ;;
+		'')
+			Err 0 'Empty response -- try again.' ;;
+		*)
+			Err 0 'Invalid response -- try again.' ;;
+	esac
+done
 
 LogFile='/tmp/autoexec-installer.log'
 [ -f "$LogFile" ] || 1> "$LogFile"
@@ -144,6 +150,29 @@ for File in\
 	'autoexec.1.gz:/usr/share/man/man1/autoexec.1.gz'\
 	'autoexec:/usr/bin/autoexec'
 do
+	Replace='False'
+
+	while :; do
+		printf "File '%s' found.\n" "${File#*:}"
+		printf 'Replace existing file? [Y/N] '
+
+		read Input
+		case $Input in
+			[Yy]|[Yy][Ee][Ss])
+				Replace='True'
+				break ;;
+			[Nn]|[Nn][Oo])
+				Replace='False'
+				break ;;
+			'')
+				Err 0 'Empty response -- try again.' ;;
+			*)
+				Err 0 'Invalid response -- try again.' ;;
+		esac
+	done
+
+	[ "$Replace" = 'True' ] || continue
+
 	printf "* Installing '%s' ... " "${File%%:*}"
 	if mv "$TmpDir/${File%%:*}" "${File#*:}" 2>> "$LogFile"; then
 		printf '\033[32m[OK]\033[0m\n'
@@ -223,7 +252,7 @@ for File in '/usr/bin/autoexec'; do
 					case $Line in
 						'#   '[!\ ]*)
 							printf '\033[1;93m%s\e[0m\n' "${Line#\#   }" ;;
-						*|'')
+						*)
 							DepErr=$((DepErr + 1)) ;;
 					esac ;;
 			esac
diff --git a/source/cito/cito-installer b/source/cito/cito-installer
--- a/source/cito/cito-installer
+++ b/source/cito/cito-installer
@@ -46,17 +46,23 @@ fi
 
 [ `id -u` -eq 0 ] || Err 1 'Root access is required for system-wide changes.'
 
-printf 'Install latest version of Cito? [Y/N] '
-read Answer
-case $Answer in
-	[Yy]|[Yy][Ee][Ss])
-		printf 'Continuing with installation.\n' ;;
-	[Nn]|[Nn][Oo])
-		printf 'Abandoning installation.\n'
-		exit 0 ;;
-	*)
-		Err 2 'Invalid response -- quitting.' ;;
-esac
+while :; do
+	printf 'Install latest version of Cito? [Y/N] '
+
+	read Input
+	case $Input in
+		[Yy]|[Yy][Ee][Ss])
+			printf 'Continuing with installation.\n'
+			break ;;
+		[Nn]|[Nn][Oo])
+			printf 'Abandoning installation.\n'
+			exit 0 ;;
+		'')
+			Err 0 'Empty response -- try again.' ;;
+		*)
+			Err 0 'Invalid response -- try again.' ;;
+	esac
+done
 
 LogFile='/tmp/cito-installer.log'
 [ -f "$LogFile" ] || 1> "$LogFile"
@@ -145,6 +151,29 @@ for File in\
 	'cito-list:/usr/bin/cito-list'\
 	'cito:/usr/bin/cito'
 do
+	Replace='False'
+
+	while :; do
+		printf "File '%s' found.\n" "${File#*:}"
+		printf 'Replace existing file? [Y/N] '
+
+		read Input
+		case $Input in
+			[Yy]|[Yy][Ee][Ss])
+				Replace='True'
+				break ;;
+			[Nn]|[Nn][Oo])
+				Replace='False'
+				break ;;
+			'')
+				Err 0 'Empty response -- try again.' ;;
+			*)
+				Err 0 'Invalid response -- try again.' ;;
+		esac
+	done
+
+	[ "$Replace" = 'True' ] || continue
+
 	printf "* Installing '%s' ... " "${File%%:*}"
 	if mv "$TmpDir/${File%%:*}" "${File#*:}" 2>> "$LogFile"; then
 		printf '\033[32m[OK]\033[0m\n'
@@ -206,7 +235,7 @@ for File in '/usr/bin/cito' '/usr/bin/cito-list'; do
 					case $Line in
 						'#   '[!\ ]*)
 							printf '\033[1;93m%s\e[0m\n' "${Line#\#   }" ;;
-						*|'')
+						*)
 							DepErr=$((DepErr + 1)) ;;
 					esac ;;
 			esac
diff --git a/source/fetcher/fetcher-installer b/source/fetcher/fetcher-installer
--- a/source/fetcher/fetcher-installer
+++ b/source/fetcher/fetcher-installer
@@ -46,17 +46,23 @@ fi
 
 [ `id -u` -ne 0 ] && Err 1 'Root access is required for system-wide changes.'
 
-printf 'Install latest version of Fetcher? [Y/N] '
-read Answer
-case $Answer in
-	[Yy]|[Yy][Ee][Ss])
-		printf 'Continuing with installation.\n' ;;
-	[Nn]|[Nn][Oo])
-		printf 'Abandoning installation.\n'
-		exit 0 ;;
-	*)
-		Err 2 'Invalid response -- quitting.' ;;
-esac
+while :; do
+	printf 'Install latest version of Fetcher? [Y/N] '
+
+	read Input
+	case $Input in
+		[Yy]|[Yy][Ee][Ss])
+			printf 'Continuing with installation.\n'
+			break ;;
+		[Nn]|[Nn][Oo])
+			printf 'Abandoning installation.\n'
+			exit 0 ;;
+		'')
+			Err 0 'Empty response -- try again.' ;;
+		*)
+			Err 0 'Invalid response -- try again.' ;;
+	esac
+done
 
 LogFile='/tmp/fetcher-installer.log'
 [ -f "$LogFile" ] || 1> "$LogFile"
@@ -144,6 +150,29 @@ for File in\
 	'fetcher.1.gz:/usr/share/man/man1/fetcher.1.gz'\
 	'fetcher:/usr/bin/fetcher'
 do
+	Replace='False'
+
+	while :; do
+		printf "File '%s' found.\n" "${File#*:}"
+		printf 'Replace existing file? [Y/N] '
+
+		read Input
+		case $Input in
+			[Yy]|[Yy][Ee][Ss])
+				Replace='True'
+				break ;;
+			[Nn]|[Nn][Oo])
+				Replace='False'
+				break ;;
+			'')
+				Err 0 'Empty response -- try again.' ;;
+			*)
+				Err 0 'Invalid response -- try again.' ;;
+		esac
+	done
+
+	[ "$Replace" = 'True' ] || continue
+
 	printf "* Installing '%s' ... " "${File%%:*}"
 	if mv "$TmpDir/${File%%:*}" "${File#*:}" 2>> "$LogFile"; then
 		printf '\033[32m[OK]\033[0m\n'
@@ -198,7 +227,7 @@ for File in '/usr/bin/fetcher'; do
 					case $Line in
 						'#   '[!\ ]*)
 							printf '\033[1;93m%s\e[0m\n' "${Line#\#   }" ;;
-						*|'')
+						*)
 							DepErr=$((DepErr + 1)) ;;
 					esac ;;
 			esac
diff --git a/source/simplify-ubuntu/simplify-ubuntu-installer b/source/simplify-ubuntu/simplify-ubuntu-installer
--- a/source/simplify-ubuntu/simplify-ubuntu-installer
+++ b/source/simplify-ubuntu/simplify-ubuntu-installer
@@ -50,18 +50,23 @@ if [ `id -u` -ne 0 ]; then
 	exit 1
 fi
 
-printf 'Install latest version of Simplify Ubuntu? [Y/N] '
-read Answer
-case $Answer in
-	[Yy]|[Yy][Ee][Ss])
-		printf 'Continuing with installation.\n' ;;
-	[Nn]|[Nn][Oo])
-		printf 'Abandoning installation.\n'
-		exit 0 ;;
-	*)
-		printf 'ERROR: Invalid response -- quitting.\n' 1>&2
-		exit 2 ;;
-esac
+while :; do
+	printf 'Install latest version of Simplify Ubuntu? [Y/N] '
+
+	read Input
+	case $Input in
+		[Yy]|[Yy][Ee][Ss])
+			printf 'Continuing with installation.\n'
+			break ;;
+		[Nn]|[Nn][Oo])
+			printf 'Abandoning installation.\n'
+			exit 0 ;;
+		'')
+			Err 0 'Empty response -- try again.' ;;
+		*)
+			Err 0 'Invalid response -- try again.' ;;
+	esac
+done
 
 LogFile='/tmp/simplify-ubuntu-installer.log'
 [ -f "$LogFile" ] || 1> "$LogFile"
@@ -156,6 +161,29 @@ for File in\
 	'simplify-ubuntu.8.gz:/usr/share/man/man8/simplify-ubuntu.8.gz'\
 	'simplify-ubuntu:/usr/bin/simplify-ubuntu'
 do
+	Replace='False'
+
+	while :; do
+		printf "File '%s' found.\n" "${File#*:}"
+		printf 'Replace existing file? [Y/N] '
+
+		read Input
+		case $Input in
+			[Yy]|[Yy][Ee][Ss])
+				Replace='True'
+				break ;;
+			[Nn]|[Nn][Oo])
+				Replace='False'
+				break ;;
+			'')
+				Err 0 'Empty response -- try again.' ;;
+			*)
+				Err 0 'Invalid response -- try again.' ;;
+		esac
+	done
+
+	[ "$Replace" = 'True' ] || continue
+
 	printf "* Installing '%s' ... " "${File%%:*}"
 	if mv "$TmpDir/${File%%:*}" "${File#*:}" 2>> "$LogFile"; then
 		printf '\033[32m[OK]\033[0m\n'
@@ -210,7 +238,7 @@ for File in '/usr/bin/simplify-ubuntu'; do
 					case $Line in
 						'#   '[!\ ]*)
 							printf '\033[1;93m%s\e[0m\n' "${Line#\#   }" ;;
-						*|'')
+						*)
 							DepErr=$((DepErr + 1)) ;;
 					esac ;;
 			esac
