Finish config file feature & improve var names

diff --git a/source/autoexec/autoexec b/source/autoexec/autoexec
--- a/source/autoexec/autoexec
+++ b/source/autoexec/autoexec
@@ -3,13 +3,15 @@
 #------------------------------------------------------------------------------
 # Project Name      - Extra/source/autoexec/autoexec
 # Started On        - Thu 31 Oct 22:49:41 GMT 2019
-# Last Change       - Fri  5 Mar 00:59:10 GMT 2021
+# Last Change       - Tue  9 Mar 00:28:40 GMT 2021
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
 # Features:
 #
+#TODO: Use sensible keys in configuration file. (IE: 'Color' VS 'NoColor')
 #TODO: Add timing functionality to C FILEs.
+#TODO: Consider support for Node.js.
 #
 # Bugs:
 #
@@ -32,7 +34,7 @@
 #   ncurses-bin (>= 6.1-1)
 #------------------------------------------------------------------------------
 
-CurVer='2021-03-05'
+CurVer='2021-03-09'
 Progrm=${0##*/}
 
 Usage(){
@@ -70,6 +72,13 @@ TIMEFORMAT='[R:%3R|U:%3U|S:%3S|P:%P]'
 MainDir="$HOME/.config/$Progrm"
 Config="$MainDir/config"
 
+Color='True'
+ExitStatus='True'
+Force='False'
+Spinner='True'
+Time='False'
+WaitMSG='True'
+
 while [ "$1" ]; do
 	case $1 in
 		--)
@@ -101,17 +110,17 @@ while [ "$1" ]; do
 		--once|-o)
 			Once='true' ;;
 		--no-waitmsg|-W)
-			NoWaitMSG='True' ;;
+			WaitMSG='False' ;;
 		--no-spinner|-S)
-			NoSpinner='True' ;;
+			Spinner='False' ;;
 		--no-exit|-E)
-			NoExitStatus='True' ;;
+			ExitStatus='False' ;;
 		--no-color|-C)
-			NoColor='True' ;;
+			Color='False' ;;
 		--force|-f)
 			Force='True' ;;
 		--time|-t)
-			DoTime='True' ;;
+			Time='True' ;;
 		--check|-c)
 			Check='True' ;;
 		-*)
@@ -160,21 +169,36 @@ fi
 
 case $ExecFile in
 	*.c|*.cpp)
-		if [ "$DoTime" == 'True' ]; then
+		if [ "$Time" == 'True' ]; then
 			Err 1 "Option '--time|-t' not supported on FILE."
 		fi
 
 		CFound='True' ;;
 esac
 
-[ -d "$MainDir" ] || mkdir -p "$MainDir"
+#-------------------------------------------------Handle the Configuration File
 
-#rm "$Config" #:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+[ -d "$MainDir" ] || mkdir -p "$MainDir"
 
 InvalidKeys=0
 if [ -f "$Config" ]; then
 	[ -r "$Config" ] || Err 1 'Configuration file unreadable.'
 
+	# Usage: Boolean <KEY> <VALUE>
+	Boolean() {
+		case $2 in
+			True|False)
+				return 0 ;;
+			'')
+				Err 0 "Key '$1' missing boolean." ;;
+			*)
+				Err 0 "Key '$1' invalid boolean." ;;
+		esac
+
+		let InvalidSets++
+	}
+
+	InvalidSets=0
 	while read; do
 		case $REPLY in
 			'#'*|'') continue ;;
@@ -183,51 +207,54 @@ if [ -f "$Config" ]; then
 		IFS='=' read Key Value <<< "$REPLY"
 
 		case $Key in
-			NoColor)
-				NoColor=$Value ;;
-			NoExit)
-				NoExit=$Value ;;
-			NoSpinner)
-				NoSpinner=$Value ;;
-			NoWaitMSG)
-				NoWaitMSG=$Value ;;
+			Color)
+				Boolean "$Key" "$Value" && Color=$Value ;;
+			ExitStatus)
+				Boolean "$Key" "$Value" && ExitStatus=$Value ;;
+			Spinner)
+				Boolean "$Key" "$Value" && Spinner=$Value ;;
+			WaitMSG)
+				Boolean "$Key" "$Value" && WaitMSG=$Value ;;
 			Check)
-				Check=$Value ;;
+				Boolean "$Key" "$Value" && Check=$Value ;;
 			Force)
-				Force=$Value ;;
+				Boolean "$Key" "$Value" && Force=$Value ;;
 			Refresh)
-				Refresh=$Value ;;
+				REGEX='^([[:digit:]]+|[[:digit:]]+\.[[:digit:]]+)$'
+				if [[ $Value =~ $REGEX ]]; then
+					Refresh=$Value
+				else
+					Err 0 "Key '$Key' given invalid refresh rate."
+				fi ;;
 			Time)
-				Time=$Value ;;
+				Boolean "$Key" "$Value" && Time=$Value ;;
 			*)
-				Err 0 "Invlaid key '$Key' detected."
-				let InvalidKeys++ ;;
+				Err 0 "Key '$Key' invalid."
+				let InvalidSets++ ;;
 		esac
 	done < "$Config"
 
-	[ $InvalidKeys -gt 0 ] && exit 1
+	[ $InvalidSets -gt 0 ] && exit 1
 else
 	while read; do
 		printf '%s\n' "$REPLY"
 	done <<-EOF > "$Config"
-		# User configuration for AutoExec (2021-03-05). For information on
-		# these options, please refer to the autoexec(1) manual page or its
-		# usage output.
+		# User configuration generated by AutoExec ($CurVer). For
+		# information on these options, please refer to the autoexec(1)
+		# manual page or its usage output.
 
-		NoColor=false
-		NoExit=false
-		NoSpinner=false
-		834u=24osfd
-		NoWaitMSG=false
-		Check=false
-		Force=false
+		Check=False
+		Color=True
+		Exit=True
+		Force=False
 		Refresh=0.05
-		Time=false
-		asdfasdfas=sdfds
+		Spinner=True
+		Time=False
+		WaitMSG=True
 	EOF
 fi
 
-exit #:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+#----------------------------------------------Prepare for an Execute Main Loop
 
 TRAP(){
 	if [ "$Once" != 'true' ]; then
@@ -270,7 +297,6 @@ Interpreter(){
 	Exec=$1
 }
 
-#printf '\n'
 while :; do
 	# Determine the interpreter to use.
 	if [ "$CFound" != 'True' ] && [ -z "$Exec" ]; then
@@ -315,10 +341,7 @@ while :; do
 
 			if [ "$Errors" != 'True' ]; then
 				if [ "$CFound" == 'True' ]; then
-					if [ "$DoTime" == 'True' ]; then
-						TimingErr='True'
-						exit 1
-					else
+					if [ "$Time" == 'True' ]; then
 						OutFile='/tmp/ae_cfile_run.tmp'
 						if gcc -o "$OutFile" "$ExecFile"; then
 							chmod 755 "$OutFile"
@@ -327,9 +350,12 @@ while :; do
 						else
 							Exit=999
 						fi
+					else
+						TimingErr='True'
+						exit 1
 					fi
 				else
-					if [ "$DoTime" == 'True' ]; then
+					if [ "$Time" == 'True' ]; then
 						time "$Exec" "$ExecFile" "$@"
 						Exit=$?
 					else
@@ -354,41 +380,41 @@ while :; do
 
 	if [ "$Once" != 'true' ]; then
 		# Have the exit status on the bottom-right of the terminal.
-		if [ "$NoExitStatus" != 'True' ]; then
+		if [ "$ExitStatus" == 'True' ]; then
 			tput cup $Lines $((Columns - 3))
 
-			if [ "$NoColor" == 'True' ]; then
-				printf '%#3d' $Exit
-			else
+			if [ "$Color" == 'True' ]; then
 				if [ $Exit -eq 0 ]; then
 					printf '\e[2;37m%#3d\e[0m' $Exit
 				else
 					printf '\e[1;31m%#3d\e[0m' $Exit
 				fi
+			else
+				printf '%#3d' $Exit
 			fi
 		fi
 
-		if [ "$NoWaitMSG" != 'True' ]; then
-			if [ "$NoSpinner" == 'True' ]; then
-				tput cud $Lines
-
-				if [ "$NoColor" == 'True' ]; then
-					printf '\rWaiting for changes... '
-				else
-					printf '\r\e[2;37mWaiting for changes...\e[0m '
-				fi
-			else
+		if [ "$WaitMSG" == 'True' ]; then
+			if [ "$Spinner" == 'True' ]; then
 				for Char in '|' '/' '-' '\'; {
 					tput cud $Lines
 
-					if [ "$NoColor" == 'True' ]; then
-						printf '\r[%s] Waiting for changes... ' "$Char"
-					else
+					if [ "$Color" == 'True' ]; then
 						printf '\r\e[2;37m[%s] Waiting for changes...\e[0m ' "$Char"
+					else
+						printf '\r[%s] Waiting for changes... ' "$Char"
 					fi
 
 					sleep 0.04
 				}
+			else
+				tput cud $Lines
+
+				if [ "$Color" == 'True' ]; then
+					printf '\r\e[2;37mWaiting for changes...\e[0m '
+				else
+					printf '\rWaiting for changes... '
+				fi
 			fi
 		fi
 	fi
