Remove config file, fix bugs, & generally improve
From this point on, I'll be focusing on _stability_.

Main changes:

* The shebang now works properly, including other arguments.
* When using `-e`, you can now provide arguments. (IE: `sh -e`)
* Because of point #2, AWK scripts can be used with AE.
* Switched over to POSIX character classes, to avoid any locale issues.
* Removed experimental C/C++ execution, to avoid complexity.
* Removed configuration file, to avoid complexity & focus on stability.
* Cleaned up header's TODOs.
* Tidied up some code, like the dependency checking.
* Opted for sane `SheBang*` variable names.
* Improved some of the error messages, regarding OPTs.
* Fixed error message for missing interpreter not displaying.
* Using realpath(1) instead of readlink(1) for '/bin/sh'.
* Updated the man page for autoexec(1) to reflect these changes.
* Added HISTORY section to man page, to document some key changes.

diff --git a/source/autoexec/autoexec b/source/autoexec/autoexec
--- a/source/autoexec/autoexec
+++ b/source/autoexec/autoexec
@@ -3,39 +3,22 @@
 #------------------------------------------------------------------------------
 # Project Name      - Extra/source/autoexec/autoexec
 # Started On        - Thu 31 Oct 22:49:41 GMT 2019
-# Last Change       - Sun 27 Jun 06:35:28 BST 2021
+# Last Change       - Sun 22 Aug 11:49:28 BST 2021
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
 # Features:
 #
-#TODO: Use sensible keys in configuration file. (IE: 'Color' VS 'NoColor')
-#TODO: Add timing functionality to C FILEs.
-#TODO: Consider support for Node.js.
 #TODO: Use POSIX character classes instead of regular ones.
 #
 # Bugs:
 #
-#TODO: Flags given to the shebang's executable are ignored.
-#
-#      This problem went unnoticed for far too long. This is especially
-#      problematic with AWK scripts, because they need the `-f` argument.
-#
-#      Consider completely switching AutExec Over to letting the kernel handle
-#      the execution, and so requiring the files have the execute bit set? Not
-#      ideal at all, but doable.
-#
-#TODO: Flags don't work, because configuration file has priority.
 #TODO: Using AutoExec for man pages (pagers) is buggy, but functional.
 #
 #      More specifically, the prompt shows through and when ^C-ing, the last
 #      line (message line with exit status) still shows. Pretty ugly. I'm not
 #      sure this is something which can be fixed, as it's probably just a
 #      limitation of Shell/terminals.
-#
-# Optional Dependencies:
-#
-#   gcc (>= 4:7.4.0-1)
 #
 # Dependencies:
 #
@@ -45,7 +28,7 @@
 #   ncurses-bin (>= 6.1-1)
 #------------------------------------------------------------------------------
 
-CurVer='2021-06-27'
+CurVer='2021-08-22'
 Progrm=${0##*/}
 ProgrmFancy='AutoExec'
 
@@ -77,12 +60,20 @@ Usage(){
 
 Err(){
 	printf 'ERROR: %s\n' "$2" 1>&2
-	[ $1 -eq 1 ] && exit 1
+	(( $1 >= 1 )) && exit $1
 }
 
-TIMEFORMAT='[R:%3R|U:%3U|S:%3S|P:%P]'
-MainDir="$HOME/.config/autoexec"
-Config="$MainDir/config"
+kIMEFORMAT='[R:%3R|U:%3U|S:%3S|P:%P]'
+
+Check='False'
+Color='True'
+ExitStatus='True'
+Force='False'
+Once='False'
+Refresh='0.05'
+Spinner='True'
+Time='False'
+WaitMSG='True'
 
 while [ "$1" ]; do
 	case $1 in
@@ -97,22 +88,25 @@ while [ "$1" ]; do
 
 			if [ -z "$1" ]; then
 				Err 1 'Name of command not provided.'
-			elif ! type -P "$1" > /dev/null 2>&1; then
-				Err 1 'Provided command not found in PATH.'
+			#elif ! type -P "$1" > /dev/null 2>&1; then
+			#	Err 1 'Provided command not found in PATH.'
 			else
 				Exec=$1
 			fi ;;
 		--refresh|-r)
+			RefreshArg=$1
 			shift
 
 			if [ -z "$1" ]; then
 				Err 1 'Unspecified refresh rate.'
-			elif ! [[ $1 =~ ^([0-9]+|[0-9]+.[0-9]+)$ ]]; then
+			elif ! [[ $1 =~ ^([[:digit:]]+|[[:digit:]]+.[[:digit:]]+)$ ]]; then
 				Err 1 'Invalid refresh rate.'
 			else
+				RefreshCustom='True'
 				Refresh=$1
 			fi ;;
 		--once|-o)
+			OnceArg=$1
 			Once='true' ;;
 		--no-waitmsg|-W)
 			WaitMSG='False' ;;
@@ -127,6 +121,7 @@ while [ "$1" ]; do
 		--time|-t)
 			Time='True' ;;
 		--check|-c)
+			CheckArg=$1
 			Check='True' ;;
 		-*)
 			Err 1 'Incorrect option(s) specified.' ;;
@@ -136,8 +131,8 @@ while [ "$1" ]; do
 	shift
 done
 
-if [ "$Once" == 'true' -a ${#Refresh} -gt 0 ]; then
-	Err 1 "Options '--once|-o' and '--refresh|-r' aren't compatible."
+if [ "$Once" == 'true' -a "$RefreshCustom" == 'True' ]; then
+	Err 1 "OPTs '$OnceArg' and '$RefreshArg' aren't compatible."
 fi
 
 [ -z "$1" ] && Err 1 'Missing argument -- file name required.'
@@ -146,107 +141,15 @@ fi
 
 ExecFile=$1; shift
 
-DepChk(){
-	DepCount=0
-	for Dep in "$@"; {
-		if ! type -P "$Dep" &> /dev/null; then
-			Err 0 "Dependency '$Dep' not met."
-			let DepCount++
-		fi
-	}
-
-	[ $DepCount -gt 0 ] && exit 1
+DepCount=0
+for Dep in file tput sleep stat realpath; {
+	if ! type -P "$Dep" &> /dev/null; then
+		Err 0 "Dependency '$Dep' not met."
+		let DepCount++
+	fi
 }
 
-DepChk file tput sleep stat
-
-#-------------------------------------------------Handle the Configuration File
-
-[ -d "$MainDir" ] || mkdir -p "$MainDir"
-
-if [ -f "$Config" ]; then
-	[ -r "$Config" ] || Err 1 'Configuration file unreadable.'
-
-	InvalidKeys=0
-
-	# Usage: Boolean <KEY> <VALUE>
-	Boolean() {
-		case $2 in
-			True|False)
-				return 0 ;;
-			'')
-				Err 0 "Key '$1' missing boolean." ;;
-			*)
-				Err 0 "Key '$1' invalid boolean." ;;
-		esac
-
-		let InvalidSets++
-	}
-
-	InvalidSets=0
-	while read; do
-		case $REPLY in
-			'#'*|'') continue ;;
-		esac
-
-		IFS='=' read Key Value <<< "$REPLY"
-
-		case $Key in
-			Color)
-				[ -n "$Color" ] && continue
-				Boolean "$Key" "$Value" && Color=$Value ;;
-			ExitStatus)
-				[ -n "$ExitStatus" ] && continue
-				Boolean "$Key" "$Value" && ExitStatus=$Value ;;
-			Spinner)
-				[ -n "$Spinner" ] && continue
-				Boolean "$Key" "$Value" && Spinner=$Value ;;
-			WaitMSG)
-				[ -n "$WaitMSG" ] && continue
-				Boolean "$Key" "$Value" && WaitMSG=$Value ;;
-			Check)
-				[ -n "$Check" ] && continue
-				Boolean "$Key" "$Value" && Check=$Value ;;
-			Force)
-				[ -n "$Force" ] && continue
-				Boolean "$Key" "$Value" && Force=$Value ;;
-			Refresh)
-				[ -n "$Refresh" ] && continue
-
-				REGEX='^([[:digit:]]+|[[:digit:]]+\.[[:digit:]]+)$'
-				if [[ $Value =~ $REGEX ]]; then
-					Refresh=$Value
-				else
-					Err 0 "Key '$Key' given invalid refresh rate."
-				fi ;;
-			Time)
-				[ -n "$Time" ] && continue
-				Boolean "$Key" "$Value" && Time=$Value ;;
-			*)
-				Err 0 "Key '$Key' invalid."
-				let InvalidSets++ ;;
-		esac
-	done < "$Config"
-
-	[ $InvalidSets -gt 0 ] && exit 1
-else
-	while read; do
-		printf '%s\n' "$REPLY"
-	done <<-EOF > "$Config"
-		# User configuration generated by $ProgrmFancy ($CurVer). For
-		# information on these options, please refer to the autoexec(1)
-		# manual page or its usage output.
-
-		Check=False
-		Color=True
-		ExitStatus=True
-		Force=False
-		Refresh=0.05
-		Spinner=True
-		Time=False
-		WaitMSG=True
-	EOF
-fi
+(( DepCount > 0 )) && exit 1
 
 #----------------------------------------------Prepare for an Execute Main Loop
 
@@ -258,38 +161,29 @@ if [ "$Force" == 'False' ]; then
 
 	case `file -b --mime-type "$ExecFile"` in
 		application|application/*)
-			Err 1 "Binary files are not supported." ;;
+			Err 1 'Binary files are not supported.' ;;
 	esac
 fi
 
-case $ExecFile in
-	*.c|*.cpp)
-		if [ "$Time" == 'True' ]; then
-			Err 1 "Option '--time|-t' not supported on FILE."
-		fi
-
-		CFound='True' ;;
-esac
-
-TRAP(){
+SignalHandler(){
 	if [ "$Once" != 'true' ]; then
 		tput ed
 		tput rmcup
 	fi
 
+	if [ -n "$InterpreterMissing" ]; then
+		Err 1 "Interpreter '$InterpreterMissing' not found."
+	fi
+
 	# Needs to be here otherwise the above line clears it.
-	if [ "$Force" == 'False' ]; then
-		if [ "$UnsupportedCheck" == 'True' ]; then
-			Err 1 "Option '--check|-c' not supported on FILE."
-		elif  [ "$TimingErr" == 'True' ]; then
-			Err 1 'Timing of C programs not yet supported.'
-		fi
+	if [ "$Force" == 'False' ] && [ "$UnsupportedCheck" == 'True' ]; then
+		Err 1 "OPT '$CheckArg' not supported on FILE."
 	fi
 
 	exit 0
 }
 
-trap 'TRAP' SIGINT EXIT
+trap 'SignalHandler' SIGINT EXIT
 
 [ "$Once" == 'true' ] || tput smcup
 
@@ -306,42 +200,43 @@ if [ "$Once" != 'true' ]; then
 fi
 
 Interpreter(){
-	type -P "$1" &> /dev/null ||
-		Err 1 "Interpreter '$1' not found."
+	if ! type -P "${1%% *}" &> /dev/null; then
+		InterpreterMissing=$1
+		exit 1
+	fi
 
 	Exec=$1
 }
 
 while :; do
 	# Determine the interpreter to use.
-	if [ "$CFound" != 'True' ] && [ -z "$Exec" ]; then
+	if [ -z "$Exec" ]; then
 		read SheBang < "$ExecFile"
-		SheBang1=${SheBang#*\!}
-		SheBang2=${SheBang1##*/}
-		SheBang3=${SheBang2%% *}
-		case $SheBang3 in
+		SheBangMain=${SheBang#\#\!}
+		SheBangBase=${SheBangMain##*/}
+		case ${SheBangBase%% *} in
 			env)
-				SheBang2A=${SheBang2#env }
-				Interpreter "${SheBang2A%% *}" ;;
+				SheBangBaseEnv=${SheBangBase#env }
+				Interpreter "${SheBangBaseEnv%% *}" ;;
 			*)
-				Interpreter "$SheBang3" ;;
+				Interpreter "$SheBangBase" ;;
 		esac
 	fi
 
 	if [ -f "$ExecFile" ] && [ -r "$ExecFile" ]; then
 		SSE=`stat -c '%Y' "$ExecFile" 2> /dev/null`
 
-		if [ 0${SSEOld//[!0-9]} -lt 0${SSE//[!0-9]} ]; then
+		if [ 0${SSEOld//[![:digit:]]} -lt 0${SSE//[![:digit:]]} ]; then
 			[ "$Once" == 'true' ] || tput clear
 
 			# If using DASH or BASH, check for errors before executing.
 			if [ "$Check" == 'True' ]; then
 				unset Errors
-				if [ "$Exec" == 'bash' ]; then
+				if [ "${Exec%% *}" == 'bash' ]; then
 					bash -n "$ExecFile" || Errors='True'
-				elif [ "$Exec" == 'sh' ]; then
+				elif [ "${Exec%% *}" == 'sh' ]; then
 					File=`type -P sh`
-					Link=`readlink -e "$File"`
+					Link=`realpath "$File"`
 					if [ "$Link" == '/bin/dash' ]; then
 						dash -n "$ExecFile" || Errors='True'
 					else
@@ -355,36 +250,19 @@ while :; do
 			fi
 
 			if [ "$Errors" != 'True' ]; then
-				if [ "$CFound" == 'True' ]; then
-					if [ "$Time" == 'True' ]; then
-						OutFile='/tmp/ae_cfile_run.tmp'
-						if gcc -o "$OutFile" "$ExecFile"; then
-							chmod 755 "$OutFile"
-							"$OutFile" "$@"
-							Exit=$?
-						else
-							Exit=999
-						fi
-					else
-						TimingErr='True'
-						exit 1
-					fi
+				if [ "$Time" == 'True' ]; then
+					time $Exec "$ExecFile" "$@"
+					Exit=$?
 				else
-					if [ "$Time" == 'True' ]; then
-						time "$Exec" "$ExecFile" "$@"
-						Exit=$?
-					else
-						"$Exec" "$ExecFile" "$@"
-						Exit=$?
-					fi
+					$Exec "$ExecFile" "$@"
+					Exit=$?
 				fi
-
 			else
 				Exit=999
 			fi
 		fi
 
-		SSEOld=${SSE//[!0-9]}
+		SSEOld=${SSE//[![:digit:]]}
 	else
 		if [ "$Once" != 'true' ]; then
 			tput ed; tput rmcup
@@ -399,7 +277,7 @@ while :; do
 			tput cup $Lines $((Columns - 3))
 
 			if [ "$Color" == 'True' ]; then
-				if [ $Exit -eq 0 ]; then
+				if (( Exit == 0 )); then
 					printf '\e[2;37m%#3d\e[0m' $Exit
 				else
 					printf '\e[1;31m%#3d\e[0m' $Exit
