Use improved syntax

diff --git a/source/fetcher/fetcher b/source/fetcher/fetcher
--- a/source/fetcher/fetcher
+++ b/source/fetcher/fetcher
@@ -3,7 +3,7 @@
 #------------------------------------------------------------------------------
 # Project Name      - Extra/source/fetcher/fetcher
 # Started On        - Fri 18 Dec 01:42:22 GMT 2020
-# Last Change       - Wed 15 Dec 23:56:44 GMT 2021
+# Last Change       - Mon 20 Dec 07:15:22 GMT 2021
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
@@ -34,10 +34,10 @@
 #   wget (>= 1.19.4-1)
 #------------------------------------------------------------------------------
 
-CurVer='2021-12-15'
+CurVer='2021-12-20'
 Progrm=${0##*/}
 
-Usage(){
+Usage() {
 	while read; do
 		printf '%s\n' "$REPLY"
 	done <<-EOF
@@ -56,7 +56,7 @@ Usage(){
 	EOF
 }
 
-Err(){
+Err() {
 	printf 'Err: %s\n' "$2" 1>&2
 	(( $1 > 0 )) && exit $1
 }
@@ -67,7 +67,7 @@ LinkFile="$MainDir/links"
 # The [p]retty names, for use in errors and such.
 P_LinkFile="~/${LinkFile#/home/*/}"
 
-while [ "$1" ]; do
+while [ -n "$1" ]; do
 	case $1 in
 		--help|-h|-\?)
 			Usage; exit 0 ;;
@@ -83,9 +83,9 @@ while [ "$1" ]; do
 	shift
 done
 
-[ $# -eq 0 ] && Err 1 "Argument error -- see: $Progrm -h"
+(( $# == 0 )) && Err 1 "Argument error -- see: $Progrm -h"
 
-while [ "$1" ]; do
+while [ -n "$1" ]; do
 	case $1 in
 		fetch|list|remove)
 			Action=$1 ;;
@@ -108,33 +108,35 @@ while [ "$1" ]; do
 done
 
 DepCount=0
-for Dep in mkdir wget; do
+for Dep in mkdir sed wget; do
 	if ! type -P "$Dep" &> /dev/null; then
 		Err 0 "Dependency '$Dep' not met."
-		let DepCount++
+		(( DepCount++ ))
 	fi
 done
 
-[ $DepCount -gt 0 ] && exit 1
+(( DepCount > 0 )) && exit 1
 
 [ -d "$MainDir" ] || mkdir -p "$MainDir"
 
 # ANSI color escape sequences.
 if [ "$NoColor" != 'True' ]; then
-	C_Red='\e[1;31m'; C_Green='\e[1;32m'; C_Reset='\e[0m'
+	C_Red='\e[1;31m'
+	C_Green='\e[1;32m'
+	C_Reset='\e[0m'
 fi
 
 #----------------------------------------------------------------Main Functions
 
-CheckIfEmpty(){
+CheckIfEmpty() {
 	Line=0
 	while read; do
 		[[ $REPLY == \#* || $REPLY == '' ]] && continue
 
-		let Line++
+		(( Line++ ))
 	done < "$LinkFile"
 
-	[ $Line -eq 0 ] && Err 1 "No stored URLs found -- nothing to $1."
+	(( Line == 0 )) && Err 1 "No stored URLs found -- nothing to $1."
 }
 
 #---------------------------------------------------Create Link File If Missing
@@ -157,7 +159,7 @@ if [ "$Action" == 'list' ]; then
 	while read; do
 		[[ $REPLY == \#* || $REPLY == '' ]] && continue
 
-		let Line++
+		(( Line++ ))
 		printf "$C_Green%2d$C_Reset:  $C_Red%s$C_Reset\n" $Line "$REPLY"
 	done < "$LinkFile"
 	printf '\n'
@@ -178,12 +180,10 @@ elif [ "$Action" == 'remove' ]; then
 
 	printf 'URLs currently stored:\n\n'
 
-	Line=0
-	URLs=()
 	while read; do
 		[[ $REPLY == \#* || $REPLY == '' ]] && continue
 
-		let Line++
+		(( Line++ ))
 		URLs+=("$Line|$REPLY")
 		printf "$C_Green%2d$C_Reset:  $C_Red%s$C_Reset\n" $Line "$REPLY"
 	done < "$LinkFile"
@@ -204,11 +204,9 @@ elif [ "$Action" == 'remove' ]; then
 				sed -i "/${ToRemove//\//\\\/}/d" "$LinkFile"
 			else
 				Err 1 "Requested URL not found."
-			fi
-
-			;;
+			fi ;;
 		*|'')
-			Err 1 'Invalid or missing URL number provided.'
+			Err 1 'Invalid or missing URL number provided.' ;;
 	esac
 elif [ "$Action" == 'fetch' ]; then
 	CheckIfEmpty "$Action"
