Update Cito installer with new dep checking

diff --git a/source/cito/cito-installer b/source/cito/cito-installer
--- a/source/cito/cito-installer
+++ b/source/cito/cito-installer
@@ -3,7 +3,7 @@
 #------------------------------------------------------------------------------
 # Project Name      - Extra/source/cito/cito-installer
 # Started On        - Thu 12 Mar 14:54:26 GMT 2020
-# Last Change       - Tue 26 Jan 14:16:02 GMT 2021
+# Last Change       - Tue  2 Mar 16:18:06 GMT 2021
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
@@ -31,19 +31,20 @@
 #   curl (>= 7.47.0-1) | wget (>= 1.17.1-1)
 #------------------------------------------------------------------------------
 
+Err(){
+	printf 'ERROR: %s\n' "$2" 1>&2
+	[ $1 -gt 0 ] && exit $1
+}
+
 if command -v curl 1> /dev/null 2>&1; then
 	DLCMD='curl -so'
 elif command -v wget 1> /dev/null 2>&1; then
 	DLCMD='wget -qO'
 else
-	printf "ERROR: Neither 'wget' nor 'curl' are available.\n" 1>&2
-	exit 1
+	Err 1 "Neither 'wget' nor 'curl' are available."
 fi
 
-if [ `id -u` -ne 0 ]; then
-	printf "ERROR: Root access is required for system-wide changes.\n" 1>&2
-	exit 1
-fi
+[ `id -u` -eq 0 ] || Err 1 'Root access is required for system-wide changes.'
 
 printf 'Install latest version of Cito? [Y/N] '
 read Answer
@@ -54,8 +55,7 @@ case $Answer in
 		printf 'Abandoning installation.\n'
 		exit 0 ;;
 	*)
-		printf 'ERROR: Invalid response -- quitting.\n' 1>&2
-		exit 2 ;;
+		Err 2 'Invalid response -- quitting.' ;;
 esac
 
 LogFile='/tmp/cito-installer.log'
@@ -112,10 +112,7 @@ for File in 'completions' 'cito' 'cito-list' 'cito.8.gz'; do
 	fi
 done
 
-if [ $ErrCount -gt 0 ]; then
-	printf 'ERROR: Failed to download one or more files.\n' 1>&2
-	exit 1
-fi
+[ $ErrCount -gt 0 ] && Err 1 'Failed to download one or more files.'
 
 printf 'Setting correct file attributes:\n'
 
@@ -171,3 +168,52 @@ if cito-list -v > /dev/null 2>&1; then
 else
 	printf '\033[31m[ERR]\033[0m\n'
 fi
+
+printf 'Checking for dependencies:\n'
+
+for File in '/usr/bin/cito' '/usr/bin/cito-list'; do
+	printf "* Looking in '%s' file...\n" "$File"
+
+	FileErr=0
+	if ! [ -f "$File" ]; then
+		Err 0 "File '$File' missing."
+		FileErr=$((FileErr + 1))
+	elif ! [ -r "$File" ]; then
+		Err 0 "File '$File' unreadable."
+		FileErr=$((FileErr + 1))
+	fi
+
+	if [ $FileErr -ne 0 ]; then
+		Err 0 'Unable to determine dependencies.'
+		continue
+	fi
+
+	DepErr=0
+	Found='False'
+	while read Line; do
+		if [ "$Line" = '#' ]; then
+			continue
+		elif [ "$Line" = '# Dependencies:' ]; then
+			Found='True'
+		elif [ "$Found" = 'True' ]; then
+			# Line to help debug parsing on stubborn files.
+			#printf '\e[2;37m%s\e[0m\n' "$Line"
+
+			case $Line in
+				'#'------*)
+					break ;;
+				*)
+					case $Line in
+						'#   '[!\ ]*)
+							printf '\033[1;91m%s\e[0m\n' "${Line#\#   }" ;;
+						*|'')
+							DepErr=$((DepErr + 1)) ;;
+					esac ;;
+			esac
+		fi
+	done < "$File"
+
+	[ $DepErr -eq 0 ] || Err 0 'One or more invalid dependencies detected.'
+done
+
+printf 'Done!\n'
