Update Cito man page & add more OPTs to Cito

diff --git a/source/cito/cito b/source/cito/cito
--- a/source/cito/cito
+++ b/source/cito/cito
@@ -3,7 +3,7 @@
 #------------------------------------------------------------------------------
 # Project Name      - Extra/source/cito/cito
 # Started On        - Thu  5 Dec 20:40:35 GMT 2019
-# Last Change       - Wed 13 Jan 16:37:59 GMT 2021
+# Last Change       - Wed 13 Jan 18:24:12 GMT 2021
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
@@ -41,7 +41,9 @@ Usage(){
 		\r  -L, --log-view <TYPE>    - Show TYPE log entries for Cito.
 		\r  -M, --mode <MODE>        - Where MODE is, IE: '755'.
 		\r  -O, --owner <UID>        - Where OWNER is, IE: '0'.
+		\r  -R, --remove-log         - Delete existing Cito log file.
 		\r  -T, --target <PATH>      - Where PATH is, IE: '/usr/bin/1337'.
+		\r  -f, --list-files         - List logged files handled by Cito.
 		\r  -l, --nolog              - Disable the logging functionality.
 		\r  -r, --remote <INFO>      - Specify a remote file; see REMOTE.
 	EOF
@@ -143,6 +145,10 @@ while [ -n "$1" ]; do
 			NullArg "$UserTarget" "$1"
 
 			shift ;;
+		--list-files|-f)
+			ListFiles='True' ;;
+		--remove-log|-R)
+			RemoveLog='True' ;;
 		-*)
 			Err 1 'Incorrect argument(s) specified.' ;;
 		*)
@@ -166,6 +172,30 @@ for Dep in mv id chmod chown md5sum mkdir date rm mktemp; do
 done
 
 [ $DepCount -gt 0 ] && exit 1
+
+if [ "$RemoveLog" = 'True' ]; then
+	if ! [ -f "$EventLog" ]; then
+		Err 1 "Log file not found."
+	elif ! [ -w "$EventLog" ]; then
+		Err 1 "Log file unwritable -- do we have root access?"
+	else
+		if rm "$EventLog"; then
+			printf 'Log file deleted -- nothing else to do.\n'
+			exit 0
+		else
+			Err 1 "Failed to delete '$EventLog' file."
+		fi
+	fi
+fi
+
+if [ "$ListFiles" = 'True' ]; then
+	if command -v cito-list 1> /dev/null 2>&1; then
+		cito-list -C
+		exit 0
+	else
+		Err 1 "Dependency 'cito-list' not met."
+	fi
+fi
 
 if command -v curl 1> /dev/null 2>&1; then
 	DLCMD='curl -so'
