Fix overwrite bug in Cito

diff --git a/source/cito/cito b/source/cito/cito
--- a/source/cito/cito
+++ b/source/cito/cito
@@ -3,7 +3,7 @@
 #------------------------------------------------------------------------------
 # Project Name      - Extra/source/cito/cito
 # Started On        - Thu  5 Dec 20:40:35 GMT 2019
-# Last Change       - Sat  7 Mar 16:02:55 GMT 2020
+# Last Change       - Sat 14 Mar 00:34:02 GMT 2020
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
@@ -15,8 +15,8 @@
 #
 # Bugs:
 #
-#TODO: Asked to overwrite files even when they don't actually exist. Annoying!
-#TODO: Non-existant remote files still trying to act as though they exist.
+#TODO: Multiple files failing to install properly, if at all.
+#TODO: Non-existant remote files don't work. (last does; all prior fail)
 #
 # Dependencies:
 #
@@ -32,7 +32,7 @@ set -e
 . /usr/lib/tflbp-sh/YNInput
 set +e
 
-CurVer='2020-03-07'
+CurVer='2020-03-14'
 Progrm=${0##*/}
 
 Usage(){
@@ -419,14 +419,20 @@ DoChmod(){ # Usage: DoChmod [MODE] [TARGET]
 AskOverwrite(){
 	Logger warning "File '$1' in '${1%/*}' already exists"
 
-	[ "$Clobber" = 'true' ] || printf "File '%s' found.\n" "$1" 1>&2
-	if [ "$Clobber" = 'true' ] || YNInput 'Overwrite the file?'; then
+	if [ "$Clobber" = 'true' ]; then
+		printf "File '%s' found -- overwriting.\n" "$1" 1>&2
+		YNInput(){ :; } # <-- Override with dumb function.
+	else
+		printf "File '%s' found.\n" "$1" 1>&2
+	fi
+
+	if YNInput 'Overwrite the file?'; then
 		Logger info "Overwriting pre-existing file '$1'"
 
 		if rm -f "$1" 1> /dev/null 2>&1; then
-			Logger info "Overwrote pre-existing file '$1'"
+			Logger info "Removed pre-existing file '$1'"
 		else
-			Logger error "Failed to overwrite pre-existing file '$1'"
+			Logger error "Failed to remove pre-existing file '$1'"
 			Err 1 "Unable to overwrite '$1' file."
 		fi
 	else
@@ -459,7 +465,7 @@ MainRemote(){
 	if $DLCMD "$TemRemFile" "$URL" 1> /dev/null 2>&1; then
 		if ChkMD5 "$1"; then
 			ReadFile "$TemRemFile" || exit 0
-			AskOverwrite "$Target"
+			[ -f "$Target" ] && AskOverwrite "$Target"
 
 			if [ "$HasCito" = 'true' -o "$Regardless" = 'true' ]; then
 				DoRegardless
@@ -508,7 +514,7 @@ else
 
 		if ChkMD5 "$CurFile"; then
 			ReadFile "$CurFile" || continue
-			AskOverwrite "$Target"
+			[ -f "$Target" ] && AskOverwrite "$Target"
 
 			if [ "$HasCito" = 'true' -o "$Regardless" = 'true' ]; then
 				DoRegardless
