Remove libtflbp-sh from lspkg{,-set}

diff --git a/source/lspkg/lspkg-set b/source/lspkg/lspkg-set
--- a/source/lspkg/lspkg-set
+++ b/source/lspkg/lspkg-set
@@ -1,19 +1,15 @@
 #!/bin/sh
 #cito M:755 O:0 G:0 T:/usr/bin/lspkg-set
-#----------------------------------------------------------------------------------
+#------------------------------------------------------------------------------
 # Project Name      - Extra/source/lspkg/lspkg-set
 # Started On        - Wed 24 Jan 17:31:41 GMT 2018
-# Last Change       - Wed 12 Feb 00:16:54 GMT 2020
+# Last Change       - Thu 12 Nov 04:00:38 GMT 2020
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
-#----------------------------------------------------------------------------------
+#------------------------------------------------------------------------------
 
-set -e
-. /usr/lib/tflbp-sh/Err
-. /usr/lib/tflbp-sh/ChkDep
-set +e
 
-CurVer='2020-02-12'
+CurVer='2020-11-12'
 Progrm=${0##*/}
 
 Usage(){
@@ -30,6 +26,11 @@ Usage(){
 		\r  -o, --optional           - Display the optional packages.
 		\r  -R, --required           - Display the required packages.
 	EOF
+}
+
+Err(){
+	printf 'ERROR: %s\n' "$2" 1>&2
+	[ $1 -gt 0 ] && exit $1
 }
 
 [ $# -eq 0 ] && Err 1 "One argument is required -- see: $Progrm -h"
@@ -53,7 +54,8 @@ case $* in
 		Err 1 'Incorrect argument(s) specified.' ;;
 esac
 
-ChkDep dpkg-query
+type -fP dpkg-query 1> /dev/null 2>&1 ||
+	Err 1 "Dependency 'dpkg-query' not met."
 
 Format="\${db:Status-Abbrev} \${${Type%:*}} \${Package}\n"
 
