Clean GLKFU output a bit & improve '.config' part
Overview of changes:

  * Updated TODOs in the header.
  * Files are now cleaned up silently, without asking the user.
  * Cleaned up the clunky configuration file section.
    - No longer asks the user for an alternative file; use the flag.
    - Automatically uses configuration file for currently-used kernel.
  * Properly exits GLKFU if you say no to continue after bad '.config'.
  * Improved wording of compilation and package building `Ask()` call.
  * Updated the man page's HISTORY section.

If you have any concerns about these changes, please do get in touch.

diff --git a/source/glkfu/glkfu b/source/glkfu/glkfu
--- a/source/glkfu/glkfu
+++ b/source/glkfu/glkfu
@@ -3,7 +3,7 @@
 #------------------------------------------------------------------------------
 # Project Name      - Extra/source/glkfu
 # Started On        - Sun  6 Dec 19:41:35 GMT 2020
-# Last Change       - Fri 27 Aug 17:37:42 BST 2021
+# Last Change       - Fri 27 Aug 18:06:23 BST 2021
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
@@ -18,18 +18,15 @@
 #
 # Features:
 #
-#TODO: Improve configuration file handling section.
+#TODO: Add cautionary message for the step which removes modules.
 #
-#      Perhaps by using the current kernel's configuration by default. The user
-#      could be asked if they're okay with using the current one, but provide a
-#      flag to adjust this, rather than a clunky `read` prompt which won't have
-#      tab completion or any evaluation of things like variables.
+#      It could cause problems for users not understanding what this means.
 #
-#      If the users says no when asked, maybe GLKFU could tell the user that
-#      such a flag exists, perhaps pointing the user to the usage output.
+#TODO: Ensure GLKFU supports EFI systems -- can anyone help with that?
 #
 # Bugs:
 #
+#TODO: Catch `Makefile:188`, for when build directory has spaces or colons.
 #TODO: Use of the -o flag(s) not working properly if unmet dependencies.
 #
 #      In this case, GLKFU is unable to determine whether the latest version is
@@ -565,9 +562,9 @@ if [ "$Verify" == 'True' ]; then
 		printf 'File verified successfully.\n'
 	fi
 
-	if Ask 'Delete the kernel signature file?'; then
-		rm -v "${BuildDir%/}/${LatestTar%.xz}.sign"
-	fi
+	#if Ask 'Delete the kernel signature file?'; then
+		rm "${BuildDir%/}/${LatestTar%.xz}.sign"
+	#fi
 fi
 
 #-----------------------------------------------Extract Contents of the Tarball
@@ -577,9 +574,9 @@ Ask 'Begin extracting tarball?' || exit 0
 printf 'Extracting tarball...\n'
 tar -C "$BuildDir" -xvf "$BuildDir/${LatestTar%.xz}"
 
-if Ask 'Delete the kernel tarball?'; then
-	rm -v "$BuildDir/${LatestTar%.xz}"
-fi
+#if Ask 'Delete the kernel tarball?'; then
+	rm "$BuildDir/${LatestTar%.xz}"
+#fi
 
 #----------------------------------------------Copy Over Existing Configuration
 
@@ -588,40 +585,17 @@ if [ -n "$ConfigOverrideFile" ]; then
 
 	cp -v "$ConfigOverrideFile" "$BuildDir/${LatestTar%.tar.xz}/.config"
 else
-	printf 'Finding a suitable kernel configuration file to use.\n'
+	printf 'Looking for suitable kernel configuration...\n'
 
-	printf 'Looking for kernel configurations...\n'
-	for File in /boot/config-*; {
-		Found+=("$File=${File//[![:digit:]]/}")
-	}
-
-	printf 'Found %d configuration file(s).\n' ${#Found[@]}
-
-	#TODO: Consider doing this without uname(1).
 	TargetConfig="/boot/config-$CurVer"
+	if [ -f "$TargetConfig" ]; then
+		printf "File found: '%s'\n" "$TargetConfig"
 
-	if ! Ask "Use the current kernel's configuration?"; then
-		printf 'Enter absolute path to target configuration file.\n'
-		while :; do
-			read -ep ': ' TargetConfig
-			case $TargetConfig in
-				'')
-					Err 0 'Enter a path, or Ctrl + C to quit.' ;;
-				*)
-					if ! [ -f "$TargetConfig" ]; then
-						Err 0 'File not found.'
-					elif [ -r "$TargetConfig" ]; then
-						Err 0 'File unreadable.'
-					else
-						break
-					fi ;;
-			esac
-		done
+		printf "Importing current kernel's configuration...\n"
+		cp -v "$TargetConfig" "$BuildDir/${LatestTar%.tar.xz}/.config"
+	else
+		Err 1 "Cannot find suitable configuration file -- see: $Progrm -h"
 	fi
-
-	printf "Using file: '%s'\n" "$TargetConfig"
-
-	cp -v "$TargetConfig" "$BuildDir/${LatestTar%.tar.xz}/.config"
 fi
 
 #--------------------------------------------------------Process Configurations
@@ -643,7 +617,7 @@ if Ask 'Use default values for new CONFIG parameters?'; then
 		Err 1 "Unexpected data found in '.config' file."
 	elif [ "$PossibleErrors" == 'True' ]; then
 		Err 0 "Possible errors found in '.config' file."
-		Ask "Continue with potentially problematic '.config' file?"
+		Ask "Continue with potentially problematic '.config' file?" || exit 0
 	fi
 else
 	$Make silentoldconfig
@@ -693,11 +667,12 @@ fi
 
 #---------------------------------------Begin Compiling and Building the Kernel
 
-Ask 'Begin compiling kernel, then building Debian packages for it?' || exit 0
+Ask 'Compile kernel and build Debian packages?' || exit 0
 
 while read; do
 	printf '%s\n' "$REPLY"
 done <<-EOF
+
 	NOTE: This operation may take some time, depending on your system
 	      performance and the options previously selected.
 
@@ -716,9 +691,9 @@ else
 	Err 0 "Non-zero exit status from make(1) after 'deb-pkg' operation."
 fi
 
-if Ask 'Remove Kernel source files?'; then
-	rm -rv "../${LatestTar%.tar.xz}"
-fi
+#if Ask 'Delete kernel source files?'; then
+	rm -r "../${LatestTar%.tar.xz}"
+#fi
 
 printf 'Synchronising cached writes...\n'
 sync
