Finish writing 'just download' functionality
This should now work properly, but it'll probably need some testing to
verify the logic hasn't broken something.

diff --git a/source/glkfu/glkfu b/source/glkfu/glkfu
--- a/source/glkfu/glkfu
+++ b/source/glkfu/glkfu
@@ -3,7 +3,7 @@
 #------------------------------------------------------------------------------
 # Project Name      - Extra/source/glkfu
 # Started On        - Sun  6 Dec 19:41:35 GMT 2020
-# Last Change       - Sun 19 Dec 03:54:43 GMT 2021
+# Last Change       - Sun 19 Dec 04:11:08 GMT 2021
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
@@ -23,7 +23,6 @@
 #
 # Bugs:
 #
-#TODO: The 'just download' flags aren't working; GLKFU just continues on.
 #TODO: Catch `Makefile:188`, for when build directory has spaces or colons.
 #TODO: Use of the -o flag(s) not working properly if unmet dependencies.
 #
@@ -387,7 +386,7 @@ fi
 
 #----------------------------------Look for Compilation & Building Dependencies
 
-if [ "$IgnoreDeps" != 'True' ]; then
+if [ "$JustDownload" != 'True' ] || [ "$IgnoreDeps" != 'True' ]; then
 	FileChk "$StatusFile"
 
 	II=' install ok installed'
@@ -471,42 +470,46 @@ fi
 
 #-----------------------------------------------Determining Number of CPU Cores
 
-if [ -f "$ProcInfoFile" -a -r "$ProcInfoFile" ]; then
-	while read -a Line; do
-		if [ "${Line[0]}${Line[1]}" == 'cpucores' ]; then
-			TTLCores=${Line[3]}
-			break
-		fi
-	done < "$ProcInfoFile"
-else
-	TTLCores=`nproc`
+if [ "$JustDownload" != 'True' ]; then
+	if [ -f "$ProcInfoFile" -a -r "$ProcInfoFile" ]; then
+		while read -a Line; do
+			if [ "${Line[0]}${Line[1]}" == 'cpucores' ]; then
+				TTLCores=${Line[3]}
+				break
+			fi
+		done < "$ProcInfoFile"
+	else
+		TTLCores=`nproc`
+	fi
+
+	Cores=$TTLCores
+
+	if ! [[ $TTLCores =~ ^[[:digit:]]+$ ]]; then
+		Err 0 'Unable to determine available number of CPU cores.'
+		Ask 'Continue with just the 1 core/thread?'
+
+		Cores=1
+	fi
+
+	printf 'Using %d/%d available CPU core(s).\n' $Cores $TTLCores
 fi
-
-Cores=$TTLCores
-
-if ! [[ $TTLCores =~ ^[[:digit:]]+$ ]]; then
-	Err 0 'Unable to determine available number of CPU cores.'
-	Ask 'Continue with just the 1 core/thread?'
-
-	Cores=1
-fi
-
-printf 'Using %d/%d available CPU core(s).\n' $Cores $TTLCores
 
 #---------------------------------Download Applicable Tarball & Verify the File
 
-while read; do
-	printf '%s\n' "$REPLY"
-done <<-EOF
+if [ "$JustDownload" != 'True' ]; then
+	while read; do
+		printf '%s\n' "$REPLY"
+	done <<-EOF
 
-	CAUTION: Compilation takes up several GBs of disk space. Depending on the
-	         options selected, you may use over 20GB. If you don't have enough
-	         disk space during compilation, it will fail and your time will be
-	         wasted.
+		CAUTION: Compilation takes up several GBs of disk space. Depending on the
+		         options selected, you may use over 20GB. If you don't have enough
+		         disk space during compilation, it will fail and your time will be
+		         wasted.
 
-EOF
+	EOF
+fi
 
-if [ "$BuildDir" == '.' ]; then
+if [ "$JustDownload" != 'True' ] && [ "$BuildDir" == '.' ]; then
 	Ask 'No build directory specified -- use CWD?' || exit 0
 fi
 
@@ -516,7 +519,7 @@ elif [ -f "$BuildDir/${LatestTar%.xz}" ]; then
 	ExistingTarball='Uncompressed'
 fi
 
-if [ -n "$ExistingTarball" ]; then
+if [ "$JustDownload" != 'True' ] && [ -n "$ExistingTarball" ]; then
 	Ask "Use existing tarball found in build directory?" && Reuse='True'
 fi
 
@@ -544,27 +547,31 @@ if [ "$Verify" == 'True' ]; then
 	Get "$BuildDir/${LatestTar%.xz}.sign" "$URL"
 fi
 
-if [ "$ExistingTarball" != 'Uncompressed' ]; then
-	printf 'Decompressing tarball...\n'
-	xz -d "$BuildDir/$LatestTar"
-	(( $? > 1 )) && Err 1 'Non-zero exit status from xz(1).'
-fi
-
-if [ "$Verify" == 'True' ]; then
-	printf 'Verifying kernel signature...\n'
-
-	gpg --verify "$BuildDir/${LatestTar%.xz}.sign"
-
-	if (( $? > 0 )); then
-		Err 1 'Non-zero exit status when verifying download.'
-	else
-		printf 'File verified successfully.\n'
+if [ "$JustDownload" != 'True' ]; then
+	if [ "$ExistingTarball" != 'Uncompressed' ]; then
+		printf 'Decompressing tarball...\n'
+		xz -d "$BuildDir/$LatestTar"
+		(( $? > 1 )) && Err 1 'Non-zero exit status from xz(1).'
 	fi
 
-	#if Ask 'Delete the kernel signature file?'; then
-		rm "${BuildDir%/}/${LatestTar%.xz}.sign"
-	#fi
+	if [ "$Verify" == 'True' ]; then
+		printf 'Verifying kernel signature...\n'
+
+		gpg --verify "$BuildDir/${LatestTar%.xz}.sign"
+
+		if (( $? > 0 )); then
+			Err 1 'Non-zero exit status when verifying download.'
+		else
+			printf 'File verified successfully.\n'
+		fi
+
+		#if Ask 'Delete the kernel signature file?'; then
+			rm "${BuildDir%/}/${LatestTar%.xz}.sign"
+		#fi
+	fi
 fi
+
+[ "$JustDownload" == 'True' ] && exit 0
 
 #-----------------------------------------------Extract Contents of the Tarball
 
