Rework verification procedure for GPG
Addresses issue #6.

* gpg(1) and xz(1) are now marked as dependencies, which is a shame,
  but well worth it. XZ is for decompression the tarball, which needs
  to be done separately for the verification part.

* Now using 'https://cdn.kernel.org' for downloading kernels and
  related data, instead of 'https://mirrors.edge.kernel.org'. Mainly
  because 5.11.6 didn't seem to exist through the old URL, and I assume
  the URL GLKFU is now using is the official one, so more reliable.

* Importing keys from 'torvalds@kernel.org' and 'gregkh@kernel.org'.

* We'll no longer be prompted about the build directory if we've
  already provided one via the related flag.

* Verification is now _optional_; you'll be prompted to do it.

* Reworded output regarding exit statuses, to make more sense.

diff --git a/source/glkfu/glkfu b/source/glkfu/glkfu
--- a/source/glkfu/glkfu
+++ b/source/glkfu/glkfu
@@ -3,7 +3,7 @@
 #------------------------------------------------------------------------------
 # Project Name      - Extra/source/glkfu
 # Started On        - Sun  6 Dec 19:41:35 GMT 2020
-# Last Change       - Thu  4 Mar 23:40:23 GMT 2021
+# Last Change       - Thu 11 Mar 18:48:55 GMT 2021
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
@@ -18,7 +18,20 @@
 #
 # Features:
 #
-# N/A
+#TODO: Move information about trusting keys to the man page.
+#
+#	As kernel.org instructs, You can mark keys as 'trusted' with:
+#
+#	  $ gpg --tofu-policy good [KEY]
+#
+#	Where KEY is the public RSA key you wish to trust. You can list keys
+#	stored on your keyring with:
+#
+#	  $ gpg --list-keys
+#
+#	Marking a key as trusted should only need to be done once.
+#
+#TODO: Prompt user if they'd like to use existing tarball.
 #
 # Bugs:
 #
@@ -37,14 +50,16 @@
 #   coreutils (>= 8.28-1ubuntu1)
 #   glkfu-changes (>= 2021-02-18)
 #   glkfu-list (>= 2020-12-24)
+#   gpg (>= 2.2.4-1)
 #   make (>= 4.1-9.1ubuntu1)
 #   tar (>= 1.29b-2)
 #   wget (>= 1.19.4-1) | curl (>= 7.58.0-2ubuntu3.10)
+#   xz-utils (>= 5.2.2-1.3)
 #------------------------------------------------------------------------------
 
-CurVer='2021-03-04'
-Progrm=${0##*/}
+CurVer='2021-03-11'
 
+Progrm=${0##*/}
 Usage(){
 	while read; do
 		printf '%s\n' "$REPLY"
@@ -78,7 +93,8 @@ VerFile='/proc/version'
 ProcInfoFile='/proc/cpuinfo'
 StatusFile='/var/lib/dpkg/status'
 KernOrg='https://www.kernel.org'
-KernOrgMirrs='https://mirrors.edge.kernel.org'
+GPGPubKeys=('torvalds@kernel.org' 'gregkh@kernel.org')
+KernOrgMirrs='https://cdn.kernel.org'
 BuildDir='.'
 
 ValidOutputs=(
@@ -189,7 +205,7 @@ elif [ "$IgnoreVers" == 'True' -a "$JustCheck" == 'True' ]; then
 fi
 
 DepCount=0
-for Dep in glkfu-{list,changes} sync make tar rm cp sha256sum; do
+for Dep in glkfu-{list,changes} sync make tar rm cp gpg; do
 	if ! type -P "$Dep" &> /dev/null; then
 		Err 0 "Dependency '$Dep' not met."
 		let DepCount++
@@ -495,8 +511,11 @@ done <<-EOF
 
 EOF
 
-Ask "Begin downloading '$LatestTar' tarball?" || exit 1
-Ask 'No build directory specified -- use CWD?' || exit 1
+if [ "$BuildDir" == '.' ]; then
+	Ask 'No build directory specified -- use CWD?' || exit 0
+fi
+
+Ask "Begin downloading '$LatestTar' tarball?" || exit 0
 
 printf 'Downloading tarball...\n'
 if [ -w "$BuildDir" ]; then
@@ -506,30 +525,48 @@ else
 	Err 1 'Build directory unwritable.'
 fi
 
-printf 'Downloading sha256sums...\n'
-URL="$KernOrgMirrs/pub/linux/kernel/v$LatestVerMaj.x/sha256sums.asc"
-Get "$BuildDir/sha256sums.asc" "$URL"
+Ask 'Verify the GPG signature of the tarball?' && Verify='True'
 
-printf 'Verifying...\n'
-sha256sum --status --ignore-missing -c "${BuildDir%/}"/sha256sums.asc
+if [ "$Verify" == 'True' ]; then
+	printf 'Importing GPG public keys...\n'
+	if ! gpg --locate-keys "${GPGPubKeys[@]}"; then
+		Err 1 'Failed to import public keys with gpg(1).'
+	fi
 
-if [ $? -gt 0 ]; then
-	Err 1 'Non-zero exit status when verifying download.'
-else
-	printf 'File verified successfully.\n'
+	printf 'Downloading GPG signature file...\n'
+	URL="$KernOrgMirrs/pub/linux/kernel/v$LatestVerMaj.x/${LatestTar%.xz}.sign"
+	Get "$BuildDir/${LatestTar%.xz}.sign" "$URL"
 fi
 
-rm -v "${BuildDir%/}"/sha256sums.asc
+printf 'Decompressing tarball...\n'
+xz -d "$BuildDir/$LatestTar"
+[ $? -gt 1 ] && Err 1 'Non-zero exit status from xz(1).'
+
+if [ "$Verify" == 'True' ]; then
+	printf 'Verifying kernel signature...\n'
+
+	gpg --verify "$BuildDir/${LatestTar%.xz}.sign"
+
+	if [ $? -gt 0 ]; then
+		Err 1 'Non-zero exit status when verifying download.'
+	else
+		printf 'File verified successfully.\n'
+	fi
+
+	if Ask 'Delete the kernel signature file?'; then
+		rm -v "${BuildDir%/}/${LatestTar%.xz}.sign"
+	fi
+fi
 
 #-----------------------------------------------Extract Contents of the Tarball
 
-Ask 'Begin extracting tarball?' || exit 1
+Ask 'Begin extracting tarball?' || exit 0
 
 printf 'Extracting tarball...\n'
-tar -C "$BuildDir" -xvf "$BuildDir/$LatestTar"
+tar -C "$BuildDir" -xvf "$BuildDir/${LatestTar%.xz}"
 
-if Ask 'Now that files are extracted, delete the tarball?'; then
-	rm -v "$BuildDir/$LatestTar"
+if Ask 'Delete the kernel tarball?'; then
+	rm -v "$BuildDir/${LatestTar%.xz}"
 fi
 
 #----------------------------------------------Copy Over Existing Configuration
@@ -628,7 +665,7 @@ fi
 
 #---------------------------------------Begin Compiling and Building the Kernel
 
-Ask 'Begin compiling kernel, then building Debian packages for it?' || exit 1
+Ask 'Begin compiling kernel, then building Debian packages for it?' || exit 0
 
 while read; do
 	printf '%s\n' "$REPLY"
@@ -648,7 +685,7 @@ DebPKGExit=$?
 if [ $DebPKGExit -eq 0 ]; then
 	printf 'Kernel compilation and package building finished.\n'
 else
-	Err 0 "Non-zero exit status detected by make(1) after 'deb-pkg' operation."
+	Err 0 "Non-zero exit status from make(1) after 'deb-pkg' operation."
 fi
 
 if Ask 'Remove Kernel source files?'; then
