Avoid wrapping if listing dependencies to install
Also tidied the code a little, by removing a nest caused by `case`.

I've avoided wrapping when listing packages, in-case the user has
issues copy-pasting and winds up doing something wrong by mistake. It's
unnecessary, especially given the target audience of this tool in the
first place, but I figured it was better safe than sorry.

I've added dim grey to the `$` or `#` when displaying a command the
user can run, to denote that it's different, so as to hopefully suggest
that you don't _actually_ run that part. Not everyone is familiar with
that syntax.

diff --git a/source/glkfu/glkfu b/source/glkfu/glkfu
--- a/source/glkfu/glkfu
+++ b/source/glkfu/glkfu
@@ -3,7 +3,7 @@
 #------------------------------------------------------------------------------
 # Project Name      - ShellProjects/source/glkfu/glkfu
 # Started On        - Sun  6 Dec 19:41:35 GMT 2020
-# Last Change       - Mon 26 Jun 22:36:06 BST 2023
+# Last Change       - Wed 28 Jun 01:11:11 BST 2023
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
@@ -45,7 +45,7 @@
 #   xz-utils (>= 5.2.2-1.3)
 #------------------------------------------------------------------------------
 
-CurVer='2023-06-26'
+CurVer='2023-06-28'
 Progrm='glkfu'
 
 Usage() {
@@ -100,6 +100,7 @@ ValidOutputs=(
     'latest.tarball'
 )
 
+C_Grey=$'\e[2;37m'
 C_Red=$'\e[91m'
 C_Green=$'\e[92m'
 C_Yellow=$'\e[93m'
@@ -222,6 +223,7 @@ while [[ -n $1 ]]; do
 		--changelog)
 			ChangeLog='True' ;;
 		--no-color|--no-colour)
+			C_Grey=
 			C_Red=
 			C_Green=
 			C_Yellow=
@@ -338,133 +340,129 @@ JustOutput() {
 
 #------------------------------------Determine the Latest Stable Kernel Version
 
-case $Output in
-	current|current.*)
-		;;
-	*)
-		# Parse page data to get tarball filename of the latest stable kernel.
-		if [[ -z $LatestTar ]]; then
-			[[ -z $Output ]] && printf '* Finding latest kernel ... '
+if [[ $Output != +(current|current.*) ]]; then
+	# Parse page data to get tarball filename of the latest stable kernel.
+	if [[ -z $LatestTar ]]; then
+		[[ -z $Output ]] && printf '* Finding latest kernel ... '
 
-			Data=$(Get - "$RSS_Feed" 2>&1)
-			Status=$?
+		Data=$(Get - "$RSS_Feed" 2>&1)
+		Status=$?
+
+		if [[ -z $Output ]]; then
+			if (( Status > 0 )); then
+				printf '[%s!%s]\n' "$C_Red" "$C_Reset"
+				printf '* Attemting alternative method ... '
+			else
+				printf '[%sOK%s]\n' "$C_Green" "$C_Reset"
+			fi
+		fi
+
+		# Parse RSS feed. Assumes most recent versions are close to top. This
+		# is much quicker than the old method (see below). This also assumes
+		# the version numbers are the usual maj.min.patch. This, and the chance
+		# of the page being inaccessble, is why the fallback is in place.
+		if (( Status == 0 )); then
+			Buffer=
+			TagStart=
+			ItemFound=
+			while read -N 1 Char; do
+				if [[ $TagStart == True ]]; then
+					if [[ $InsideTag == True ]]; then
+						Buffer+=$Char
+
+						if [[ $Char == '<' ]]; then
+							if [[ ${Buffer:0:6} == title\> ]]; then
+								Buffer=${Buffer#*>}
+								if [[ ${Buffer:0 - 7:-1} == stable ]]; then
+									LatestTar="linux-${Buffer%:*}.tar.xz"
+
+									break
+								fi
+							fi
+
+							TagStart=
+							Buffer=
+						fi
+					elif [[ $Char == '>' ]]; then
+						InsideTag='True'
+						Buffer=
+					fi
+				elif [[ $Char == '<' ]]; then
+					TagStart='True'
+				fi
+			done <<< "$Data"
+		fi
+
+		# As of 2023-06-14, this is the old method, kept as fallback.
+		Pattern='linux-+([[:digit:]]).+([[:digit:]]).+([[:digit:]]).tar.xz'
+		if [[ -z $LatestTar || $LatestTar != $Pattern ]]; then
+			while read; do
+				if [[ $REPLY == +([[:space:]])'<td id="latest_link">' ]]; then
+					FirstLineFound='True'
+				elif [[ $FirstLineFound == True ]]; then
+					IFS='/' read -a Buffer <<< "$REPLY"
+					LatestTar=${Buffer[7]%%\"*}
+					break
+				fi
+			done <<< "$(Get - "$KernOrg")"
 
 			if [[ -z $Output ]]; then
-				if (( Status > 0 )); then
+				if [[ -z $LatestTar ]]; then
 					printf '[%s!%s]\n' "$C_Red" "$C_Reset"
-					printf '* Attemting alternative method ... '
 				else
 					printf '[%sOK%s]\n' "$C_Green" "$C_Reset"
 				fi
 			fi
-
-			# Parse RSS feed. Assumes most recent versions are close to top.
-			# This is much quicker than the old method (see below). This also
-			# assumes the version numbers are the usual maj.min.patch. This, -
-			# and the chance of the page being inaccessble, is why the fallback
-			# is in place.
-			if (( Status == 0 )); then
-				Buffer=
-				TagStart=
-				ItemFound=
-				while read -N 1 Char; do
-					if [[ $TagStart == True ]]; then
-						if [[ $InsideTag == True ]]; then
-							Buffer+=$Char
-
-							if [[ $Char == '<' ]]; then
-								if [[ ${Buffer:0:6} == title\> ]]; then
-									Buffer=${Buffer#*>}
-									if [[ ${Buffer:0 - 7:-1} == stable ]]; then
-										LatestTar="linux-${Buffer%:*}.tar.xz"
-
-										break
-									fi
-								fi
-
-								TagStart=
-								Buffer=
-							fi
-						elif [[ $Char == '>' ]]; then
-							InsideTag='True'
-							Buffer=
-						fi
-					elif [[ $Char == '<' ]]; then
-						TagStart='True'
-					fi
-				done <<< "$Data"
-			fi
-
-			# As of 2023-06-14, this is the old method, kept as fallback.
-			Pattern='linux-+([[:digit:]]).+([[:digit:]]).+([[:digit:]]).tar.xz'
-			if [[ -z $LatestTar || $LatestTar != $Pattern ]]; then
-				while read; do
-					if [[ $REPLY == +([[:space:]])'<td id="latest_link">' ]]; then
-						FirstLineFound='True'
-					elif [[ $FirstLineFound == True ]]; then
-						IFS='/' read -a Buffer <<< "$REPLY"
-						LatestTar=${Buffer[7]%%\"*}
-						break
-					fi
-				done <<< "$(Get - "$KernOrg")"
-
-				if [[ -z $Output ]]; then
-					if [[ -z $LatestTar ]]; then
-						printf '[%s!%s]\n' "$C_Red" "$C_Reset"
-					else
-						printf '[%sOK%s]\n' "$C_Green" "$C_Reset"
-					fi
-				fi
-			fi
 		fi
+	fi
 
-		JustOutput 'latest.tarball' "$LatestTar"
+	JustOutput 'latest.tarball' "$LatestTar"
 
-		[[ -z $Output ]] && printf '* Verifying tarball filename ... '
+	[[ -z $Output ]] && printf '* Verifying tarball filename ... '
 
-		# Just in-case, check the resulting filename is valid.
-		EmptyFileName=
-		InvalidFileName=
-		if [[ -z $LatestTar ]]; then
-			# Indirectly addresses when there is no Internet connection
-			# available, to avoid an empty string being quoted in what would be
-			# the next condition's error.
-			#
-			# This is mainly here to compensate for BASH command substitutions
-			# being executed within a subshell, thus exiting out of GLKFU from
-			# Get() with a suitable error via Err() is not possible.
-			EmptyFileName='True'
-		elif ! [[ $LatestTar == linux-+([[:digit:]]).+([[:digit:].]).tar.xz ]]; then
-			InvalidFileName='True'
-		fi
+	# Just in-case, check the resulting filename is valid.
+	EmptyFileName=
+	InvalidFileName=
+	if [[ -z $LatestTar ]]; then
+		# Indirectly addresses when there is no Internet connection
+		# available, to avoid an empty string being quoted in what would be the
+		# next condition's error.
+		#
+		# This is mainly here to compensate for BASH command substitutions
+		# being executed within a subshell, thus exiting out of GLKFU from
+		# Get() with a suitable error via Err() is not possible.
+		EmptyFileName='True'
+	elif ! [[ $LatestTar == linux-+([[:digit:]]).+([[:digit:].]).tar.xz ]]; then
+		InvalidFileName='True'
+	fi
 
-		if [[ $EmptyFileName == True ]]; then
-			[[ -z $Output ]] && printf '[%s!%s]\n' "$C_Red" "$C_Reset"
+	if [[ $EmptyFileName == True ]]; then
+		[[ -z $Output ]] && printf '[%s!%s]\n' "$C_Red" "$C_Reset"
 
-			Err 1 'Tarball filename empty.'
-		elif [[ $InvalidFileName == True ]]; then
-			[[ -z $Output ]] && printf '[%s!%s]\n' "$C_Red" "$C_Reset"
+		Err 1 'Tarball filename empty.'
+	elif [[ $InvalidFileName == True ]]; then
+		[[ -z $Output ]] && printf '[%s!%s]\n' "$C_Red" "$C_Reset"
 
-			Err 1 "Tarball filename '$LatestTar' not valid."
-		else
-			[[ -z $Output ]] && printf '[%sOK%s]\n' "$C_Green" "$C_Reset"
-		fi
+		Err 1 "Tarball filename '$LatestTar' not valid."
+	else
+		[[ -z $Output ]] && printf '[%sOK%s]\n' "$C_Green" "$C_Reset"
+	fi
 
-		# From the tarball filename, store just the version string. Shouldn't
-		# be a need to check the value here, as checking is done above.
-		LatestVerBuffer=${LatestTar//[![:digit:].]/}
-		LatestVer=${LatestVerBuffer%..}
+	# From the tarball filename, store just the version string. Shouldn't be a
+	# need to check the value here, as checking is done above.
+	LatestVerBuffer=${LatestTar//[![:digit:].]/}
+	LatestVer=${LatestVerBuffer%..}
 
-		# Get the major number of the latest version.
-		LatestVerMaj=${LatestVer%%.*}
+	# Get the major number of the latest version.
+	LatestVerMaj=${LatestVer%%.*}
 
-		JustOutput 'latest' "$LatestVer"
+	JustOutput 'latest' "$LatestVer"
 
-		if [[ -z $Output && $JustDownload != True ]]; then
-			printf 'Latest Linux version: %s%s%s\n'\
-				"$C_Yellow" "$LatestVer" "$C_Reset"
-		fi ;;
-esac
+	if [[ -z $Output && $JustDownload != True ]]; then
+		printf 'Latest Linux version: %s%s%s\n'\
+			"$C_Yellow" "$LatestVer" "$C_Reset"
+	fi
+fi
 
 #-----------------------------------Viewing the Changelog (via `glkfu-changes`)
 
@@ -559,8 +557,8 @@ if [[ $JustCheck == True ]]; then
 	exit 2 # <-- No new version is available.
 fi
 
-if [[ $IgnoreVers != True ]] && [[ $NewVerAvail == False ]]; then
-	printf "Kernel appears up-to-date -- quitting.\n"
+if [[ $IgnoreVers != True && $NewVerAvail == False ]]; then
+	printf 'Kernel appears up-to-date -- quitting.\n'
 	exit 0
 fi
 
@@ -626,18 +624,19 @@ if [[ $JustDownload != True && $IgnoreDeps != True ]]; then
 	if (( Count != ${#ReqPKGs[@]} )); then
 		Err 0 'One or more dependencies not met.'
 
-		if [[ $HasSudo == True ]]; then
-			printf 'Refer to the following command:\n'
-			printf '\n$ sudo apt-get install '
-		else
-			printf '\n# apt-get install '
-		fi
+		# Line-by-line to avoid wrapping.
+		printf 'Refer to the following command(s):\n\n'
+		for Missing in "${MissingDeps[@]}"; {
+			if [[ $HasSudo == True ]]; then
+				Out="  $C_Grey\$$C_Reset sudo"
+			else
+				Out="  $C_Grey#$C_Reset"
+			fi
 
-		for PKG in "${MissingDeps[@]}"; {
-			printf '%s ' "$PKG"
+			printf '%s apt-get install %s\n' "$Out" "$Missing"
 		}
 
-		printf '\n\nNothing to do -- quitting.\n'
+		printf '\nNothing to do -- quitting.\n'
 		exit 1
 	fi
 
@@ -700,7 +699,8 @@ if [[ $JustDownload != True ]]; then
 		printf '[%sOK%s]\n' "$C_Green" "$C_Reset"
 	fi
 
-	printf 'Using %d/%d available CPU core(s).\n' $Cores $TTLCores
+	printf 'Using %s%d%s/%d available CPU core(s).\n'\
+		"$C_Yellow" $Cores "$C_Reset" $TTLCores
 fi
 
 #---------------------------------Download Applicable Tarball & Verify the File
