Finalize changes following new glkfu-changes
This commit includes an updated man(1) page and glkfu(1)'s new
`--changelog` option.

I've also slightly tweaked the formatting in the man(1) page.

All previous instances of strings 'WGet' and 'cURL' have more
accurately been replaced with 'wget(1)' and 'curl(1)', respectively.

The GLKFU installer has been updated, too.

diff --git a/source/glkfu/glkfu b/source/glkfu/glkfu
--- a/source/glkfu/glkfu
+++ b/source/glkfu/glkfu
@@ -3,7 +3,7 @@
 #------------------------------------------------------------------------------
 # Project Name      - Extra/source/glkfu
 # Started On        - Sun  6 Dec 19:41:35 GMT 2020
-# Last Change       - Sun 14 Feb 01:39:36 GMT 2021
+# Last Change       - Thu 18 Feb 16:47:56 GMT 2021
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
@@ -41,13 +41,14 @@
 #
 #   bash (>= 4.3-14)
 #   coreutils (>= 8.28-1ubuntu1)
+#   glkfu-changes (>= 2021-02-18)
 #   glkfu-list (>= 2020-12-24)
 #   make (>= 4.1-9.1ubuntu1)
 #   tar (>= 1.29b-2)
 #   wget (>= 1.19.4-1) | curl (>= 7.58.0-2ubuntu3.10)
 #------------------------------------------------------------------------------
 
-CurVer='2021-02-14'
+CurVer='2021-02-18'
 Progrm=${0##*/}
 
 Usage(){
@@ -58,6 +59,7 @@ Usage(){
 
 		  -h, --help               - Display this help information.
 		  -v, --version            - Output the version datestamp.
+		  --changelog              - View kernel's changelog using less(1).
 		  -C, --config [FILE]      - Use FILE instead of newest available.
 		  -D, --build-dir [PATH]   - Build in PATH instead of CWD.
 		  -I, --ignore-deps        - Ignore compile & build dependencies.
@@ -181,6 +183,8 @@ while [ "$1" ]; do
 			fi ;;
 		--list-kerns|-l)
 			ListKerns='True' ;;
+		--changelog)
+			ChangeLog='True' ;;
 		*)
 			Err 1 'Incorrect option(s) specified.' ;;
 	esac
@@ -194,7 +198,7 @@ elif [ "$IgnoreVers" == 'True' -a "$JustCheck" == 'True' ]; then
 fi
 
 DepCount=0
-for Dep in glkfu-list sync make tar rm cp sha256sum; do
+for Dep in glkfu-{list,changes} sync make tar rm cp sha256sum; do
 	if ! type -P "$Dep" &> /dev/null; then
 		Err 0 "Dependency '$Dep' not met."
 		let DepCount++
@@ -217,14 +221,14 @@ Get(){
 		[ "$1" == '-' ] || Progress='--progress-bar'
 
 		curl ${Progress:-\-s} -o "$1" "$2" ||
-			Err $? 'Downloading with cURL failed.'
+			Err $? 'Downloading with curl(1) failed.'
 	elif type -P wget &> /dev/null; then
 		[ "$1" == '-' ] || Progress='--show-progress'
 
 		wget $Progress -q -O "$1" "$2" ||
-			Err $? 'Downloading with WGet failed.'
+			Err $? 'Downloading with wget(1) failed.'
 	else
-		Err 1 "Neither 'WGet' nor 'cURL' were found."
+		Err 1 "Neither 'wget' nor 'curl' were found."
 	fi
 
 	unset DoStdIn Args
@@ -295,6 +299,13 @@ case $Output in
 
 		[ -z "$Output" ] && printf 'Latest Linux version: %s\n' "$LatestVer" ;;
 esac
+
+#-----------------------------------Viewing the Changelog (via `glkfu-changes`)
+
+if [ "$ChangeLog" == 'True' ]; then
+	glkfu-changes "$LatestVer"
+	exit $?
+fi
 
 #---------------------Determine if the Latest is Newer than the Current Version
 
diff --git a/source/glkfu/glkfu-changes b/source/glkfu/glkfu-changes
--- a/source/glkfu/glkfu-changes
+++ b/source/glkfu/glkfu-changes
@@ -3,7 +3,7 @@
 #------------------------------------------------------------------------------
 # Project Name      - Extra/source/glkfu/glkfu-changes
 # Started On        - Thu 18 Feb 15:32:07 GMT 2021
-# Last Change       - Thu 18 Feb 16:32:59 GMT 2021
+# Last Change       - Thu 18 Feb 16:47:30 GMT 2021
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
@@ -85,19 +85,6 @@ for Dep in less rm mktemp; {
 [ $DepCount -gt 0 ] && exit 1
 
 Get(){
-	if type -P curl &> /dev/null; then
-		[ "$1" == '-' ] || Progress='--progress-bar'
-
-		curl ${Progress:-\-s} -fo "$1" "$2" 2> /dev/null ||
-			Err $? 'Downloading with cURL failed.'
-	elif type -P wget &> /dev/null; then
-		[ "$1" == '-' ] || Progress='--show-progress'
-
-		wget $Progress -qO "$1" "$2" ||
-			Err $? 'Downloading with WGet failed.'
-	else
-		Err 1 "Neither 'WGet' nor 'cURL' were found."
-	fi
 
 	unset DoStdIn Args
 }
@@ -113,7 +100,18 @@ trap SigHandler HUP INT EXIT
 URL="$KernOrgMirrs/pub/linux/kernel/v${Version%%.*}.x/ChangeLog-$Version"
 OutFile=`mktemp`
 
-Get "$OutFile" "$URL"
+if type -P curl &> /dev/null; then
+	if ! curl -fso "$OutFile" "$URL" 2> /dev/null; then
+		Err $? 'Downloading with curl(1) failed.'
+	fi
+elif type -P wget &> /dev/null; then
+	if ! wget -qO "$OutFile" "$URL"; then
+		Err $? 'Downloading with wget(1) failed.'
+	fi
+else
+	Err 1 "Neither 'WGet' nor 'cURL' were found."
+fi
+
 while read; do
 	if [[ "${Data[1]}" == \<title\>404:\ * ]]; then
 		Err 1 "Changelog for Linux v$Version not found."
