Add include flags, convert to BASH, and improve
Overview of changes:

  * Converted to BASH, because BASH is Essential anyway. The old header
    mentioned that RMNE was faster because of using DASH, but that was
    likely only the case because it wasn't initially written optimally
    in BASH.

  * Sorted the resulting package list, including how it's given to APT.
    Added a sort(1) fallback as well, using an optimized Bubble Sort
    algorithm. This was done in-case the user gets aggressive, removing
    even the 'coreutils' package, which is feasible, given the nature
    of RMNE.

  * No longer using the 'available' file, as it wasn't needed; I'm not
    even sure why I included it in the first place. The 'status' file
    should be sufficient. As a result of this, the flag related to the
    file is of course gone.

  * Because of using BASH and a sort(1) fallback, 'coreutils' is no
    longer a dependency, making RMNE much more portable, although APT
    is still unfortunately needed.

    I did consider using just dpkg(1), but it doesn't automatically
    handle dependencies, so it wouldn't be a practical choice, unless
    I write a lot of code to determine the dependencies and the right
    order in which to uninstall the packages -- no, thank you!

  * Improved the WARNING message, making it less obnoxious.
    - The part about the 'available' file was removed.
    - Added mention of package Priority and what is ignored.

  * The prompt is now looped, instead of just bailing after an invalid
    or empty response. I've also simplified the pattern matching.

  * I'm not convinced the package list was even correct before, because
    it seems like I didn't properly handle the Essential packages as an
    exception, due to the variable staying 'yes' when found. This
    caused a lot of confusion while writing this commit, but has now
    been handled by simply clearing the variable after handling each
    package.

  * The Architecture is now included and its use is required when
    making exceptions. This is to ensure the _right_ packages are being
    removed, and that the user can be more specific.

  * Removed the check for duplicate package names, as I figure that's
    not even likely to happen, due to the nature of the file; this is
    further the case now that the Architecture is used and matched.

  * No longer using apt-get(8)'s `--purge` flag with APT, but instead
    either `remove` or `purge`, making things a bit simpler.

diff --git a/source/rmne/rmne b/source/rmne/rmne
--- a/source/rmne/rmne
+++ b/source/rmne/rmne
@@ -1,68 +1,93 @@
-#!/bin/sh
+#!/usr/bin/env bash
 #cito M:755 O:0 G:0 T:/usr/bin/rmne
 #------------------------------------------------------------------------------
 # Project Name      - Extra/source/rmne/rmne
 # Started On        - Fri  6 Apr 21:27:34 BST 2018
-# Last Change       - Thu 16 Dec 16:10:43 GMT 2021
+# Last Change       - Sat 26 Mar 19:38:35 GMT 2022
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
-# This program was written (as of 2019-12-03) with Bourne POSIX-compliance in
-# mind. Why? For portability and speed -- rmne is at least 3x faster now!
+# Features:
+#
+#TODO: Allow comma-separated list of priorities for `-i`/`--include` flags.
+#
+# Bugs:
+#
+# N/A
 #
 # Dependencies:
 #
 #   apt (>= 1.2.32)
-#   coreutils (>= 8.25-2)
+#   bash (>= 3.1)
 #------------------------------------------------------------------------------
 
-CurVer='2021-12-16'
-Progrm=${0##*/}
 
-Usage(){
-	while read -r CurLine; do
-		printf '%b\n' "$CurLine"
-	done <<-EOF
-		\rUsage: $Progrm [OPTS] [PKG_1 [PKG_2] ...]
 
-		\r  -h, --help               - Display this help information.
-		\r  -v, --version            - Output the version datestamp.
-		\r  --afile PATH             - Override 'available' file.
-		\r  --no-purge               - Don't purge remaining files.
-		\r  --sfile PATH             - Override 'status' file.
-		\r  -l, --list               - List would-be-removed packages.
+CurVer='2022-03-26'
+Progrm='rmne'
 
-		\rWhere 'PKG' is one or more packages to hold back.
+Usage() {
+	read -d '' <<-EOF
+		Usage: $Progrm [OPTS] [PATTERN [PATTERN] ...]
+
+		  -h, --help               - Display this help information.
+		  -v, --version            - Output the version datestamp.
+		  --no-purge               - Don't purge remaining files.
+		  --sfile PATH             - Override 'status' file.
+		  -i, --include STR        - Destroy STR priority packages, too.
+		  -l, --list               - List would-be-removed packages.
+
+		Where PATTERN is a glob pattern for one or more packages to keep. In
+		order to specify such packages, the Architecture must be included or
+		be taken into account within the pattern.
 	EOF
+
+	printf '%s' "$REPLY"
 }
 
-Err(){
+Err() {
 	printf 'Err: %s\n' "$2" 1>&2
-	[ $1 -gt 0 ] && exit $1
+	(( $1 > 0 )) && exit $1
 }
 
 StatusFile='/var/lib/dpkg/status'
-AvailFile='/var/lib/dpkg/available'
+KeepPriors=(important standard required)
 
-Purge='--purge'
+type -P apt-get &> /dev/null && Destroy='True'
 
-command -V apt-get 1> /dev/null 2>&1 && DoAptGet='true'
-
-while [ -n "$1" ]; do
+while [[ -n $1 ]]; do
 	case $1 in
 		--help|-h)
 			Usage; exit 0 ;;
 		--version|-v)
-			printf "%s\n" "$CurVer"
-			exit 0 ;;
+			printf '%s\n' "$CurVer"; exit 0 ;;
 		--no-purge)
-			unset Purge ;;
+			Purge='remove' ;;
 		--list|-l)
-			unset DoAptGet ;;
+			Destroy='False' ;;
 		--sfile)
-			shift; StatusFile=$1 ;;
-		--afile)
-			shift; AvailFile=$1 ;;
+			if [[ -z $2 ]]; then
+				Err 1 "Option '$1' requires an argument."
+			else
+				StatusFile=$2
+				shift
+			fi ;;
+		--include|-i)
+			if [[ -z $2 ]]; then
+				Err 1 "Option '$1' requires an argument."
+			else
+				shift
+				case $1 in
+					important)
+						KeepPriors[0]= ;;
+					standard)
+						KeepPriors[1]= ;;
+					required)
+						KeepPriors[2]= ;;
+					*)
+						Err 1 "Priority '$1' invalid." ;;
+				esac
+			fi ;;
 		-*)
 			Err 1 "Incorrect argument(s) specified." ;;
 		*)
@@ -71,125 +96,115 @@ while [ -n "$1" ]; do
 	shift
 done
 
-if ! [ -f "$StatusFile" -a -r "$StatusFile" ]; then
+if ! [[ -f $StatusFile && -r $StatusFile ]]; then
 	Err 1 "File '$StatusFile' missing or inaccessible."
-elif ! [ -f "$AvailFile" -a -r "$AvailFile" ]; then
-	Err 1 "File '$AvailFile' missing or inaccessible."
-elif [ ${UID:-`id -u`} -ne 0 -a "$DoAptGet" = 'true' ]; then
+elif (( UID != 0 )) && [[ $Destroy == True ]]; then
 	Err 1 "Root access required for system-wide changes."
 fi
 
-if [ "$DoAptGet" = 'true' ]; then
-	while read -r CurLine; do
-		printf '%b\n' "$CurLine"
-	done <<-EOF
-		\rWARNING +---------------------------------------------------+ WARNING
+if [[ $Destroy == True ]]; then
+	read -d '' <<-EOF
+		WARNING +---------------------------------------------------+ WARNING
 
-		\rThis is a small but dangerous program for the sole purpose of tearing
-		\rdown the non-essential packages, for educational, fun, or other
-		\rpurposes, such as setting up a specific type of installation.
+		This is a small but dangerous program for the sole purpose of tearing
+		down the non-essential packages and their dependencies. Packages with a
+		Priority of 'standard', 'important', or 'required' are ignored, unless
+		otherwise specified.
 
-		\rThis program is ONLY for Debian and Ubuntu, or distributions based
-		\rthereon. You'll pretty much be left with just the Debian
-		\ressentials, unless your distribution has set some odd packages as
-		\ressential, such as in Linux Lite and Linux Mint.
+		RMNE is strictly for Debian- and Ubuntu-based distributions of Linux.
 
-		\rNOTE: You may now wish to download some DEB packages in preperation
-		\r      for setting up the system how you want, in-case you're left
-		\r      without an Internet connection.
+		NOTE: You may now wish to prepare for setting up the system how you
+		      want, as you will very likely be left without an Internet
+		      connection, kernel, bootloader, APT, sudo(8), etc.
 
-		\rThere is no 'undo' for this action, so it's worth making a backup
-		\rbeforehand.
-
-		\rSpecifically, packages to be removed must not:
-
-		\r  1. Have the priority of standard, important, or required.
-		\r  2. Be those which are specified as command arguments.
-		\r  3. Be part of the minimal task.
-
-		\rWARNING +---------------------------------------------------+ WARNING
-
+		WARNING +---------------------------------------------------+ WARNING
 	EOF
 
-	printf "[C]ontinue, despite the impending doom, or [q]uit? "
-	read Answer
-	printf "\n"
-
-	case $Answer in
-		[Cc]|[Cc][Oo][Nn][Tt][Ii][Nn][Uu][Ee])
-			;;
-		[Qq]|[Qq][Uu][Ii][Tt])
-			printf "No action taken -- quitting.\n"
-			exit 0 ;;
-		'')
-			printf "No response -- quitting.\n"
-			exit 1 ;;
-		*)
-			printf "Unrecognised response -- quitting.\n"
-			exit 1 ;;
-	esac
+	printf '%s\n' "$REPLY"
+	while :; do
+		read -p '[C]ontinue, despite the impending doom, or [q]uit? '
+		case ${REPLY,,} in
+			c|continue)
+				break ;;
+			q|quit)
+				exit 0 ;;
+			'')
+				Err 0 'Response required -- try again.' ;;
+			*)
+				Err 0 'Invalid response -- try again.' ;;
+		esac
+	done
 fi
-
-# Fetch a list of packages whose 'Task:' is marked as 'minimal'. (need these)
-# This is thankfully not all that slow, unless this file becomes gigantic.
-while read Key Value _; do
-	case $Key in
-		Package:)
-			Package=$Value ;;
-		Task:)
-			[ "$Value" = 'minimal' ] && continue ;;
-		''|*)
-			continue ;;
-	esac
-
-	if ! [ "$Package" = "$OldPackage" ]; then
-		Minimals=" $Minimals $Package "
-	fi
-
-	OldPackage=$Package
-done < "$AvailFile"
 
 # Gather a list of currently installed packages, check they're not set to be
 # kept, check their priority is applicable, check they're not marked as being
 # essential, and cross-check with prior loop's results to ensure non-minimals.
-while read Key Value _; do
+while IFS=':' read Key Value; do
+	Value=${Value# }
 	case $Key in
-		Package:)
-			for CurKeep in "$@"; do
-				[ "$Value" = "$CurKeep" ] && continue 2
-			done
-
+		Package)
+			Essential='False'
 			Package=$Value ;;
-		Essential:)
-			[ "$Value" = 'yes' ] && continue ;;
-		Status:)
-			[ "$Value $_" = 'install ok installed' ] || continue ;;
-		Priority:)
-			case $Value in
-				important|standard|required)
-					continue ;;
-				*)
-					Priority=$Value ;;
-			esac ;;
-		''|*)
-			continue ;;
+		Essential)
+			[[ $Value == yes ]] && Essential='True' ;;
+		Status)
+			Status=$Value ;;
+		Priority)
+			Priority=$Value ;;
+		Architecture)
+			if [[ $Status == install\ ok\ installed ]]; then
+				[[ $Essential == True ]] && continue
+
+				SkipPrior='False'
+				for KeepPrior in "${KeepPriors[@]}"; {
+					if [[ $KeepPrior == $Priority ]]; then
+						SkipPrior='True'
+						break
+					fi
+				}
+
+				# We want to keep packages with a given priority. However, the
+				# user can choose to include the destruction of packages of a
+				# priority of 'standard', 'important', or 'required'; that's
+				# why this and the above `for` loop is here.
+				[[ $SkipPrior == True ]] && continue
+
+				Package="$Package:$Value"
+
+				for KeepPKG in "$@"; {
+					[[ $Package == $KeepPKG ]] && continue 2
+				}
+
+				[[ $FoundKeep == True ]] || List+=("$Package")
+			fi ;;
 	esac
-
-	if ! [ "$Package" = "$OldPackage" ]; then
-		for CurPKG in $Minimals; do
-			[ "$CurPKG" = "$Package" ] && continue 2
-		done
-
-		List=" $List $Package "
-	fi
-
-	OldPackage=$Package
-	unset Package
 done < "$StatusFile"
 
-if [ "$DoAptGet" = 'true' ]; then
-	apt-get -q -o Dpkg::Progress-Fancy=true --show-progress\
-		remove $Purge --autoremove $List
+# Sort array. Using an optimized Bubble Sort algorithm as a fallback, in-case
+# in-case the user previously removed the Essential 'coreutils' package.
+if type -P sort &> /dev/null; then
+	List=(`printf '%s\n' "${List[@]}" | sort`)
 else
-	printf '%s\n' $List
+	Len=${#List[@]}
+	for (( Iter = 0; Iter < Len; Iter++ )); {
+		Switched='False'
+		for (( Index = 0; Index < Len - (1 + Iter); Index++ )); {
+			if [[ ${List[Index]} > ${List[Index + 1]} ]]; then
+				Temp=${List[Index]}
+				List[Index]=${List[Index + 1]}
+				List[Index + 1]=$Temp
+
+				Switched='True'
+			fi
+		}
+
+		[[ $Switched == False ]] && break
+	}
+fi
+
+if [[ $Destroy == True ]]; then
+	apt-get -q -o Dpkg::Progress-Fancy=true --show-progress\
+		${Purge:-purge} --autoremove "${List[@]}"
+else
+	printf '%s\n' "${List[@]}"
 fi
