Update `libtflbp-sh` functions
Bug Fixes:

  * Began catching lots of errors for function misuse.

  * Removed `Err()` use from `YNInput()`; now `printf` + `exit`.

  * Fixed function comments (`#: `) -- will eventually be parsed.

  * Fixed `GetStr` variable from spilling out.

  * Addressed `Err()` being used out of range. (0-255)

Additions:

  * New errors, with format `NAME() ARG: MSG` or `NAME(): MSG`.

  * Added `--long` and `--short` options for `LibTFLBPVer()`.

  * New syntax for `Err()`; now supports `return` via new syntax.

Code:

  * Addressed some unnecessary quotes.

diff --git a/source/libtflbp-sh/Err b/source/libtflbp-sh/Err
--- a/source/libtflbp-sh/Err
+++ b/source/libtflbp-sh/Err
@@ -3,7 +3,7 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/libtflbp-sh/* (Terminal for Life Bourne POSIX)
 # Started On        - Mon  2 Dec 15:32:30 GMT 2019
-# Last Change       - Thu  5 Dec 22:16:33 GMT 2019
+# Last Change       - Fri 13 Dec 20:43:24 GMT 2019
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
@@ -12,7 +12,29 @@
 # NOTE: POSIX compliance has largely been determined through the guidance of YASH.
 #----------------------------------------------------------------------------------
 
-Err(){ #: Exit status $1 (0 by default) with error message $2.
+Err(){ #: Exit/return status [E|R]$1 (0 by default) with message $2.
+	if [ -z "$1" ]; then
+		printf 'Err() \$1: Exit status integer missing.\n' 1>&2
+		exit 126
+	elif [ -z "$2" ]; then
+		printf 'Err() \$2: Message string required.\n' 1>&2
+		exit 126
+	elif [ $1 -lt 0 -o $1 -gt 255 ]; then
+		printf 'Err() \$1: Exit status out of range.\n' 1>&2
+		exit 126
+	fi
+
 	printf "ERROR: %s\n" "$2" 1>&2
-	[ $1 -gt 0 ] && exit $1
+
+	case $1 in
+		E*)
+			exit ${1#E} ;;
+		R*)
+			return ${1#R} ;;
+		[0-9]*)
+			exit $1 ;; # <-- For compatibility, as of 2019-12-13.
+		*)
+			printf 'Err() \$1: Invalid exit status.\n' 1>&2
+			exit 126 ;;
+	esac
 }
diff --git a/source/libtflbp-sh/FirstLook b/source/libtflbp-sh/FirstLook
--- a/source/libtflbp-sh/FirstLook
+++ b/source/libtflbp-sh/FirstLook
@@ -3,7 +3,7 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/libtflbp-sh/* (Terminal for Life Bourne POSIX)
 # Started On        - Tue 10 Dec 02:56:10 GMT 2019
-# Last Change       - Tue 10 Dec 03:01:11 GMT 2019
+# Last Change       - Fri 13 Dec 20:22:26 GMT 2019
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
@@ -12,8 +12,12 @@
 # NOTE: POSIX compliance has largely been determined through the guidance of YASH.
 #----------------------------------------------------------------------------------
 
-FirstLook(){ # Usage: FirstLook [GLOB] [FILE]
-	[ $# -lt 2 ] && return 4
+FirstLook(){ #: Check line one of file $2 for glob $1.
+	if [ $# -lt 2 ]; then
+		printf "FirstLook() \$1: Glob pattern missing.\n" 1>&2
+		printf "FirstLook() \$2: No file specified.\n" 1>&2
+		exit 126
+	fi
 
 	if [ -f "$2" ] && [ -r "$2" ]; then
 		read Line < "$2"
@@ -24,7 +28,7 @@ FirstLook(){ # Usage: FirstLook [GLOB] [FILE]
 		unset Line
 		return 1
 	else
-		printf "ERROR: File '%s' missing or unreadable.\n" "$2" 1>&2
-		return 2
+		printf "FirstLook() \$2: File missing or unreadable.\n" 1>&2
+		exit 126
 	fi
 }
diff --git a/source/libtflbp-sh/LibFChk b/source/libtflbp-sh/LibFChk
--- a/source/libtflbp-sh/LibFChk
+++ b/source/libtflbp-sh/LibFChk
@@ -3,7 +3,7 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/libtflbp-sh/* (Terminal for Life Bourne POSIX)
 # Started On        - Mon  2 Dec 15:32:30 GMT 2019
-# Last Change       - Thu  5 Dec 22:16:33 GMT 2019
+# Last Change       - Fri 13 Dec 19:39:45 GMT 2019
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
@@ -18,11 +18,15 @@ LibFChk(){ #: Check for function(s) $@ existing, after sourcing library.
 		GetStr=`command -v "$CurFunc"`
 		if ! [ "$GetStr" = "$CurFunc" ]; then
 			printf "ERROR: Unavailable '$CurFunc()' in library." 1>&2
+
+			printf "LibFChk() \$@: Function '$CurFunc()' missing.\n" 1>&2
+			exit 126
+
 			FuncNum=$((FuncNum + 1))
 		fi
 	done
 
 	[ $FuncNum -gt 0 ] && exit 2
 
-	unset FuncNum CurFunc
+	unset FuncNum CurFunc GetStr
 }
diff --git a/source/libtflbp-sh/LibTFLBPVer b/source/libtflbp-sh/LibTFLBPVer
--- a/source/libtflbp-sh/LibTFLBPVer
+++ b/source/libtflbp-sh/LibTFLBPVer
@@ -3,7 +3,7 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/libtflbp-sh/* (Terminal for Life Bourne POSIX)
 # Started On        - Mon  2 Dec 15:32:30 GMT 2019
-# Last Change       - Thu  5 Dec 22:16:33 GMT 2019
+# Last Change       - Fri 13 Dec 19:03:32 GMT 2019
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
@@ -12,11 +12,18 @@
 # NOTE: POSIX compliance has largely been determined through the guidance of YASH.
 #----------------------------------------------------------------------------------
 
-LibTFLBPVer(){ #: Output the 'libtflbp-sh' version string.
+LibTFLBPVer(){ #: Output the 'libtflbp-sh' version, in `--long` or `--short` ($1).
 	CurVer='2019-12-05'
 	Progrm=${0##*/}
 
-	printf "POSIX Bourne library '%s' is version '%s'.\n" "$CurVer" "$Progrm"
+	if [ $1 = '--long' ]; then
+		printf "POSIX Bourne library '%s' is version '%s'.\n" "$CurVer" "$Progrm"
+	elif [ $1 = '--short' ]; then
+		printf '%s\n' "$CurVer"
+	else
+		printf 'LibTFLBPVer(): Invalid argument(s) detected.\n' 1>&2
+		exit 126
+	fi
 
 	unset CurVer Progrm
 }
diff --git a/source/libtflbp-sh/OneSearch b/source/libtflbp-sh/OneSearch
--- a/source/libtflbp-sh/OneSearch
+++ b/source/libtflbp-sh/OneSearch
@@ -3,7 +3,7 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/libtflbp-sh/* (Terminal for Life Bourne POSIX)
 # Started On        - Tue 10 Dec 02:09:33 GMT 2019
-# Last Change       - Tue 10 Dec 02:52:41 GMT 2019
+# Last Change       - Fri 13 Dec 19:02:24 GMT 2019
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
@@ -12,8 +12,14 @@
 # NOTE: POSIX compliance has largely been determined through the guidance of YASH.
 #----------------------------------------------------------------------------------
 
-OneSearch(){ # Usage: OneSearch [GLOB] [FILE_1 [FILE_2] ...]
+OneSearch(){ #: Search for glob $1 in one or more ($2 ...) files.
 	Glob=$1
+
+	if [ -z "$1" ]; then
+		printf 'OneSearch() $1: String required for glob matching.\n' 1>&2
+		exit 126
+	fi
+
 	shift 1
 
 	[ $# -eq 0 ] && return 4
@@ -29,9 +35,8 @@ OneSearch(){ # Usage: OneSearch [GLOB] [FILE_1 [FILE_2] ...]
 			unset CurLine Glob CurFile
 			return 1
 		else
-			printf "ERROR: File '%s' missing or unreadable.\n" "$CurFile" 1>&2
-			unset Glob CurFile
-			return 2
+			printf "OneSearch(): File '%s' missing or unreadable.\n" "$CurFile" 1>&2
+			exit 126
 		fi
 	done
 }
diff --git a/source/libtflbp-sh/SplitStr b/source/libtflbp-sh/SplitStr
--- a/source/libtflbp-sh/SplitStr
+++ b/source/libtflbp-sh/SplitStr
@@ -3,7 +3,7 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/libtflbp-sh/* (Terminal for Life Bourne POSIX)
 # Started On        - Mon  2 Dec 15:32:30 GMT 2019
-# Last Change       - Thu  5 Dec 22:16:33 GMT 2019
+# Last Change       - Fri 13 Dec 18:57:56 GMT 2019
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
@@ -13,9 +13,18 @@
 #----------------------------------------------------------------------------------
 
 SplitStr(){ #: Split string $2 by delimiter $1.
-	local IFS=$1
-	set -- $2
-	printf "%s\n" "$@"
+	IFS=$1
+
+	if [ ${#IFS} -gt 1 ]; then
+		printf "SplitStr() \$1: Too many characters for delimiter.\n" 1>&2
+		exit 126
+	elif [ -z "$2" ]; then
+		printf "SplitStr() \$2: A string to split is required.\n" 1>&2
+		exit 126
+	else
+		set -- $2
+		printf '%s\n' "$@"
+	fi
 
 	unset IFS
 }
diff --git a/source/libtflbp-sh/YNInput b/source/libtflbp-sh/YNInput
--- a/source/libtflbp-sh/YNInput
+++ b/source/libtflbp-sh/YNInput
@@ -3,7 +3,7 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/libtflbp-sh/* (Terminal for Life Bourne POSIX)
 # Started On        - Mon  2 Dec 15:32:30 GMT 2019
-# Last Change       - Fri  6 Dec 01:53:08 GMT 2019
+# Last Change       - Fri 13 Dec 20:47:12 GMT 2019
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
@@ -13,7 +13,12 @@
 #----------------------------------------------------------------------------------
 
 YNInput(){ #: An easy-to-script prompt for the user, asking yes or no.
-	printf "%s [Y/N] " "$1"
+	if [ -z "$1" ]; then
+		printf 'YNInput() $1: Prompt string required.\n' 1>&2
+		exit 126
+	fi
+
+	printf '%s [Y/N] ' "$1"
 	read Answer
 
 	case $Answer in
@@ -22,7 +27,8 @@ YNInput(){ #: An easy-to-script prompt for the user, asking yes or no.
 		[Nn]|[Nn][Oo])
 			return 1 ;;
 		*)
-			Err 1 'Invalid response -- quitting.' ;;
+			printf 'ERROR: Invalid response -- quitting.\n'
+			exit 1 ;;
 	esac
 
 	unset Answer
