Optimize, tweak, and improve

diff --git a/source/autoscrot b/source/autoscrot
--- a/source/autoscrot
+++ b/source/autoscrot
@@ -3,7 +3,7 @@
 #------------------------------------------------------------------------------
 # Project Name      - Extra/source/autoscrot
 # Started On        - Sun 17 Sep 05:06:50 BST 2017
-# Last Change       - Tue 23 Feb 17:45:13 GMT 2021
+# Last Change       - Thu 13 Jan 16:10:10 GMT 2022
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
@@ -11,15 +11,16 @@
 #
 # Dependencies:
 #
-#   bash (>= 4.3-14)
+#   bash (>= 4.2)
 #   coreutils (>= 8.25-2)
 #   scrot (>= 0.8-17)
 #------------------------------------------------------------------------------
 
-CurVer='2021-02-23'
+CurVer='2022-01-13'
 Progrm='autoscrot'
+ProgrmFancy='AutoScrot'
 
-Usage(){
+Usage() {
 	while read; do
 		printf '%s\n' "$REPLY"
 	done <<-EOF
@@ -28,12 +29,11 @@ Usage(){
 		  -h, --help               - Display this help information.
 		  -v, --version            - Output the version datestamp.
 		  -i, --interval [INT]     - Where INT is seconds of interval.
-		  -q, --quiet              - Quieter operation, with errors.
 
 		  If no interval is provided, a default of '3' will be used.
 
 		  The scrot arguments (via SCROT_ARGS) are optional. Due to the nature
-		  of $Progrm, some arguments will make no sense to pass over to scrot
+		  of $ProgrmFancy, some arguments will make no sense to pass over to scrot
 		  to process.
 
 		  Images are saved using the default quality for JPG images.
@@ -42,18 +42,27 @@ Usage(){
 	EOF
 }
 
-while [ "$1" ]; do
+Err() {
+	printf 'Err: %s\n' "$2" 1>&2
+	(( $1 > 0 )) && exit $1
+}
+
+MainDir="$HOME/Pictures/AutoScrot"
+
+while [[ -n $1 ]]; do
 	case $1 in
 		--help|-h|-\?)
 			Usage; exit 0 ;;
 		--version|-v)
 			printf '%s\n' "$CurVer"; exit 0 ;;
-		--quiet|-q)
-			BeQuiet='true' ;;
 		--interval|-I)
-			shift; Interval=$1
-			if ! [[ ${Interval} =~ ^[0-9]+$ ]] || [ $Interval -lt 1 ]; then
+			if [[ -z $1 ]]; then
+				Err 1 "Option '$ArgInterval' requires an argument."
+			elif ! [[ $2 =~ ^[0-9]+$ ]] || (( $2 < 1 )); then
 				Err 1 'Invalid interval selected.'
+			else
+				Interval=$2
+				shift
 			fi ;;
 		-*)
 			Err 1 'Incorrect argument specified.' ;;
@@ -64,32 +73,29 @@ while [ "$1" ]; do
 done
 
 DepCount=0
-for Dep in scrot mkdir sleep; {
+for Dep in scrot mkdir; {
 	if ! type -P "$Dep" &> /dev/null; then
 		Err 0 "Dependency '$Dep' not met."
-		let DepCount++
+		(( DepCount++ ))
 	fi
 }
 
-[ $DepCount -eq 0 ] || exit 1
+(( DepCount == 0 )) || exit 1
 
-[ "$BeQuiet" == 'true' ] && exec 1> /dev/null
+#------------------------------------------------------------------------------
 
-printf "Press Ctrl + C to cancel and exit $Progrm.\n"
+printf 'Press Ctrl + C to cancel and exit %s.\n' "$ProgrmFancy"
 
-declare -i Num=0
 while :; do
-	sleep ${Interval:-3}s
+	read -n 1 -st ${Interval:-3}
 
-	MainDir="$HOME/Pictures/AutoScrot"
-	[ -d "$MainDir" ] || mkdir -p "$MainDir"
-	printf -v FILENAME "%s/Screenshot_%(%F_%X)T.jpg" $MainDir -1
+	[[ -d $MainDir ]] || mkdir -p "$MainDir"
+	printf -v Filename "%s/Screenshot_%(%F_%X)T.jpg" $MainDir -1
 
-	if scrot "$@" "$FILENAME"; then
-		let Num++
-		printf "\rScreenshots taken:   %'d" "$Num"
+	if scrot "$@" "$Filename"; then
+		printf "\rScreenshots taken: %'d" $(( ++Num ))
 	else
-		Err 0 "Non-zero exit status for screenshot #${Num}."
+		Err 1 "Failed to take screenshot #$Num with scrot(1)."
 	fi
 done
 printf '\n'
