Overhaul and Bourne POSIX-ify `backmeup`
Bug Fixes:

  * Cleaned up a lot of the weirdness in output from the older version.

  * Probably caught some old errors, as I've added a lot more testing.

Additions:

  * At last, `backmeup` is Bourne POSIX-compliant. Very portable, now.

  * Now using `libtflbp-sh` for code condensing and easier reading.

  * Instead of `tar` _then_ `gzip`, they're now one in the same.

  * Plenty of trapping now occurs, ensuring a cleanup and safer run.

  * No more shall `tar` display the `--totals` to the user.

  * Stopped parsing files for configurations; now `exclude` & `store`.

  * Now `tar` will use the `posix` format, hence the `--posix` flag.

  * The old `--quiet|-q` flag is now effectively the default.

  * Added `--verbose|-V` for something like the old output.

  * Added `--exclude|-E` to override the default exclusions file.

  * Added `--command|-C` to execute a command(s) after main processing.

  * Now `gzip` is no longer a dependency, but I think `tar` uses it.

  * Added `--set-store|-S` to set and save the archive store path.

  * Updated the `Usage()` output, including a new short description.

Flipside:

  * Removed the update feature, at least for now. (because Bourne)

  * More dependencies, but nothing new that isn't part of Coreutils.

  * Removed the `--reset|-R` flag because it's no longer relevant.

  * Removed debugging `--debug|-D` due to not really needing it.

Code:

  * Reworked a lot of the logic in `backmeup`; it was pretty outdated.

  * Now `tar` no longer uses `eval`; what was I thinking?

  * More cleanly act (at the end) if it's a non-zero `tar` status.

  * Updated to the newer standards I follow.

Miscellaneous:

  * The `standard.sh` script is fixed up and Bourne POSIX, now.

  * Updated the `versions` and `md5sum` files.

diff --git a/source/backmeup b/source/backmeup
--- a/source/backmeup
+++ b/source/backmeup
@@ -1,203 +1,156 @@
-#!/bin/bash
+#!/bin/sh
 #cito M:755 O:0 G:0 T:/usr/bin/backmeup
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/source/backmeup
 # Started On        - Tue  7 Nov 21:50:05 GMT 2017
-# Last Change       - Fri  6 Dec 22:45:56 GMT 2019
+# Last Change       - Wed 11 Dec 02:00:59 GMT 2019
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
 
-_VERSION_="2019-12-06"
-_PROJECT_=${0##*/}
+set -e
+. /usr/lib/tflbp-sh/Err
+. /usr/lib/tflbp-sh/ChkDep
+. /usr/lib/tflbp-sh/YNInput
+set +e
 
-Err(){
-	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
-	[ $1 -eq 1 ] && exit 1
-}
+CurVer='2019-12-11'
+Progrm=${0##*/}
 
-DOM="https://github.com"
+MainDir="$HOME/.config/$Progrm"
+StoreFile="$MainDir/store"
+ExcluFile="$MainDir/exclude"
+Exclude="--exclude-from=$ExcluFile"
 
-USAGE(){
-	while read -r; do
-		printf "%s\n" "$REPLY"
+Usage(){
+	while read -r CurLine; do
+		printf '%b\n' "$CurLine"
 	done <<-EOF
-		            ${_PROJECT_^^} ($_VERSION_)
-		            Written by terminalforlife (terminalforlife@yahoo.com)
+		\r            BACKMEUP ($CurVer)
+		\r            Written by terminalforlife (terminalforlife@yahoo.com)
 
-		            A simple tool to quickly and easily back up your HOME.
+		\r            Simple Bourne POSIX tool to quickly and easily back up your HOME.
 
-		SYNTAX:     $_PROJECT_ [OPTS]
+		\rSYNTAX:     $Progrm [OPTS]
 
-		OPTS:       --help|-h|-?            - Displays this help information.
-		            --version|-v            - Output only the version datestamp.
-		            --quiet|-q              - Runs in quiet mode. Errors still output.
-		            --update|-U             - Check for updates to $_PROJECT_.
-		            --debug|-D              - Enables the built-in bash debugging.
-		            --reset|-R              - Re-run the initial setting prompts.
-		            --notify|-N             - Notify after completion, via notify-send.
+		\rOPTS:       --help|-h|-?            - Displays this help information.
+		\r            --version|-v            - Output only the version datestamp.
+		\r            --verbose|-V            - Be more verbose during archive creation.
+		\r            --set-store|-s PATH     - Set and save the archive store to PATH.
+		\r            --exclude|-E PATH       - Override default exclusions file with PATH.
+		\r            --command|-C CMD        - Run CMD when $Progrm has finished.
+		\r            --notify|-N             - Notify after completion, via notify-send.
 
-		EXAMPLE:    $_PROJECT_ --notify -Q
+		\rEXCLUDE:    To ignore files which would otherwise be added to the archive, you
+		\r            must create an 'exclude' file (see below) which will then be used.
 
-		FILE:       User settings saved in and read from: \$HOME/.$_PROJECT_/settings
+		\r            Importantly, strictly one path must exist per line.
 
-		NOTE:       When entering your settings, ensure that no variables are used.
-
-		SITE:       $DOM/terminalforlife/Extra
+		\rFILE:       ~/.config/$Progrm/store
+		\r            ~/.config/$Progrm/exclude
 	EOF
 }
 
 while [ "$1" ]; do
 	case $1 in
 		--help|-h|-\?)
-			USAGE; exit 0 ;;
+			Usage; exit 0 ;;
 		--version|-v)
-			printf "%s\n" "$_VERSION_"; exit 0 ;;
-		--quiet|-q)
-			BEQUIET='true' ;;
-		--update|-U)
-			UPDATE='true' ;;
-		--debug|-D)
-			DEBUGME='true' ;;
-		--reset|-R)
-			RESET='true' ;;
+			printf "%s\n" "$CurVer"; exit 0 ;;
+		--verbose|-V)
+			Verbose='-v' ;;
+		--set-store|-s)
+			shift; Store=$1
+
+			if [ -z "$Store" ]; then
+				Err 1 "Option '--set-store|-S' requires a path."
+				if ! YNInput "Directory store not found -- set anyway?"; then
+					Err 1 'User declined -- quitting.'
+				fi
+			fi
+
+			printf '%s\n' "$Store" 1> "$StoreFile"
+			printf "Store '%s' set.\n" "$Store"
+
+			exit 0 ;;
+		--exclude|-E)
+			shift; ExcluFile=$1 ;;
+		--command|-C)
+			shift; UserCMD=$1
+
+			if [ -z "$UserCMD" ]; then
+				Err 1 "Option '--command|-C' requires one or more arguments."
+			elif ! sh -nc "$UserCMD" 1> /dev/null 2>&1; then
+				Err 1 "User-specified command(s) resulted in errors."
+			fi ;;
 		--notify|-N)
-			NOTIFY='true' ;;
+			Notify='true' ;;
 		*)
-			Err 1 $LINENO "Incorrect argument(s) specified." ;;
+			Err 1 "Incorrect argument(s) specified." ;;
 	esac
 	shift
 done
 
-declare -i DEPCOUNT=0
-for DEP in gzip tar sync mkdir; {
-	if ! type -fP "$DEP" > /dev/null 2>&1; then
-		Err 0 $LINENO "Dependency '$DEP' not met."
-		DEPCOUNT+=1
+ChkDep tar sync mkdir date notify-send sh
+
+if ! [ -d "$MainDir" ] && ! mkdir -p "$MainDir"; then
+	Err 1 "Directory '~/.config/$Progrm' not made."
+elif [ -f "$ExcluFile" ] && ! [ -r "$ExcluFile" ]; then
+	Err 1 "Exclusions file unreadable."
+else
+	if [ -f "$StoreFile" ] && [ -r "$StoreFile" ]; then
+		read Store < "$StoreFile"
+
+		if ! [ -d "$Store" ]; then
+			Err 1 'Store directory not found.'
+		elif ! [ -r "$Store" ] || ! [ -x "$Store" ]; then
+			Err 1 'Store directory has insufficient permissions.'
+		fi
+	else
+		Err 1 "Unknown store -- see: $Progrm -h"
 	fi
+
+	[ -f "$ExcluFile" ] || unset Exclude ExcluFile
+fi
+
+TimeStamp=`date '+%F_%H%M'`
+Archive="BMU_$TimeStamp.tgz"
+
+SigHandler(){
+	Sig=$?
+	printf '\rERROR: Interrupted -- removing incomplete archive.\n' 1>&2
+	rm -f "${Store%/}/$Archive"
+	exit $Sig
 }
 
-[ $DEPCOUNT -eq 0 ] || exit 1
+trap SigHandler INT HUP TERM ABRT QUIT
 
-[ "$BEQUIET" == 'true' ] && exec > /dev/null
-[ "$DEBUGME" == 'true' ] && set -xeu
+TarArgs='--posix --xattrs --ignore-failed-read --one-file-system'
+tar $TarArgs $Verbose "$Exclude" -czpf "${Store%/}/$Archive" "$HOME" 2> /dev/null
+ExitStatus=$?
 
+trap 'printf "\rERROR: Wait, to avoid data loss.\n" 1>&2' INT HUP TERM ABRT QUIT
 
-if [ "$UPDATE" == 'true' ]; then
-	if ! type -fP wget > /dev/null 2>&1; then
-		Err 1 $LINENO "Dependency 'wget' not met."
+sync "${Store%/}/$Archive" 1> /dev/null 2>&1
+
+trap - INT HUP TERM ABRT QUIT
+
+[ -n "$UserCMD" ] && sh -c "$UserCMD"
+
+if [ $ExitStatus -eq 0 ]; then
+	printf 'Backup successfully created.\n'
+
+	if [ "$Notify" = 'true' ]; then
+		notify-send "Instance of '$Progrm' successfully finished."
 	fi
 
-	VERSION_URL="$DOM/terminalforlife/Extra/raw/master/versions"
-	while IFS='=' read -a LINE; do
-		if  [ "${LINE[0]}" == "$_PROJECT_" ]; then
-			LATEST=${LINE[1]}
-
-			if [[ ${LATEST//-} =~ ^[0-9]{8}$ ]]; then
-				if [ ${LATEST//-} -gt ${_VERSION_//-} ]; then
-					while read -r; do
-						printf "%s\n" "$REPLY"
-					done <<-EOF
-						New version available:    $LATEST
-						Current version:          $_VERSION_
-					EOF
-				fi
-			else
-				Err 1 $LINENO "Failed to check for available updates."
-			fi
-		fi
-	done <<< "$(wget -q "$VERSION_URL" -O -)"
-
 	exit 0
-fi
-
-MAIN_DIR="$HOME/.$_PROJECT_"
-SETTINGS="$MAIN_DIR/settings"
-
-[ -d "$MAIN_DIR" ] || mkdir "$MAIN_DIR"
-
-if [ ! -f "$SETTINGS" -o "$RESET" == 'true' ]; then
-	read -ep "Directory for $_PROJECT_ archives: " STORE
-
-	case $REPLY in
-		*)
-			if ! [ -d "$STORE" ]; then
-				Err 1 $LINENO "Directory not found or inaccessible."
-			fi ;;
-		"")
-			Err 1 $LINENO "You must enter a valid path." ;;
-	esac
-
-	printf -v DATETIME "%(%F_%H%M)T" "-1"
-
-	{
-		while read -r; do
-			printf "%s\n" "$REPLY"
-		done <<-EOF
-			# User settings file for and parsed by $_PROJECT_.
-			# Created:   $DATETIME
-			# User:      $USER
-			# UID:       $UID
-
-			# The path to the target file system. (mountpoint)
-			STORE=$STORE
-
-			# Exclude directories or files here.
-			EXCLUDE="$HOME/.cache"
-			EXCLUDE="$HOME/.thumbnails"
-		EOF
-	} > "$SETTINGS"
-
-	printf "Settings saved - Please relaunch $_PROJECT_.\n"
-	exit 0
-elif ! [ -r "$SETTINGS" ]; then
-	Err 1 $LINENO "File '$SETTINGS' inaccessible."
-fi
-
-declare -a EXCLUDE
-declare -i LINE=0
-while read -a X; do
-	LINE+=1
-
-	[ "${X[0]:0:1}" == "#" ] && continue
-	IFS="=" read -ra Y <<< "${X[@]}"
-
-	case ${Y[0]:-EMPTY} in
-		STORE)
-			printf "STORE: %s\n" "${Y[1]//\"}"
-			STORE=${Y[1]//\"} ;;
-		EXCLUDE)
-			printf "EXCLUDING: %s\n" "${Y[1]//\"}"
-			EXCLUDE+=("--exclude=${Y[1]%/}") ;;
-		EMPTY)
-			;;
-		*)
-			Err 1 $LINENO "Invalid parameter '${Y[0]}' on line #$LINE." ;;
-	esac
-done < "$SETTINGS"
-
-[ -d "$STORE" ] || Err 1 $LINENO "Target '$STORE' not found."
-
-printf -v ARCHIVE "BMU_%(%F_%H%M)T" "-1"
-declare -i SECONDS=0
-
-tar --xattrs --ignore-failed-read `eval printf "%s\\\\\n" ${EXCLUDE[@]}`\
-	--totals -cvpf "${STORE%/}/$ARCHIVE" "$HOME" || Err='true'
-
-gzip -v --best --suffix ".tgz" "${STORE%/}/$ARCHIVE" || Err='true'
-sync "${STORE%/}/$ARCHIVE.tgz" || Err='true'
-
-if ! [ "$Err" == 'true' ]; then
-	printf "Backup successfully created in %d seconds.\n" "$SECONDS"
 else
-	Err 0 $LINENO "One or more errors detected during backup."
-fi
+	printf 'WARNING: One or more errors detected during backup.\n' 1>&2
 
-if [ "$NOTIFY" == 'true' ]; then
-	if type -fP notify-send > /dev/null 2>&1; then
-		notify-send "Your $_PROJECT_ execution is finished."
-	else
-		Err 1 $LINENO "Dependency 'notify-send' not met."
+	if [ "$Notify" = 'true' ]; then
+		notify-send "Instance of '$Progrm' completed with errors."
 	fi
-fi
 
+	exit 1
+fi
