Error out on arg dir not found & rm old comment
Didn't meant to leave that TODO comment there -- oops.

For each argument directory not found, an error will be displayed, but
Baddot will still continue as normal.

diff --git a/source/baddot b/source/baddot
--- a/source/baddot
+++ b/source/baddot
@@ -3,7 +3,7 @@
 #------------------------------------------------------------------------------
 # Project Name      - Extra/source/baddot
 # Started On        - Tue 16 May 02:41:55 BST 2023
-# Last Change       - Tue 16 May 17:29:49 BST 2023
+# Last Change       - Tue 16 May 17:55:29 BST 2023
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
@@ -89,13 +89,17 @@ shopt -s dotglob nullglob
 
 #---------------------------------------------------Begin Scanning and Reporting
 
-#TODO Not working recursively in the first directory, but is the last/rest.
-
 Found=
 PrintDir=
 FoundTTL=0
 Pointers=()
 for ArgDir; {
+	if ! [[ -d $ArgDir ]]; then
+		Err 0 "Directory '$ArgDir' not found."
+
+		continue
+	fi
+
 	for Dir in "${ArgDir%/}"/$Glob; {
 		File=${Dir##*/}
 
