Switch all scripts to 'Err' instead of 'ERROR'
I've also replaced a lot of the error functions with my more recent
approach.

diff --git a/source/ccfiles b/source/ccfiles
--- a/source/ccfiles
+++ b/source/ccfiles
@@ -3,7 +3,7 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/source/ccfiles (Cross-Check Files)
 # Started On        - Wed 13 Dec 13:45:22 GMT 2017
-# Last Change       - Wed 27 Nov 15:53:59 GMT 2019
+# Last Change       - Wed 15 Dec 23:33:29 GMT 2021
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
@@ -15,12 +15,12 @@
 #       seems to have gone a different direction.
 #----------------------------------------------------------------------------------
 
-_VERSION_="2019-11-27"
+_VERSION_="2021-12-15"
 _PROJECT_=${0##*/}
 
 Err(){
-	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
-	[ $1 -eq 1 ] && exit 1
+	printf 'Err: %s\n' "$2" 1>&2
+	(( $1 > 0 )) && exit $1
 }
 
 DIR="/var/lib/dpkg/info"
@@ -59,13 +59,13 @@ while [ "$1" ]; do
 		--nobell|-B)
 			NOBELL='true' ;;
 		*)
-			Err 1 $LINENO "Incorrect argument(s) specified." ;;
+			Err 1 'Incorrect argument(s) specified.' ;;
 	esac
 	shift
 done
 
 if ! type -P readlink > /dev/null 2>&1; then
-	Err 1 $LINENO "Dependency 'readlink' not met."
+	Err 1 "Dependency 'readlink' not met."
 fi
 
 [ "$BEQUIET" == 'true' ] && exec > /dev/null
@@ -96,6 +96,5 @@ if [ -d $DIR/ ]; then
 		done < "$FILE"
 	}
 else
-	Err 1 $LINENO "Directory '$DIR' not found."
+	Err 1 "Directory '$DIR' not found."
 fi
-
diff --git a/source/cito/cito b/source/cito/cito
--- a/source/cito/cito
+++ b/source/cito/cito
@@ -3,7 +3,7 @@
 #------------------------------------------------------------------------------
 # Project Name      - Extra/source/cito/cito
 # Started On        - Thu  5 Dec 20:40:35 GMT 2019
-# Last Change       - Mon  1 Feb 23:59:21 GMT 2021
+# Last Change       - Wed 15 Dec 23:54:59 GMT 2021
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
@@ -27,7 +27,7 @@
 #   curl (>= 7.47.0-1) | wget (>= 1.17.1-1)
 #------------------------------------------------------------------------------
 
-CurVer='2021-02-01'
+CurVer='2021-12-15'
 Progrm=${0##*/}
 
 Usage(){
@@ -52,7 +52,7 @@ Usage(){
 }
 
 Err(){
-	printf 'ERROR: %s\n' "$2" 1>&2
+	printf 'Err: %s\n' "$2" 1>&2
 	[ $1 -gt 0 ] && exit $1
 }
 
@@ -383,7 +383,7 @@ SigHandler(){
 
 		if ! rm -f "$HashFile" "$TemRemFile" 1> /dev/null 2>&1; then
 			Logger error "File '$HashFile' and/or '$TemRemFile' failed removal"
-			printf 'ERROR: One or more temporary files failed removal.\n' 1>&2
+			printf 'Err: One or more temporary files failed removal.\n' 1>&2
 		else
 			Logger info "Removed '$HashFile' and '$TemRemFile'"
 		fi
diff --git a/source/dl-ubuntu-podcasts b/source/dl-ubuntu-podcasts
--- a/source/dl-ubuntu-podcasts
+++ b/source/dl-ubuntu-podcasts
@@ -3,7 +3,7 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/source/dl-ubuntu-podcasts
 # Started On        - Sat  7 Oct 19:08:59 BST 2017
-# Last Change       - Wed 27 Nov 15:54:06 GMT 2019
+# Last Change       - Wed 15 Dec 23:40:21 GMT 2021
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
@@ -11,12 +11,12 @@
 # interested in, please let me know.
 #----------------------------------------------------------------------------------
 
-_VERSION_="2019-11-27"
+_VERSION_="2021-12-15"
 _PROJECT_=${0##*/}
 
 Err(){
-	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
-	[ $1 -eq 1 ] && exit 1
+	printf 'Err: %s\n' "$2" 1>&2
+	(( $1 > 0 )) && exit $1
 }
 
 #TODO: Currently won't download S01E01.
@@ -67,7 +67,7 @@ while [ "$1" ]; do
 
 			ALTDEST=$1
 			if ! [ -d "$ALTDEST" ]; then
-				Err 1 "Destination directory not found."
+				Err 1 'Destination directory not found.'
 			fi ;;
 		--get-season-eight)
 			EXTRA="08 01 42" ;;
@@ -82,7 +82,7 @@ while [ "$1" ]; do
 done
 
 if ! type -P wget > /dev/null 2>&1; then
-	Err 1 $LINENO "Dependency 'wget' not met."
+	Err 1 "Dependency 'wget' not met."
 fi
 
 read -a WGET_VER_LINE <<< "$(wget --version)"
@@ -117,7 +117,7 @@ if [ "$*" ]; then
 
 	while [ "$1" ]; do
 		if ! [[ $1 =~ [0-9]+ ]]; then
-			Err 1 $LINENO "Incorrect page number specified."
+			Err 1 'Incorrect page number specified.'
 		else
 			[ $1 -eq 2 ] || NUM+=" $1"
 		fi
diff --git a/source/filesitter b/source/filesitter
--- a/source/filesitter
+++ b/source/filesitter
@@ -3,17 +3,17 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/source/filesitter
 # Started On        - Thu 28 Sep 23:58:07 BST 2017
-# Last Change       - Fri  6 Dec 22:49:34 GMT 2019
+# Last Change       - Wed 15 Dec 23:57:24 GMT 2021
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
 
-_VERSION_="2019-12-06"
+_VERSION_="2021-12-15"
 _PROJECT_=${0##*/}
 
 Err(){
-	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
-	[ $1 -eq 1 ] && exit 1
+	printf 'Err: %s\n' "$2" 1>&2
+	(( $1 > 0 )) && exit $1
 }
 
 USAGE(){
@@ -57,12 +57,12 @@ while [ "$1" ]; do
 			if [[ $1 =~ ^([0-9]+|[0-9]+.[0-9]+)$ ]]; then
 				INTERVAL=$1
 			else
-				Err 1 $LINENO "Invalid interval specified."
+				Err 1 "Invalid interval specified."
 			fi ;;
 		--shutdown|-S)
 			ACTION="poweroff" ;;
 		-*)
-			Err 1 $LINENO "Incorrect argument(s) specified." ;;
+			Err 1 "Incorrect argument(s) specified." ;;
 		*)
 			break ;;
 	esac
@@ -70,13 +70,13 @@ while [ "$1" ]; do
 done
 
 if ! [ "$*" ]; then
-	Err 1 $LINENO "No files were given for $_PROJECT_ to monitor."
+	Err 1 "No files were given for $_PROJECT_ to monitor."
 fi
 
 declare -i DEPCOUNT=0
 for DEP in stat systemctl sleep; {
 	if ! type -P "$DEP" > /dev/null 2>&1; then
-		Err 0 $LINENO "Dependency '$DEP' not met."
+		Err 0 "Dependency '$DEP' not met."
 		DEPCOUNT+=1
 	fi
 }
@@ -103,6 +103,6 @@ while [ "$GO" == "yes" ]; do
 done
 
 if ! systemctl $ACTION; then
-	Err 1 $LINENO "System $ACTION failed."
+	Err 1 "System $ACTION failed."
 fi
 
diff --git a/source/freelfm b/source/freelfm
--- a/source/freelfm
+++ b/source/freelfm
@@ -3,17 +3,17 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/source/freelfm
 # Started On        - Fri 15 Sep 21:19:42 BST 2017
-# Last Change       - Wed 27 Nov 15:54:14 GMT 2019
+# Last Change       - Wed 15 Dec 23:58:31 GMT 2021
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
 
-_VERSION_="2019-11-27"
+_VERSION_="2021-12-15"
 _PROJECT_=${0##*/}
 
 Err(){
-	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
-	[ $1 -eq 1 ] && exit 1
+	printf 'Err: %s\n' "$2" 1>&2
+	(( $1 > 0 )) && exit $1
 }
 
 USAGE(){
@@ -72,7 +72,7 @@ while [ "$1" ]; do
 		--links-only)
 			LINKSONLY='true' ;;
 		-*)
-			Err 1 $LINENO "Incorrect argument(s) specified." ;;
+			Err 1 "Incorrect argument(s) specified." ;;
 		*)
 			break ;;
 	esac
@@ -82,7 +82,7 @@ done
 declare -i DEPCOUNT=0
 for DEP in tee wget sync sleep sed grep mkdir; {
 	if ! type -P "$DEP" > /dev/null 2>&1; then
-		Err 0 $LINENO "Dependency '$DEP' not met."
+		Err 0 "Dependency '$DEP' not met."
 		DEPCOUNT+=1
 	fi
 }
@@ -91,12 +91,12 @@ for DEP in tee wget sync sleep sed grep mkdir; {
 
 
 if ! [ "$*" ]; then
-	Err 1 $LINENO "One or more page numbers missing."
+	Err 1 "One or more page numbers missing."
 else
 	PAGENUM="$@"
 	for NUM in $PAGENUM; {
 		if ! [[ $NUM == [0-9] ]]; then
-			Err 1 $LINENO "Invalid page number at: $NUM"
+			Err 1 "Invalid page number at: $NUM"
 		fi
 	}
 fi
@@ -136,7 +136,7 @@ for PAGE in $PAGENUM; {
 				printf "%s\n" "FILE: ${TITLE}.mp3"
 				wget -qc --no-cookies $NOWARC \
 					"$LINK" -O "$DLDIR/${TITLE//\"}.mp3" || {
-					Err 0 $LINENO "Track '${TITLE}.mp3' failed."
+					Err 0 "Track '${TITLE}.mp3' failed."
 				}
 			else
 				printf "%s\n" "LINK: ${TITLE}.mp3"
@@ -173,7 +173,7 @@ if [ "$SUSPEND" == 'true' ]; then
 	elif type -P pm-suspend > /dev/null 2>&1; then
 		pm-suspend
 	else
-		Err 1 $LINENO "Unable to find a supported suspend method."
+		Err 1 "Unable to find a supported suspend method."
 	fi
 fi
 
diff --git a/source/github-ssh-setup b/source/github-ssh-setup
--- a/source/github-ssh-setup
+++ b/source/github-ssh-setup
@@ -3,18 +3,13 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/source/github-ssh-setup
 # Started On        - Thu 14 Sep 18:32:41 BST 2017
-# Last Change       - Wed 27 Nov 15:56:10 GMT 2019
+# Last Change       - Wed 15 Dec 23:59:48 GMT 2021
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
 
-_VERSION_="2019-11-27"
+_VERSION_="2021-12-15"
 _PROJECT_=${0##*/}
-
-Err(){
-	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
-	[ $1 -eq 1 ] && exit 1
-}
 
 USAGE(){
 	while read; do
@@ -37,6 +32,11 @@ USAGE(){
 	EOF
 }
 
+Err(){
+	printf 'Err: %s\n' "$2" 1>&2
+	(( $1 > 0 )) && exit $1
+}
+
 while [ "$1" ]; do
 	case $1 in
 		--help|-h|-\?)
@@ -48,7 +48,7 @@ while [ "$1" ]; do
 		--install-git|-G)
 			INSTALLGIT='true' ;;
 		-*)
-			Err 1 $LINENO "Incorrect argument(s) specified." ;;
+			Err 1 "Incorrect argument(s) specified." ;;
 		*)
 			break ;;
 	esac
@@ -61,14 +61,14 @@ SSH_KEY_FILE=$2
 declare -i DEPCOUNT=0
 for DEP in find ssh-add ssh-agent ssh-keygen apt-get; {
 	if ! type -P "$DEP" > /dev/null 2>&1; then
-		Err 0 $LINENO "Dependency '$DEP' not met."
+		Err 0 "Dependency '$DEP' not met."
 		DEPCOUNT+=1
 	fi
 }
 
 [ $DEPCOUNT -eq 0 ] || exit 1
 
-[ $UID -eq 0 ] || Err 1 $LINENO "Root access is required."
+[ $UID -eq 0 ] || Err 1 "Root access is required."
 
 [ "$DEBUGME" == 'true' ] && set -x
 
@@ -77,10 +77,10 @@ if [ "$INSTALLGIT" == 'true' ]; then
 		printf "INFO: Installing git packages with apt-get.\n"
 		apt-get -q --show-progress -o Dpkg::Progress-Fancy=true install git
 	else
-		Err 0 $LINENO "It seems git is already installed."
+		Err 0 "It seems git is already installed."
 	fi
 elif [ ! "$INSTALLGIT" == 'true' ] && ! type -P git > /dev/null 2>&1; then
-	Err 0 $LINENO "Unable to find 'git'; is it installed?"
+	Err 0 "Unable to find 'git'; is it installed?"
 fi
 
 if [ "$INSTALLSSH" == 'true' ]; then
@@ -88,10 +88,10 @@ if [ "$INSTALLSSH" == 'true' ]; then
 		printf "INFO: Installing ssh packages with apt-get.\n"
 		apt-get -q --show-progress -o Dpkg::Progress-Fancy=true  install ssh
 	else
-		Err 0 $LINENO "SSH seems to already be installed."
+		Err 0 "SSH seems to already be installed."
 	fi
 elif [ ! "$INSTALLSSH" == 'true' -a ! -x /usr/bin/ssh ]; then
-	Err 1 $LINENO "SSH, which is required, is not installed."
+	Err 1 "SSH, which is required, is not installed."
 fi
 
 if ! [ "$EMAIL" ]; then
@@ -100,7 +100,7 @@ if ! [ "$EMAIL" ]; then
 fi
 
 if ! [[ $EMAIL =~ ^[[:alnum:]]+@[[:alnum:]]+\.[[:alnum:]]+$ ]]; then
-	Err 1 $LINENO "Incorrect E-Mail address (format) specified."
+	Err 1 "Incorrect E-Mail address (format) specified."
 fi
 
 if ! [ "$SSH_KEY_FILE" ]; then
@@ -114,7 +114,7 @@ if ! [ "$SSH_KEY_FILE" ]; then
 fi
 
 if ! [ -d "${SSH_KEY_FILE%\/*}" ]; then
-	Err 1 $LINENO "One or more key file parent directories missing."
+	Err 1 "One or more key file parent directories missing."
 fi
 
 printf "INFO: Generating a new SSH (RSA, 4096) key pair.\n"
@@ -124,23 +124,23 @@ if ssh-keygen -t rsa -b 4096 -C "$EMAIL" -f $SSH_KEY_FILE; then
 	chown -v $SUDO_UID:$SUDO_GID $SSH_KEY_FILE
 	chown -v $SUDO_UID:$SUDO_GID ${SSH_KEY_FILE}.pub
 else
-	Err 1 $LINENO "Non-zero exit status: /usr/bin/ssh-keygen."
+	Err 1 "Non-zero exit status: /usr/bin/ssh-keygen."
 fi
 
 printf "INFO: Starting the ssh-agent background process.\n"
 if ! eval `ssh-agent -s`; then
-	Err 1 $LINENO 'Non-zero exit status: eval `/usr/bin/ssh-agent -s`'
+	Err 1 'Non-zero exit status: eval `/usr/bin/ssh-agent -s`'
 fi
 
 printf "INFO: Adding SSH key to the ssh-agent -- storing in keychain.\n"
 if ! ssh-add $SSH_KEY_FILE; then
-	Err 1 $LINENO "Non-zero exit status: /usr/bin/ssh-add"
+	Err 1 "Non-zero exit status: /usr/bin/ssh-add"
 fi
 
 if type -P xclip > /dev/null 2>&1; then
 	printf "INFO: Adding public key to clipboard with /usr/bin/xclip.\n"
 	if ! xclip -sel clip < ${SSH_KEY_FILE}.pub; then
-		Err 1 $LINENO "Non-zero exit status: /usr/bin/xclip"
+		Err 1 "Non-zero exit status: /usr/bin/xclip"
 	fi
 
 	printf "INFO: Now paste the .pub key into GitHub's 'Key' field.\n"
diff --git a/source/iplite b/source/iplite
--- a/source/iplite
+++ b/source/iplite
@@ -3,7 +3,7 @@
 #------------------------------------------------------------------------------
 # Project Name      - Extra/source/iplite
 # Started On        - Sat 29 Feb 14:56:05 GMT 2020
-# Last Change       - Sat 29 Feb 15:30:33 GMT 2020
+# Last Change       - Thu 16 Dec 00:00:47 GMT 2021
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
@@ -28,7 +28,7 @@
 #   bash (>= 4.0)
 #------------------------------------------------------------------------------
 
-CurVer='2020-02-29'
+CurVer='2021-12-16'
 Progrm=${0##*/}
 
 Usage(){
@@ -51,7 +51,7 @@ while [ "$1" ]; do
 		--version|-v)
 			printf '%s\n' "$CurVer"; exit 0 ;;
 		*)
-			printf 'ERROR: Incorrect option(s) specified.\n' 1>&2
+			printf 'Err: Incorrect option(s) specified.\n' 1>&2
 			exit 1 ;;
 	esac
 	shift
@@ -82,10 +82,10 @@ if [ -n "$IP" ]; then
 	if [[ $IP =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
 		printf '%s\n' "$IP"
 	else
-		printf 'ERROR: Received invalid IP address.\n' 1>&2
+		printf 'Err: Received invalid IP address.\n' 1>&2
 		exit 1
 	fi
 else
-	printf 'ERROR: Unable to fetch external IP.\n' 1>&2
+	printf 'Err: Unable to fetch external IP.\n' 1>&2
 	exit 1
 fi
diff --git a/source/mplay b/source/mplay
--- a/source/mplay
+++ b/source/mplay
@@ -3,7 +3,7 @@
 #------------------------------------------------------------------------------
 # Project Name      - Extra/source/mplay
 # Started On        - Sat 16 Sep 19:42:57 BST 2017
-# Last Change       - Sun 29 Nov 04:28:36 GMT 2020
+# Last Change       - Thu 16 Dec 00:03:56 GMT 2021
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
@@ -15,14 +15,14 @@
 # repository on the same GitHub store from which this file originated.
 #------------------------------------------------------------------------------
 
-_VERSION_="2020-11-29"
+_VERSION_="2021-12-16"
 _PROJECT_=${0##*/}
 
 DOM="https://github.com"
 
 Err(){
-	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
-	[ $1 -eq 1 ] && exit 1
+	printf 'Err: %s\n' "$2" 1>&2
+	(( $1 > 0 )) && exit $1
 }
 
 THEMEDIR="/usr/share/moc/themes"
@@ -66,18 +66,18 @@ while [ "$1" ]; do
 		--once|-o)
 			ONCE='true' ;;
 		-*)
-			Err 1 $LINENO "Incorrect argument(s) specified." ;;
+			Err 1 "Incorrect argument(s) specified." ;;
 	esac
 	shift
 done
 
-[ "$1" -a ! -d "$1" ] && Err 1 $LINENO "Unable to find the given music directory."
+[ "$1" -a ! -d "$1" ] && Err 1 "Unable to find the given music directory."
 
-[ -d $THEMEDIR ] || Err 1 $LINENO "Theme directory not found."
-[ -f "$THEMEDIR/tfl_moc_theme" ] || Err 1 $LINENO "Theme file not found."
+[ -d $THEMEDIR ] || Err 1 "Theme directory not found."
+[ -f "$THEMEDIR/tfl_moc_theme" ] || Err 1 "Theme file not found."
 
 if ! type -P mocp > /dev/null 2>&1; then
-	Err 1 $LINENO "Dependency 'mocp' not met."
+	Err 1 "Dependency 'mocp' not met."
 fi
 
 /usr/bin/mocp -n -T "$THEMEDIR/tfl_moc_theme"     \
@@ -100,7 +100,7 @@ fi
 	-O OutputBuffer=512                       \
 	-O Prebuffering=256                       \
 	-m "${1:-$HOME/Music}"                    \
-|| Err 1 $LINENO "Unable to start the MOC player."
+|| Err 1 "Unable to start the MOC player."
 
 if [ "$ONCE" == 'true' ]; then
 	wait; mocp -x
diff --git a/source/noprtscr b/source/noprtscr
--- a/source/noprtscr
+++ b/source/noprtscr
@@ -3,7 +3,7 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/source/noprtscr (No Print Screen)
 # Started On        - Sun 21 Jan 18:30:36 GMT 2018
-# Last Change       - Wed 27 Nov 15:56:23 GMT 2019
+# Last Change       - Thu 16 Dec 00:04:22 GMT 2021
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
@@ -17,16 +17,16 @@
 #             --prtsc-is-menu         - Use PrtSC to launch the Mint Menu.
 #----------------------------------------------------------------------------------
 
-_VERSION_="2019-11-27"
+_VERSION_="2021-12-16"
 _PROJECT_=${0##*/}
 
 Err(){
-	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
-	[ $1 -eq 1 ] && exit 1
+	printf 'Err: %s\n' "$2" 1>&2
+	(( $1 > 0 )) && exit $1
 }
 
 if ! type -P gsettings > /dev/null 2>&1; then
-	Err 1 $LINENO "Dependency 'gsettings' not met."
+	Err 1 "Dependency 'gsettings' not met."
 fi
 
 while [ "$1" ]; do
@@ -39,10 +39,10 @@ while [ "$1" ]; do
 			# Feature the OP in the thread requested.
 			SCHEMA="com.linuxmint.mintmenu"
 			if ! gsettings set "$SCHEMA" hot-key "Print" 2> /dev/null; then
-				Err 1 $LINENO "Unable to set 'hot-key' to 'Print' in: $SCHEMA"
+				Err 1 "Unable to set 'hot-key' to 'Print' in: $SCHEMA"
 			fi ;;
 		*)
-			Err 1 $LINENO "Incorrect argument(s) specified." ;;
+			Err 1 "Incorrect argument(s) specified." ;;
 	esac
 	shift
 done
@@ -50,7 +50,7 @@ done
 SCHEMA="org.cinnamon.desktop.keybindings.media-keys"
 for KEY in {area,window}-screenshot{,-clip} screenshot{,-clip}; {
 	if ! gsettings set "$SCHEMA" "$KEY" "[]" 2> /dev/null; then
-		Err 1 $LINENO "Unable to clear: $KEY"
+		Err 1 "Unable to clear: $KEY"
 	fi
 }
 
diff --git a/source/nxbt b/source/nxbt
--- a/source/nxbt
+++ b/source/nxbt
@@ -3,19 +3,19 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/source/nxbt (New XBT)
 # Started On        - Fri  6 Oct 17:52:55 BST 2017
-# Last Change       - Fri  6 Dec 22:53:19 GMT 2019
+# Last Change       - Thu 16 Dec 00:05:14 GMT 2021
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
 
-_VERSION_="2019-12-06"
+_VERSION_="2021-12-16"
 _PROJECT_=${0##*/}
 
 declare -i SECONDS=0
 
 Err(){
-	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
-	[ $1 -eq 1 ] && exit 1
+	printf 'Err: %s\n' "$2" 1>&2
+	(( $1 > 0 )) && exit $1
 }
 
 DOM="https://github.com"
@@ -67,21 +67,21 @@ while [ "$1" ]; do
 			if [ -d "${1%\/*}" ]; then
 				LOGFILE=$1
 			else
-				Err 1 $LINENO "Logfile directory not found."
+				Err 1 "Logfile directory not found."
 			fi ;;
 #		--source|-s)
 #			shift
 #			if [ -d "${1%\/*}" ]; then
 #				SOURCE+=" $1"
 #			else
-#				Err 1 $LINENO "Source directory not found."
+#				Err 1 "Source directory not found."
 #			fi ;;
 #		--and-source|-S)
 #			shift
 #			if [ -d "${1%\/*}" ]; then
 #				ANDSOURCE='true' SOURCE+=( "$1")
 #			else
-#				Err 1 $LINENO "Source directory not found."
+#				Err 1 "Source directory not found."
 #			fi ;;
 		*)
 			break ;;
@@ -92,18 +92,18 @@ done
 declare -i DEPCOUNT=0
 for DEP in wget rsync mkdir sync; {
 	if ! type -P "$DEP" > /dev/null 2>&1; then
-		Err 0 $LINENO "Dependency '$DEP' not met."
+		Err 0 "Dependency '$DEP' not met."
 		DEPCOUNT+=1
 	fi
 }
 
 [ $DEPCOUNT -eq 0 ] || exit 1
 
-#Err 1 $LINENO "Incorrect option(s) specified." ;;
+#Err 1 "Incorrect option(s) specified." ;;
 [ "$BEQUIET" == 'true' ] && exec > /dev/null
 [ "$DEBUGME" == 'true' ] && set -x
 
-[ -d "$*" ] || Err 1 $LINENO "Unable to find or access the TARGET directory."
+[ -d "$*" ] || Err 1 "Unable to find or access the TARGET directory."
 
 TARGET="$*"
 [ -f "$TARGET" ] && Err 1 "Target is not a directory."
@@ -176,7 +176,7 @@ if [ -f "$LOGFILE" ]; then
 		printf "[+%0.7d] CLEANING: %s\n" "$SECONDS" "$LOGFILE"
 	fi
 else
-	Err 1 $LINENO "Logfile not found."
+	Err 1 "Logfile not found."
 fi
 
 if [ -f "$LOGFILE" ]; then
diff --git a/source/pagewatch b/source/pagewatch
--- a/source/pagewatch
+++ b/source/pagewatch
@@ -3,7 +3,7 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/source/pagewatch
 # Started On        - Wed 18 Oct 19:27:40 BST 2017
-# Last Change       - Fri  6 Dec 22:53:26 GMT 2019
+# Last Change       - Thu 16 Dec 00:05:39 GMT 2021
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
@@ -15,12 +15,12 @@
 # 17.10 download link.
 #----------------------------------------------------------------------------------
 
-_VERSION_="2019-12-06"
+_VERSION_="2021-12-16"
 _PROJECT_=${0##*/}
 
 Err(){
-	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
-	[ $1 -eq 1 ] && exit 1
+	printf 'Err: %s\n' "$2" 1>&2
+	(( $1 > 0 )) && exit $1
 }
 
 shopt -s extglob
@@ -67,7 +67,7 @@ while [ "$1" ]; do
 		--interval|-i)
 			shift; INTERVAL="$1" ;;
 		-*|--*)
-			Err 1 $LINENO "Incorrect argument(s) specified." ;;
+			Err 1 "Incorrect argument(s) specified." ;;
 		*)
 			break ;;
 	esac
@@ -83,20 +83,20 @@ COMMANDS="$@"
 declare -i DEPCOUNT=0
 for DEP in sleep md5sum wget; {
 	if ! type -P "$DEP" > /dev/null 2>&1; then
-		Err 0 $LINENO "Dependency '$DEP' not met."
+		Err 0 "Dependency '$DEP' not met."
 		DEPCOUNT+=1
 	fi
 }
 
 [ $DEPCOUNT -eq 0 ] || exit 1
 
-[ "$URL" ] || Err 1 $LINENO "A webpage address (URL) is required."
+[ "$URL" ] || Err 1 "A webpage address (URL) is required."
 
 [ "$BEQUIET" == 'true' ] && exec > /dev/null
 [ "$DEBUGME" == 'true' ] && set -x
 
 printf -v BUFFER "/tmp/${_PROJECT_}_%(%F_%X)T.md5" "-1"
-[ -d /tmp ] || Err 1 $LINENO "Directory /tmp is missing or inaccessible."
+[ -d /tmp ] || Err 1 "Directory /tmp is missing or inaccessible."
 
 wget -q "$URL" -O - | md5sum > "$BUFFER" 2> /dev/null
 
diff --git a/source/ripmydvd b/source/ripmydvd
--- a/source/ripmydvd
+++ b/source/ripmydvd
@@ -3,18 +3,13 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/source/ripmydvd
 # Started On        - Fri 29 Sep 21:19:47 BST 2017
-# Last Change       - Fri  6 Dec 22:53:43 GMT 2019
+# Last Change       - Thu 16 Dec 00:05:58 GMT 2021
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
 
-_VERSION_="2019-12-06"
+_VERSION_="2021-12-16"
 _PROJECT_=${0##*/}
-
-Err(){
-	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
-	[ $1 -eq 1 ] && exit 1
-}
 
 USAGE(){
 	while read; do
@@ -51,6 +46,11 @@ USAGE(){
 	EOF
 }
 
+Err(){
+	printf 'Err: %s\n' "$2" 1>&2
+	(( $1 > 0 )) && exit $1
+}
+
 while [ "$1" ]; do
 	case $1 in
 		--help|-h|-\?)
@@ -64,7 +64,7 @@ while [ "$1" ]; do
 		--device|-d)
 			shift
 
-			[ -b "$1" ] || Err 1 $LINENO "Device not found at: $1"
+			[ -b "$1" ] || Err 1 "Device not found at: $1"
 			DEVICE="$1" ;;
 		--combine|-C)
 			COMBINE='true' ;;
@@ -74,7 +74,7 @@ while [ "$1" ]; do
 			if [[ $1 =~ ^([0-9]+|[0-9]+-[0-9]+)$ ]]; then
 				TITLE=$1
 			else
-				Err 1 $LINENO "Invalid title."
+				Err 1 "Invalid title."
 			fi ;;
 		--aid)
 			shift
@@ -112,15 +112,15 @@ TARGET="$*"
 declare -i DEPCOUNT=0
 for DEP in eject mkfifo ffmpeg mplayer; {
 	if ! type -P "$DEP" > /dev/null 2>&1; then
-		Err 0 $LINENO "Dependency '$DEP' not met."
+		Err 0 "Dependency '$DEP' not met."
 		DEPCOUNT+=1
 	fi
 }
 
 [ $DEPCOUNT -eq 0 ] || exit 1
 
-[ "$TARGET" ] || Err 1 $LINENO "You need to provide a filename."
-[ "$TITLE" ] || Err 1 $LINENO "Which title do you want to rip?"
+[ "$TARGET" ] || Err 1 "You need to provide a filename."
+[ "$TITLE" ] || Err 1 "Which title do you want to rip?"
 [ "$DEVICE" ] || DEVICE="/dev/sr0"
 
 [ "$BEQUIET" == 'true' ] && exec > /dev/null
@@ -137,7 +137,7 @@ mkfifo "$FIFO"
 
 if [ "$COMBINE" == 'true' ]; then
 	if ! [ "$ALANG" -a "$AID" ]; then
-		Err 1 $LINENO "The --combine argument requires -alang or -aid."
+		Err 1 "The --combine argument requires -alang or -aid."
 	fi
 
 	mplayer $MPARGS1 -dumpaudio -dumpfile "/tmp/audio.dump"\
diff --git a/source/simplify-ubuntu/simplify-ubuntu-installer b/source/simplify-ubuntu/simplify-ubuntu-installer
--- a/source/simplify-ubuntu/simplify-ubuntu-installer
+++ b/source/simplify-ubuntu/simplify-ubuntu-installer
@@ -3,7 +3,7 @@
 #------------------------------------------------------------------------------
 # Project Name      - Extra/source/simplify-ubuntu/simplify-ubuntu-installer
 # Started On        - Sun 31 Jan 22:35:39 GMT 2021
-# Last Change       - Fri  9 Jul 11:24:57 BST 2021
+# Last Change       - Thu 16 Dec 00:09:18 GMT 2021
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
@@ -32,7 +32,7 @@
 #------------------------------------------------------------------------------
 
 Err(){
-	printf 'ERROR: %s\n' "$2" 1>&2
+	printf 'Err: %s\n' "$2" 1>&2
 	[ $1 -gt 0 ] && exit $1
 }
 
@@ -41,14 +41,10 @@ if command -v curl 1> /dev/null 2>&1; then
 elif command -v wget 1> /dev/null 2>&1; then
 	DLCMD='wget -qO'
 else
-	printf "ERROR: Neither 'wget' nor 'curl' are available.\n" 1>&2
-	exit 1
+	Err 1 "Neither 'wget' nor 'curl' are available."
 fi
 
-if [ `id -u` -ne 0 ]; then
-	printf "ERROR: Root access is required for system-wide changes.\n" 1>&2
-	exit 1
-fi
+[ `id -u` -ne 0 ] && Err 1 'Root access required for system-wide changes.'
 
 while :; do
 	printf 'Install latest version of Simplify Ubuntu? [Y/N] '
@@ -122,10 +118,7 @@ for File in 'completions' 'simplify-ubuntu' 'simplify-ubuntu.8.gz'; do
 	fi
 done
 
-if [ $ErrCount -gt 0 ]; then
-	printf 'ERROR: Failed to download one or more files.\n' 1>&2
-	exit 1
-fi
+[ $ErrCount -gt 0 ] && Err 1 'Failed to download one or more files.'
 
 printf 'Setting correct file attributes:\n'
 
diff --git a/source/simwea b/source/simwea
--- a/source/simwea
+++ b/source/simwea
@@ -3,18 +3,13 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/source/simwea (Simple Weather)
 # Started On        - Sun 17 Sep 22:16:30 BST 2017
-# Last Change       - Fri  6 Dec 22:54:40 GMT 2019
+# Last Change       - Thu 16 Dec 00:10:26 GMT 2021
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
 
-_VERSION_="2019-12-06"
+_VERSION_="2021-12-16"
 _PROJECT_=${0##*/}
-
-Err(){
-	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
-	[ $1 -eq 1 ] && exit 1
-}
 
 DOM="https://darksky.net"
 
@@ -46,7 +41,12 @@ USAGE(){
 	EOF
 }
 
-[ $# -eq 0 ] && Err 1 $LINENO "Arguments are required."
+Err(){
+	printf 'Err: %s\n' "$2" 1>&2
+	(( $1 > 0 )) && exit $1
+}
+
+[ $# -eq 0 ] && Err 1 'Argument(s) required.'
 
 while [ "$1" ]; do
 	case $1 in
@@ -66,14 +66,14 @@ while [ "$1" ]; do
 			if [[ $1 =~ [-0-9.]+ ]]; then
 				LONG=$1
 			else
-				Err 1 $LINENO "Invalid longitude."
+				Err 1 "Invalid longitude."
 			fi ;;
 		--lat|-L)
 			shift
 			if [[ $1 =~ [-0-9.]+ ]]; then
 				LAT=$1
 			else
-				Err 1 $LINENO "Invalid latitude."
+				Err 1 'Invalid latitude.'
 			fi ;;
 		*)
 			break ;;
@@ -81,14 +81,14 @@ while [ "$1" ]; do
 	shift
 done
 
-type -P wget > /dev/null 2>&1 || Err 1 $LINENO "Dependency 'wget' not met."
+type -P wget > /dev/null 2>&1 || Err 1 "Dependency 'wget' not met."
 
 if ! [ "$#" ]; then
-	Err 1 $LINENO "Incorrect argument(s) given."
+	Err 1 'Incorrect argument(s) given.'
 elif [ -z "$UKUS" ] || [ -z "$SYM" ]; then
-	Err 1 $LINENO "Missing Fahrenheit or Celsius arguments."
+	Err 1 'Missing Fahrenheit or Celsius arguments.'
 elif [ -z "$LONG" ] || [ -z "$LAT" ]; then
-	Err 1 $LINENO "Missing longitude and latitude arguments."
+	Err 1 'Missing longitude and latitude arguments.'
 fi
 
 [ "$DEBUGME" == 'true' ] && set -x
