Vastly patch up `cito`, and support more
Highlighted changes for Cito:

  * Has been significantly debugged.

  * Improvements in the logging output and additional lines.

  * Added a lot of new content to `Usage()`, including examples.

  * Tweaked Cito's short description.

  * MD5 hash verifying has been tweaked, but is still untested.

  * OPT `--hash|-H` added to specify the hash file to use.

  * Now entirely detached from _my_ GitHub. Free reign!

  * Easily fetch and install remote files with `--remote|-r` OPT.

  * Signal handling for logging and cleaning up temporary files.

  * Now using `mv` instead of `cp`, thus removed dependency `cp`.

  * Dependency `mktemp` added for the creation of temporary files.

  * Some additional errors were caught and `Err()` calls were added.

  * The user can now specify one or more local files to install.

  * Changing file ownership and mode now function correctly.

  * Condensed some code via functions in order to aid legibility.

Miscellaneous changes:

  * Many of the better programs now support Cito. Some need TLC though.

diff --git a/source/cito b/source/cito
--- a/source/cito
+++ b/source/cito
@@ -3,7 +3,7 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/source/cito
 # Started On        - Thu  5 Dec 20:40:35 GMT 2019
-# Last Change       - Fri  6 Dec 17:36:32 GMT 2019
+# Last Change       - Fri  6 Dec 22:37:41 GMT 2019
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
@@ -27,12 +27,7 @@ CurVer='2019-12-06'
 Progrm=${0##*/}
 
 EventLog='/var/log/cito-events.log'
-
 RawDomain='https://raw.githubusercontent.com'
-GHUser='terminalforlife'
-Repo='Extra'
-Branch='master'
-
 LogTypes='all info warning error'
 
 Usage(){
@@ -42,17 +37,42 @@ Usage(){
 		\r            CITO ($CurVer)
 		\r            Written by terminalforlife (terminalforlife@yahoo.com)
 
-		\r            Bourne POSIX installer for one-file programs from GitHub.
+		\r            Bourne POSIX installer for files within GitHub repositories.
 
-		\rSYNTAX:     $Progrm [OPTS] [FILE_1 [FILE_2] ...]
+		\rSYNTAX:     $Progrm [OPTS] [File_1 [File_2] ...]
 
 		\rOPTS:       --help|-h|-?            - Displays this help information.
 		\r            --version|-v            - Output only the version datestamp.
 		\r            --log-view|-L TYPE      - Show TYPE log entries for Cito.
+		\r            --remote|-r INFO        - Specify a remote file; see REMOTE.
+		\r            --hash|-H FILE          - Use FILE to cross-check hashes.
 
 		\rNOTE:       The use of '--' to specify the end of OPTS, is supported.
 
 		\r            Where TYPE is one of 'all', 'info', 'warning', or 'error'.
+
+		\r            When a remote file is selected, the '--hash|-H' FILE will
+		\r            be assumed as within the selected user, repo', and branch.
+
+		\r            Hash checks assume the following traditional format:
+
+		\r              0t1h2e3h4a5s6h7g8o9e1s2h3e4r5e67  .secret_dot_file
+
+		\r            Currently, only MD5 hash checking is supported.
+
+		\rREMOTE:     Where INFO is an order-dependent, space-delimited list of
+		\r            strings used by Cito to correctly fetch the file.
+
+		\r              [U]SER [R]EPO [B]RANCH [F]ILE
+
+		\r            U = The GitHub user account.
+		\r            R = The repository for the user.
+		\r            B = The branch for the repository.
+		\r            F = The file within the repository.
+
+		\rEXAMPLE:    cito -r terminalforlife Extra master source/cito
+		\r            cito -H md5sum -r chubin cheat.sheets master sheets/awk
+		\r            cito ./world-peace.pl ~/Downloads/coolscript.sh
 
 		\rFILE:       $EventLog
 	EOF
@@ -74,6 +94,18 @@ for CurArg in "$@"; do
 			if [ -z "$LogView" ]; then
 				Err 1 "Option '--log-view|-L' requires one of TYPE."
 			fi ;;
+		--remote|-r)
+			DoRemote='true'
+			shift; GHUser=$1
+			shift; Repo=$1
+			shift; Branch=$1
+			shift; RemoteFile=$1 ;;
+		--hash|-H)
+			shift; MD5File="x$1"
+
+			if [ -z "$MD5File" ]; then
+				Err 1 "Missing argument for '--hash|-H' option."
+			fi ;;
 		-*)
 			Err 1 'Incorrect argument(s) specified.' ;;
 		*)
@@ -81,7 +113,7 @@ for CurArg in "$@"; do
 	esac
 done
 
-ChkDep id chmod chown md5sum mkdir date rm
+ChkDep mv id chmod chown md5sum mkdir date rm mktemp
 
 if command -v curl 1> /dev/null 2>&1; then
 	DLCMD='curl -so'
@@ -95,11 +127,12 @@ if ! [ ${UID:-`id -u`} -eq 0 ]; then
 	Err 1 'Root permissions required for system-wide changes.'
 fi
 
-ChkMD5(){
-	HashFile=`mktemp`
+TemRemFile=`mktemp`
+HashFile=`mktemp`
 
-	URL="$RawDomain/$GHUser/$Repo/md5sum"
-	$DLCMD "$HashFile" "$URL" 1> /dev/null 2>&1
+ChkMD5(){
+	MD5URL="$RawDomain/$GHUser/$Repo/$1"
+	$DLCMD "$HashFile" "$MD5URL" 1> /dev/null 2>&1
 
 	while read Hash File; do
 		if [ "$File" = "$1" ]; then
@@ -110,7 +143,7 @@ ChkMD5(){
 		fi
 	done < "$HashFile"
 
-	unset URL HashFile Hash File GetHash
+	unset MD5URL Hash File GetHash
 }
 
 Logger(){ # Usage: Logger TYPE MESSAGE
@@ -136,6 +169,7 @@ Logger(){ # Usage: Logger TYPE MESSAGE
 LogErrInf(){ # Usage: LogErrInf [$KEY] [KEY] [FILE]
 	if [ -z "$1" ]; then
 		Logger error "$2 is null for '$3'"
+		Err 1 "Value for '$2' not set."
 	else
 		Logger info "$2 is '$1' for '$3'"
 	fi
@@ -157,10 +191,31 @@ LogTypeChk(){ # Usage: LogTypeChk [TYPE] [VALID_TYPES]
 	unset CheckType TypeCount CurType
 }
 
+SigHandler(){
+	Signal=$?
+
+	if [ $Signal -eq 0 ]; then
+		Logger info "Signal '$Signal' detected by 'SigHandler()'"
+	else
+		Logger warning "Signal '$Signal'  detected by 'SigHandler()'"
+	fi
+
+	if ! rm -f "$HashFile" "$TemRemFile" 1> /dev/null 2>&1; then
+		Logger error "File '$HashFile' and/or '$TemRemFile' failed removal"
+		printf "ERROR: One or more temporary files failed removal.\n" 1>&2
+	fi
+
+	exit $Signal
+}
+
+trap SigHandler INT EXIT STOP QUIT
+
 if [ -n "$LogView" ]; then
+	Logger info "Attempting to view Cito log file"
 	LogTypeChk "$LogView" $LogTypes
 
 	if [ -f "$EventLog" ]; then
+		Logger info "Viewing Cito log file"
 		while IFS=':' read Epoch Type MSG; do
 			ShowLog(){
 				FTime=`date '+%F %X' --date="@$Epoch"`
@@ -180,12 +235,10 @@ if [ -n "$LogView" ]; then
 	fi
 fi
 
-for CurFile in "$@"; do
-	Logger info "Processing '$CurFile'"
-
+ReadFile(){
 	while read F1 _; do
 		if [ "$F1" = '#cito' ]; then
-			Logger info "File '$CurFile' is supported by Cito"
+			Logger info "File '$1' is supported by Cito"
 
 			HasCito='true'
 
@@ -193,78 +246,122 @@ for CurFile in "$@"; do
 				case $CurField in
 					M:*)
 						Mode=${CurField#*:}
-
-						LogErrInf "$Mode" Mode "$CurFile" ;;
+						LogErrInf "$Mode" Mode "$1" ;;
 					O:*)
 						Owner=${CurField#*:}
-
-						LogErrInf "$Owner" Owner "$CurFile" ;;
+						LogErrInf "$Owner" Owner "$1" ;;
 					G:*)
 						Group=${CurField#*:}
-
-						LogErrInf "$Group" Group "$CurFile" ;;
+						LogErrInf "$Group" Group "$1" ;;
 					T:*)
 						Target=${CurField#*:}
-
-						LogErrInf "$Target" Target "$CurFile"
-
-						if [ -f "$Target" ]; then
-							Logger warning "File '$CurFile' in '${Target%/*}' already exists"
-
-							printf "File '%s' already exists.\n" "$Target" 1>&2
-							FilesToRemove=" $FilesToRemove $Target "
-							continue 2
-						fi ;;
+						LogErrInf "$Target" Target "$1"
+						[ -f "$Target" ] && IsFound='true' ;;
 					*)
-						Logger error "Field '$CurField' in '$CurFile' is invalid"
-						Err 0 "File '$CurFile' contains an invalid field."
+						Logger error "Field '$CurField' in '$1' is invalid"
+						Err 0 "File '$1' contains an invalid field."
+						break 2
 				esac
 			done
 
-			break
+			break 1
 		fi
-	done < "$CurFile"
+	done < "$1"
 
-	if ! [ "$HasCito" = 'true' ]; then
-		Logger error "File '$CurFile' is NOT supported by Cito"
-		Err 0 "File '$CurFile' is not supported by Cito."
-		continue
-	else
-		URL="$RawDomain/$GHUser/$Repo/$Branch/source/$CurFile"
-		Logger info "URL for '$CurFile' is '$URL'"
-		if $DLCMD "$Target" "$URL" 1> /dev/null; then
-			if chown $Owner:$Group "$Target" 1> /dev/null; then
-				Logger info "Successfully changed '$Target' to '$Owner:$Group'"
-			else
-				Logger error "Failed to change '$Target' to '$Owner:$Group'"
-			fi
-
-			if chmod $Mode "$Target" 1> /dev/null; then
-				Logger info "Successfully changed '$Target' to '$Mode'"
-			else
-				Logger error "Failed to change '$Target' to '$Mode'"
-			fi
-		else
-			Logger error "File '$CurFile' failed to download with '${DLCMD%% *}'"
-			Err 0 "File '$CurFile' failed to install."
-		fi
+	if [ "$IsFound" = 'true' ]; then
+		AskRemove "$Target"
+		exit 0
 	fi
+}
 
-	Logger info "Finished processing '$CurFile'"
+DoChown(){ # Usage: DoChown [OWNER:GROUP] [TARGET]
+	if chown "${1:-0:0}" "$2" 1> /dev/null; then
+		Logger info "Successfully changed '$2' to '$1'"
+	else
+		Logger error "Failed to change '$2' to '$1'"
+	fi
+}
 
-	unset HasCito Target Group Owner Mode CurField URL
-done
+DoChmod(){ # Usage: DoChmod [MODE] [TARGET]
+	if chmod "${1:-600}" "$2" 1> /dev/null; then
+		Logger info "Successfully changed '$2' to '$1'"
+	else
+		Logger error "Failed to change '$2' to '$1'"
+	fi
+}
 
-for CurFile in $FilesToRemove; do
-	if YNInput "Remove '$CurFile' file?"; then
-		Logger info "Removing pre-existing file '$CurFile'"
-		if rm -f "$CurFile" 1> /dev/null; then
-			Logger info "Removed pre-existing file '$CurFile'"
+AskRemove(){
+	Logger warning "File '$1' in '${1%/*}' already exists"
+
+	printf "File '%s' found.\n" "$1" 1>&2
+	if YNInput 'Remove the file?'; then
+		Logger info "Removing pre-existing file '$1'"
+
+		if rm -f "$1" 1> /dev/null; then
+			Logger info "Removed pre-existing file '$1'"
 		else
-			Logger error "Failed to remove pre-existing file '$CurFile'"
-			Err 1 "Unable to remove '$CurFile' file."
+			Logger error "Failed to remove pre-existing file '$1'"
+			Err 1 "Unable to remove '$1' file."
 		fi
 	else
-		Logger info "NOT removing pre-existing file '$CurFile'"
+		Logger info "NOT removing pre-existing file '$1'"
 	fi
-done
+}
+
+if [ "$DoRemote" = 'true' ]; then
+	Logger info "Beginning remote operation"
+
+	URL="$RawDomain/$GHUser/$Repo/$Branch/${RemoteFile#/}"
+	Logger info "URL for '$RemoteFile' is '${URL#https://*/}'"
+
+	echo "if $DLCMD \"$TemRemFile\" \"$URL\" 1> /dev/null; then"
+	if $DLCMD "$TemRemFile" "$URL" 1> /dev/null; then
+		ReadFile "$TemRemFile"
+
+		DoChown "$Owner:$Group" "$TemRemFile"
+		DoChmod "$Mode" "$TemRemFile"
+
+		if mv "$TemRemFile" "$Target" 1> /dev/null; then
+			Logger info "File '$TemRemFile' moved to '$Target'"
+		else
+			Logger error "File '$CurFile' failed to move to '$Target'"
+		fi
+	else
+		Logger error "File '$RemoteFile' failed to download with '${DLCMD%% *}'"
+		Err 0 "Remote file '$RemoteFile' failed to install."
+	fi
+elif [ $# -gt 0 ]; then
+	Logger info "Beginning local operation"
+
+	for CurFile in "$@"; do
+		Logger info "Processing '$CurFile'"
+
+		if ! [ -f "$CurFile" ] || ! [ -r "$CurFile" ]; then
+			Logger error "File '$CurFile' not found or has no read access"
+			Err 1 "File '$CurFile' missing or unreadable."
+		fi
+
+		ReadFile "$CurFile"
+
+		if ! [ "$HasCito" = 'true' ]; then
+			Logger error "File '$CurFile' is NOT supported by Cito"
+			Err 0 "File '$CurFile' is not supported by Cito."
+			continue
+		else
+			if mv "$CurFile" "$Target" 1> /dev/null; then
+				Logger info "File '$CurFile' moved to '$Target'"
+				DoChown "$Owner:$Group" "$Target"
+				DoChmod "$Mode" "$Target"
+			else
+				Logger error "File '$CurFile' failed to move to '$Target'"
+				Err 0 "Local file '$CurFile' failed to install."
+			fi
+		fi
+
+		Logger info "Finished processing '$CurFile'"
+
+		unset HasCito Target Group Owner Mode CurField
+	done
+else
+	printf "Nothing to do -- quitting.\n"
+fi
