Fully implement Cito's `md5sum` checks
This now works!

Changes:

  * If local file and hash file used, changes to hash file's directory.

  * Additional logging lines relating to the hash checking.

  * More errors will now be caught and/or handled.

diff --git a/source/cito b/source/cito
--- a/source/cito
+++ b/source/cito
@@ -3,7 +3,7 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/source/cito
 # Started On        - Thu  5 Dec 20:40:35 GMT 2019
-# Last Change       - Sat  7 Dec 00:53:03 GMT 2019
+# Last Change       - Sat  7 Dec 02:22:48 GMT 2019
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
@@ -138,20 +138,65 @@ fi
 TemRemFile=`mktemp`
 HashFile=`mktemp`
 
-ChkMD5(){
-	MD5URL="$RawDomain/$GHUser/$Repo/$1"
-	$DLCMD "$HashFile" "$MD5URL" 1> /dev/null 2>&1
+ChkMD5(){ # Usage: ChkMD5 [FILE]
+	# Skip, but stay zero to continue with the file.
+	[ -z "$MD5File" ] && return 0
 
-	while read Hash File; do
-		if [ "$File" = "$1" ]; then
-			GetHash=`CutStr ' ' 1 "$(md5sum "$1")"`
-			if ! [ "$Hash" = "$GetHash" ]; then
-				Err 1 "MD5 for '$1' mis-match!"
-			fi
+	if [ "$DoRemote" = 'true' ]; then
+		MD5URL="$RawDomain/$GHUser/$Repo/$Branch/$MD5File"
+		$DLCMD "$HashFile" "$MD5URL" 1> /dev/null 2>&1
+
+		# Use the temporary file taken remotely.
+		ReadHashFile=$HashFile
+	else
+		# If it's local, change to whichever directory the hash file is in. This is
+		# required, to avoid the issue of the sum file using relative paths not
+		# matching up to where the user currently is, despite the file existing.
+		if ! cd "${MD5File%/*}"; then
+			Logger error "Failed to 'cd' into '${MD5File%/*}'"
+			Err 1 'Failed to change to hash directory.'
 		fi
-	done < "$HashFile"
 
-	unset MD5URL Hash File GetHash
+		# Assume the user provided a local hash file.
+		ReadHashFile=${MD5File##*/}
+	fi
+
+	if ! [ -f "$1" ]; then
+		Logger error "File '$1' not found or has no read access"
+		Err 1 "File '$1' missing or unreadable."
+	fi
+
+	if [ -f "$ReadHashFile" ]; then
+		while read Hash File; do
+			if [ "$File" = "$1" ]; then
+				GetHash=`CutStr ' ' 1 "$(md5sum "$1" 2> /dev/null)"`
+
+				# Gets around weird trailing space.
+				GetHash=${GetHash% }
+
+				Logger info "New MD5 for '$1' is '$GetHash'"
+				Logger info "Old MD5 for '$1' is '$Hash'"
+
+				if ! [ "$Hash" = "$GetHash" ]; then
+					Logger error "MD5 mis-match for file '$1'"
+					Err 0 "MD5 for '$1' mis-match!"
+					return 1
+				fi
+
+				FoundHash='true'
+				break
+			fi
+		done < "$ReadHashFile"
+
+		if ! [ "$FoundHash" = 'true' ]; then
+			Logger error "Old MD5 hash missing for '$1'"
+			Err 1 "File '$1' missing from provided hash file."
+		fi
+	else
+		Err 1 "Hash file '$ReadHashFile' missing."
+	fi
+
+	unset MD5URL Hash File GetHash ReadHashFile FoundHash
 }
 
 Logger(){ # Usage: Logger TYPE MESSAGE
@@ -325,15 +370,17 @@ if [ "$DoRemote" = 'true' ]; then
 	Logger info "URL for '$RemoteFile' is '${URL#https://*/}'"
 
 	if $DLCMD "$TemRemFile" "$URL" 1> /dev/null; then
-		ReadFile "$TemRemFile"
+		if ChkMD5 "$RemoteFile"; then
+			ReadFile "$TemRemFile"
 
-		DoChown "$Owner:$Group" "$TemRemFile"
-		DoChmod "$Mode" "$TemRemFile"
+			DoChown "$Owner:$Group" "$TemRemFile"
+			DoChmod "$Mode" "$TemRemFile"
 
-		if mv "$TemRemFile" "$Target" 1> /dev/null; then
-			Logger info "File '$TemRemFile' moved to '$Target'"
-		else
-			Logger error "File '$CurFile' failed to move to '$Target'"
+			if mv "$TemRemFile" "$Target" 1> /dev/null; then
+				Logger info "File '$TemRemFile' moved to '$Target'"
+			else
+				Logger error "File '$CurFile' failed to move to '$Target'"
+			fi
 		fi
 	else
 		Logger error "File '$RemoteFile' failed to download with '${DLCMD%% *}'"
@@ -345,25 +392,22 @@ elif [ $# -gt 0 ]; then
 	for CurFile in "$@"; do
 		Logger info "Processing '$CurFile'"
 
-		if ! [ -f "$CurFile" ] || ! [ -r "$CurFile" ]; then
-			Logger error "File '$CurFile' not found or has no read access"
-			Err 1 "File '$CurFile' missing or unreadable."
-		fi
+		if ChkMD5 "$CurFile"; then
+			ReadFile "$CurFile"
 
-		ReadFile "$CurFile"
-
-		if ! [ "$HasCito" = 'true' ]; then
-			Logger error "File '$CurFile' is NOT supported by Cito"
-			Err 0 "File '$CurFile' is not supported by Cito."
-			continue
-		else
-			if mv "$CurFile" "$Target" 1> /dev/null; then
-				Logger info "File '$CurFile' moved to '$Target'"
-				DoChown "$Owner:$Group" "$Target"
-				DoChmod "$Mode" "$Target"
+			if ! [ "$HasCito" = 'true' ]; then
+				Logger error "File '$CurFile' is NOT supported by Cito"
+				Err 0 "File '$CurFile' is not supported by Cito."
+				continue
 			else
-				Logger error "File '$CurFile' failed to move to '$Target'"
-				Err 0 "Local file '$CurFile' failed to install."
+				if mv "$CurFile" "$Target" 1> /dev/null; then
+					Logger info "File '$CurFile' moved to '$Target'"
+					DoChown "$Owner:$Group" "$Target"
+					DoChmod "$Mode" "$Target"
+				else
+					Logger error "File '$CurFile' failed to move to '$Target'"
+					Err 0 "Local file '$CurFile' failed to install."
+				fi
 			fi
 		fi
 
