Improve syntax of dlclecs

diff --git a/source/dlclecs b/source/dlclecs
--- a/source/dlclecs
+++ b/source/dlclecs
@@ -1,47 +1,46 @@
 #!/bin/sh
 
-#----------------------------------------------------------------------------------
+#------------------------------------------------------------------------------
 # Project Name      - Extra/source/dlclecs
 # Started On        - Tue 19 Sep 13:00:16 BST 2017
-# Last Change       - Thu  9 May 00:54:07 BST 2019
+# Last Change       - Sat  5 Jun 19:42:03 BST 2021
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
-#----------------------------------------------------------------------------------
-# With this small shell program you can download some C programming teaching files.
-#----------------------------------------------------------------------------------
+#------------------------------------------------------------------------------
+# Downloader for various C programming teaching files.
+#------------------------------------------------------------------------------
 
-XERR(){ echo "ERROR: $1" 1>&2; exit 1; }
-ERR(){ echo "ERROR: $1" 1>&2; }
+Err(){
+	printf 'ERROR: %s\n' "$2" 1>&2
+	[ $1 -gt 0 ] && exit $1
+}
 
-DEPCOUNT=0
-for DEP in /usr/bin/id /usr/bin/basename /bin/grep /usr/bin/wget; do
-	[ -x "$DEP" ] || {
-		ERR "Dependency '$DEP' not met."
-		DEPCOUNT=$(( DEPCOUNT + 1 ))
-	}
+DepCount=0
+for CurDep in id basename grep wget; do
+	if ! command -V "$CurDep" 1> /dev/null 2>&1; then
+		Err 0 "Dependency '$CurDep' not met."
+		DepCount=$((DepCount + 1))
+	fi
 done
 
-[ $DEPCOUNT -eq 0 ] || exit 1
+[ $DepCount -eq 0 ] || exit 1
 
-[ `/usr/bin/id -u` -eq 0 ] && XERR "Root access isn't required."
+[ `id -u` -eq 0 ] && Err 1 "Root access isn't required."
 
-DOMAIN="https://ocw.mit.edu"
-CATEGORY="electrical-engineering-and-computer-science"
-COURSE="6-087-practical-programming-in-c-january-iap-2010"
-URL1="/courses/$CATEGORY/$COURSE/lecture-notes/"
-GREP_REGEX="${URL1}MIT6_087IAP10_lec"
+Domain="https://ocw.mit.edu"
+Category="electrical-engineering-and-computer-science"
+Course="6-087-practical-programming-in-c-january-iap-2010"
+URL1="/courses/$Category/$Course/lecture-notes/"
+GrepRegex="${URL1}MIT6_087IAP10_lec"
 
-DLINKS=$(
-	/usr/bin/wget -q "$DOMAIN/$URL1" -O -\
-		| /bin/grep -o "${GREP_REGEX}[0-9]\+.pdf"
-)
+DownloadLinks=`wget -qO - "$Domain/$URL1" | grep -o "${GrepRegex}[0-9]\+.pdf"`
 
-for FILE in $DLINKS; do
-	FILENAME=`/usr/bin/basename $FILE`
-
-	/usr/bin/wget -q "${DOMAIN}${FILE}" && {
-		echo "FILE: $FILENAME"
-	} || {
-		XERR "$FILENAME"
-	}
+for File in $DownloadLinks; do
+	FileName=`basename $File`
+	if wget -q "${Domain}${File}"; then
+		printf 'File: %s\n' "$FileName"
+	else
+		#TODO: Use proper error message.
+		Err 1 "$FileName"
+	fi
 done
