Update DWW Downloader (dwwdl)

diff --git a/source/dwwdl b/source/dwwdl
--- a/source/dwwdl
+++ b/source/dwwdl
@@ -1,145 +1,138 @@
-#!/bin/bash
-
-#----------------------------------------------------------------------------------
-# Project Name      - Extra/source/dwwdl (Distrowatch Weekly Downloader)
+#!/usr/bin/env bash
+#cito M:755 O:0 G:0 T:/usr/bin/dwwdl
+#------------------------------------------------------------------------------
+# Project Name      - Extra/source/dwwdl
 # Started On        - Sat 16 Sep 22:41:54 BST 2017
-# Last Change       - Wed 27 Nov 15:54:07 GMT 2019
+# Last Change       - Sun 17 Jan 01:04:27 GMT 2021
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
-#----------------------------------------------------------------------------------
+#------------------------------------------------------------------------------
+# DistroWatch Weekly Downloader.
+#
+# Dependencies:
+#
+#   bash (>= 4.4.18-2)
+#   coreutils (>= 8.25-2)
+#   wget (>= 1.19.4-1)
+#------------------------------------------------------------------------------
 
-_VERSION_="2019-11-27"
-_PROJECT_=${0##*/}
+CurVer='2021-01-17'
+Progrm=${0##*/}
 
-Err(){
-	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
-	[ $1 -eq 1 ] && exit 1
-}
-
-DLURL="http://distrowatch.com/podcast/dww"
-
-USAGE(){
+Usage(){
 	while read; do
-		printf "%s\n" "$REPLY"
+		printf '%s\n' "$REPLY"
 	done <<-EOF
-		            ${_PROJECT_^^} - Distrowatch Weekly Downloader ($_VERSION_)
-		            Written by terminalforlife <terminalforlife@yahoo.com>
+		Usage: $Progrm [OPTS]
 
-		            Download all of the available DistroWatch Weekly podcasts.
+		  -h, --help               - Displays this help information.
+		  -v, --version            - Output only the version datestamp.
+		  --quiet-sleep            - Omit the sleep messages, if being kind.
+		  --server-kind            - Use a random interval between downloads.
+		  --show-progress          - Display the WGet download progress bar.
+		  -S, --shutdown           - Shut system down after $Progrm finishes.
+		  -d, --date [YYYYMMDD]    - Specify the podcast to download, by date.
+		  -i, --interval [N]       - Use a specific interval between downloads.
+		  -s, --suspend            - Suspend system after $Progrm finishes.
+		  -t, --type [OGG|MP3]     - Use file type of either 'OGG' or 'MP3'.
 
-		SYNTAX:     $_PROJECT_ [OPTS]
+		  All podcasts will be downloaded to the current working directory and
+		  are from newest to oldest, unless a date is specified.
 
-		OPTS:       --help|-h|-?            - Displays this help information.
-		            --version|-v            - Output only the version datestamp.
-		            --server-kind           - A random number of seconds from 1-9 between
-		                                      each image. An 'interval' also occurs for
-		                                      every set of images, in minutes.
-		            --interval|-i N         - Default value is set to 10. Error if missing
-		                                      the above flag. Where N is an integer(s).
-		                                      If N is '0', it will disable the feature.
-		            --show-progress         - Output the wget 'bar' type progress.
-		            --type|-t X             - Where X is the file type; either mp3 or ogg.
-		            --date|-d N             - Where n is the number which corrosponds to
-		                                      the date of the podcast you want to download.
-		                                      An example of n would be 20170804.
-		            --quiet-sleep           - Prevents the display of the sleep messages.
-		                                      Only applicable if --server-kind is used.
-		            --suspend|-s            - Suspend the system after $_PROJECT_ finishes.
-		            --shutdown|-S           - Shut the system down after $_PROJECT_ finishes.
-
-		NOTE:       All podcasts will be downloaded to the current working directory and
-		            are from newest to oldest, unless --date=n is used.
-
-		            Entries older than 20050822 were before DWW podcasts were available.
-
-		SITE:       ${DLURL%/podcast/*}
+		  Entries older than 20050822 were before DWW podcasts were available.
 	EOF
 }
 
-SERVER_KIND='false'
-SLEEP_S=9
-INTERVAL=10
-EXT="ogg"
+Err(){
+	printf 'ERROR: %s\n' "$2" 1>&2
+	[ $1 -gt 0 ] && exit $1
+}
+
+ServerKind='false'
+Interval=10
+Extension='ogg'
+
+DownloadURL="http://distrowatch.com/podcast/dww"
 
 while [ "$1" ]; do
 	case $1 in
 		--help|-h|-\?)
-			USAGE; exit 0 ;;
+			Usage; exit 0 ;;
 		--version|-v)
-			printf "%s\n" "$_VERSION_"; exit 0 ;;
+			printf "%s\n" "$CurVer"; exit 0 ;;
 		--server-kind)
-			SERVER_KIND='true' ;;
+			ServerKind='true' ;;
 		--interval|-i)
 			shift
 
-			if [[ $1 =~ [0-9]+ ]]; then
-				INTERVAL=$1
+			if [[ $1 =~ ^[0-9]+$ ]]; then
+				Interval=$1
 			else
-				Err 1 $LINENO "Incorrect interval."
+				Err 1 "Incorrect interval."
 			fi ;;
 		--quiet-sleep)
-			QUIET_SLEEP='true' ;;
+			QuietSleep='true' ;;
 		--show-progress)
-			PROGRESS="--show-progress" ;;
+			ProgressBar="--show-progress" ;;
 		--type|-t)
 			shift
 
-			if [[ $1 =~ ^(mp3|ogg)$ ]]; then
-				EXT=$1
+			if [ "$1" == 'MP3' ] || [ "$1" == 'OGG' ]; then
+				Extension=${1,,}
 			else
-				Err 1 $LINENO "Incorrect file type selected."
+				Err 1 "Incorrect file type selected."
 			fi ;;
 		--date|-d)
 			shift
 
 			if [[ $1 =~ ^[0-9]{8} ]]; then
-				PODS+=" $1"
+				Podcasts+=" $1"
 			else
-				Err 1 $LINENO "Incorrect podcast date provided."
+				Err 1 "Incorrect podcast date provided."
 			fi ;;
 		--suspend|-s)
-			SUSPEND='true'
-			if ! type -P systemctl > /dev/null 2>&1; then
-				Err 1 $LINENO "Dependency 'systemctl' not met."
+			Suspend='true'
+
+			if ! type -P systemctl &> /dev/null; then
+				Err 1 "Dependency 'systemctl' not met."
 			fi ;;
 		--shutdown|-S)
-			SHUTDOWN='true'
-			if ! type -P shutdown > /dev/null 2>&1; then
-				Err 1 $LINENO "Dependency 'shutdown' not met."
+			Shutdown='true'
+
+			if ! type -P shutdown &> /dev/null; then
+				Err 1 "Dependency 'shutdown' not met."
 			fi ;;
 		*)
-			break ;;
+			Err 1 'Incorrect option(s) specified.' ;;
 	esac
 	shift
 done
 
-declare -i DEPCOUNT=0
+DepCount=0
 for DEP in wget sync sleep; {
-	if ! type -P "$DEP" > /dev/null 2>&1; then
-		Err 0 $LINENO "Dependency '$DEP' not met."
-		DEPCOUNT+=1
+	if ! type -P "$DEP" &> /dev/null; then
+		Err 0 "Dependency '$DEP' not met."
+		let DepCount+=1
 	fi
 }
 
-[ $DEPCOUNT -gt 0 ] && exit 1
+[ $DepCount -gt 0 ] && exit 1
 
-[ "$*" ] && Err 1 $LINENO "Incorrect argument(s) detected."
-
-if ! [ "$SERVER_KIND" == 'true' ]; then
-	if [ "$QUIET_SLEEP" == 'true' -o ! "$INTERVAL" -eq 10 ]; then
-		Err 1 $LINENO "Expecting '--server-kind' argument."
+if ! [ "$ServerKind" == 'true' ]; then
+	if [ "$QuietSleep" == 'true' -o ! "$Interval" -eq 10 ]; then
+		Err 1 "Expecting '--server-kind' argument."
 	fi
 fi
 
-declare -i TIME_COUNT=0
+declare -i TimeCount=0
 
-if ! [ "$PODS" ]; then
+if [ -z "$Podcasts" ]; then
 	#TODO: See about adding $OLDTONEW functionality here with pure shell.
-	PODS=$(
+	Podcasts=$(
 		LINK="http://distrowatch.com/weekly.php?issue=1"
 
-		while read -ra X; do
-			for A in ${X[@]}; {
+		while read -ra Line; do
+			for A in ${Line[@]}; {
 				if [[ $A == *\?issue\=* ]]; then
 					printf "%s\n" ${A//[!0-9]/}
 				fi
@@ -148,57 +141,56 @@ if ! [ "$PODS" ]; then
 	)
 fi
 
-DLURL="http://distrowatch.com/podcast/dww"
+DownloadURL='http://distrowatch.com/podcast/dww'
 
-for DATE in $PODS; {
-	[ $DATE -lt 20050822 ] && continue
+for Date in $Podcasts; {
+	[ $Date -lt 20050822 ] && continue
 
-	[ "$PROGRESS" ] || printf "PODCAST: %s\n" "$DATE"
+	[ "$ProgressBar" ] || printf "PODCAST: %s\n" "$Date"
 
-	if [ "$SERVER_KIND" == 'true' -a ! -f "${DL_LINK//*\/}" ]; then
-		TIME_COUNT+=1; printf -v RAND "%0.5d" "$RANDOM"
-		if ! [ "$QUIET_SLEEP" == 'true' ]; then
-			printf "Sleeping for %d second(s)...\n" "${RAND/????}"
+	if [ "$ServerKind" == 'true' -a ! -f "${DL_LINK//*\/}" ]; then
+		TimeCount+=1; printf -v RandomNumber "%0.5d" "$RANDOM"
+		if ! [ "$QuietSleep" == 'true' ]; then
+			printf "Sleeping for %d second(s)...\n" "${RandomNumber/????}"
 		fi
 
-		sleep ${RAND/????}s
+		sleep ${RandomNumber/????}s
 
-		if [ $INTERVAL -eq 0 -a $TIME_COUNT -eq $INTERVAL ]; then
-			printf -v RAND "%0.5d" "$RANDOM"
+		if [ $Interval -eq 0 -a $TimeCount -eq $Interval ]; then
+			printf -v RandomNumber "%0.5d" "$RANDOM"
 
-			if ! [ "$QUIET_SLEEP" == 'true' ]; then
+			if ! [ "$QuietSleep" == 'true' ]; then
 				printf "Sleeping for %d minute(s)...\n"\
-					"${RAND/????}"
+					"${RandomNumber/????}"
 			fi
 
-			sleep ${RAND/????}m
-			TIME_COUNT=0
+			sleep ${RandomNumber/????}m
+			TimeCount=0
 		fi
 	fi
 
-	if ! wget -cq --no-cookies $PROGRESS ${DLURL}${DATE}.${EXT}; then
-		Err 0 $LINENO "Podcast '$DATE' failed."
+	if ! wget -cq --no-cookies $ProgressBar $DownloadURL$Date.$Extension; then
+		Err 0 "Podcast '$Date' failed."
 	fi
 }
 
-if [ "$SHUTDOWN" == 'true' ]; then
-	shutdown +3 &> /dev/null
+if [ "$Shutdown" == 'true' ]; then
+	shutdown '+3' &> /dev/null
 	printf "%s\n" "Shutting down in 3 minutes..."
-	read -n 1 -e -p "Type 'C' to cancel, or 'N' to shutdown now: " SHUTDOWN_PROMPT
+	read -n 1 -ep "Type 'C' to cancel, or 'N' to shutdown now: "
 
-	case ${SHUTDOWN_PROMPT:-EMPTY} in
+	case ${REPLY:-EMPTY} in
 		[Cc])
 			shutdown --no-wall -c
 			exit 0 ;;
 		[Nn])
 			shutdown --no-wall now ;;
 		EMPTY|*)
-			Err 1 $LINENO "Invalid response -- quitting." ;;
+			Err 1 "Invalid response -- quitting." ;;
 	esac
-elif [ "$SUSPEND" == 'true' ]; then
+elif [ "$Suspend" == 'true' ]; then
 	sync
-	printf "%s\n" "System will suspend in 3s; type Ctrl+C to cancel and quit $_PROJECT_."
+	printf 'System will suspend in 3s! Ctrl + C to cancel.\n'
 	sleep 3
 	systemctl suspend
 fi
-
