Make fbdriver a bit more robust
This requires user intervention if you want to check for other values.
Or let me know and I'll add them in and push the changes.

diff --git a/source/fbdriver b/source/fbdriver
--- a/source/fbdriver
+++ b/source/fbdriver
@@ -3,7 +3,7 @@
 #------------------------------------------------------------------------------
 # Project Name      - Extra/source/fbdriver
 # Started On        - Thu 10 Dec 14:59:18 GMT 2020
-# Last Change       - Thu 10 Dec 15:01:16 GMT 2020
+# Last Change       - Thu 10 Dec 19:44:25 GMT 2020
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
@@ -12,14 +12,26 @@
 #   https://forums.linuxmint.com/viewtopic.php?f=213&t=337105
 #------------------------------------------------------------------------------
 
+Err(){
+	printf 'ERROR: %s\n' "$2" 1>&2
+	[ $1 -gt 0 ] && exit $1
+}
+
 UEventFile='/sys/class/graphics/fb0/device/uevent'
-if type -P lshw &> /dev/null; then
+if [ -f "$UEventFile" -a -r "$UEventFile" ]; then
+	while IFS='=' read -a Line; do
+		if [ "${Line[0]}" == 'DRIVER' ]; then
+			Driver=${Line[1]}
+			break
+		fi
+	done < "$UEventFile"
+elif type -P lshw &> /dev/null; then
 	while IFS=':' read -a Line; do
 		if [ "${Line[0]// /}" == 'configuration' ]; then
 			for Field in ${Line[1]}; {
 				IFS='=' read -a KeyVal <<< "$Field"
 				if [ "${KeyVal[0]}" == 'driver' ]; then
-					printf '%s\n' "${KeyVal[1]}"
+					Driver=${KeyVal[1]}
 					break
 				fi
 			}
@@ -27,13 +39,16 @@ if type -P lshw &> /dev/null; then
 			break
 		fi
 	done <<< "$(lshw -c video 2> /dev/null)"
-elif [ -f "$UEventFile" -a -r "$UEventFile" ]; then
-	while IFS='=' read -a Line; do
-		if [ "${Line[0]}" == 'DRIVER' ]; then
-			printf '%s\n' "${Line[1]}"
-			break
-		fi
-	done < "$UEventFile"
-else
-	exit 1
 fi
+
+case $Driver in
+	nvidia|amd|nouveau)
+		# I have no idea what all the possible values are, so add as needed.
+		printf '%s\n' "$Driver" ;;
+	'')
+		Err 1 'Unable to determine display driver.' ;;
+	*)
+		# You could replace 'Unrecognised' with 'Unsupported' if that's your
+		# goal from this functionality.
+		Err 1 "Unrecognised '$Driver' display driver." ;;
+esac
