Improve page handling, fix bugs, & add features
* Allow partially running FreeLFM without specifying pages.

  This allows the user to see first how many pages were found. Nothing
  really happens still, except the initial site page (1) will be still
  be parsed.

* Display any and all page check errors before quitting.

  Quitting after every single page error is as much an oversight as
  quitting after every single missing dependency error. Showing all
  errors first allows the user to immediately and easily spot issues.

* Final message shows how many tracks, of those found, were downloaded.

  This might help users who're not quite sure what happened, or want
  a general idea of how successful the operation was. Do expect at
  least 25 not to be downloaded (skipped), due to decoding issues.

* Use POSIX character classes for digit checks to avoid locale issues.
* Accept page ranges, such as `1-4`.

  This is quite robust, so you won't be able to enter weird things, -
  like `4-2`, which would make no sense. Multiple ranges can be
  provided at once.

* When listing or downloading, handle pages in ascending order.
* Sorting moved to `SortInt()` which uses a name reference.
* Sorting automatically removes duplicate numbers from the array.

  This mainly prevents users accessing the same pages multiple times.

* Moved `TrackURLs=()` to correct place, fixing first page only bug.

  Previously, only the first page would be handled, because the array
  was being mistakenly wiped.

* Tracks with seemingly undecodable filenames are ignored.

  This currently only amounts to 25, still leaving 202 tracks. This has
  been explained ad nauseam via comments in the code itself.

* Filenames now more consistently titled.

diff --git a/source/freelfm b/source/freelfm
--- a/source/freelfm
+++ b/source/freelfm
@@ -3,13 +3,14 @@
 #------------------------------------------------------------------------------
 # Project Name      - Extra/source/freelfm
 # Started On        - Fri 15 Sep 21:19:42 BST 2017
-# Last Change       - Fri 12 May 23:07:27 BST 2023
+# Last Change       - Sat 13 May 03:03:02 BST 2023
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
 # Download last.fm's free music into the current working directory.
 #
-# 2023-05-12: Currently 12 pages holding 220+ MP3 tracks.
+# 2023-05-12: Currently 12 pages holding 202+ MP3 tracks, with 25 being ignored
+#             because of URL decoding issues due to some non-English text.
 #
 # Downloaded tracks will not clobber those partially-downloaded.
 #
@@ -21,11 +22,10 @@
 # Features:
 #
 #TODO: Add a target directory flag.
-#TODO: Provide range feature as an argument. Like `freelfm 2-7`. Think WCDL.
 #
 # Bugs:
 #
-#TODO: Multiple duplicate pages can be provided by the user -- handle this.
+#TODO: `printf` in `DecodeURL()` fails with some non-English characters.
 #
 # Dependencies:
 #
@@ -33,7 +33,7 @@
 #   wget (>= 1.17.1-1)
 #------------------------------------------------------------------------------
 
-CurVer='2023-05-12'
+CurVer='2023-05-13'
 Progrm=${0##*/}
 
 Usage() {
@@ -96,8 +96,6 @@ for CurDep in wget sleep systemctl; {
 
 (( DepCount > 0 )) && exit 1
 
-(( $# == 0 )) && Err 1 "Page number(s) required -- see: $Progrm -h"
-
 #----------------------------------------------------------------Main Functions
 
 # I know this can be done in a simple way using BASH's parameter expansion's
@@ -129,7 +127,13 @@ DecodeURL() {
 			# Note that `printf` will spit out a null value if so-called not
 			# valid. Hence using the character class to check it's actually
 			# printable, vs. just checking the variable is not empty.
-			printf -v HexTest "\x$HexChars"
+			#
+			# If `printf` fails, the filename probably has weird Unicode, that
+			# even with `\u` won't decode properly. Frustrating, but at that
+			# point, just ignore the file to make life easier.
+			if ! printf -v HexTest "\x$HexChars" 2> /dev/null; then
+				return 1
+			fi
 
 			if [[ $HexTest == [[:print:]] ]]; then
 				OutChars+=$HexTest
@@ -148,13 +152,77 @@ DecodeURL() {
 	Return=$OutChars
 }
 
+# Usage: SortInts {<|>} ARRAY
+#
+# Numerically sorts ascending or descending depending on `$1`, and filters out
+# duplicate integers from the array.
+SortInts() {
+	declare -n Arr=$2
+
+	Len=${#Arr[@]}
+	for (( Iter = 0; Iter <= Len; Iter++ )); {
+		Switched='False'
+		for (( Index = 0; Index < Len - (1 + Iter); Index++ )); {
+			if (( ${Arr[Index]} == ${Arr[Index + 1]} )); then
+				Arr=("${Arr[@]:0:Index}" "${Arr[@]:Index + 1:Len - 1}")
+				Len=${#Arr[@]}
+
+				# We don't want to break yet.
+				continue
+			elif (( ${Arr[Index]} $1 ${Arr[Index + 1]} )); then
+				Temp=${Arr[Index]}
+				Arr[Index]=${Arr[Index + 1]}
+				Arr[Index + 1]=$Temp
+
+				Switched='True'
+			fi
+		}
+
+		[[ $Switched == False ]] && break
+	}
+}
+
+# Usage: Title VARIABLE STRING
+#
+# Not an especially hard and fast rule, but it does keep it more in line with
+# a standard UK title in which small prepositions and conjunctions are not
+# capitalised, but everything else is. I'd be more specific, but it'd get silly
+# after a while.
+#
+# The reason for this is because whoever manages the site is inconsistent with
+# their titles, with different styles and some not even being titles at all. To
+# save people's sanity, for those like me that care, I've handled it.
+Title() {
+	declare -n Title=$1
+
+	read -a Fields <<< "$2"
+
+	Out=
+	Len=${#Fields[@]}
+	for (( Index = 0; Index < Len; Index++ )); {
+		Field=${Fields[Index]}
+		case $Field in
+			the|or|of|in|for|to|on|and|with)
+				if (( Index == 0 )); then
+					Out+="${Field^}"
+				else
+					Out+="$Field"
+				fi ;;
+			*)
+				Out+="${Field^}" ;;
+		esac
+
+		(( Index != Len - 1 )) && Out+=' '
+	}
+
+	Title=$Out
+}
+
 Info() {
 	[[ $LinksOnly == True ]] || printf '%s\n' "$1"
 }
 
 #----------------------------------------------------Determine Valid Page Range
-
-Info 'Looking for available pages.'
 
 # Kinder to the servers if page 1 is later requested.
 Page1Data=`wget -qO - "$PageURL=1"`
@@ -178,52 +246,77 @@ while read; do
 done <<< "$Page1Data"
 
 # Ensure we know the maximum page by sorting.
-Len=${#PagesFound[@]}
-for (( Iter = 0; Iter <= Len; Iter++ )); {
-	Switched='False'
-	for (( Index = 0; Index < Len - (1 + Iter); Index++ )); {
-		if (( ${PagesFound[Index]} < ${PagesFound[Index + 1]} )); then
-			Temp=${PagesFound[Index]}
-			PagesFound[Index]=${PagesFound[Index + 1]}
-			PagesFound[Index + 1]=$Temp
-
-			Switched='True'
-		fi
-	}
-
-	[[ $Switched == False ]] && break
-}
+SortInts '<' PagesFound
 
 PageMax=${PagesFound[0]}
 
 Info "Found $PageMax available page(s)."
 
-#----------------------------------Fetch List of Track URLs Per the Valid Pages
+#-------------------------Validate Target Pages, Handle Ranges, and Sort Result
 
-for PageNr; {
-	if [[ $PageNr != +([0-9]) ]]; then
-		Err 0 "Page number '$PageNr' invalid."
-		continue
-	elif ! (( PageNr >= 1 && PageNr <= PageMax )); then
-		Err 0 "Page number '$PageNr' not found."
+TargetPages=()
+while [[ -n $1 ]]; do
+	if [[ $1 == +([[:digit:]])-+([[:digit:]]) ]]; then
+		Left=${1%-*}
+		Right=${1#*-}
+
+		if (( Left >= Right )); then
+			Err 0 "Page range '$1' invalid."
+			(( PageErrs++ ))
+
+			shift
+			continue
+		fi
+
+		PushArgs=()
+		for (( Nr = Left; Nr <= Right; Nr++ )); {
+			PushArgs+=($Nr)
+		}
+
+		shift
+
+		set -- $* "${PushArgs[@]}"
+
+		# We don't want to `shift` twice, and the below checks will be
+		# performed on the new arguments which were added above.
 		continue
 	fi
 
-	Info "Scanning page $PageNr."
+	if [[ $1 != +([[:digit:]]) ]]; then
+		Err 0 "Page number(s) '$1' invalid."
+		(( PageErrs++ ))
+	elif ! (( $1 >= 1 && $1 <= PageMax )); then
+		Err 0 "Page number '$1' not found."
+		(( PageErrs++ ))
+	else
+		TargetPages+=("$1")
+	fi
 
-	CurPageURL="$PageURL=$PageNr"
+	shift
+done
 
+(( PageErrs > 0 )) && exit 1
+
+if (( ${#TargetPages[@]} == 0 )); then
+	Err 1 "Page number(s) required -- see: $Progrm -h"
+fi
+
+# Sort ascending so we handle pages in order.
+SortInts '>' TargetPages
+
+#------------------------------------------------------Fetch List of Track URLs
+
+TrackURLs=()
+TotalTracksAll=0
+for PageNr in "${TargetPages[@]}"; {
 	if (( PageNr == 1 )); then
 		PageData=$Page1Data
 	else
-		PageData=`wget -qO - "$CurPageURL"`
+		PageData=`wget -qO - "$PageURL=$PageNr"`
 	fi
 
-	Info 'Looking for tracks.'
-
 	# Grab direct download link for each track.
-	TrackURLs=()
-	TrackTotal=0
+	TotalTracksPage=0
 	while read; do
 		if [[ $REPLY == *\"https:*.mp3\"* ]]; then
 			FileURL=${REPLY#*https://}
@@ -231,34 +324,45 @@ for PageNr; {
 			FileURL="https://$FileURL.mp3"
 			TrackURLs+=("$FileURL")
 
-			(( TrackTotal++ ))
+			(( TotalTracksAll++ ))
+			(( TotalTracksPage++ ))
 		fi
 	done <<< "$PageData"
 
-	Info "Found $TrackTotal track(s) on page $PageNr."
+	Info "Found $TotalTracksPage track(s) on page $PageNr."
 }
 
 #-------------------------------------------Begin Downloading or Listing Tracks
 
+SuccessDL=0
+DecodeFails=0
 if [[ $LinksOnly == True ]]; then
 	printf '%s\n' "${TrackURLs[@]}"
 else
 	for TrackURL in "${TrackURLs[@]}"; {
 		TrackName=${TrackURL##*/}
 
-		# Cleanse the filename for our local version.
-		DecodeURL TrackName "$TrackName"
+		# Cleanse the filename for our local version. Skipping undecodable
+		# filenames, at least until a sane solution can be found to include
+		# them. Refer to `DecodeURL()` for more information.
+		if ! DecodeURL TrackName "$TrackName"; then
+			(( DecodeFails++ ))
+
+			continue
+		fi
+
+		Title TrackName "$TrackName"
 
 		Info "Found: ${TrackName%.mp3}"
 		if wget -qc -O ./"$TrackName" "$TrackURL"; then
-			Info 'Download successful.'
+			(( SuccessDL++ ))
 		else
 			Info 'Error(s) detected.'
 		fi
 	}
 fi
 
-Info 'Finished!'
+Info "Finished! Downloaded $SuccessDL/$TotalTracksAll track(s)."
 
 #-------------------------------------------------Power Down or Suspend Machine
 
