Make core-checking a bit more robust in GLKFU

diff --git a/source/glkfu b/source/glkfu
--- a/source/glkfu
+++ b/source/glkfu
@@ -3,7 +3,7 @@
 #------------------------------------------------------------------------------
 # Project Name      - Extra/source/glkfu
 # Started On        - Sun  6 Dec 19:41:35 GMT 2020
-# Last Change       - Tue  8 Dec 03:54:44 GMT 2020
+# Last Change       - Tue  8 Dec 14:51:51 GMT 2020
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
@@ -332,7 +332,14 @@ else
 	TTLCores=`nproc`
 fi
 
-[ -z "$Cores" ] && Cores=$TTLCores
+Cores=$TTLCores
+
+if ! [[ $TTLCores =~ ^[0-9]+$ ]]; then
+	Err 0 'Unable to determine available number of CPU cores.'
+	Ask 'Continue with just the 1 core/thread?'
+
+	Cores=1
+fi
 
 printf 'Using %d/%d available CPU core(s).\n' $Cores $TTLCores
 
