Add `--ignore-versions` option to GLKFU

diff --git a/source/glkfu b/source/glkfu
--- a/source/glkfu
+++ b/source/glkfu
@@ -3,7 +3,7 @@
 #------------------------------------------------------------------------------
 # Project Name      - Extra/source/glkfu
 # Started On        - Sun  6 Dec 19:41:35 GMT 2020
-# Last Change       - Mon  7 Dec 22:05:30 GMT 2020
+# Last Change       - Mon  7 Dec 22:16:50 GMT 2020
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
@@ -44,6 +44,7 @@ Usage(){
 
 		  -h, --help               - Display this help information.
 		  -v, --version            - Output the version datestamp.
+		  --ignore-versions        - Disregard current & new version strings.
 		  -D, --build-dir [PATH]   - Build in PATH instead of CWD.
 		  -O, --override [FILE]    - Use FILE instead of the latest. See below.
 		  -c, --cores [INT]        - Use INT CPU cores (jobs) for make(1).
@@ -124,6 +125,8 @@ while [ "$1" ]; do
 			else
 				Cores=$1
 			fi ;;
+		--ignore-versions)
+			IgnoreVers='True' ;;
 		*)
 			Err 1 'Incorrect option(s) specified.' ;;
 	esac
@@ -220,12 +223,16 @@ CurVer=${Line[2]}
 
 printf 'Current Linux version: %s\n' "$CurVer"
 
-if [[ $CurVer =~ ^[0-9]+\.[0-9]+\.[0-9]+-.* ]]; then
-	printf 'Unable to determine if latest kernel is newer.\n' 1>&2
-	Ask "Continue with $Progrm?" || exit 1
-elif [ ${CurVer//[!0-9]/} -lt ${LatestVer//[!0-9]/} ]; then
-	printf "You're already up-to-date -- nothing to do.\n"
-	exit 0
+if [ "$IgnoreVers" != 'True' ]; then
+	if [[ $CurVer =~ ^[0-9]+\.[0-9]+\.[0-9]+-.* ]]; then
+		printf 'Unable to determine if latest kernel is newer.\n' 1>&2
+		Ask "Continue with $Progrm?" || exit 1
+	elif [ ${CurVer//[!0-9]/} -ge ${LatestVer//[!0-9]/} ]; then
+		printf "You're already up-to-date -- nothing to do.\n"
+		exit 0
+	fi
+else
+	printf 'Ignoring version strings.\n'
 fi
 
 #----------------------------------Look for Compilation & Building Dependencies
