Add CPU core features to make(1) + localmodconfig
GLKFU is now much smarter.

diff --git a/source/glkfu b/source/glkfu
--- a/source/glkfu
+++ b/source/glkfu
@@ -3,7 +3,7 @@
 #------------------------------------------------------------------------------
 # Project Name      - Extra/source/glkfu
 # Started On        - Sun  6 Dec 19:41:35 GMT 2020
-# Last Change       - Mon  7 Dec 16:21:19 GMT 2020
+# Last Change       - Mon  7 Dec 20:50:23 GMT 2020
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
@@ -38,6 +38,7 @@ Usage(){
 		  -v, --version            - Output the version datestamp.
 		  -D, --build-dir [PATH]   - Build in PATH instead of CWD.
 		  -O, --override [FILE]    - Use FILE instead of the latest. See below.
+		  -c, --cores [INT]        - Use INT CPU cores (jobs) for make(1).
 		  -y, --assume-yes         - Assume user answers yes when prompted.
 
 		  When specifying an alternative tarball FILE, ensure that you use the
@@ -47,6 +48,8 @@ Usage(){
 		    '^linux-[0-9]+\\\.[0-9]+\\\.[0-9]+\\\.tar\\\.xz$'
 
 		  Otherwise $Progrm will error out.
+
+		  By default, $Progrm will determine how many cores to use for make(1).
 	EOF
 }
 
@@ -55,7 +58,9 @@ Err(){
 	[ $1 -gt 0 ] && exit $1
 }
 
+Make="make -j ${Cores:-1}"
 VerFile='/proc/version'
+ProcInfoFile='/proc/cpuinfo'
 StatusFile='/var/lib/dpkg/status'
 KernOrg='https://www.kernel.org'
 KernOrgMirrs='https://mirrors.edge.kernel.org'
@@ -101,6 +106,16 @@ while [ "$1" ]; do
 			fi ;;
 		--ignore-deps|-I)
 			IgnoreDeps='True' ;;
+		--cores|-c)
+			shift
+
+			if [ -z "$1" ]; then
+				Err 1 'Unspecified number of cores for make(1) to use.'
+			elif ! [[ $1 =~ ^[0-9]+$ ]]; then
+				Err 1 'Invalid number of cores specified.'
+			else
+				Cores=$1
+			fi ;;
 		*)
 			Err 1 'Incorrect option(s) specified.' ;;
 	esac
@@ -258,6 +273,23 @@ else
 	printf 'Told to ignore dependencies.\n'
 fi
 
+#-----------------------------------------------Determining Number of CPU Cores
+
+if [ -f "$ProcInfoFile" -a -r "$ProcInfoFile" ]; then
+	while read -a Line; do
+		if [ "${Line[0]}${Line[1]}" == 'cpucores' ]; then
+			TTLCores=${Line[3]}
+			break
+		fi
+	done < "$ProcInfoFile"
+else
+	TTLCores=`nproc`
+fi
+
+[ -z "$Cores" ] && Cores=$TTLCores
+
+printf 'Using %d/%d available CPU core(s).\n' $Cores $TTLCores
+
 #---------------------------------Download Applicable Tarball & Verify the File
 
 Ask "Begin downloading '$LatestTar' tarball?" || exit 1
@@ -316,15 +348,30 @@ cp -v "${Top%=*}" "$BuildDir/${LatestTar%.tar.xz}/.config"
 cd "$BuildDir/${LatestTar%.tar.xz}"
 
 if Ask 'Use default values for new CONFIG parameters?'; then
-	make olddefconfig
+	$Make olddefconfig
 else
-	make silentoldconfig
+	$Make silentoldconfig
+fi
+
+if Ask 'Strip unneeded modules for the current system?'; then
+	$Make localmodconfig
+	Exit=$?
+
+	if [ $Exit -gt 1 ]; then
+		Err 0 'Unexpected (non-zero) exit by make(1).'
+		printf 'NOTE: You may need to start again.\n'
+		exit $Exit
+	fi
 fi
 
 #---------------------------------------Begin Compiling and Building the Kernel
 
 printf 'Attempting to compile kernel & build Debian packages...\n'
-make deb-pkg || exit $?
+$Make deb-pkg || exit $?
+
+if [ $? -gt 0 ]; then
+	Err 1 'Non-zero exit status detected by make(1).'
+fi
 
 #-----------------------------------------------------------------------Cleanup
 
