Del source files at end & show version b4 prompt

diff --git a/source/glkfu b/source/glkfu
--- a/source/glkfu
+++ b/source/glkfu
@@ -3,7 +3,7 @@
 #------------------------------------------------------------------------------
 # Project Name      - Extra/source/glkfu
 # Started On        - Sun  6 Dec 19:41:35 GMT 2020
-# Last Change       - Mon  7 Dec 04:07:56 GMT 2020
+# Last Change       - Mon  7 Dec 16:21:19 GMT 2020
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
@@ -108,7 +108,7 @@ while [ "$1" ]; do
 done
 
 DepCount=0
-for Dep in make tar rm cp sha256sum; do
+for Dep in sync make tar rm cp sha256sum; do
 	if ! type -P "$Dep" &> /dev/null; then
 		Err 0 "Dependency '$Dep' not met."
 		let DepCount++
@@ -195,6 +195,8 @@ FileChk "$VerFile"
 read -a Line < "$VerFile"
 CurVer=${Line[2]}
 
+printf 'Current Linux version: %s\n' "$CurVer"
+
 if [[ $CurVer =~ ^[0-9]+\.[0-9]+\.[0-9]+-.* ]]; then
 	printf 'Unable to determine if latest kernel is newer.\n' 1>&2
 	Ask "Continue with $Progrm?" || exit 1
@@ -202,8 +204,6 @@ elif [ ${CurVer//[!0-9]/} -lt ${LatestVer//[!0-9]/} ]; then
 	printf "You're already up-to-date -- nothing to do.\n"
 	exit 0
 fi
-
-printf 'Current Linux version: %s\n' "$CurVer"
 
 #----------------------------------Look for Compilation & Building Dependencies
 
@@ -324,9 +324,15 @@ fi
 #---------------------------------------Begin Compiling and Building the Kernel
 
 printf 'Attempting to compile kernel & build Debian packages...\n'
-make deb-pkg
-ExitStatus=$?
+make deb-pkg || exit $?
+
+#-----------------------------------------------------------------------Cleanup
+
+if Ask 'Remove Kernel source files?'; then
+	rm -rv "$BuildDir/${LatestTar%.tar.xz}"
+fi
+
+printf 'Synchronising cached writes...\n'
+sync
 
 printf 'Finished.\n'
-
-exit $ExitStatus
