Update standards of `jotd` & `bios-info`
JOTD is still borked. I think things changed site-side.

diff --git a/source/jotd b/source/jotd
--- a/source/jotd
+++ b/source/jotd
@@ -1,121 +1,127 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #cito M:755 O:0 G:0 T:/usr/bin/jotd
-#----------------------------------------------------------------------------------
-# Project Name      - Extra/source/jotd (Joke of the Day)
+#------------------------------------------------------------------------------
+# Project Name      - Extra/source/jotd
 # Started On        - Fri  2 Mar 13:27:44 GMT 2018
-# Last Change       - Fri  6 Dec 22:50:52 GMT 2019
+# Last Change       - Sat 14 Mar 14:02:56 GMT 2020
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
-#----------------------------------------------------------------------------------
+#------------------------------------------------------------------------------
+# Features:
+#
+#TODO: Add other sites, in-case one or more fail.
+#
+# Bugs:
+#
+#TODO: Unable to fetch JOTD for a long time, now. Parsing fail, or site-side?
+#
+# Dependencies:
+#
+#   bash (>= 4.3-14)
+#   coreutils (>= 8.25-2)
+#   libtflbp-sh (>= 2019-12-10)
+#   ncurses-bin (>= 6.0+20160213-1)
+#   wget (>= 1.17.1-1)
+#------------------------------------------------------------------------------
 
-_VERSION_="2019-12-06"
-_PROJECT_=${0##*/}
 
-Err(){
-	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
-	[ $1 -eq 1 ] && exit 1
-}
+set -e
+. /usr/lib/tflbp-sh/Err
+. /usr/lib/tflbp-sh/ChkDep
+set +e
 
-DOM="http://www.laughfactory.com"
+CurVer='2020-03-14'
+Progrm=${0##*/}
 
-USAGE(){
-	while read -r; do
+Domain='http://www.laughfactory.com'
+
+Usage(){
+	while read; do
 		printf "%s\n" "$REPLY"
 	done <<-EOF
-		            ${_PROJECT_^^} - JOKE OF THE DAY ($_VERSION_)
+		            ${Progrm^^} ($CurVer)
 		            Written by terminalforlife <terminalforlife@yahoo.com>
 
 		            Display a Joke of the Day on your terminal.
 
-		SYNTAX:     $_PROJECT_ [OPTS]
+		SYNTAX:     $Progrm [OPTS]
 
-		OPTS:       --help|-h|-?            - Displays this help information.
-		            --version|-v            - Output only the version datestamp.
-		            --debug|-D              - Enables the built-in bash debugging.
+		OPTS:       --help|-h|-?            - Display this help information.
+		            --version|-v            - Output the version datestamp.
+		            --debug|-D              - Enable built-in Bash debugging.
 
 		NOTE:       These jokes may or may not be tasteful!
 
 		FILE:       Jokes are saved in:
 
-		              /tmp/${_PROJECT_}_store.txt
+		              /tmp/${Progrm}_store.txt
 
-		            This is to avoid contacting the server on each execution of $_PROJECT_. When
-		            the system is restarted, assuming /tmp is cleared, $_PROJECT_ will once again
-		            contact the server and recreate the file with the current joke.
+		            This is to avoid contacting the server on each execution of
+		            $Progrm. When the system is restarted, assuming /tmp is
+		            cleared, $Progrm will once again contact the server and
+		            recreate the file with the current joke.
 
-		SITE:       $DOM
+		SITE:       $Domain
 	EOF
 }
 
 while [ "$1" ]; do
 	case $1 in
 		--help|-h|-\?)
-			USAGE; exit 0 ;;
+			Usage; exit 0 ;;
 		--version|-v)
-			printf "%s\n" "$_VERSION_"
+			printf '%s\n' "$CurVer"
 			exit 0 ;;
 		--debug|-D)
-			DEBUGME='true' ;;
+			DebugMe='true' ;;
 		*)
-			Err 1 $LINENO "Incorrect argument(s) specified." ;;
+			Err 1 'Incorrect argument(s) specified.' ;;
 	esac
 	shift
 done
 
-declare -i DEPCOUNT=0
-for DEP in tee wget fold; {
-	if ! type -fP "$DEP" > /dev/null 2>&1; then
-		Err 0 $LINENO "Dependency '$DEP' not met."
-		DEPCOUNT+=1
-	fi
-}
+ChkDep tee wget fold tput
 
-[ $DEPCOUNT -eq 0 ] || exit 1
+[ "$DebugMe" == 'true' ] && set -x
 
-if [ "$COLUMNS" ] && ! type -fP tput > /dev/null 2>&1; then
-	Err 1 $LINENO "Dependency 'tput' not met."
-fi
+URL="$Domain/jokes/joke-of-the-day"
+File="/tmp/${Progrm}_store.txt"
 
-[ "$DEBUGME" == 'true' ] && set -x
-
-URL="$DOM/jokes/joke-of-the-day"
-FILE="/tmp/${_PROJECT_}_store.txt"
-
-MAIN(){
-	if type -fP curl > /dev/null 2>&1; then
-		JOKE_RAW=`curl -s -C - "$URL"`
-	elif type -fP wget > /dev/null 2>&1; then
-		JOKE_RAW=`wget -q -t 1 "$URL" -O -`
+MainOp(){
+	if type -fP curl 1> /dev/null 2>&1; then
+		RawJoke=`curl -s "$URL"`
+	elif type -fP wget 1> /dev/null 2>&1; then
+		RawJoke=`wget -q "$URL" -O -`
 	else
-		Err 0 $LINENO "Dependency 'wget' or 'curl' not met."
+		Err 0 "Dependency 'wget' or 'curl' not met."
 	fi
 
-	declare -i C=1
-	while read X; do
-		if [[ $X =~ \<p\ id\=\"joke_[0-9]+\"\> ]]; then
-			printf -v JID "%d" "${X//[!0-9]}"
-		 [[ $JID =~ ^[0-9]+$ ]] && C+=1
-		elif [ $C -eq 2 ]; then
-			for F in $X; {
-				if [[ $F == *\<br\>* ]]; then
-					printf "${F//<br>/$'\n'} "
-				elif [[ $F == *\</p\>* ]]; then
+	declare -i Count=1
+	while read Line; do
+		if [[ $Line =~ \<p\ id\=\"joke_[0-9]+\"\> ]]; then
+			printf -v JokeID "%d" "${Line//[!0-9]}"
+			[[ $JokeID =~ ^[0-9]+$ ]] && Count+=1
+		elif [ $Count -eq 2 ]; then
+			for Field in $Line; {
+				if [[ $Field == *\<br\>* ]]; then
+					printf "${Field//<br>/$'\n'} "
+				elif [[ $Field == *\</p\>* ]]; then
 					break
 				else
-					printf "%s " "$F"
+					printf "%s " "$Field"
 				fi
 			}
 
 			printf "\n"
 			break
 		fi
-	done <<< "$JOKE_RAW" | fold -s --width=${COLUMNS:-`tput cols`}
+	done <<< "$RawJoke" | fold -s --width=`tput cols`
 }
 
-if [ -z "$(MAIN)" ]; then
-	Err 1 $LINENO "Fetching the JOTD is currently unavailable."
-elif ! [ -f "$FILE" ]; then
-	MAIN | tee "$FILE"
+if [ -z "$(MainOp)" ]; then
+	Err 1 'Fetching the JOTD is currently unavailable.'
+elif ! [ -f "$File" ]; then
+	MainOp | tee "$File"
 else
-	MAIN
+	MainOp
 fi
