Overhaul & vastly improved
This is now not a quick and dirty script but an actual program, or at
least the initial step towards that. It needs an installation script, -
a BASH completion script, a man page, and potentially some more
features.

diff --git a/source/lmc-darklight b/source/lmc-darklight
--- a/source/lmc-darklight
+++ b/source/lmc-darklight
@@ -3,97 +3,220 @@
 #------------------------------------------------------------------------------
 # Project Name      - Extra/source/lmc-darklight
 # Started On        - Wed 23 Feb 21:40:31 GMT 2022
-# Last Change       - Thu 24 Feb 19:25:46 GMT 2022
+# Last Change       - Fri 25 Feb 02:30:07 GMT 2022
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
 # This seems to be an oft-requested feature in Linux Mint, so I thought I'd
-# have a bash (pun intended) at writing something quick which will effectively
-# work as a daemon to auto-set values based on the time of day, down to the
-# minute.
+# have a bash (pun intended) at writing something which will effectively work
+# as a daemon to auto-set values based on the time of day.
 #
-# This is for Linux Mint Cinnamon ONLY, but you could surely repurpose it for
-# your own desktop environment or distribution.
+# This is strictly for Linux Mint Cinnamon.
 #
-# Run this as a regular user. You'll probably want to store this in '~/bin', -
-# make it executable (IE: `chmod u+x FILE`), then set it to be executed every
-# time you log in, with the 'Startup Applications' GUI in Cinnamon.
+# Features:
 #
-# Set what you need using the variables below.
+# N/A
+#
+# Bugs:
+#
+# N/A
+#
+# Dependencies:
+#
+#   bash (>= 4.4.20)
+#   coreutils (>= 8.28)
 #------------------------------------------------------------------------------
 
-# How often it'll check the time and adjust themes.
-Interval=60
+CurVer='2022-02-25'
+Progrm='lmc-darklight'
+ProgrmFancy='LMC-DarkLight'
 
-# Like 600 (6am) or 2000 (8pm), in 24hr. The colon is optional.
-LightTime=600
-DarkTime=2000
+Usage() {
+	read -d '' <<-EOF
+		Usage: $Progrm [OPTS]
 
-# Names relative to the 'Themes' GUI in Cinnamon.
-LightDesktop='Mint-Y'
-DarkDesktop='Mint-Y-Dark-Red'
-LightControls='Mint-Y'
-DarkControls='Mint-Y-Dark-Red'
-LightIcons='Mint-Y-Blue'
-DarkIcons='Mint-Y-Dark-Red'
-LightCursor='DMZ-White'
-DarkCursor='DMZ-Black'
-LightBorders='Mint-Y'
-DarkBorders='Mint-Y'
+		  -h, --help               - Display this help information.
+		  -v, --version            - Output the version datestamp.
+		  --genconfig              - Generate new configuration file.
+	EOF
 
-# Absolute paths to the light and dark backgrounds.
-LightBG='/usr/share/backgrounds/linuxmint/sele_ring_green.jpg'
-DarkBG='/usr/share/backgrounds/linuxmint/default_background.jpg'
-
-#-----------------------------------------Work Like A Daemon to Auto-Set Themes
+	printf '%s' "$REPLY"
+}
 
 Err() {
-	printf 'Err: %s\n' "$1" 1>&2
-	(( Err++ ))
+	printf 'Err: %s\n' "$2" 1>&2
+	(( $1 > 0 )) && exit $1
+}
+
+MainDir="$HOME/.config/$Progrm"
+Config="$MainDir/config"
+
+ValidKeys=(
+		LightCursor LightDesktop DarkBorders DarkIcons DarkControls\
+		Interval LightTime DarkTime LightBorders LightIcons LightControls\
+		DarkCursor DarkDesktop LightBG DarkBG
+)
+
+while [[ -n $1 ]]; do
+	case $1 in
+		--help|-h)
+			Usage; exit 0 ;;
+		--version|-v)
+			printf '%s\n' "$CurVer"; exit 0 ;;
+		--genconfig)
+			NewConfig='True' ;;
+		*)
+			Err 1 'Incorrect option(s) specified.' ;;
+	esac
+	shift
+done
+
+(( UID == 0 )) && Err "Do not run \`$0\` as the 'root' user."
+
+for Dep in mkdir gsettings sleep; do
+	if ! type -P "$Dep" &> /dev/null; then
+		Err 0 "Dependency '$Dep' not met."
+		(( DepCount++ ))
+	fi
+done
+
+(( DepCount > 0 )) && exit 1
+
+[[ -d $MainDir ]] || mkdir -p "$MainDir"
+
+#-----------------------------------------------Generate New Configuration File
+
+if [[ $NewConfig == True ]]; then
+	read -d '' <<-EOF
+		# $ProgrmFancy configurations for Linux Mint Cinnamon.
+
+		# How often to check the time and set the themes.
+		Interval=60
+
+		# The time to start light/dark theme. Time is in 24hr. Do not zero-pad the
+		# numbers. 6am is 600 not 0600 or 06:00. Do not include the colon.
+		LightTime=600
+		DarkTime=2000
+
+		# Dark and light themes, relative to \`cinnamon-settings startup\`.
+		LightBorders='Mint-Y'
+		LightIcons='Mint-Y-Blue'
+		LightControls='Mint-Y'
+		LightCursor='DMZ-White'
+		LightDesktop='Mint-Y'
+		DarkBorders='Mint-Y'
+		DarkIcons='Mint-Y-Dark-Red'
+		DarkControls='Mint-Y-Dark-Red'
+		DarkCursor='DMZ-Black'
+		DarkDesktop='Mint-Y-Dark-Red'
+
+		# Absolute paths to the light and dark backgrounds.
+		LightBG='/usr/share/backgrounds/linuxmint/sele_ring_green.jpg'
+		DarkBG='/usr/share/backgrounds/linuxmint/default_background.jpg'
+	EOF
+
+	printf '%s' "$REPLY" > "$Config"
+	exit 0
+fi
+
+#------------------------Process the Configuration File and Begin the Main Loop
+
+Info() {
+	printf "INFO: %s='%s'\n" "$1" "$2"
 }
 
 Set() {
+	Info 'org.cinnamon.theme/name' "$1"
 	gsettings set org.cinnamon.theme name "$1"
+
+	Info 'org.gnome.desktop.interface/gtk-theme' "$1"
 	gsettings set org.gnome.desktop.interface gtk-theme "$1"
+
+	Info 'org.cinnamon.desktop.interface/gtk-theme' "$2"
 	gsettings set org.cinnamon.desktop.interface gtk-theme "$2"
+
+	Info 'org.gnome.desktop.interface/icon-theme' "$3"
 	gsettings set org.gnome.desktop.interface icon-theme "$3"
+
+	Info 'org.cinnamon.desktop.interface/icon-theme' "$3"
 	gsettings set org.cinnamon.desktop.interface icon-theme "$3"
+
+	Info 'org.cinnamon.desktop.interface/cursor-theme' "$4"
 	gsettings set org.cinnamon.desktop.interface cursor-theme "$4"
+
+	Info 'org.gnome.desktop.interface/cursor-theme' "$4"
 	gsettings set org.gnome.desktop.interface cursor-theme "$4"
+
+	Info 'org.cinnamon.desktop.wm.preferences/theme' "$5"
 	gsettings set org.cinnamon.desktop.wm.preferences theme "$5"
+
+	Info 'org.gnome.desktop.wm.preferences/theme' "$5"
 	gsettings set org.gnome.desktop.wm.preferences theme "$5"
+
+	Info 'org.cinnamon.desktop.background/picture-uri' "file://$6"
 	gsettings set org.cinnamon.desktop.background picture-uri "file://$6"
 }
 
-(( $# > 0 )) && Err 'No arguments required.'
-(( UID == 0 )) && Err "Do not run \`$0\` as the 'root' user."
-(( Err > 0 )) && exit 1
-
-if ! type -P gsettings &> /dev/null; then
-	Err "Dependency 'gsettings' not met."
-fi
-
-if [[ -z $LightTime || -z $DarkTime ]]; then
-	Err "Variable 'LightTime' and/or 'DarkTime' not set."
-elif ! [[ $LightTime =~ ^[[:digit:]]+$ && $DarkTime =~ ^[[:digit:]]+$ ]]; then
-	Err "Variable 'LightTime' and/or 'DarkTime' invalid."
-fi
-
-for Value in {Light,Dark}{Desktop,Controls,Icons,Cursor,Borders}; {
-	[[ -z ${!Value} ]] && Err "Value '$Value' not set."
-}
-
-if [[ -z $LightBG || -z $DarkBG ]]; then
-	Err "Variable 'LightBG' and/or 'DarkBG' not set."
-elif ! [[ -f $LightBG && -f $DarkBG ]]; then
-	Err "File for variable 'LightBG' and/or 'DarkBG' not found."
-elif ! [[ -r $LightBG && -r $DarkBG ]]; then
-	Err "File for variable 'LightBG' and/or 'DarkBG' unreadable."
-fi
-
-(( Err > 0 )) && exit 1
-
 while :; do
+	# Read and verify the configuration file.
+	if [[ -f $Config ]]; then
+		VErr() {
+			Err 0 "$1"
+			(( VErrs++ ))
+		}
+
+		while IFS='=' read Key Value; do
+			[[ $Key == \#* || -z $Key ]] && continue
+			Value=${Value//[\"\']}
+
+			Found='False'
+			for Valid in "${ValidKeys[@]}"; {
+				if [[ $Key == $Valid ]]; then
+					Found='True'
+					break
+				fi
+			}
+
+			if [[ $Found == True ]]; then
+				declare $Key="$Value"
+			else
+				Err 0 "Key '$Key' invalid."
+				(( InvalidKeys++ ))
+			fi
+		done < "$Config"
+
+		(( InvalidKeys > 0 )) && exit 1
+
+		if [[ -z $LightTime || -z $DarkTime ]]; then
+			VErr "Key 'LightTime' and/or 'DarkTime' not set."
+		elif ! [[ $LightTime =~ ^[[:digit:]]+$ && $DarkTime =~ ^[[:digit:]]+$ ]]; then
+			VErr "Key 'LightTime' and/or 'DarkTime' invalid."
+		fi
+
+		for Value in {Light,Dark}{Desktop,Controls,Icons,Cursor,Borders}; {
+			[[ -z ${!Value} ]] && VErr "Value '$Value' not set."
+		}
+
+		if [[ -z $LightBG || -z $DarkBG ]]; then
+			VErr "Key 'LightBG' and/or 'DarkBG' not set."
+		fi
+
+		if ! [[ -f $LightBG && -r $LightBG ]]; then
+			VErr "File for key 'LightBG' not found or unreadable."
+		fi
+
+		if ! [[ -f $DarkBG && -r $DarkBG ]]; then
+			VErr "File for key 'DarkBG' not found or unreadable."
+		fi
+
+		(( VErrs > 0 )) && exit 1
+	elif ! [[ -r $Config ]]; then
+		Err 1 "File '$Config' unreadable."
+	else
+		Err 1 "File '$Config' not found."
+	fi
+
+	# Begin the main loop.
 	printf -v Time '%(%k%M)T' -1
 	if (( Time >= LightTime && Time < DarkTime )); then
 		Set "$LightDesktop" "$LightControls" "$LightIcons"\
