Convert `lspkg-set` to Bourne POSIX & Update it

diff --git a/source/lspkg-set b/source/lspkg-set
--- a/source/lspkg-set
+++ b/source/lspkg-set
@@ -1,88 +1,78 @@
-#!/bin/bash
+#!/bin/sh
 #cito M:755 O:0 G:0 T:/usr/bin/lspkg-set
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/source/lspkg-set (List Packages Set)
 # Started On        - Wed 24 Jan 17:31:41 GMT 2018
-# Last Change       - Fri  6 Dec 22:51:11 GMT 2019
+# Last Change       - Fri 10 Jan 00:53:01 GMT 2020
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
 
-_VERSION_="2019-12-06"
-_PROJECT_=${0##*/}
+set -e
+. /usr/lib/tflbp-sh/Err
+. /usr/lib/tflbp-sh/ChkDep
+set +e
 
-Err(){
-	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
-	[ $1 -eq 1 ] && exit 1
-}
+CurVer='2020-01-10'
+Progrm=${0##*/}
 
-USAGE(){
-	while read -r; do
-		printf "%s\n" "$REPLY"
+Usage(){
+	while read -r CurLine; do
+		printf '%b\n' "$CurLine"
 	done <<-EOF
-		            ${_PROJECT_^^} ($_VERSION_)
-		            Written by terminalforlife <terminalforlife@yahoo.com>
+		\r            LSPKG-SET ($CurVer)
+		\r            Written by terminalforlife <terminalforlife@yahoo.com>
 
-		            Add-on for lspkg to output sets of installed packages.
+		\r            Add-on for lspkg to output sets of installed packages.
 
-		SYNTAX:     $_PROJECT_ [OPT]
+		\rSYNTAX:     $Progrm [OPT]
 
-		OPTS:       --help|-h|-?            - Displays this help information.
-		            --version|-v            - Output only the version datestamp.
-		            --essential|-E          - Display the essential packages.
-		            --extra|-e              - Display the extra packages.
-		            --required|-R           - Display the required packages.
-		            --optional|-o           - Display the optional packages.
-		            --important|-I          - Display the important packages.
+		\rOPTS:       --help|-h|-?            - Displays this help information.
+		\r            --version|-v            - Output only the version datestamp.
+		\r            --essential|-E          - Display the essential packages.
+		\r            --extra|-e              - Display the extra packages.
+		\r            --important|-I          - Display the important packages.
+		\r            --optional|-o           - Display the optional packages.
+		\r            --required|-R           - Display the required packages.
 
-		NOTE:       Much like lspkg, this shell program is only compatible with Debian or
-		            Ubuntu based systems, as it parses dpkg-query's output.
+		\rNOTE:       Like lspkg, this POSIX-ly correct Bourne shell program is
+		\r            only compatible with Debian or Ubuntu based systems, as it
+		\r            parses dpkg-query's output.
 	EOF
 }
 
+[ $# -eq 0 ] && Err 1 "One argument is required -- see: $Progrm -h"
+
 case $* in
 	--help|-h|-\?)
-		USAGE; exit 0 ;;
+		Usage; exit 0 ;;
 	--version|-v)
-		printf "%s\n" "$_VERSION_"
-		exit 0 ;;
+		printf '%s\n' "$CurVer"; exit 0 ;;
 	--essential|-E)
-		TYPE="Essential:yes" ;;
+		Type='Essential:yes' ;;
 	--extra|-e)
-		TYPE="Priority:extra" ;;
+		Type='Priority:extra' ;;
 	--required|-R)
-		TYPE="Priority:required" ;;
+		Type='Priority:required' ;;
 	--optional|-o)
-		TYPE="Priority:optional" ;;
+		Type='Priority:optional' ;;
 	--important|-I)
-		TYPE="Priority:important" ;;
+		Type='Priority:important' ;;
 	*)
-		Err 1 $LINENO "Incorrect argument(s) specified." ;;
+		Err 1 'Incorrect argument(s) specified.' ;;
 esac
 
-if ! type -fP dpkg-query > /dev/null 2>&1; then
-	Err 1 $LINENO "Dependency 'dpkg-query' not met."
-fi
+ChkDep dpkg-query
 
-#TODO: Not seeing the Binary:Summary of the packages.
+Format="\${db:Status-Abbrev} \${${Type%:*}} \${Package}\n"
 
-FMT1="\${db:Status-Abbrev} \${${TYPE%:*}} "
-FMT2="\${Package} - \${Binary:Summary}"
+dpkg-query -Wf "$Format" \* | while read F1 F2 F3 _; do
+	if [ "$F1" = 'ii' -a "$F2" = "${Type#*:}" ]; then
+		New=$F3
 
-while read -a X; do
-	if [ "${X[0]}" == "ii" -a "${X[1]}" == "${TYPE/*:}" ]; then
-		printf -v INUM "%d" "$((${#X[@]}-1))"
+		[ "$New" = "$Old" ] && continue
+		printf '%s\n' "$New"
 
-		OLD=$NEW
-		NEW=$(
-			for FIELD in `eval printf {2..$INUM}`; {
-				printf "%s " "${X[FIELD]}"
-			}
-		)
-
-		if ! [ "$NEW" == "$OLD" ]; then
-			printf "%s\n" "$NEW"
-		fi
+		Old=$New
 	fi
-done <<< "$(dpkg-query -Wf="${FMT1}${FMT2}\n" \*)"
-
+done
