Optimize with generally better syntax

diff --git a/source/mif b/source/mif
--- a/source/mif
+++ b/source/mif
@@ -3,23 +3,21 @@
 #------------------------------------------------------------------------------
 # Project Name      - Extra/source/mif
 # Started On        - Fri 13 Oct 13:21:13 BST 2017
-# Last Change       - Wed  7 Jun 22:22:18 BST 2023
+# Last Change       - Thu 15 Jun 21:39:15 BST 2023
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
 
-CurVer='2022-01-13'
+CurVer='2023-06-15'
 Progrm=${0##*/}
 
 Usage(){
-	while read; do
-		printf '%s\n' "$REPLY"
-	done <<-EOF
+	read -d '' <<-EOF
 		Usage: $Progrm [OPTS] [YEAR]
 
 		  -h, --help               - Displays this help information.
 		  -v, --version            - Output only the version datestamp.
-		  --mklist[:{+|-}]         - Output a $Progrm-usable list from CWD.
+		  --mklist[:{+|-}]         - Output a ${Progrm^^}-usable list from CWD.
 		  -O, --organize           - Attempt to organise files in CWD by year.
 		  -a, --all                - Display films; disregard filters.
 		  -f, --file FILE          - Override saved path with FILE.
@@ -38,6 +36,8 @@ Usage(){
 
 		  Default index file is '~/.$Progrm', but can be easily overridden.
 	EOF
+
+	printf '%s' "$REPLY"
 }
 
 Err(){
@@ -45,38 +45,38 @@ Err(){
 	(( $1 > 0 )) && exit $1
 }
 
-if [ "${BASH_VERSINFO[0]}" -ge 4 ]; then
+if (( ${BASH_VERSINFO[0]} >= 4 )); then
 	shopt -s extglob globstar
 else
 	Err 1 "Bash version 4.0 or greater is required."
 fi
 
 MovieIndex="$HOME/.$Progrm"
-Seen='false'
-Total='false'
+Seen='False'
+Total='False'
 
-while [ "$1" ]; do
+while [[ -n $1 ]]; do
 	case $1 in
 		--help|-h|-\?)
 			Usage; exit 0 ;;
 		--version|-v)
-			printf "%s\n" "$CurVer"; exit 0 ;;
+			printf '%s\n' "$CurVer"; exit 0 ;;
 		--mklist|-M)
-			shift; MAKE_LIST_OPT=':[+]' ;;
+			shift; MakeListOpt=':[+]' ;;
 		--mklist:N|-M:N)
-			shift; MAKE_LIST_OPT=':' ;;
+			shift; MakeListOpt=':' ;;
 		--file|-f)
 			shift; MovieIndex=$1 ;;
 		--all|-a)
 			Seen='all' ;;
 		--organize|-O)
-			Organise='true' ;;
+			Organise='True' ;;
 		--total|-t)
-			Total='true' ;;
+			Total='True' ;;
 		--seen|-s)
-			Seen='true' ;;
+			Seen='True' ;;
 		--unseen|-u)
-			Seen='false' ;;
+			Seen='False' ;;
 		*)
 			break ;;
 	esac
@@ -87,39 +87,40 @@ DepCount=0
 for Dep in mkdir mv; {
 	if ! type -P "$Dep" &> /dev/null; then
 		Err 0 "Dependency '$Dep' not met."
-		let DepCount++
+		(( DepCount++ ))
 	fi
 }
 
-[ $DepCount -eq 0 ] || exit 1
+(( DepCount == 0 )) || exit 1
 
-if [[ $MAKE_LIST_OPT =~ (:|:\[+\]) ]]; then
-	for FILE in **; {
-		[ -f "$FILE" ] || continue
-		IFS='/' read -a X <<< "${FILE% (*}"
-		printf "%s%s: %s\n" "${X[0]}" "${MAKE_LIST_OPT#:}" "${X[1]}"
-	}
+case $MakeListOpt in
+	:|:\[+\])
+		for FILE in **; {
+			[[ -f $FILE ]] || continue
+			IFS='/' read -a X <<< "${FILE% (*}"
+			printf '%s%s: %s\n' "${X[0]}" "${MakeListOpt#:}" "${X[1]}"
+		}
 
-	exit 0
-fi
+		exit 0 ;;
+esac
 
-if ! [ "$Organise" == 'true' ]; then
+if [[ $Organise != True ]]; then
 	if [[ $1 =~ ^[[:digit:]]+$ ]]; then
 		Year=$1; shift
 	else
-		if ! [ "$Seen" == "all" ]; then
+		if ! [[ $Seen == all ]]; then
 			Err 1 "Invalid year specified."
 		fi
 	fi
 fi
 
-[ -n "$*" ] && Err 1 "Incorrect argument(s) specified."
+(( $# > 0 )) && Err 1 "Incorrect argument(s) specified."
 
-if [ "$Organise" == 'true' ]; then
+if [[ $Organise == True ]]; then
 	for X in *; {
 		Y=${X//*\(}
 
-	 [[ ${Y%\)*} =~ ^[[:digit:]]+$ ]] || continue
+		[[ ${Y%\)*} == +([[:digit:]]) ]] || continue
 
 		if mkdir "${Y%\)*}"; then
 			printf '%s\n' "MAKE: ${Y%\)*}"
@@ -137,30 +138,30 @@ if [ "$Organise" == 'true' ]; then
 	exit 0
 fi
 
-[ -f "$MovieIndex" ] || Err 1 "Index file '$MovieIndex' not found."
+[[ -f $MovieIndex ]] || Err 1 "Index file '$MovieIndex' not found."
 
 declare -i Line=0
 while read -r; do
 	{ [[ $REPLY == +(#)* ]] || [ -z "$REPLY" ]; } && continue
 
-	if [ "$Seen" == 'false'  ]; then
+	if [[ $Seen == False  ]]; then
 		if [[ $REPLY == $Year\[\+\]:\ * ]]; then
-			printf "%s\n" "${REPLY/+([[:digit:]])\[?\]: }"
+			printf '%s\n' "${REPLY/+([[:digit:]])\[?\]: }"
 			Line+=1
 		fi
-	elif [ "$Seen" == 'true'  ]; then
+	elif [[ $Seen == True ]]; then
 		if [[ $REPLY == $Year\[\-\]:\ * ]]; then
-			printf "%s\n" "${REPLY/+([[:digit:]])\[?\]: }"
+			printf '%s\n' "${REPLY/+([[:digit:]])\[?\]: }"
 			Line+=1
 		fi
-	elif [ "$Seen" == 'all'  ]; then
-		printf "%s\n" "${REPLY/+([[:digit:]])\[?\]: }"
+	elif [[ $Seen == all ]]; then
+		printf '%s\n' "${REPLY/+([[:digit:]])\[?\]: }"
 		Line+=1
 	fi
 done < "$MovieIndex"
 
-[ $Line -eq 0 ] && Err 1 "Unable to find year $Year."
+[[ $Line -eq 0 ]] && Err 1 "Unable to find year $Year."
 
-if [ "$Total" == 'true' ]; then
-	printf "\nTotal: %d\n" "$Line"
+if [[ $Total == True ]]; then
+	printf '\nTotal: %d\n' "$Line"
 fi
