Update `mkpass` to newer standards & clean code

diff --git a/source/mkpass b/source/mkpass
--- a/source/mkpass
+++ b/source/mkpass
@@ -1,140 +1,96 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #cito M:755 O:0 G:0 T:/usr/bin/mkpass
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/source/mkpass
 # Started On        - Fri 20 Oct 12:14:09 BST 2017
-# Last Change       - Fri  6 Dec 22:52:26 GMT 2019
+# Last Change       - Sun 16 Feb 22:58:46 GMT 2020
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
 
-_VERSION_="2019-12-06"
-_PROJECT_=${0##*/}
+set -e
+. /usr/lib/tflbp-sh/Err
+set +e
 
-Err(){
-	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
-	[ $1 -eq 1 ] && exit 1
-}
+CurVer='2020-02-16'
+Progrm=${0##*/}
 
-DOM="https://github.com"
-
-USAGE(){
-	while read -r; do
+Usage(){
+	while read; do
 		printf "%s\n" "$REPLY"
 	done <<-EOF
-		            ${_PROJECT_^^} ($_VERSION_)
+		            ${Progrm^^} ($CurVer)
 		            Written by terminalforlife <terminalforlife@yahoo.com>
 
 		            Pure Bourne Again Shell approach to complex password generation.
 
-		SYNTAX:     $_PROJECT_ [OPTS] INT
+		SYNTAX:     $Progrm [OPTS] [INT]
 
-		OPTS:       --help|-h|-?            - Displays this help information.
-		            --version|-v            - Output only the version datestamp.
-		            --update|-U             - Check for updates to mkpass.
-		            --type|-t TYPE          - Where T is the type. See below.
+		OPTS:       --help|-h|-?            - Display this help information.
+		            --version|-v            - Output the version datestamp.
+		            --type|-t TYPE          - Where TYPE is the type to use.
 
-		NOTE:       This small program uses /dev/urandom to generate a wide range of
-		            characters, just as you would expect from genpass, but fuller and
-		            with extra features and choices for the user.
+		TYPES:      Valid types below.
 
-		            Where INT is the number (integer) of characters to generate.
+		              alnum, alpha, digit, punct, alnumpunct
 
-		TYPES:      Available TYPEs:
+		NOTE:       This small program uses '/dev/urandom' to generate a wide
+		            range of characters, just as you would expect from
+		            genpass, but fuller and with extra features and choices for
+		            the user.
 
-		            +------------+----------------------+------------------+
-		            | VALID TYPE | WHAT IT INCLUDES     | REGEX FORM       |
-		            +------------+----------------------+------------------+
-		            | punct      | Punctuation          | [[:punct:]]      |
-		            | digit      | Digits               | [[:digit:]]      |
-		            | alpha      | Letters              | [[:alpha:]]      |
-		            | alnum      | Letters and Digits   | [[:alnum:]]      |
-		            | alphapunct | All of the above.    | [[:alphapunct:]] |
-		            +-----------------------------------+------------------+
-
-		SITE:       $DOM/terminalforlife/Extra
+		            Where INT is the number of characters to generate.
 	EOF
 }
 
 while [ "$1" ]; do
 	case $1 in
 		--help|-h|-\?)
-			USAGE; exit 0 ;;
+			Usage; exit 0 ;;
 		--version|-v)
-			printf "%s\n" "$_VERSION_"; exit 0 ;;
-		--update|-U)
-			UPDATE='true' ;;
+			printf '%s\n' "$CurVer"; exit 0 ;;
 		--type|-t)
-			shift; TYPE="$1" ;;
+			shift; Type=$1 ;;
 		-*)
-			Err 1 $LINENO "Incorrect argument(s) specified." ;;
+			Err 1 "Incorrect argument(s) specified." ;;
 		*)
 			break ;;
 	esac
 	shift
 done
 
-if [ "$UPDATE" == 'true' ]; then
-	if ! type -fP wget > /dev/null 2>&1; then
-		Err 1 $LINENO "Dependency 'wget' not met."
-	fi
-
-	VERSION_URL="$DOM/terminalforlife/Extra/raw/master/versions"
-	while IFS='=' read -a LINE; do
-		if  [ "${LINE[0]}" == 'mkpass' ]; then
-			LATEST=${LINE[1]}
-
-			if [[ ${LATEST//-} =~ ^[0-9]{8}$ ]]; then
-				if [ ${LATEST//-} -gt ${_VERSION_//-} ]; then
-					while read -r; do
-						printf "%s\n" "$REPLY"
-					done <<-EOF
-						New version available:    $LATEST
-						Current version:          $_VERSION_
-					EOF
-				fi
-			else
-				Err 1 $LINENO "Failed to check for available updates."
-			fi
-		fi
-	done <<< "$(wget -q "$VERSION_URL" -O -)"
-
-	exit 0
-fi
-
-if [[ $1 =~ [0-9]+ ]]; then
-	INT=$1
-elif [ -z "$INT" ]; then
-	Err 1 $LINENO "Invalid or missing INT."
+if [[ $1 =~ ^[0-9]+$ ]]; then
+	Int=$1
+elif [ -z "$Int" ]; then
+	Err 1 'Invalid or missing INT.'
 elif ! [ -e /dev/urandom ]; then
-	Err 1 $LINENO "Unable to access /dev/urandom device."
-elif ! [[ "$*" =~ [0-9]+ ]] && [ "$INT" -ge 1 ]; then
-	Err 1 $LINENO "Requires an integer greater than or equal to 1."
+	Err 1 "Unable to access the '/dev/urandom' device."
+elif ! [[ "$*" =~ [0-9]+ ]] && [ $Int -ge 1 ]; then
+	Err 1 'Requires an integer >= 1.'
 fi
 
-case ${TYPE:-EMPTY} in
+case ${Type:-EMPTY} in
 	punct)
-		CHARS='[\`/\+\\\|\_\,\.\?\!\"\\\/\$\%\^\&\*\(\)\{\}\]\[-\>\<\:\@\~]' ;;
+		Chars='[\`/\+\\\|\_\,\.\?\!\"\\\/\$\%\^\&\*\(\)\{\}\]\[-\>\<\:\@\~]' ;;
 	digit)
-		CHARS='[0-9]' ;;
+		Chars='[[:digit:]]' ;;
 	alpha)
-		CHARS='[A-Za-z]' ;;
+		Chars='[[:upper:][:lower:]]' ;;
 	alnum)
-		CHARS='[0-9A-Za-z]' ;;
+		Chars='[[:upper:][:lower:][:digit:]]' ;;
 	alphapunct|EMPTY)
-		CHARS='[\`/\+\\\|0-9A-Za-z\_\,\.\?\!\"\\\/\$\%\^\&\*\(\)\{\}\]\[-\>\<\:\@\~]' ;;
+		Chars='[\_\,\.\?\!\"\\\/\$\%\^\&\*\(\)\{\}\]\[-\>\<\:\@\~\`/\+\\\|[:upper:][:lower:][:digit:]]' ;;
 	*)
-		Err 1 $LINENO "Invalid TYPE selected." ;;
+		Err 1 'Invalid Type selected.' ;;
 esac
 
 declare -i A=0
 while read -a X; do
-	if [[ ${X:0:1} == $CHARS ]]; then
+	if [[ ${X:0:1} == $Chars ]]; then
 		A+=1
-		printf "%s" "${X:0:1}"
-		[ $A -eq $INT ] && break
+		printf '%s' "${X:0:1}"
+		[ $A -eq $Int ] && break
 	fi
 done < /dev/urandom
 
-printf "\n"
-
+printf '\n'
