Optimize, improve, and make relevant
MPlay was marked as abandoned in favor of a Python rewrite, but it's
perfectly fine as it is, so I'll keep it around and keep the Python
rewrite as simply an alternative I wrote just for educational reasons.

TL;DR: No longer abandoned.

diff --git a/source/mplay b/source/mplay
--- a/source/mplay
+++ b/source/mplay
@@ -3,29 +3,17 @@
 #------------------------------------------------------------------------------
 # Project Name      - Extra/source/mplay
 # Started On        - Sat 16 Sep 19:42:57 BST 2017
-# Last Change       - Mon 20 Dec 08:47:15 GMT 2021
+# Last Change       - Thu 13 Jan 16:28:02 GMT 2022
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
-# Abandoned in favor of the recent Python3.6 rewrite, which turned out to be a
-# surprising replacement. Reported bugs may be addressed, but new features or
-# effort to update or optimize the code will probably not be made.
-#
-# The Python3.6 rewrite of `mplay` can be found in the PythonProjects
-# repository on the same GitHub store from which this file originated.
+# A Python3.6 rewrite of MPlay can be found in the PythonProjects repository on
+# the same GitHub store from which this file originated.
 #------------------------------------------------------------------------------
 
-CurVer='2021-12-20'
-Progrm=${0##*/}
+CurVer='2022-01-13'
+Progrm='mplay'
 ProgrmFancy='MPlay'
-
-Err() {
-	printf 'Err: %s\n' "$2" 1>&2
-	(( $1 > 0 )) && exit $1
-}
-
-Domain="https://github.com"
-ThemeDir="/usr/share/moc/themes"
 
 Usage() {
 	while read; do
@@ -35,37 +23,52 @@ Usage() {
 
 		  -h, --help               - Displays this help information.
 		  -v, --version            - Output only the version datestamp.
-		  -o, --run-once           - Exit the MOC server when closed.
+		  -o, --run-once           - Exit the MoC server when closed.
 
 		  To exit $ProgrmFancy, send the SIGINT (130) signal using the Ctrl + C
 		  shortcut (^C). Your previous terminal layout will be restored.
 
 		  When forcing, unsupported mimetypes and executables will be allowed.
+
+		  The use of '--' to ignore proceeding flags is supported.
 	EOF
 }
 
-while [ -n "$1" ]; do
+Err() {
+	printf 'Err: %s\n' "$2" 1>&2
+	(( $1 > 0 )) && exit $1
+}
+
+Domain="https://github.com"
+ThemeDir="/usr/share/moc/themes"
+
+while [[ -n $1 ]]; do
 	case $1 in
+		--)
+			shift;
+			break ;;
 		--help|-h|-\?)
 			Usage; exit 0 ;;
 		--version|-v)
 			printf "%s\n" "$CurVer"; exit 0 ;;
 		--once|-o)
-			Once='true' ;;
+			Once='True' ;;
 		-*)
 			Err 1 "Incorrect argument(s) specified." ;;
+		*)
+			break ;;
 	esac
 	shift
 done
 
-if [ -z "$1" ]; then
-	Err 1 'Please provide a directory in which to find music.'
-elif ! [ -d "$1" ]; then
+if [[ -z $1 ]]; then
+	Err 1 'Path to music files not provided.'
+elif ! [[ -d $1 ]]; then
 	Err 1 'Unable to find the given music directory.'
 fi
 
-[ -d $ThemeDir ] || Err 1 'Theme directory not found.'
-[ -f "$ThemeDir/tfl_moc_theme" ] || Err 1 'Theme file not found.'
+[[ -d $ThemeDir ]] || Err 1 'Theme directory not found.'
+[[ -f $ThemeDir/tfl_moc_theme ]] || Err 1 'Theme file not found.'
 type -P mocp 2> /dev/null 1>&2 || Err 1 "Dependency 'mocp' not met."
 
 mocp -n -T "$ThemeDir/tfl_moc_theme"          \
@@ -88,9 +91,9 @@ mocp -n -T "$ThemeDir/tfl_moc_theme"          \
 	-O OutputBuffer=512                       \
 	-O Prebuffering=256                       \
 	-m "${1:-$HOME/Music}"                    \
-|| Err 1 "Unable to start the MOC player."
+|| Err 1 'Unable to start the MoC player.'
 
-if [ "$Once" == 'true' ]; then
+if [[ $Once == True ]]; then
 	wait
 	mocp -x
 fi
