Update and improve noprtscr code

diff --git a/source/noprtscr b/source/noprtscr
--- a/source/noprtscr
+++ b/source/noprtscr
@@ -1,56 +1,66 @@
-#!/bin/bash
-
-#----------------------------------------------------------------------------------
-# Project Name      - Extra/source/noprtscr (No Print Screen)
+#!/usr/bin/env bash
+#cito M:755 O:0 G:0 T:/usr/bin/noprtscr
+#------------------------------------------------------------------------------
+# Project Name      - Extra/source/noprtscr
 # Started On        - Sun 21 Jan 18:30:36 GMT 2018
-# Last Change       - Thu 16 Dec 00:04:22 GMT 2021
+# Last Change       - Sun 30 Jan 16:01:30 GMT 2022
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
-#----------------------------------------------------------------------------------
+#------------------------------------------------------------------------------
 # A small script to remedy this issue in Linux Mint 18.3 with Cinnamon:
 #
 #   https://forums.linuxmint.com/viewtopic.php?f=90&t=152887
-#
-# Also enable the exra feature (launch the Menu with PrtSc) with:
-#
-# OPTS:       --version|-v            - Output only the version datestamp.
-#             --prtsc-is-menu         - Use PrtSC to launch the Mint Menu.
-#----------------------------------------------------------------------------------
+#------------------------------------------------------------------------------
 
-_VERSION_="2021-12-16"
-_PROJECT_=${0##*/}
+CurVer='2022-01-30'
+Progrm='noprtscr'
 
-Err(){
+Usage() {
+	while read; do
+		printf '%s\n' "$REPLY"
+	done <<-EOF
+		Usage: $Progrm [OPTS]
+
+		  -h, --help               - Display this help information.
+		  -v, --version            - Output the version datestamp.
+		  --prtsc-is-menu          - Use PrtSc to launch the Mint Menu.
+	EOF
+}
+
+Err() {
 	printf 'Err: %s\n' "$2" 1>&2
 	(( $1 > 0 )) && exit $1
 }
 
-if ! type -P gsettings > /dev/null 2>&1; then
-	Err 1 "Dependency 'gsettings' not met."
-fi
-
-while [ "$1" ]; do
+while [[ -n $1 ]]; do
 	case $1 in
-		--help|-h|-\?)
-			printf "USAGE: %s [[--help|-h|-?] | [--version|-v]] | [--prtsc-is-menu]\n" "$_PROJECT_" ;;
+		--help|-h)
+			Usage; exit 0 ;;
 		--version|-v)
-			printf "%s\n" "$_VERSION_"; exit 0 ;;
+			printf '%s\n' "$CurVer"; exit 0 ;;
 		--prtsc-is-menu)
-			# Feature the OP in the thread requested.
-			SCHEMA="com.linuxmint.mintmenu"
-			if ! gsettings set "$SCHEMA" hot-key "Print" 2> /dev/null; then
-				Err 1 "Unable to set 'hot-key' to 'Print' in: $SCHEMA"
-			fi ;;
+			PrtScIsMenu='True' ;;
 		*)
-			Err 1 "Incorrect argument(s) specified." ;;
+			Err 1 'Incorrect argument(s) specified.' ;;
 	esac
 	shift
 done
 
-SCHEMA="org.cinnamon.desktop.keybindings.media-keys"
-for KEY in {area,window}-screenshot{,-clip} screenshot{,-clip}; {
-	if ! gsettings set "$SCHEMA" "$KEY" "[]" 2> /dev/null; then
-		Err 1 "Unable to clear: $KEY"
+if ! type -P gsettings &> /dev/null; then
+	Err 1 "Dependency 'gsettings' not met."
+fi
+
+# Feature the OP in the thread requested.
+if [[ $PrtScIsMenu == True ]]; then
+	Schema='com.linuxmint.mintmenu'
+	if ! gsettings set "$Schema" 'hot-key' 'Print' 2> /dev/null; then
+		Err 1 "Unable to set 'hot-key' to 'Print' in: $Schema"
+	fi
+fi
+
+Schema="org.cinnamon.desktop.keybindings.media-keys"
+for Key in {area,window}-screenshot{,-clip} screenshot{,-clip}; {
+	if ! gsettings set "$Schema" "$Key" '[]' 2> /dev/null; then
+		Err 1 "Unable to clear: $Key"
 	fi
 }
-
