Convert nosp to BASH, and tweak

diff --git a/source/nosp b/source/nosp
--- a/source/nosp
+++ b/source/nosp
@@ -1,9 +1,9 @@
-#!/bin/sh
-
+#!/usr/bin/env bash
+#cito M:755 O:0 G:0 T:/usr/bin/nosp
 #------------------------------------------------------------------------------
-# Project Name      - Extra/source/nosp (No Smart-Placement)
+# Project Name      - Extra/source/nosp
 # Started On        - Sat 16 Sep 20:03:52 BST 2017
-# Last Change       - Thu 16 Dec 00:04:29 GMT 2021
+# Last Change       - Tue 25 Jan 18:58:54 GMT 2022
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
@@ -14,27 +14,26 @@
 # needed to effectively disable Smart Placement.
 #------------------------------------------------------------------------------
 
-Err(){
+Err() {
 	printf 'Err: %s\n' "$2" 1>&2
-	[ $1 -gt 0 ] && exit $1
+	(( $1 > 0 )) && exit $1
 }
 
-[ $# -eq 0 ] || Err 1 "No arguments are required."
+(( $# == 0 )) || Err 1 'No arguments are required.'
 
-DepCount=0
-for Dep in xfconf-query sleep; do
-	if ! command -V 1> /dev/null 2>&1; then
+for Dep in xfconf-query sleep; {
+	if ! type -P &> /dev/null; then
 		Err 0 "Dependency '$Dep' not met."
-		DepCount=$((DepCount + 1))
+		(( DepCount++ ))
 	fi
-done
+}
 
-[ $DepCount -gt 0 ] && exit 1
+(( DepCount > 0 )) && exit 1
 
 LocalXMLFile="$HOME/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml"
 CurrentValue=`xfconf-query -c xfwm4 -p /general/placement_ratio -t int`
 
-if [ -f "$LocalXMLFile" ] && [ -w "$LocalXMLFile" ]; then
+if [[ -f $LocalXMLFile && -w $LocalXMLFile ]]; then
 	# This command group waits, sets value to 90, waits, then sets back to 100.
 	{
 		sleep 3s
@@ -43,5 +42,5 @@ if [ -f "$LocalXMLFile" ] && [ -w "$LocalXMLFile" ]; then
 		xfconf-query -c xfwm4 -p /general/placement_ratio -s 100 -t int
 	} &
 else
-	Err 1 "Unable to fix Smart Placement."
+	Err 1 'Unable to fix Smart Placement.'
 fi
