Add usual program stuff (e.g., `Usage()`) & more
The more:

- Added '--' argument to handle files with leading dashes
- Added flag to allow user to _just_ summarise data in existing file
- Set default value of 0 for some AWK variables

diff --git a/source/pkgstats b/source/pkgstats
--- a/source/pkgstats
+++ b/source/pkgstats
@@ -3,7 +3,7 @@
 #------------------------------------------------------------------------------
 # Project Name      - Extra/source/pkgstats
 # Started On        - Sat 17 Jun 09:08:12 BST 2023
-# Last Change       - Mon 19 Jun 16:00:02 BST 2023
+# Last Change       - Mon 19 Jun 18:15:43 BST 2023
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
@@ -53,14 +53,97 @@
 # NOTE: If you run this, please be mindful of the servers. While sending a
 #       spider to grab the header is surely harmless, it's still constant
 #       connections, so please don't run this excessively!
+#
+# Features:
+#
+# N/A
+#
+# Bugs:
+#
+# N/A
+#
+# Dependencies:
+#
+#   apt (>= 1.6.17)
+#   bash (>= 4.0)
+#   gawk (>= 4.1.4)
+#   wget (>= 1.19.4)
 #------------------------------------------------------------------------------
+
+CurVer='2023-06-19'
+Progrm='pkgstats'
+ProgrmFancy='PKGStats'
+
+Usage() {
+	read -d '' <<-EOF
+		Usage: $Progrm [OPTS] FILE
+
+		  -h, --help               - Display this help information.
+		  -v, --version            - Output the version datestamp.
+		  -s, --summary-only       - Just display summary of existing FILE.
+
+		  The use of '--' to ignore proceeding options is supported.
+	EOF
+
+	printf '%s' "$REPLY"
+}
+
+Err() {
+	printf 'Err: %s\n' "$2" 1>&2
+	(( $1 > 0 )) && exit $1
+}
+
+SummaryOnly='False'
+
+Skip=
+Args=()
+while [[ -n $1 ]]; do
+	case $1 in
+		--)
+			Args+=(--)
+			Skip='True' ;;
+		-[^-]*)
+			if [[ $Skip == True ]]; then
+				Args+=("$1")
+			else
+				Str=${1#-}
+				Len=${#Str}
+				for (( Index = 0; Index < Len; Index++ )); {
+					Args+=(-"${Str:Index:1}")
+				}
+			fi ;;
+		*)
+			Args+=("$1") ;;
+	esac
+	shift
+done
+
+set -- "${Args[@]}"
+
+while [[ -n $1 ]]; do
+	case $1 in
+		--)
+			break ;;
+		--help|-h)
+			Usage; exit 0 ;;
+		--version|-v)
+			printf '%s\n' "$CurVer"; exit 0 ;;
+		--summary-only|-s)
+			SummaryOnly='True' ;;
+		-*)
+			Err 1 'Incorrect option(s) specified.' ;;
+		*)
+			break ;;
+	esac
+	shift
+done
 
 Args=$#
 if (( Args < 1 )); then
 	read -d '' <<-EOF
 		Err: Argument required.
 
-		     This script requires a file into which to save the package
+		     $ProgrmFancy requires a file into which to save the package
 		     information, consisting of a 'BYTES PACKAGE' format.
 
 		Nothing to do -- quitting.
@@ -71,14 +154,19 @@ if (( Args < 1 )); then
 elif (( Args > 1 )); then
 	printf 'Err: Invalid argument(s).\n' 1>&2
 	exit 1
-elif [[ $1 == -* ]]; then
-	printf 'Err: PKGStats takes no options.\n' 1>&2
-	exit 1
 elif [[ -d $1 ]]; then
 	printf 'Err: Argument is a directory.\n' 1>&2
 	exit 1
 elif [[ -f $1 ]]; then
 	FileExists='True'
+
+	if [[ $SummaryOnly == True && ! -s $1 ]]; then
+		Err 1 'Unable to summarize empty FILE.'
+	fi
+else
+	if [[ $SummaryOnly == True ]]; then
+		Err 1 'Unable to summarize non-existent FILE.'
+	fi
 fi
 
 DepCount=0
@@ -99,78 +187,89 @@ SigHandler() {
 	exit 130
 }
 
-trap SigHandler INT
+#----------------------------------------------------------Begin Gathering Data
 
-if [[ $FileExists == True ]]; then
-	readarray -t FileLines < "$1"
+if [[ $SummaryOnly != True ]]; then
+	trap SigHandler INT
 
-	declare -A FilePKGs=()
-	for Line in "${FileLines[@]}"; {
-		Bytes=${Line%% *}
-		FilePKG=${Line#* }
+	if [[ $FileExists == True ]]; then
+		readarray -t FileLines < "$1"
 
-		FilePKGs["$FilePKG"]=$Bytes
+		declare -A FilePKGs=()
+		for Line in "${FileLines[@]}"; {
+			Bytes=${Line%% *}
+			FilePKG=${Line#* }
+
+			FilePKGs["$FilePKG"]=$Bytes
+		}
+	fi
+
+	readarray -t Packages <<< "$(apt-cache pkgnames 2>&-)" || exit 1
+
+	[[ $FileExists == True ]] || > "$1"
+
+	Exists=
+	Count=0
+	Len=${#Packages[@]}
+	for Package in "${Packages[@]}"; {
+		if [[ $FileExists == True ]]; then
+			Exists=
+			if [[ -n ${FilePKGs["$Package"]} ]]; then
+				Bytes=${FilePKGs["$Package"]}
+				Exists='True'
+			fi
+		fi
+
+		if [[ $Exists != True ]]; then
+			while read Line; do
+				if [[ ${Line:0:1} == "'" ]]; then
+					Link=${Line%\'*}
+					Link=${Link#\'}
+
+					break
+				fi
+			done <<< "$(apt-get download --print-uris "$Package" 2>&-)"
+
+			while read F1 Bytes _; do
+				if [[ $F1 == Length: ]]; then
+					printf '%s %s\n' "$Bytes" "$Package" >> "$1"
+
+					break
+				fi
+			done <<< "$(wget --spider "$Link" 2>&1)"
+		fi
+
+		if [[ $Interactive == True ]]; then
+			if [[ $Exists == True ]]; then
+				printf '\r[???.????] \e[92m%s\e[0m is \e[93m%d\e[0m bytes\e[K'\
+					"$Package" $Bytes
+
+				continue
+			fi
+
+			awk -v C=$(( ++Count )) -v L=$Len -v PKG="$Package" -v B=$Bytes '
+				BEGIN {
+					Format = "\r[%08.4f%%] \033[92m%s\033[0m "
+					Format = Format "is \033[93m%d\033[0m bytes\033[K"
+					printf(Format, C / L * 100, PKG, B)
+				}
+			' 2>&-
+		fi
 	}
 fi
 
-readarray -t Packages <<< "$(apt-cache pkgnames 2>&-)" || exit 1
-
-[[ $FileExists == True ]] || > "$1"
-
-Exists=
-Count=0
-Len=${#Packages[@]}
-for Package in "${Packages[@]}"; {
-	if [[ $FileExists == True ]]; then
-		Exists=
-		if [[ -n ${FilePKGs["$Package"]} ]]; then
-			Bytes=${FilePKGs["$Package"]}
-			Exists='True'
-		fi
-	fi
-
-	if [[ $Exists != True ]]; then
-		while read Line; do
-			if [[ ${Line:0:1} == "'" ]]; then
-				Link=${Line%\'*}
-				Link=${Link#\'}
-
-				break
-			fi
-		done <<< "$(apt-get download --print-uris "$Package" 2>&-)"
-
-		while read F1 Bytes _; do
-			if [[ $F1 == Length: ]]; then
-				printf '%s %s\n' "$Bytes" "$Package" >> "$1"
-
-				break
-			fi
-		done <<< "$(wget --spider "$Link" 2>&1)"
-	fi
-
-	if [[ $Interactive == True ]]; then
-		if [[ $Exists == True ]]; then
-			printf '\r[???.????] \e[92m%s\e[0m is \e[93m%d\e[0m bytes\e[K'\
-				"$Package" $Bytes
-
-			continue
-		fi
-
-		awk -v C=$(( ++Count )) -v L=$Len -v PKG="$Package" -v B=$Bytes '
-			BEGIN {
-				Format = "\r[%08.4f%%] \033[92m%s\033[0m "
-				Format = Format "is \033[93m%d\033[0m bytes\033[K"
-				printf(Format, C / L * 100, PKG, B)
-			}
-		' 2>&-
-	fi
-}
+#---------------------------------------------------------------Display Summary
 
 Interactive=True
 if [[ $Interactive == True ]]; then
-	printf '\rDone! Summary below.\e[K\n\n'
+	[[ $SummaryOnly == True ]] || printf '\rDone! Summary below.\e[K\n\n'
 
 	awk '
+		BEGIN {
+			GE500M = 0
+			LE500M = 0
+		}
+
 		# Underscores because AWK sucks at localizing variables.
 		function Human(_Size) {
 			_UnitStr = "b K M G T P E Z Y"
