Update syntax & Usage() of `roks`

diff --git a/source/roks b/source/roks
--- a/source/roks
+++ b/source/roks
@@ -1,89 +1,91 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #cito M:755 O:0 G:0 T:/usr/bin/roks
-#----------------------------------------------------------------------------------
+#------------------------------------------------------------------------------
 # Project Name      - Extra/source/roks (inspired by purge-old-kernels)
 # Started On        - Sun 17 Sep 23:32:47 BST 2017
-# Last Change       - Fri  6 Dec 22:54:06 GMT 2019
+# Last Change       - Tue 15 Dec 23:01:25 GMT 2020
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
-#----------------------------------------------------------------------------------
+#------------------------------------------------------------------------------
+# Features:
+#
+# N/A
+#
+# Bugs:
+#
+# N/A
+#
+# Dependencies:
+#
+#   apt (>= 1.6.12)
+#   bash (>= 4.3-14)
+#   coreutils (>= 8.28)
+#   linux-base (>= 4.5)
+#------------------------------------------------------------------------------
 
-CurVer='2019-12-06'
+CurVer='2020-12-15'
 Progrm=${0##*/}
 
-Err(){
-	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
-	[ $1 -gt 0 ] && exit $1
-}
-
 Usage(){
-	while read -r; do
-		printf "%s\n" "$REPLY"
+	while read; do
+		printf '%s\n' "$REPLY"
 	done <<-EOF
-		            ${Progrm^^} ($CurVer)
-		            Written by terminalforlife <terminalforlife@yahoo.com>
+		Usage: $Progrm [OPTS]
 
-		            Remove old kernel versions on an Ubuntu- or Debian-based system.
+		  -h, --help               - Display this help information.
+		  -v, --version            - Output the version datestamp.
+		  -p, --purge              - Don't just remove, but purge the kernels.
+		  -t, --type [TYPE]        - Work with TYPE kernels. Any by default.
+		  -k, --keep [INT]         - Keep INT number of kernels, instead of 1.
 
-		SYNTAX:     $Progrm [OPTS]
+		  Written as an improvement over the now-deprecated script called
+		  'purge-old-kernels' found in the byobu package. This small program
+		  will clear out your system of old kernel versions on an Ubuntu- or
+		  Debian-based system.
 
-		OPTS:       --help|-h|-?            - Displays this help information.
-		            --version|-v            - Output only the version datestamp.
-		            --quiet|-q              - Disable STDOUT. Errors still output.
-		            --debug|-D              - Enables the built-in bash debugger.
-		            --keep|-k N             - Where N is the number of kernels to keep.
-		                                      The default is 2, which is recommended.
-		            --type X                - Where X is the type of kernel, such as
-		                                      generic, lowlatency, aws, gke, etc. The
-		                                      default is to disregard the type.
-		            --purge                 - Don't just remove; purge the blighters.
+		  Unrecognised short or long flags will be passed to apt or apt-get.
 
-		NOTE:      Written as an improvement over the now-deprecated script called
-		           'purge-old-kernels' found in the byobu package. This small program will
-		           clear out your system of old kernel versions on an Ubuntu- or
-		           Debian-based system.
-
-		           Unrecognised short or long flags will be passed to apt or apt-get.
-
-		           As of 2019-03-31, $Progrm no longer supports handling older kernel versions
-		           in Debian- or Ubuntu-based systems. I recommend taking extra care when
-		           using $Progrm on systems with kernels older than 4.15; it might work, but
-		           not necessarily as intended.
+		  As of 2019-03-31, $Progrm no longer supports handling older kernel
+		  versions in Debian- or Ubuntu-based systems. I recommend taking extra
+		  care when using $Progrm on systems with kernels older than 4.15; it
+		  might work, but not necessarily as intended.
 	EOF
 }
 
-KernKeep=2
+Err(){
+	printf 'ERROR: %s\n' "$2" 1>&2
+	[ $1 -gt 0 ] && exit $1
+}
+
+declare -i KernKeep=2
 
 while [ "$1" ]; do
 	case $1 in
 		--help|-h|-\?)
 			Usage; exit 0 ;;
 		--version|-v)
-			printf "%s\n" "$CurVer"
+			printf '%s\n' "$CurVer"
 			exit 0 ;;
-		--quiet|-q)
-			exec > /dev/null ;;
-		--debug|-D)
-			DebugMe='true' ;;
 		--keep|-k)
 			shift
+
 			if [[ $1 =~ ^[0-9]+$ ]]; then
 				if [ $1 -eq 0 ]; then
-					Err 1 $LINENO "Invalid number of kernels selected."
+					Err 1 'Invalid number of kernels selected.'
 				else
-					declare -i KernKeep=$1
+					KernKeep=$1
 				fi
 			else
-				Err 1 $LINENO "Invalid expression specified."
+				Err 1 'Invalid expression specified.'
 			fi ;;
-		--type)
+		--type|-t)
 			shift; KernType="-$1" ;;
-		--purge)
-			DoPurge="--purge" ;;
+		--purge|-p)
+			DoPurge='--purge' ;;
 		-*|--*)
 			AptGetOpts+=" $1" ;;
 		*)
-			Err 1 $LINENO "Incorrect argument(s) provided." ;;
+			Err 1 "Incorrect argument(s) provided." ;;
 	esac
 	shift
 done
@@ -91,7 +93,7 @@ done
 declare -i DepCount=0
 for CurDep in uname apt-get linux-version; {
 	if ! type -P "$CurDep" > /dev/null 2>&1; then
-		Err 0 $LINENO "Dependency '$CurDep' not met."
+		Err 0 "Dependency '$CurDep' not met."
 		DepCount+=1
 	fi
 }
@@ -106,19 +108,19 @@ if [ -f /proc/version -a -r /proc/version ]; then
 elif ! type -P uname > /dev/null 2>&1; then
 	CurKern=`uname -r`
 else
-	Err 1 $LINENO "Unable to determine current kernel version."
+	Err 1 "Unable to determine current kernel version."
 fi
 
 if ! [ $UID -eq 0 ]; then
-	Err 1 $LINENO "Root access is required for system-wide changes."
+	Err 1 "Root access is required for system-wide changes."
 fi
 
 KernKeep+=2
 KernList=`linux-version list`
 if ! [ "$KernList" ]; then
-	Err 1 $LINENO "No kernels were found."
+	Err 1 "No kernels were found."
 elif ! [ "$KernList" ]; then
-	Err 1 $LINENO "No kernels were selected for removal."
+	Err 1 "No kernels were selected for removal."
 else
 	declare -a KernRemove=()
 	for CurIter in $KernList; {
@@ -131,7 +133,6 @@ else
 		-o Dpkg::Progress-Fancy=true remove $DoPurge ${KernRemove[@]}
 
 	if [ $? -ne 0 ]; then
-		Err 1 $LINENO "Non-zero exit status while removing old kernels."
+		Err 1 'Non-zero exit status while removing old kernels.'
 	fi
 fi
-
