Update simplify-ubuntu with omission of tflbp-sh
ChkDep() and Err() are now handled in-house.

diff --git a/source/simplify-ubuntu b/source/simplify-ubuntu
--- a/source/simplify-ubuntu
+++ b/source/simplify-ubuntu
@@ -3,18 +3,27 @@
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/source/simplify-ubuntu
 # Started On        - Fri 12 Jan 04:52:52 GMT 2018
-# Last Change       - Wed 21 Oct 16:46:51 BST 2020
+# Last Change       - Wed 11 Nov 03:46:16 GMT 2020
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
 # Q-COUNT = 169
+#
+# Features:
+#
+# N/A
+#
+# Bugs:
+#
+# N/A
+#
+# Dependencies:
+#
+#   bash (>= 4.3-14)
 #----------------------------------------------------------------------------------
 
-CurVer='2020-10-21'
+CurVer='2020-11-11'
 Progrm=${0##*/}
-
-. /usr/lib/tflbp-sh/Err
-. /usr/lib/tflbp-sh/ChkDep
 
 DoSay(){ printf "%s\n" "$1"; }
 
@@ -56,6 +65,11 @@ Usage(){
 	EOF
 }
 
+Err(){
+	printf 'ERROR: %s\n' "$1" 1>&2
+	[ $1 -eq 1 ] && exit 1
+}
+
 while [ "$1" ]; do
 	case $1 in
 		--help|-h|-\?)
@@ -86,6 +100,19 @@ while [ "$1" ]; do
 done
 
 PathLook(){ type -fP $@ &> /dev/null || return 1; }
+
+ChkDep(){
+	DepCount=0
+	for CurDep in "$@"; do
+		if command -v "$CurDep" 1> /dev/null 2>&1; then
+			DepCount=$((DepCount + 1))
+		else
+			Err 0 "Dependency '$CurDep' not met."
+		fi
+	done
+
+	[ $DepCount -eq $# ] || exit 1
+}
 
 ChkDep rm lspkg clean-locales apt-get
 
