Tidy code & dynamically show line numbers
Quite a bit better than it was. I abandoned the idea of supporting
multiple matches, because it's annoying and adds needless complexity.
Use grep(1) or something, if you need to get fancy.

The line numbers being dynamic required some pre-processing, which
might slow `snotes` down a bit if you have a very large notes file.

diff --git a/source/snotes b/source/snotes
--- a/source/snotes
+++ b/source/snotes
@@ -3,13 +3,13 @@
 #------------------------------------------------------------------------------
 # Project Name      - Extra/source/snotes
 # Started On        - Fri  9 Feb 00:07:19 GMT 2018
-# Last Change       - Thu 28 Jan 23:49:09 GMT 2021
+# Last Change       - Fri  3 Sep 00:29:03 BST 2021
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
 # Features:
 #
-#TODO: Support multiple MATCHes.
+# N/A
 #
 # Bugs:
 #
@@ -21,7 +21,7 @@
 # will eventually be included into snotes properly.
 #------------------------------------------------------------------------------
 
-CurVer='2021-01-28'
+CurVer='2021-09-03'
 Progrm=${0##*/}
 
 Comment='#'
@@ -47,18 +47,22 @@ Usage(){
 		    ${Comment}END
 
 		  The default comment character is '$Comment'.
+
+		  The use of '--' to ignore proceeding flags is supported.
 	EOF
 }
 
 Err(){
 	printf 'ERROR: %s\n' "$2" 1>&2
-	[ $1 -gt 0 ] && exit $1
+	(( $1 > 0 )) && exit $1
 }
 
 ProjConf="$HOME/.config/$Progrm.conf"
 
-while [ "$1" ]; do
+while [ -n "$1" ]; do
 	case $1 in
+		--)
+			break ;;
 		--help|-h|-\?)
 			Usage; exit 0 ;;
 		--version|-v)
@@ -75,17 +79,19 @@ while [ "$1" ]; do
 	shift
 done
 
-[ -n "$2" ] && Err 1 'Multiple matches are not supported.'
+(( $# > 1 )) && Err 1 'Multiple matches are not supported.'
 
-SnotesChk(){
-	if ! [ -f "$NotesFile" ] || ! [ -r "$NotesFile" ]; then
-		Err 1 'Notes file inaccessible or not found.'
+FileChk(){
+	if ! [ -f "$NotesFile" ]; then
+		Err 1 'File not found.'
+	elif ! [ -r "$NotesFile" ]; then
+		Err 1 'File unreadable.'
 	fi
 }
 
 if [ -f "$ProjConf" ]; then
 	if [ -n "$NotesFile" ]; then
-		SnotesChk
+		FileChk
 		read -n 1 -ep 'Notes file already set -- replace? [Y/N] '
 		case $REPLY in
 			[Yy]|[Yy][Ee][Ss])
@@ -109,19 +115,26 @@ else
 	printf "$NotesFile\n" > "$ProjConf"
 fi
 
-SnotesChk
-Match=$1
-declare -i LineCount=0
+FileChk
+LineCount=0
+LineCountLenMax=0
 while read -r CurLine; do
-	CurLineCount+=1
-	[ "$CurLine" == "${Comment}"END ] && break
-	if [[ $CurLine =~ ^(|${Comment}.*)$ ]]; then
+	let LineCount++
+
+	[ "$CurLine" == "${Comment}END" ] && break
+	if [[ $CurLine =~ ^($|$Comment) ]]; then
 		continue
-	elif [[ $CurLine =~ "$Match" ]]; then
-		if [ "$CurLineNums" == 'true' ]; then
-			printf "%4d  %s\n" "$CurLineCount" "$CurLine"
-		else
-			printf "%s\n" "$CurLine"
+	elif [[ $CurLine =~ $1 ]]; then
+		LineCountLen=${#LineCount}
+		if (( LineCountLen > LineCountLenMax )); then
+			LineCountLenMax=$LineCountLen
 		fi
+
+		FinalLines+=("$LineCount:$CurLine")
 	fi
 done < "$NotesFile"
+
+for Line in "${FinalLines[@]}"; {
+	printf '\e[2;37m%*d\e[0m  %s\n'\
+		$LineCountLenMax ${Line%%:*} "${Line#*:}"
+}
