Highlight match, improve code, and remove prompt
Changes:

  * Removed old bug TODO which was addressed ages ago.
  * Moved `Comment` somewhere more appropriate.
  * Added to `Usage()` for clarity.
  * Changed `ProjConf` to `SnotesFile` to be more accurate.
  * Added error-checking for `-C` and `-f` flags.
  * Checked for mkdir(1) being found in `PATH`.
  * Removed the prompt code for when notes file is already saved.
  * Made sane changes to the messy logic of the `SnotesFile`.

diff --git a/source/snotes b/source/snotes
--- a/source/snotes
+++ b/source/snotes
@@ -3,28 +3,24 @@
 #------------------------------------------------------------------------------
 # Project Name      - Extra/source/snotes
 # Started On        - Fri  9 Feb 00:07:19 GMT 2018
-# Last Change       - Sun  9 Jan 23:43:19 GMT 2022
+# Last Change       - Thu 13 Jan 15:29:51 GMT 2022
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
+# To use your own comment character, change the Comment variable. This feature
+# will eventually be included into snotes properly.
+#
 # Features:
 #
 # N/A
 #
 # Bugs:
 #
-#TODO: Fix clash between snotes' arguments and those found in the notes file.
-#
-#      Also, --edit/-e CMD is not working.
-#
-# To use your own comment character, change the Comment variable. This feature
-# will eventually be included into snotes properly.
+# N/A
 #------------------------------------------------------------------------------
 
-CurVer='2022-01-09'
+CurVer='2022-01-13'
 Progrm=${0##*/}
-
-Comment='#'
 
 Usage() {
 	while read; do
@@ -37,8 +33,9 @@ Usage() {
 		  -C, --comment [STR]      - Use STR as the single comment character.
 		  -f, --file [PATH]        - Specify & remember the notes file to use.
 
-		  By default, the notes file saved in the $Progrm configuration file
-		  will be the one used.
+		  The location of the file read by ${Progrm^} is saved here:
+
+		    ~${SnotesFile##*$HOME}
 
 		  Regular expressions are used for MATCH. Comment lines are ignored. To
 		  tell $Progrm when you wish to stop searching for MATCH, have a line
@@ -57,7 +54,8 @@ Err() {
 	(( $1 > 0 )) && exit $1
 }
 
-ProjConf="$HOME/.config/$Progrm.conf"
+Comment='#'
+SnotesFile="$HOME/.config/$Progrm.conf"
 
 while [[ -n $1 ]]; do
 	case $1 in
@@ -69,9 +67,21 @@ while [[ -n $1 ]]; do
 		--version|-v)
 			printf '%s\n' "$CurVer"; exit 0 ;;
 		--comment|-C)
-			shift; Comment=${1:0:1} ;;
+			ArgComment=$1
+			if [[ -z $2 ]]; then
+				Err 1 "Option '$ArgComment' requires an argument."
+			else
+				Comment=$2
+				shift
+			fi ;;
 		--file|-f)
-			shift; NotesFile=$1 ;;
+			ArgFile=$1
+			if [[ -z $2 ]]; then
+				Err 1 "Option '$ArgFile' requires an argument."
+			else
+				NotesFile=$2
+				shift
+			fi ;;
 		-*)
 			Err 1 'Incorrect argument(s) specified.' ;;
 		*)
@@ -80,43 +90,34 @@ while [[ -n $1 ]]; do
 	shift
 done
 
-(( $# > 1 )) && Err 1 'Multiple matches are not supported.'
-
-FileChk() {
-	if ! [[ -f $NotesFile ]]; then
-		Err 1 'File not found.'
-	elif ! [[ -r $NotesFile ]]; then
-		Err 1 'File unreadable.'
-	fi
-}
-
-if [[ -f $ProjConf ]]; then
-	if [[ -n $NotesFile ]]; then
-		FileChk
-		read -n 1 -ep 'Notes file already set -- replace? [Y/N] '
-		case $REPLY in
-			[Yy]|[Yy][Ee][Ss])
-				if ! [[ -d $HOME/.config ]]; then
-					if type -P mkdir &> /dev/null; then
-						mkdir "$HOME/.config"
-					else
-						Err 1 "Dependency 'mkdir' not met."
-					fi
-				fi
-
-				printf '%q\n' "$NotesFile" > "$ProjConf" ;;
-			[Nn]|[Nn][Oo])
-				printf 'No action taken -- quitting.\n'
-				exit 0 ;;
-		esac
-	else
-		NotesFile=$(< "$ProjConf")
-	fi
-else
-	printf '%s\n' "$NotesFile" > "$ProjConf"
+if ! type -P mkdir &> /dev/null; then
+	Err 1 "Dependency 'mkdir' not met."
 fi
 
-FileChk
+(( $# > 1 )) && Err 1 'Multiple matches not supported.'
+
+#---------------------------------------------Process or Create the Snotes File
+
+if [[ -n $NotesFile ]]; then
+	ConfigDir=${SnotesFile%/*}
+	[[ -d $ConfigDir ]] || mkdir -p "$ConfigDir"
+	printf '%s\n' "$NotesFile" > "$SnotesFile"
+
+	printf 'New location saved.\n'
+	exit 0
+fi
+
+[[ -r $SnotesFile ]] || Err 1 "File '$SnotesFile' unreadable."
+NotesFile=$(< "$SnotesFile")
+
+#--------------------------------------------------------Parse and Display Data
+
+if ! [[ -f $NotesFile ]]; then
+	Err 1 'Notes file not found.'
+elif ! [[ -r $NotesFile ]]; then
+	Err 1 'Notes file unreadable.'
+fi
+
 LineCount=0
 LineCountLenMax=0
 while read -r CurLine; do
@@ -136,5 +137,9 @@ while read -r CurLine; do
 done < "$NotesFile"
 
 for Line in "${FinalLines[@]}"; {
+	# Colorize the match, à la grep(1). Need to use the $'' syntax to use
+	# escape sequences properly, otherwise it won't work.
+	Line=${Line//$1/$'\e[91m'$1$'\e[0m'}
+
 	printf '\e[2;37m%*d\e[0m  %s\n' $LineCountLenMax ${Line%%:*} "${Line#*:}"
 }
