Prefer arithmetic evaluation

diff --git a/source/tlptog b/source/tlptog
--- a/source/tlptog
+++ b/source/tlptog
@@ -3,7 +3,7 @@
 #------------------------------------------------------------------------------
 # Project Name      - Extra/source/tlptog
 # Started On        - Fri 18 May 14:19:48 BST 2018
-# Last Change       - Thu 16 Dec 00:11:57 GMT 2021
+# Last Change       - Fri 24 Dec 18:47:27 GMT 2021
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
@@ -11,10 +11,10 @@
 # setups.
 #------------------------------------------------------------------------------
 
-CurVer='2021-12-16'
+CurVer='2021-12-24'
 Progrm='tlptog'
 
-Usage(){
+Usage() {
 	while read; do
 		printf '%s\n' "$REPLY"
 	done <<-EOF
@@ -25,7 +25,7 @@ Usage(){
 	EOF
 }
 
-Err(){
+Err() {
 	printf 'Err: %s\n' "$2" 1>&2
 	(( $1 > 0 )) && exit $1
 }
@@ -46,30 +46,28 @@ done
 
 if ! type -P sed &> /dev/null; then
 	Err 1 "Dependency 'sed' not met."
-elif [ $UID -ne 0 ]; then
+elif (( UID != 0 )); then
 	Err 1 'Root access is required.'
 fi
 
-if [ -f "$WorkFile" ]; then
-	while IFS='=' read -a Line; do
-		if [[ ${Line[0]} == \#* ]]; then
-			continue
-		elif [ "${Line[0]}" == 'TLP_ENABLE' ]; then
-			if [ ${Line[1]} -eq 1 ]; then
-				if ! sed -i 's/\(TLP_ENABLE=\)1/\10/' "$WorkFile"; then
-					Err 1 "Parameter 'TLP_ENABLE' unsuccessfully set to '1'."
-				fi
-			elif [ ${Line[1]} -eq 0 ]; then
-				if ! sed -i 's/\(TLP_ENABLE=\)0/\11/' "$WorkFile"; then
-					Err 1 "Parameter 'TLP_ENABLE' unsuccessfully set to '0'."
-				fi
-			else
-				Err 1 "Invalid 'TLP_ENABLE' parameter assignment."
-			fi
+[ -f "$WorkFile" ] || Err 1 "Unable to find the '$WorkFile' file."
 
-			break
+while IFS='=' read -a Line; do
+	if [[ ${Line[0]} == \#* ]]; then
+		continue
+	elif [ "${Line[0]}" == 'TLP_ENABLE' ]; then
+		if (( ${Line[1]} == 1 )); then
+			if ! sed -i 's/\(TLP_ENABLE=\)1/\10/' "$WorkFile"; then
+				Err 1 "Parameter 'TLP_ENABLE' unsuccessfully set to '1'."
+			fi
+		elif (( ${Line[1]} == 0 )); then
+			if ! sed -i 's/\(TLP_ENABLE=\)0/\11/' "$WorkFile"; then
+				Err 1 "Parameter 'TLP_ENABLE' unsuccessfully set to '0'."
+			fi
+		else
+			Err 1 "Invalid 'TLP_ENABLE' parameter assignment."
 		fi
-	done < "$WorkFile"
-else
-	Err 1 "Unable to find the '$WorkFile' file."
-fi
+
+		break
+	fi
+done < "$WorkFile"
