Add paging support & correctly handle FILE
We can also see the total number of key bindings, thanks to the new
flags for that. Pagination also has a flag associated with that
functionality.

diff --git a/source/csdwm/csdwm b/source/csdwm/csdwm
--- a/source/csdwm/csdwm
+++ b/source/csdwm/csdwm
@@ -1,16 +1,15 @@
 #!/usr/bin/env bash
+#cito M:755 O:0 G:0 T:/usr/bin/csdwm
 #------------------------------------------------------------------------------
-# Project Name      -
+# Project Name      - Extra/source/csdwm/csdwm
 # Started On        - Wed 26 May 15:36:21 BST 2021
-# Last Change       - Wed 26 May 20:30:05 BST 2021
+# Last Change       - Wed 26 May 20:58:18 BST 2021
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
 # Features:
 #
-#TODO: Add support for own FILE via flag.
 #TODO: Automate the `if` statement block handling arguments.
-#TODO: Add support for less(1), or more(1) if less(1) isn't present.
 #TODO: Handle additional special keys, such as 'Period' and 'Comma'.
 #TODO: Add flags for user customization of output.
 #TODO: Show what 'Mod' actually is at the top of the output, if possible.
@@ -33,10 +32,14 @@ Usage(){
 	while read; do
 		printf '%s\n' "$Line"
 	done <<-EOF
-		Usage: $Progrm [OPTS]
+		Usage: $Progrm [OPTS] [FILE]
 
 		  -h, --help               - Display this help information.
 		  -v, --version            - Output the version datestamp.
+		  -p, --paginate           - Send output to less(1) or more(1).
+		  -t, --total              - Show total discovered key bindings.
+
+		Where FILE is that from which to read DWM's key bindings.
 	EOF
 }
 
@@ -51,11 +54,31 @@ while [ "$1" ]; do
 			Usage; exit 0 ;;
 		--version|-v)
 			printf '%s\n' "$CurVer"; exit 0 ;;
-		*)
+		--paginate|-p)
+			if type -P less &> /dev/null; then
+				Pager='less'
+			elif type -P more &> /dev/null; then
+				Pager='more'
+			else
+				Err 1 'No suitable pager found in PATH.'
+			fi ;;
+		--total|-t)
+			ShowTTL='True' ;;
+		-*)
 			Err 1 'Incorrect option(s) specified.' ;;
+		*)
+			break ;;
 	esac
 	shift
 done
+
+if ! [ -f "$1" ]; then
+	Err 1 'Configuration FILE not found.'
+elif ! [ -r "$1" ]; then
+	Err 1 'Configuration FILE unreadable.'
+else
+	File=$1
+fi
 
 DepCount=0
 for Dep in sort; do
@@ -68,8 +91,6 @@ done
 [ $DepCount -gt 0 ] && exit 1
 
 #-------------------------------------------------------------------Gather Data
-
-File='config.def.h'
 
 ModKeyLenMax=0
 while read Line; do
@@ -150,10 +171,27 @@ while read Line; do
 	fi
 done < "$File"
 
+Total=$((${#Bindings[@]} + 0))
+
 #------------------------------------------------------Begin Displaying Results
 
-for Binding in "${!Bindings[@]}"; {
-	printf ' %*s %s\n' $((ModKeyLenMax + 1)) $Binding "${Bindings["$Binding"]}"
-} | sort -k 2
+DisplayMain(){
+	for Binding in "${!Bindings[@]}"; {
+		printf ' %*s %s\n' $((ModKeyLenMax + 1))\
+			$Binding "${Bindings["$Binding"]}"
+	} | sort -k 2
 
-#printf '\nTotal: %d\n' ${#Bindings[@]}
+	if [ "$ShowTTL" == 'True' -a $Total -ne 0 ]; then
+		printf '\nTotal: %d\n' ${#Bindings[@]}
+	fi
+}
+
+if [ $Total -eq 0 ]; then
+	printf 'Uh-oh! No key bindings found.\n' 1>&2
+elif [ "$Pager" == 'less' ]; then
+	DisplayMain | less
+elif [ "$Pager" == 'more' ]; then
+	DisplayMain | more
+else
+	DisplayMain
+fi
